from __future__ import annotations

# source: profiles/FlyingBear/process/Ghost7/0.12mm Fine @FlyingBear Ghost7.json
DATA = {'bottom_shell_layers': '5',
 'brim_width': '5',
 'compatible_printers': ['FlyingBear Ghost7 0.4 nozzle'],
 'exclude_object': '1',
 'from': 'system',
 'gap_infill_speed': '180',
 'inherits': 'fdm_process_common_Ghost7',
 'inner_wall_acceleration': '3000',
 'inner_wall_speed': '150',
 'instantiation': 'true',
 'internal_bridge_speed': '50',
 'internal_solid_infill_speed': '180',
 'layer_height': '0.12',
 'name': '0.12mm Fine @FlyingBear Ghost7',
 'outer_wall_speed': '80',
 'overhang_1_4_speed': '30',
 'overhang_2_4_speed': '30',
 'overhang_3_4_speed': '10',
 'print_settings_id': '0.12mm Fine @FlyingBear Ghost7',
 'setting_id': 'GP004',
 'sparse_infill_speed': '180',
 'top_shell_layers': '5',
 'top_shell_thickness': '0.6',
 'top_surface_speed': '150',
 'tree_support_wall_count': '0',
 'type': 'process'}
