from __future__ import annotations

# source: profiles/Blocks/process/0.32mm Draft 0.6 nozzle @Blocks_RF50.json
DATA = {'accel_to_decel_enable': '1',
 'accel_to_decel_factor': '50%',
 'bottom_shell_layers': '4',
 'bottom_solid_infill_flow_ratio': '1.08',
 'bridge_acceleration': '50%',
 'bridge_infill_acceleration': '50%',
 'bridge_speed': '50%',
 'compatible_printers': ['BLOCKS RF50', 'BLOCKS RF50 0.6 nozzle'],
 'default_acceleration': '5000',
 'detect_overhang_wall': '1',
 'elefant_foot_compensation': '0.25',
 'elefant_foot_compensation_layers': '1',
 'enable_arc_fitting': '0',
 'enable_overhang_speed': '1',
 'filename_format': '{input_filename_base}_{filament_type[0]}_{print_time}.gcode',
 'from': 'system',
 'gap_infill_speed': '260',
 'inherits': 'fdm_process_common 0.6 nozzle',
 'initial_layer_acceleration': '1500',
 'initial_layer_infill_speed': '80',
 'initial_layer_print_height': '0.3',
 'initial_layer_speed': '60',
 'initial_travel_speed': '100%',
 'inner_wall_acceleration': '4500',
 'inner_wall_speed': '300',
 'instantiation': 'true',
 'internal_bridge_speed': '100%',
 'internal_solid_infill_acceleration': '100%',
 'internal_solid_infill_speed': '270',
 'layer_height': '0.32',
 'name': '0.32mm Draft 0.6 nozzle @Blocks_RF50',
 'outer_wall_acceleration': '2500',
 'outer_wall_speed': '180',
 'overhang_1_4_speed': '0',
 'overhang_2_4_speed': '50',
 'overhang_3_4_speed': '30',
 'overhang_4_4_speed': '10',
 'overhang_speed_classic': '0',
 'seam_position': 'aligned',
 'setting_id': 'GP004',
 'slow_down_layers': '5',
 'slow_layers_count': '5',
 'slowdown_for_curled_perimeters': '1',
 'small_perimeter_speed': '50%',
 'small_perimeter_threshold': '0',
 'sparse_infill_acceleration': '100%',
 'sparse_infill_patter': 'grid',
 'sparse_infill_speed': '300',
 'support_interface_speed': '180',
 'support_speed': '300',
 'top_shell_layers': '4',
 'top_solid_infill_flow_ratio': '0.97',
 'top_surface_acceleration': '2000',
 'top_surface_speed': '200',
 'travel_acceleration': '20000',
 'travel_speed': '500',
 'type': 'process',
 'wall_generator': 'classic'}
