from __future__ import annotations

# source: profiles/Blocks/process/fdm_process_blocks_common.json
DATA = {'adaptive_layer_height': '0',
 'bottom_shell_layers': '3',
 'bottom_shell_thickness': '0',
 'bottom_surface_pattern': 'monotonic',
 'bridge_flow': '0.95',
 'bridge_no_support': '0',
 'bridge_speed': '150',
 'brim_object_gap': '0.1',
 'brim_width': '5',
 'compatible_printers': ['BLOCKS Pro S100 0.4 nozzle',
                         'BLOCKS Pro S100 0.6 nozzle',
                         'BLOCKS Pro S100 0.8 nozzle',
                         'BLOCKS Pro S100 1.0 nozzle',
                         'BLOCKS Pro S100 1.2 nozzle',
                         'BLOCKS RD50 V2 0.4 nozzle',
                         'BLOCKS RD50 V2 0.6 nozzle',
                         'BLOCKS RD50 V2 0.8 nozzle',
                         'BLOCKS RF50 0.4 nozzle',
                         'BLOCKS RF50 0.6 nozzle',
                         'BLOCKS RF50 0.8 nozzle'],
 'compatible_printers_condition': '',
 'default_acceleration': '4500',
 'detect_overhang_wall': '1',
 'detect_thin_wall': '0',
 'draft_shield': 'disabled',
 'elefant_foot_compensation': '0.1',
 'enable_arc_fitting': '1',
 'enable_prime_tower': '0',
 'enable_support': '0',
 'filename_format': '{input_filename_base}_{filament_type[initial_tool]}_{print_time}.gcode',
 'from': 'system',
 'gap_infill_speed': '100',
 'infill_combination': '0',
 'infill_direction': '45',
 'infill_wall_overlap': '15%',
 'inherits': 'fdm_process_common',
 'initial_layer_acceleration': '3000',
 'initial_layer_infill_speed': '80',
 'initial_layer_line_width': '0.42',
 'initial_layer_print_height': '0.2',
 'initial_layer_speed': '60',
 'inner_wall_acceleration': '4000',
 'inner_wall_line_width': '0.42',
 'inner_wall_speed': '120',
 'instantiation': 'false',
 'interface_shells': '0',
 'internal_bridge_speed': '100%',
 'internal_solid_infill_line_width': '0.42',
 'internal_solid_infill_speed': '120',
 'ironing_flow': '10%',
 'ironing_spacing': '0.15',
 'ironing_speed': '30',
 'ironing_type': 'no ironing',
 'layer_height': '0.2',
 'line_width': '0.42',
 'max_travel_detour_distance': '0',
 'minimum_sparse_infill_area': '15',
 'name': 'fdm_process_blocks_common',
 'outer_wall_acceleration': '3000',
 'outer_wall_line_width': '0.42',
 'outer_wall_speed': '100',
 'overhang_1_4_speed': '0',
 'overhang_2_4_speed': '120',
 'overhang_3_4_speed': '80',
 'overhang_4_4_speed': '30',
 'prime_tower_width': '60',
 'print_sequence': 'by layer',
 'print_settings_id': '',
 'raft_layers': '0',
 'reduce_crossing_wall': '0',
 'reduce_infill_retraction': '1',
 'resolution': '0.012',
 'seam_gap': '2%',
 'seam_position': 'nearest',
 'skirt_distance': '2',
 'skirt_height': '1',
 'skirt_loops': '1',
 'sparse_infill_density': '15%',
 'sparse_infill_line_width': '0.42',
 'sparse_infill_pattern': 'grid',
 'sparse_infill_speed': '120',
 'spiral_mode': '0',
 'standby_temperature_delta': '-5',
 'support_base_pattern': 'rectilinear',
 'support_base_pattern_spacing': '2.5',
 'support_filament': '0',
 'support_interface_bottom_layers': '2',
 'support_interface_filament': '0',
 'support_interface_loop_pattern': '0',
 'support_interface_spacing': '0.5',
 'support_interface_speed': '80',
 'support_interface_top_layers': '2',
 'support_line_width': '0.42',
 'support_object_xy_distance': '0.35',
 'support_on_build_plate_only': '0',
 'support_speed': '130',
 'support_style': 'default',
 'support_threshold_angle': '30',
 'support_top_z_distance': '0.2',
 'support_type': 'normal(auto)',
 'top_shell_layers': '3',
 'top_shell_thickness': '0.8',
 'top_surface_acceleration': '4000',
 'top_surface_line_width': '0.42',
 'top_surface_pattern': 'monotonicline',
 'top_surface_speed': '100',
 'travel_acceleration': '5000',
 'travel_speed': '250',
 'tree_support_branch_angle': '45',
 'tree_support_wall_count': '0',
 'type': 'process',
 'wall_infill_order': 'inner wall/outer wall/infill',
 'wall_loops': '3',
 'wipe_tower_no_sparse_layers': '0',
 'xy_contour_compensation': '0',
 'xy_hole_compensation': '0.075'}
