from __future__ import annotations

# source: profiles/Blocks/process/fdm_process_common 0.6 nozzle.json
DATA = {'adaptive_layer_height': '0',
 'bridge_flow': '0.95',
 'bridge_no_support': '0',
 'brim_width': '5',
 'compatible_printers': ['BLOCKS Pro S100',
                         'BLOCKS Pro S100 0.6 nozzle',
                         'BLOCKS RD50 V2',
                         'BLOCKS RD50 V2 0.6 nozzle',
                         'BLOCKS RF50',
                         'BLOCKS RF50 0.6 nozzle'],
 'default_acceleration': '4500',
 'detect_overhang_wall': '0',
 'detect_thin_wall': '0',
 'elefant_foot_compensation': '0.1',
 'enable_prime_tower': '0',
 'enable_support': '0',
 'exclude_object': '1',
 'filename_format': '{input_filename_base}.gcode',
 'from': 'system',
 'infill_combination': '0',
 'infill_direction': '45',
 'infill_wall_overlap': '15%',
 'inherits': 'fdm_process_blocks_common',
 'initial_layer_line_width': '0.62',
 'initial_layer_print_height': '0.2',
 'inner_wall_line_width': '0.62',
 'instantiation': 'false',
 'interface_shells': '0',
 'internal_solid_infill_line_width': '0.62',
 'line_width': '0.62',
 'minimum_sparse_infill_area': '0',
 'name': 'fdm_process_common 0.6 nozzle',
 'outer_wall_line_width': '0.62',
 'prime_tower_width': '60',
 'print_sequence': 'by layer',
 'print_settings_id': '',
 'raft_layers': '0',
 'reduce_crossing_wall': '0',
 'reduce_infill_retraction': '0',
 'seam_gap': '2%',
 'seam_position': 'nearest',
 'skirt_distance': '2',
 'skirt_height': '2',
 'sparse_infill_density': '15%',
 'sparse_infill_line_width': '0.62',
 'sparse_infill_pattern': 'grid',
 'spiral_mode': '0',
 'standby_temperature_delta': '-5',
 'support_base_pattern': 'rectilinear',
 'support_base_pattern_spacing': '2',
 'support_filament': '0',
 'support_interface_filament': '0',
 'support_interface_loop_pattern': '0',
 'support_interface_spacing': '0',
 'support_interface_top_layers': '2',
 'support_line_width': '0.62',
 'support_object_xy_distance': '0.5',
 'support_on_build_plate_only': '0',
 'support_threshold_angle': '30',
 'support_top_z_distance': '0.15',
 'top_surface_line_width': '0.62',
 'travel_speed': '250',
 'type': 'process',
 'wall_infill_order': 'inner wall/outer wall/infill',
 'wall_loops': '3',
 'xy_contour_compensation': '0',
 'xy_hole_compensation': '0'}
