from __future__ import annotations

# source: profiles/Custom/filament/Generic PA @MyToolChanger.json
DATA = {'compatible_printers': ['MyToolChanger 0.4 nozzle',
                         'MyToolChanger 0.2 nozzle',
                         'MyToolChanger 0.6 nozzle',
                         'MyToolChanger 0.8 nozzle'],
 'filament_cooling_final_speed': ['3.5'],
 'filament_cooling_initial_speed': ['10'],
 'filament_cooling_moves': ['2'],
 'filament_load_time': ['10.5'],
 'filament_loading_speed': ['10'],
 'filament_loading_speed_start': ['50'],
 'filament_multitool_ramming': ['1'],
 'filament_multitool_ramming_flow': ['40'],
 'filament_stamping_distance': ['45'],
 'filament_stamping_loading_speed': ['29'],
 'filament_unload_time': ['8.5'],
 'filament_unloading_speed': ['100'],
 'from': 'system',
 'inherits': 'Generic PA @System',
 'instantiation': 'true',
 'name': 'Generic PA @MyToolChanger',
 'renamed_from': 'My Generic PA @MyToolChanger',
 'setting_id': 'GFN99_MTC_0',
 'type': 'filament'}
