from __future__ import annotations

# source: profiles/RolohaunDesign/process/fdm_process_Rook MK1 LDO_common.json
DATA = {'default_acceleration': '10000',
 'default_jerk': '9',
 'exclude_object': '1',
 'from': 'system',
 'gap_infill_speed': '200',
 'infill_jerk': '12',
 'inherits': 'fdm_process_common',
 'initial_layer_acceleration': '2000',
 'initial_layer_infill_speed': '105',
 'initial_layer_jerk': '7',
 'initial_layer_speed': '50',
 'inner_wall_acceleration': '8000',
 'inner_wall_jerk': '7',
 'inner_wall_speed': '200',
 'instantiation': 'false',
 'internal_solid_infill_speed': '300',
 'name': 'fdm_process_Rook MK1 LDO_common',
 'outer_wall_acceleration': '5000',
 'outer_wall_jerk': '7',
 'outer_wall_speed': '150',
 'sparse_infill_speed': '300',
 'top_surface_acceleration': '5000',
 'top_surface_jerk': '7',
 'top_surface_speed': '120',
 'travel_acceleration': '10000',
 'travel_jerk': '12',
 'travel_speed': '500',
 'type': 'process'}
