from __future__ import annotations

# source: profiles/InfiMech/process/0.08mm Extra Fine @InfiMech TX.json
DATA = {'bottom_shell_layers': '7',
 'brim_width': '5',
 'compatible_printers': ['InfiMech TX 0.4 nozzle'],
 'exclude_object': '1',
 'from': 'system',
 'gap_infill_speed': '120',
 'inherits': 'fdm_process_common',
 'inner_wall_acceleration': '3000',
 'inner_wall_speed': '120',
 'instantiation': 'true',
 'internal_bridge_speed': '50',
 'internal_solid_infill_speed': '150',
 'layer_height': '0.08',
 'name': '0.08mm Extra Fine @InfiMech TX',
 'outer_wall_speed': '60',
 'overhang_1_4_speed': '30',
 'overhang_2_4_speed': '30',
 'overhang_3_4_speed': '10',
 'print_settings_id': '0.08mm Extra Fine @InfiMech TX',
 'setting_id': 'GP004',
 'sparse_infill_speed': '150',
 'top_shell_layers': '9',
 'top_shell_thickness': '0.8',
 'top_surface_speed': '150',
 'tree_support_wall_count': '1',
 'type': 'process'}
