from __future__ import annotations

# source: profiles/BBL/filament/Polymaker/Fiberon PA6-GF @base.json
DATA = {'eng_plate_temp': ['40'],
 'eng_plate_temp_initial_layer': ['40'],
 'fan_cooling_layer_time': ['15'],
 'fan_max_speed': ['100'],
 'filament_cost': ['63.99'],
 'filament_density': ['1.2'],
 'filament_flow_ratio': ['0.95'],
 'filament_id': 'GFL51',
 'filament_max_volumetric_speed': ['12'],
 'filament_type': ['PA-GF'],
 'filament_vendor': ['Polymaker'],
 'from': 'system',
 'full_fan_speed_layer': ['2'],
 'hot_plate_temp': ['40'],
 'hot_plate_temp_initial_layer': ['40'],
 'inherits': 'fdm_filament_pa',
 'instantiation': 'false',
 'name': 'Fiberon PA6-GF @base',
 'nozzle_temperature': ['300'],
 'nozzle_temperature_initial_layer': ['300'],
 'nozzle_temperature_range_low': ['280'],
 'overhang_fan_speed': ['100'],
 'reduce_fan_stop_start_freq': ['1'],
 'temperature_vitrification': ['191'],
 'textured_plate_temp': ['40'],
 'textured_plate_temp_initial_layer': ['40'],
 'type': 'filament'}
