from __future__ import annotations

# source: profiles/BBL/filament/Polymaker/Panchroma PLA Satin @BBL X1C.json
DATA = {'compatible_printers': ['Bambu Lab X1 Carbon 0.4 nozzle',
                         'Bambu Lab X1 Carbon 0.6 nozzle',
                         'Bambu Lab X1 Carbon 0.8 nozzle',
                         'Bambu Lab P1S 0.4 nozzle',
                         'Bambu Lab P1S 0.6 nozzle',
                         'Bambu Lab P1S 0.8 nozzle',
                         'Bambu Lab X1E 0.4 nozzle',
                         'Bambu Lab X1E 0.6 nozzle',
                         'Bambu Lab X1E 0.8 nozzle'],
 'fan_cooling_layer_time': ['100'],
 'fan_max_speed': ['100'],
 'fan_min_speed': ['100'],
 'filament_flow_ratio': ['0.95'],
 'filament_max_volumetric_speed': ['16'],
 'from': 'system',
 'inherits': 'Panchroma PLA Satin @base',
 'instantiation': 'true',
 'name': 'Panchroma PLA Satin @BBL X1C',
 'renamed_from': 'Panchroma PLA Stain @BBL X1C',
 'setting_id': 'GFSPM005_08',
 'slow_down_layer_time': ['15'],
 'type': 'filament'}
