from __future__ import annotations

# source: profiles/Folgertech/process/0.08mm Extra Fine @FT.json
DATA = {'bottom_shell_layers': '7',
 'bridge_flow': '1',
 'compatible_printers': ['Folgertech i3 0.4 nozzle', 'Folgertech FT-5 0.4 nozzle', 'Folgertech FT-6 0.4 nozzle'],
 'elefant_foot_compensation': '0.15',
 'from': 'system',
 'gap_infill_speed': '150',
 'inherits': 'fdm_process_folgertech_common',
 'initial_layer_infill_speed': '60',
 'initial_layer_speed': '30',
 'inner_wall_speed': '100',
 'instantiation': 'true',
 'internal_solid_infill_speed': '125',
 'ironing_flow': '8%',
 'layer_height': '0.08',
 'name': '0.08mm Extra Fine @FT 0.4 nozzle',
 'outer_wall_speed': '80',
 'overhang_1_4_speed': '60',
 'overhang_2_4_speed': '30',
 'overhang_3_4_speed': '10',
 'overhang_4_4_speed': '10',
 'setting_id': 'GP001',
 'sparse_infill_speed': '125',
 'support_threshold_angle': '30',
 'top_shell_layers': '9',
 'top_surface_speed': '80',
 'type': 'process'}
