from __future__ import annotations

# source: profiles/Folgertech/process/0.12mm Fine @FT.json
DATA = {'bottom_shell_layers': '5',
 'bridge_flow': '1',
 'compatible_printers': ['Folgertech i3 0.4 nozzle', 'Folgertech FT-5 0.4 nozzle', 'Folgertech FT-6 0.4 nozzle'],
 'elefant_foot_compensation': '0.15',
 'from': 'system',
 'gap_infill_speed': '110',
 'inherits': 'fdm_process_folgertech_common',
 'initial_layer_infill_speed': '60',
 'initial_layer_speed': '30',
 'inner_wall_speed': '110',
 'instantiation': 'true',
 'internal_solid_infill_speed': '110',
 'layer_height': '0.12',
 'name': '0.12mm Fine @FT 0.4 nozzle',
 'outer_wall_speed': '70',
 'overhang_1_4_speed': '60',
 'overhang_2_4_speed': '30',
 'overhang_3_4_speed': '10',
 'overhang_4_4_speed': '10',
 'setting_id': 'GP002',
 'sparse_infill_speed': '125',
 'support_threshold_angle': '30',
 'top_shell_layers': '5',
 'top_shell_thickness': '0.6',
 'top_surface_speed': '70',
 'type': 'process'}
