from __future__ import annotations

# source: profiles/Folgertech/process/0.24mm Draft @FT.json
DATA = {'bottom_shell_layers': '3',
 'bridge_flow': '1',
 'compatible_printers': ['Folgertech i3 0.4 nozzle', 'Folgertech FT-5 0.4 nozzle', 'Folgertech FT-6 0.4 nozzle'],
 'elefant_foot_compensation': '0.15',
 'from': 'system',
 'gap_infill_speed': '80',
 'inherits': 'fdm_process_folgertech_common',
 'initial_layer_infill_speed': '50',
 'initial_layer_speed': '40',
 'inner_wall_speed': '80',
 'instantiation': 'true',
 'internal_solid_infill_speed': '80',
 'layer_height': '0.24',
 'name': '0.24mm Draft @FT 0.4 nozzle',
 'outer_wall_speed': '70',
 'setting_id': 'GP005',
 'sparse_infill_speed': '80',
 'support_threshold_angle': '30',
 'top_shell_layers': '3',
 'top_shell_thickness': '0.6',
 'top_surface_line_width': '0.45',
 'top_surface_speed': '70',
 'type': 'process'}
