from __future__ import annotations

# source: profiles/Folgertech/process/0.36mm Draft @FT 0.6 nozzle.json
DATA = {'bottom_shell_layers': '3',
 'bridge_flow': '1',
 'bridge_speed': '30',
 'compatible_printers': ['Folgertech i3 0.6 nozzle', 'Folgertech FT-5 0.6 nozzle', 'Folgertech FT-6 0.6 nozzle'],
 'from': 'system',
 'gap_infill_speed': '40',
 'inherits': 'fdm_process_folgertech_common',
 'initial_layer_infill_speed': '55',
 'initial_layer_line_width': '0.62',
 'initial_layer_print_height': '0.3',
 'initial_layer_speed': '35',
 'inner_wall_line_width': '0.62',
 'inner_wall_speed': '80',
 'instantiation': 'true',
 'internal_solid_infill_line_width': '0.62',
 'internal_solid_infill_speed': '80',
 'layer_height': '0.36',
 'line_width': '0.62',
 'name': '0.36mm Draft @FT 0.6 nozzle',
 'outer_wall_line_width': '0.62',
 'outer_wall_speed': '60',
 'overhang_1_4_speed': '0',
 'overhang_2_4_speed': '50',
 'overhang_3_4_speed': '15',
 'overhang_4_4_speed': '10',
 'setting_id': 'GP030',
 'sparse_infill_line_width': '0.62',
 'sparse_infill_speed': '60',
 'support_line_width': '0.62',
 'top_shell_layers': '3',
 'top_surface_line_width': '0.62',
 'top_surface_speed': '60',
 'type': 'process',
 'wall_loops': '2'}
