from __future__ import annotations

# source: profiles/Snapmaker/machine/fdm_a350.json
DATA = {'bed_model': 'Snapmaker A350_bed.stl',
 'bed_texture': 'Snapmaker A350_texture.svg',
 'before_layer_change_gcode': '; layer_num: [layer_num]\nG92 E0',
 'from': 'system',
 'inherits': 'fdm_linear2',
 'instantiation': 'false',
 'machine_end_gcode': 'G92 E0\n'
                      '\n'
                      'G0 Z{max_layer_z + 2.0} F600\n'
                      '; retract the filament to make it easier to replace\n'
                      'G0 E-5 F200\n'
                      'G28\n'
                      '\n'
                      '  M104 S0\n'
                      'M140 S0\n'
                      'M107\n'
                      'M220 S100\n'
                      'M84\n'
                      '\n'
                      ';\n'
                      "; DON'T REMOVE these lines if you're using the smfix (https://github.com/macdylan/SMFix)\n"
                      '; min_x = [first_layer_print_min_0]\n'
                      '; min_y = [first_layer_print_min_1]\n'
                      '; max_x = [first_layer_print_max_0]\n'
                      '; max_y = [first_layer_print_max_1]\n'
                      '; max_z = [max_layer_z]\n'
                      '; total_layer_number = [layer_num]\n'
                      ';',
 'machine_start_gcode': '; Model: Snapmaker A350\n'
                        '; Update: 20240922\n'
                        '; Maintained by https://github.com/macdylan/3dp-configs\n'
                        '; Printer : [printer_preset]\n'
                        '; Profile : [print_preset]\n'
                        '; Plate   : [plate_name]\n'
                        '\n'
                        'T[initial_extruder]\n'
                        '\n'
                        'M140 S{first_layer_bed_temperature[initial_extruder]}\n'
                        '\n'
                        '; you can clean the nozzle\n'
                        'M104 S165\n'
                        'M204 S100\n'
                        'G28\n'
                        'G0 Z216 F960.0\n'
                        'G0 Y175.0 F3420.0\n'
                        'G0 X160.0\n'
                        '\n'
                        'M190 R{first_layer_bed_temperature[initial_extruder]}\n'
                        '\n'
                        'G28\n'
                        '{if 0==1} ; boundary check(for dual/quick swap kit), not recommanded if there are any '
                        'clamps \n'
                        '  G0 X0\n'
                        '  G0 Z0.2 F960.0\n'
                        '  G0 Y0 F3420.0\n'
                        '  G0 X320\n'
                        '  G0 Y350\n'
                        '  G0 X0\n'
                        '  G0 Y0\n'
                        '{endif}\n'
                        '\n'
                        'M83\n'
                        '{if 1==1 && max(hot_plate_temp_initial_layer[initial_extruder], '
                        'hot_plate_temp[initial_extruder]) >= 90}\n'
                        'G0 Z0.06\n'
                        'G92 Z0 ;reset z\n'
                        '{endif}\n'
                        '\n'
                        '; flush initial nozzle\n'
                        'T[initial_extruder]\n'
                        'M104 S{max(250, min(290, nozzle_temperature_initial_layer[(initial_extruder % 2 == 0 ? '
                        'min(initial_extruder + initial_extruder, 63) : max(initial_extruder - (1-initial_extruder), '
                        '0))] + 15))}; common flush temp\n'
                        'G0 Z1.6 F960.0\n'
                        'G0 X{( initial_extruder % 2 == 0 ? 145.0 : 175.0 )} F3420.0\n'
                        'G0 Y0 F3420.0\n'
                        '\n'
                        'M109 S{max(250, min(290, nozzle_temperature_initial_layer[(initial_extruder % 2 == 0 ? '
                        'min(initial_extruder + initial_extruder, 63) : max(initial_extruder - (1-initial_extruder), '
                        '0))] + 15))} C2 W1\n'
                        'G1 E15 F80.0\n'
                        'G92 E0\n'
                        '\n'
                        'M106 S{min(255, (fan_max_speed[(initial_extruder % 2 == 0 ? min(initial_extruder + '
                        'initial_extruder, 63) : max(initial_extruder - (1-initial_extruder), 0))] + 10) * 2.55)}\n'
                        '\n'
                        'M104 S{nozzle_temperature_initial_layer[(initial_extruder % 2 == 0 ? min(initial_extruder + '
                        'initial_extruder, 63) : max(initial_extruder - (1-initial_extruder), 0))] + 5}\n'
                        '\n'
                        'G1 E9.0 F200\n'
                        'G92 E0\n'
                        'G1 E6.0 Z4.6 F200\n'
                        'G92 E0\n'
                        '\n'
                        'G0 Z5.6 F200\n'
                        'M107\n'
                        '\n'
                        'G0 X{( initial_extruder % 2 == 0 ? 100.0 : 220.0 )} F3420.0\n'
                        'G0 Z0.3 F960.0\n'
                        'M109 S{nozzle_temperature_initial_layer[(initial_extruder % 2 == 0 ? min(initial_extruder + '
                        'initial_extruder, 63) : max(initial_extruder - (1-initial_extruder), 0))]} C3 W1\n'
                        'G1 E3 F200\n'
                        'G92 E0\n'
                        'G1 X{( initial_extruder % 2 == 0 ? 0 : 320 )} E6.23628 F3420.0\n'
                        'G92 E0\n'
                        '\n'
                        'G1 E-{retraction_length[initial_extruder]} F200\n'
                        'G92 E0\n'
                        'G0 Y20 F3420.0\n'
                        '\n'
                        '; ready [plate_name]',
 'name': 'fdm_a350',
 'printable_area': ['0x0', '320x0', '320x350', '0x350'],
 'printable_height': '325',
 'printer_notes': 'PRINTER_MODEL_SNAPMAKER_A350\n',
 'type': 'machine'}
