from __future__ import annotations

# source: profiles/Snapmaker/machine/fdm_common.json
DATA = {'auxiliary_fan': '0',
 'cooling_tube_length': '0',
 'cooling_tube_retraction': '0',
 'deretraction_speed': ['45'],
 'enable_filament_ramming': '0',
 'extra_loading_move': '-2',
 'fan_speedup_overhangs': ['1'],
 'from': 'system',
 'gcode_flavor': 'marlin2',
 'high_current_on_filament_swap': '0',
 'instantiation': 'false',
 'name': 'fdm_common',
 'nozzle_type': 'hardened_steel',
 'nozzle_volume': '0',
 'parking_pos_retraction': '0',
 'pause_gcode': 'M600 ;pause print',
 'purge_in_prime_tower': '0',
 'remaining_times': '1',
 'retract_before_wipe': ['0%'],
 'retract_when_changing_layer': ['1'],
 'retraction_length': ['0.8'],
 'retraction_minimum_travel': ['1'],
 'retraction_speed': ['45'],
 'silent_mode': '0',
 'single_extruder_multi_material': '0',
 'type': 'machine',
 'use_relative_e_distances': '1',
 'wipe': ['0'],
 'wipe_distance': ['1'],
 'z_hop': ['0.4'],
 'z_hop_types': ['Auto Lift']}
