from __future__ import annotations

# source: profiles/iQ/process/0.20mm Standard @iQ TiQ8 P1 - ABS Natur Material4Print (0.4 Nozzle).json
DATA = {'bottom_shell_layers': '4',
 'bridge_flow': '1.4',
 'bridge_speed': '100',
 'brim_object_gap': '0.05',
 'brim_type': 'outer_only',
 'compatible_printers': ['iQ TiQ8 0.4 Nozzle'],
 'default_acceleration': '600',
 'enable_overhang_speed': '0',
 'enable_prime_tower': '0',
 'enable_support': '1',
 'exclude_object': '0',
 'from': 'system',
 'gcode_label_objects': '0',
 'independent_support_layer_height': '1',
 'inherits': 'fdm_process_tiq_common',
 'initial_layer_infill_speed': '80',
 'initial_layer_speed': '80',
 'inner_wall_acceleration': '600',
 'inner_wall_speed': '140',
 'instantiation': 'true',
 'internal_bridge_speed': '50%',
 'internal_solid_infill_speed': '50',
 'ironing_pattern': 'concentric',
 'layer_height': '0.2',
 'name': '0.20mm Standard @iQ TiQ8 P1 - ABS Natur Material4Print (0.4 Nozzle)',
 'notes': 'Process file version 1.0 20250620',
 'outer_wall_acceleration': '600',
 'outer_wall_speed': '90',
 'prime_tower_width': '80',
 'print_settings_id': '0.20mm Standard @iQ TiQ8 P1 - ABS Natur Material4Print (0.4 Nozzle)',
 'raft_first_layer_expansion': '3',
 'reduce_crossing_wall': '1',
 'skirt_height': '3',
 'skirt_loops': '2',
 'slow_down_layers': '1',
 'small_perimeter_speed': '5%',
 'small_perimeter_threshold': '0',
 'sparse_infill_acceleration': '50',
 'sparse_infill_density': '35%',
 'sparse_infill_pattern': 'triangles',
 'sparse_infill_speed': '160',
 'support_angle': '45',
 'support_base_pattern': 'default',
 'support_base_pattern_spacing': '3',
 'support_bottom_interface_spacing': '0',
 'support_bottom_z_distance': '0.5',
 'support_expansion': '1',
 'support_filament': '1',
 'support_interface_filament': '1',
 'support_interface_pattern': 'auto',
 'support_interface_spacing': '0.2',
 'support_interface_speed': '100',
 'support_object_xy_distance': '0.04',
 'support_on_build_plate_only': '0',
 'support_speed': '300',
 'support_threshold_angle': '35',
 'support_top_z_distance': '0.2',
 'support_type': 'normal(auto)',
 'top_shell_thickness': '0',
 'top_solid_infill_flow_ratio': '0.98',
 'top_surface_acceleration': '600',
 'top_surface_speed': '140',
 'travel_acceleration': '600',
 'travel_speed': '300',
 'tree_support_branch_diameter_angle': '10',
 'tree_support_branch_diameter_organic': '3',
 'tree_support_tip_diameter': '2',
 'type': 'process',
 'wall_loops': '2'}
