from __future__ import annotations

# source: profiles/Folgertech.json
DATA = {'description': 'Folgertech configurations',
 'filament_list': [],
 'force_update': '0',
 'machine_list': [{'name': 'fdm_machine_common', 'sub_path': 'machine/fdm_machine_common.json'},
                  {'name': 'fdm_folgertech_common', 'sub_path': 'machine/fdm_folgertech_common.json'},
                  {'name': 'Folgertech FT-5 0.4 nozzle', 'sub_path': 'machine/Folgertech FT-5 0.4 nozzle.json'},
                  {'name': 'Folgertech FT-5 0.6 nozzle', 'sub_path': 'machine/Folgertech FT-5 0.6 nozzle.json'},
                  {'name': 'Folgertech FT-6 0.4 nozzle', 'sub_path': 'machine/Folgertech FT-6 0.4 nozzle.json'},
                  {'name': 'Folgertech FT-6 0.6 nozzle', 'sub_path': 'machine/Folgertech FT-6 0.6 nozzle.json'},
                  {'name': 'Folgertech i3 0.4 nozzle', 'sub_path': 'machine/Folgertech i3 0.4 nozzle.json'},
                  {'name': 'Folgertech i3 0.6 nozzle', 'sub_path': 'machine/Folgertech i3 0.6 nozzle.json'}],
 'machine_model_list': [{'name': 'Folgertech FT-5', 'sub_path': 'machine/Folgertech FT-5.json'},
                        {'name': 'Folgertech FT-6', 'sub_path': 'machine/Folgertech FT-6.json'},
                        {'name': 'Folgertech i3', 'sub_path': 'machine/Folgertech i3.json'}],
 'name': 'Folgertech',
 'process_list': [{'name': 'fdm_process_common', 'sub_path': 'process/fdm_process_common.json'},
                  {'name': 'fdm_process_folgertech_common', 'sub_path': 'process/fdm_process_folgertech_common.json'},
                  {'name': '0.08mm Extra Fine @FT 0.4 nozzle', 'sub_path': 'process/0.08mm Extra Fine @FT.json'},
                  {'name': '0.12mm Fine @FT 0.4 nozzle', 'sub_path': 'process/0.12mm Fine @FT.json'},
                  {'name': '0.16mm Optimal @FT 0.4 nozzle', 'sub_path': 'process/0.16mm Optimal @FT.json'},
                  {'name': '0.18mm Fine @FT 0.6 nozzle', 'sub_path': 'process/0.18mm Fine @FT 0.6 nozzle.json'},
                  {'name': '0.20mm Standard @FT 0.4 nozzle', 'sub_path': 'process/0.20mm Standard @FT.json'},
                  {'name': '0.20mm Strength @FT 0.4 nozzle', 'sub_path': 'process/0.20mm Strength @FT.json'},
                  {'name': '0.24mm Draft @FT 0.4 nozzle', 'sub_path': 'process/0.24mm Draft @FT.json'},
                  {'name': '0.24mm Optimal @FT 0.6 nozzle', 'sub_path': 'process/0.24mm Optimal @FT 0.6 nozzle.json'},
                  {'name': '0.28mm Extra Draft @FT 0.4 nozzle', 'sub_path': 'process/0.28mm Extra Draft @FT.json'},
                  {'name': '0.30mm Standard @FT 0.6 nozzle', 'sub_path': 'process/0.30mm Standard @FT 0.6 nozzle.json'},
                  {'name': '0.30mm Strength @FT 0.6 nozzle', 'sub_path': 'process/0.30mm Strength @FT 0.6 nozzle.json'},
                  {'name': '0.36mm Draft @FT 0.6 nozzle', 'sub_path': 'process/0.36mm Draft @FT 0.6 nozzle.json'},
                  {'name': '0.42mm Extra Draft @FT 0.6 nozzle',
                   'sub_path': 'process/0.42mm Extra Draft @FT 0.6 nozzle.json'}],
 'version': '02.03.01.10'}
