from __future__ import annotations

# source: profiles/Volumic/filament/fdm_filament_pa.json
DATA = {'close_fan_the_first_x_layers': ['3'],
 'cool_plate_temp': ['65'],
 'cool_plate_temp_initial_layer': ['65'],
 'eng_plate_temp': ['65'],
 'eng_plate_temp_initial_layer': ['65'],
 'fan_cooling_layer_time': ['4'],
 'fan_max_speed': ['50'],
 'fan_min_speed': ['0'],
 'filament_cost': ['37.50'],
 'filament_density': ['1.04'],
 'filament_max_volumetric_speed': ['20'],
 'filament_type': ['PA'],
 'from': 'system',
 'hot_plate_temp': ['65'],
 'hot_plate_temp_initial_layer': ['65'],
 'inherits': 'fdm_filament_common',
 'instantiation': 'false',
 'name': 'fdm_filament_pa',
 'nozzle_temperature': ['235'],
 'nozzle_temperature_initial_layer': ['238'],
 'overhang_fan_speed': ['50'],
 'reduce_fan_stop_start_freq': ['0'],
 'slow_down_for_layer_cooling': ['1'],
 'slow_down_layer_time': ['2'],
 'slow_down_min_speed': ['10'],
 'textured_plate_temp': ['65'],
 'textured_plate_temp_initial_layer': ['65'],
 'type': 'filament'}
