from __future__ import annotations

# source: profiles/Volumic/filament/fdm_filament_tpu.json
DATA = {'additional_cooling_fan_speed': ['70'],
 'close_fan_the_first_x_layers': ['1'],
 'cool_plate_temp': ['45'],
 'cool_plate_temp_initial_layer': ['30'],
 'eng_plate_temp': ['45'],
 'eng_plate_temp_initial_layer': ['30'],
 'fan_cooling_layer_time': ['100'],
 'fan_max_speed': ['100'],
 'fan_min_speed': ['100'],
 'filament_cost': ['37.50'],
 'filament_density': ['1.24'],
 'filament_max_volumetric_speed': ['5'],
 'filament_type': ['TPU'],
 'from': 'system',
 'hot_plate_temp': ['45'],
 'hot_plate_temp_initial_layer': ['30'],
 'inherits': 'fdm_filament_common',
 'instantiation': 'false',
 'name': 'fdm_filament_tpu',
 'nozzle_temperature': ['235'],
 'overhang_fan_speed': ['100'],
 'reduce_fan_stop_start_freq': ['1'],
 'slow_down_for_layer_cooling': ['1'],
 'textured_plate_temp': ['45'],
 'textured_plate_temp_initial_layer': ['30'],
 'type': 'filament'}
