from __future__ import annotations

# source: profiles/Volumic/filament/fdm_filament_abs.json
DATA = {'close_fan_the_first_x_layers': ['3'],
 'cool_plate_temp': ['90'],
 'cool_plate_temp_initial_layer': ['90'],
 'eng_plate_temp': ['90'],
 'eng_plate_temp_initial_layer': ['90'],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['30'],
 'fan_min_speed': ['0'],
 'filament_cost': ['37.50'],
 'filament_density': ['1.04'],
 'filament_max_volumetric_speed': ['42'],
 'filament_type': ['ABS'],
 'from': 'system',
 'hot_plate_temp': ['90'],
 'hot_plate_temp_initial_layer': ['90'],
 'inherits': 'fdm_filament_common',
 'instantiation': 'false',
 'name': 'fdm_filament_abs',
 'nozzle_temperature': ['235'],
 'nozzle_temperature_initial_layer': ['235'],
 'overhang_fan_speed': ['70'],
 'reduce_fan_stop_start_freq': ['1'],
 'slow_down_for_layer_cooling': ['1'],
 'slow_down_layer_time': ['3'],
 'slow_down_min_speed': ['10'],
 'textured_plate_temp': ['90'],
 'textured_plate_temp_initial_layer': ['90'],
 'type': 'filament'}
