from __future__ import annotations

# source: profiles/Volumic/filament/fdm_filament_pet.json
DATA = {'close_fan_the_first_x_layers': ['1'],
 'cool_plate_temp': ['60'],
 'cool_plate_temp_initial_layer': ['60'],
 'eng_plate_temp': ['60'],
 'eng_plate_temp_initial_layer': ['60'],
 'fan_cooling_layer_time': ['20'],
 'fan_max_speed': ['80'],
 'fan_min_speed': ['30'],
 'filament_cost': ['37.50'],
 'filament_density': ['1.27'],
 'filament_max_volumetric_speed': ['42'],
 'filament_type': ['PETG'],
 'from': 'system',
 'hot_plate_temp': ['60'],
 'hot_plate_temp_initial_layer': ['60'],
 'inherits': 'fdm_filament_common',
 'instantiation': 'false',
 'name': 'fdm_filament_pet',
 'nozzle_temperature': ['230'],
 'nozzle_temperature_initial_layer': ['235'],
 'overhang_fan_speed': ['100'],
 'reduce_fan_stop_start_freq': ['1'],
 'slow_down_for_layer_cooling': ['1'],
 'textured_plate_temp': ['60'],
 'textured_plate_temp_initial_layer': ['60'],
 'type': 'filament'}
