from __future__ import annotations

# source: profiles/Volumic/filament/fdm_filament_pva.json
DATA = {'close_fan_the_first_x_layers': ['1'],
 'cool_plate_temp': ['60'],
 'cool_plate_temp_initial_layer': ['60'],
 'eng_plate_temp': ['60'],
 'eng_plate_temp_initial_layer': ['60'],
 'fan_cooling_layer_time': ['100'],
 'fan_max_speed': ['70'],
 'fan_min_speed': ['40'],
 'filament_cost': ['37.50'],
 'filament_density': ['1.24'],
 'filament_is_support': ['1'],
 'filament_max_volumetric_speed': ['15'],
 'filament_soluble': ['1'],
 'filament_type': ['PVA'],
 'from': 'system',
 'hot_plate_temp': ['60'],
 'hot_plate_temp_initial_layer': ['60'],
 'inherits': 'fdm_filament_common',
 'instantiation': 'false',
 'name': 'fdm_filament_pva',
 'nozzle_temperature': ['220'],
 'nozzle_temperature_initial_layer': ['220'],
 'overhang_fan_speed': ['80'],
 'reduce_fan_stop_start_freq': ['1'],
 'slow_down_for_layer_cooling': ['1'],
 'slow_down_layer_time': ['4'],
 'slow_down_min_speed': ['10'],
 'textured_plate_temp': ['60'],
 'textured_plate_temp_initial_layer': ['60'],
 'type': 'filament'}
