from __future__ import annotations

# source: profiles/Volumic/filament/fdm_filament_common.json
DATA = {'bed_type': ['Hot Plate'],
 'close_fan_the_first_x_layers': ['1'],
 'cool_plate_temp': ['50'],
 'cool_plate_temp_initial_layer': ['50'],
 'eng_plate_temp': ['50'],
 'eng_plate_temp_initial_layer': ['50'],
 'fan_cooling_layer_time': ['60'],
 'fan_max_speed': ['100'],
 'fan_min_speed': ['60'],
 'filament_cost': ['37.50'],
 'filament_density': ['1'],
 'filament_diameter': ['1.75'],
 'filament_max_volumetric_speed': ['42'],
 'filament_minimal_purge_on_wipe_tower': ['15'],
 'filament_type': ['PLA'],
 'filament_vendor': ['Volumic'],
 'from': 'system',
 'full_fan_speed_layer': ['0'],
 'hot_plate_temp': ['50'],
 'hot_plate_temp_initial_layer': ['50'],
 'instantiation': 'false',
 'name': 'fdm_filament_common',
 'nozzle_temperature': ['210'],
 'nozzle_temperature_initial_layer': ['210'],
 'overhang_fan_speed': ['100'],
 'slow_down_for_layer_cooling': ['1'],
 'slow_down_layer_time': ['8'],
 'slow_down_min_speed': ['10'],
 'textured_plate_temp': ['50'],
 'textured_plate_temp_initial_layer': ['50'],
 'type': 'filament'}
