from __future__ import annotations

# source: profiles/Volumic/filament/Volumic FLEX93 Ultra.json
DATA = {'compatible_printers': ['EXO42 (0.4 nozzle)',
                         'EXO65 (0.6 nozzle)',
                         'SH65 (0.4 nozzle)',
                         'VS30MK3 (0.4 nozzle)',
                         'VS30SC2 (0.4 nozzle)',
                         'VS30SC (0.4 nozzle)',
                         'VS30ULTRA (0.4 nozzle)',
                         'VS30MK2 (0.4 nozzle)',
                         'VS20MK2 (0.4 nozzle)',
                         'EXO42 Stage 2 (0.4 nozzle)',
                         'EXO65 Stage 2 (0.6 nozzle)',
                         'SH65 Stage 2 (0.4 nozzle)',
                         'VS30SC2 Stage 2 (0.4 nozzle)',
                         'VS30MK3 Stage 2 (0.4 nozzle)'],
 'fan_max_speed': ['100'],
 'fan_min_speed': ['80'],
 'filament_flow_ratio': ['1.20'],
 'filament_id': 'GFU99',
 'filament_max_volumetric_speed': ['5'],
 'from': 'system',
 'hot_plate_temp': ['45'],
 'inherits': 'fdm_filament_tpu',
 'instantiation': 'true',
 'name': 'Volumic FLEX93 Ultra',
 'nozzle_temperature': ['235'],
 'setting_id': 'GFSR99',
 'type': 'filament'}
