from __future__ import annotations

# source: profiles/Volumic/filament/Volumic ASA Ultra Performance.json
DATA = {'compatible_printers': ['EXO42 Performance (0.4 nozzle)',
                         'EXO65 Performance (0.4 nozzle)',
                         'EXO65 Performance (0.6 nozzle)',
                         'EXO65 Performance (0.8 nozzle)',
                         'SH65 Performance (0.4 nozzle)',
                         'EXO42 IDRE (0.4 nozzle)',
                         'EXO42 IDRE COPY MODE (0.4 nozzle)',
                         'EXO42 IDRE MIRROR MODE (0.4 nozzle)',
                         'EXO65 IDRE (0.4 nozzle)',
                         'EXO65 IDRE COPY MODE (0.4 nozzle)',
                         'EXO65 IDRE MIRROR MODE (0.4 nozzle)',
                         'SH65 IDRE (0.4 nozzle)',
                         'SH65 IDRE COPY MODE (0.4 nozzle)',
                         'SH65 IDRE MIRROR MODE (0.4 nozzle)'],
 'fan_max_speed': ['30'],
 'fan_min_speed': ['30'],
 'filament_flow_ratio': ['0.96'],
 'filament_id': 'GFB99',
 'filament_max_volumetric_speed': ['50'],
 'from': 'system',
 'hot_plate_temp': ['85'],
 'inherits': 'fdm_filament_asa',
 'instantiation': 'true',
 'name': 'Volumic ASA Ultra (Performance)',
 'nozzle_temperature': ['245'],
 'nozzle_temperature_initial_layer': ['245'],
 'setting_id': 'GFSA04',
 'type': 'filament'}
