from __future__ import annotations

# source: profiles/Volumic/filament/Volumic PC.json
DATA = {'compatible_printers': ['EXO42 (0.4 nozzle)',
                         'EXO65 (0.6 nozzle)',
                         'SH65 (0.4 nozzle)',
                         'VS30MK3 (0.4 nozzle)',
                         'VS30SC2 (0.4 nozzle)',
                         'VS30SC (0.4 nozzle)',
                         'VS30ULTRA (0.4 nozzle)',
                         'VS30MK2 (0.4 nozzle)',
                         'VS20MK2 (0.4 nozzle)',
                         'EXO42 Stage 2 (0.4 nozzle)',
                         'EXO65 Stage 2 (0.6 nozzle)',
                         'SH65 Stage 2 (0.4 nozzle)',
                         'VS30SC2 Stage 2 (0.4 nozzle)',
                         'VS30MK3 Stage 2 (0.4 nozzle)'],
 'fan_max_speed': ['0'],
 'fan_min_speed': ['0'],
 'filament_flow_ratio': ['1.00'],
 'filament_id': 'GFC99',
 'filament_max_volumetric_speed': ['22'],
 'from': 'system',
 'hot_plate_temp': ['115'],
 'inherits': 'fdm_filament_pc',
 'instantiation': 'true',
 'name': 'Volumic PC',
 'nozzle_temperature': ['270'],
 'setting_id': 'GFSC99',
 'type': 'filament'}
