from __future__ import annotations

# source: profiles/Dremel/process/.20mm Standard @Dremel 3D20 0.4.json
DATA = {'adaptive_layer_height': '0',
 'bottom_shell_layers': '4',
 'bottom_shell_thickness': '0',
 'bottom_surface_pattern': 'monotonic',
 'bridge_flow': '0.95',
 'bridge_no_support': '0',
 'bridge_speed': '25',
 'brim_object_gap': '0.1',
 'brim_width': '5',
 'compatible_printers': ['Dremel 3D20 0.4 nozzle'],
 'default_acceleration': '5000',
 'detect_overhang_wall': '1',
 'enable_support': '1',
 'filename_format': '{input_filename_base}_{filament_type[0]}_{print_time}.gcode',
 'from': 'system',
 'gap_infill_speed': '50',
 'infill_combination': '1',
 'infill_direction': '45',
 'infill_wall_overlap': '25%',
 'inherits': 'fdm_process_dremel_common',
 'initial_layer_acceleration': '2000',
 'initial_layer_infill_speed': '35%',
 'initial_layer_line_width': '0.42',
 'initial_layer_print_height': '0.2',
 'initial_layer_speed': '50',
 'inner_wall_acceleration': '5000',
 'inner_wall_line_width': '0.45',
 'inner_wall_speed': '60',
 'instantiation': 'true',
 'internal_bridge_support_thickness': '0.8',
 'internal_solid_infill_line_width': '0.4',
 'internal_solid_infill_speed': '60',
 'ironing_flow': '15%',
 'ironing_spacing': '0.1',
 'ironing_speed': '15',
 'ironing_type': 'no ironing',
 'layer_height': '0.2',
 'line_width': '0.45',
 'max_travel_detour_distance': '0',
 'minimum_sparse_infill_area': '10',
 'name': '.20mm Standard @Dremel 3D20 0.4',
 'only_one_wall_top': '1',
 'outer_wall_acceleration': '2500',
 'outer_wall_line_width': '0.45',
 'outer_wall_speed': '60',
 'overhang_1_4_speed': '0',
 'overhang_2_4_speed': '20',
 'overhang_3_4_speed': '15',
 'overhang_4_4_speed': '10',
 'print_sequence': 'by layer',
 'raft_first_layer_density': '10%',
 'raft_first_layer_expansion': '1.5',
 'reduce_infill_retraction': '1',
 'resolution': '0.012',
 'seam_position': 'aligned',
 'skirt_distance': '2',
 'skirt_height': '1',
 'skirt_loops': '3',
 'slow_down_layers': '2',
 'sparse_infill_density': '18%',
 'sparse_infill_line_width': '0.45',
 'sparse_infill_pattern': 'crosshatch',
 'sparse_infill_speed': '60',
 'support_base_pattern': 'default',
 'support_base_pattern_spacing': '3.5',
 'support_bottom_z_distance': '0.4',
 'support_expansion': '1.5',
 'support_interface_bottom_layers': '1',
 'support_interface_pattern': 'auto',
 'support_interface_spacing': '0.2',
 'support_interface_speed': '100%',
 'support_interface_top_layers': '3',
 'support_line_width': '0.38',
 'support_object_xy_distance': '60%',
 'support_speed': '50',
 'support_threshold_angle': '30',
 'support_top_z_distance': '0.3',
 'top_shell_layers': '4',
 'top_shell_thickness': '0.8',
 'top_surface_acceleration': '1000',
 'top_surface_line_width': '0.4',
 'top_surface_pattern': 'monotonicline',
 'top_surface_speed': '50',
 'travel_acceleration': '5000',
 'travel_speed': '100',
 'type': 'process',
 'wall_distribution_count': '2',
 'wall_generator': 'arachne',
 'wall_infill_order': 'inner wall/outer wall/infill',
 'wall_loops': '3'}
