from __future__ import annotations

# source: profiles/Sovol/filament/Generic PC @Sovol SV08 MAX.json
DATA = {'activate_air_filtration': ['0'],
 'additional_cooling_fan_speed': '0',
 'close_fan_the_first_x_layers': '3',
 'compatible_printers': ['Sovol SV08 MAX 0.4 nozzle', 'Sovol SV08 MAX 0.6 nozzle', 'Sovol SV08 MAX 0.8 nozzle'],
 'complete_print_exhaust_fan_speed': '50',
 'dont_slow_down_outer_wall': '0',
 'during_print_exhaust_fan_speed': '50',
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['40'],
 'fan_min_speed': ['10'],
 'filament_flow_ratio': ['0.98'],
 'filament_id': 'GFL99',
 'filament_max_volumetric_speed': ['18'],
 'from': 'system',
 'full_fan_speed_layer': ['3'],
 'hot_plate_temp': ['100'],
 'hot_plate_temp_initial_layer': ['100'],
 'inherits': 'Generic PC @System',
 'instantiation': 'true',
 'name': 'Generic PC @Sovol SV08 MAX',
 'nozzle_temperature': ['260'],
 'nozzle_temperature_initial_layer': ['280'],
 'nozzle_temperature_range_high': ['350'],
 'nozzle_temperature_range_low': ['190'],
 'overhang_fan_speed': ['60'],
 'overhang_fan_threshold': ['25%'],
 'setting_id': 'GFSA04',
 'slow_down_layer_time': ['12'],
 'slow_down_min_speed': ['10'],
 'temperature_vitrification': ['60'],
 'type': 'filament'}
