from __future__ import annotations

# source: profiles/Sovol/filament/Generic PLA Silk @Sovol SV08 MAX.json
DATA = {'activate_air_filtration': ['0'],
 'additional_cooling_fan_speed': '75%',
 'compatible_printers': ['Sovol SV08 MAX 0.4 nozzle', 'Sovol SV08 MAX 0.6 nozzle', 'Sovol SV08 MAX 0.8 nozzle'],
 'complete_print_exhaust_fan_speed': '50%',
 'dont_slow_down_outer_wall': '0',
 'during_print_exhaust_fan_speed': '50%',
 'enable_pressure_advance': '1',
 'fan_cooling_layer_time': ['50'],
 'fan_max_speed': ['100'],
 'fan_min_speed': ['80'],
 'filament_flow_ratio': ['0.98'],
 'filament_id': 'GFL99',
 'filament_max_volumetric_speed': ['15'],
 'filament_z_hop': '0.4',
 'from': 'system',
 'full_fan_speed_layer': ['3'],
 'hot_plate_temp': ['65'],
 'hot_plate_temp_initial_layer': ['65'],
 'inherits': 'Generic PLA @System',
 'instantiation': 'true',
 'name': 'Generic PLA Silk @Sovol SV08 MAX',
 'nozzle_temperature': ['230'],
 'nozzle_temperature_initial_layer': ['250'],
 'nozzle_temperature_range_high': ['250'],
 'nozzle_temperature_range_low': ['190'],
 'overhang_fan_speed': ['100'],
 'overhang_fan_threshold': ['50%'],
 'pressure_advance': '0.038',
 'setting_id': 'GFSA04',
 'slow_down_layer_time': ['6'],
 'slow_down_min_speed': ['10'],
 'temperature_vitrification': ['60'],
 'type': 'filament'}
