from __future__ import annotations

# source: profiles/Sovol/filament/Sovol SV06 Plus ACE PLA.json
DATA = {'compatible_printers': ['Sovol SV06 Plus ACE 0.4 nozzle'],
 'fan_cooling_layer_time': ['80'],
 'fan_max_speed': ['80'],
 'fan_min_speed': ['50'],
 'filament_flow_ratio': ['0.98'],
 'filament_id': 'GFL99',
 'filament_max_volumetric_speed': ['21'],
 'from': 'system',
 'full_fan_speed_layer': ['3'],
 'hot_plate_temp': ['60'],
 'hot_plate_temp_initial_layer': ['60'],
 'inherits': 'Generic PLA @System',
 'instantiation': 'true',
 'name': 'Sovol SV06 Plus ACE PLA',
 'nozzle_temperature': ['210'],
 'nozzle_temperature_initial_layer': ['235'],
 'nozzle_temperature_range_high': ['300'],
 'nozzle_temperature_range_low': ['190'],
 'setting_id': 'GFSA04',
 'slow_down_layer_time': ['6'],
 'slow_down_min_speed': ['20'],
 'type': 'filament'}
