from __future__ import annotations

# source: profiles/Sovol/filament/Sovol Zero PETG HS Nozzle.json
DATA = {'activate_air_filtration': '1',
 'close_fan_the_first_x_layers': ['1'],
 'compatible_printers': ['Sovol Zero 0.4 nozzle'],
 'complete_print_exhaust_fan_speed': '50',
 'during_print_exhaust_fan_speed': '50',
 'enable_pressure_advance': '1',
 'fan_cooling_layer_time': ['50'],
 'fan_max_speed': ['40'],
 'fan_min_speed': ['10'],
 'filament_flow_ratio': ['0.98'],
 'filament_id': 'GFL99',
 'filament_max_volumetric_speed': ['15'],
 'filament_retraction_length': ['0.5'],
 'filament_z_hop': ['0.4'],
 'from': 'system',
 'full_fan_speed_layer': ['3'],
 'hot_plate_temp': ['85'],
 'hot_plate_temp_initial_layer': ['85'],
 'inherits': 'Generic PETG @System',
 'instantiation': 'true',
 'name': 'Sovol Zero PETG HS Nozzle',
 'nozzle_temperature': ['250'],
 'nozzle_temperature_initial_layer': ['265'],
 'nozzle_temperature_range_high': ['280'],
 'nozzle_temperature_range_low': ['230'],
 'overhang_fan_speed': ['70'],
 'overhang_fan_threshold': ['10%'],
 'pressure_advance': '0.048',
 'setting_id': 'GFSA04',
 'slow_down_layer_time': ['10'],
 'slow_down_min_speed': ['10'],
 'temperature_vitrification': ['60'],
 'type': 'filament'}
