from __future__ import annotations

# source: profiles/Sovol/filament/Sovol Zero PC.json
DATA = {'activate_air_filtration': '1',
 'additional_cooling_fan_speed': '0',
 'compatible_printers': ['Sovol Zero 0.4 nozzle'],
 'complete_print_exhaust_fan_speed': '50',
 'dont_slow_down_outer_wall': '0',
 'during_print_exhaust_fan_speed': '50',
 'fan_cooling_layer_time': ['40'],
 'fan_max_speed': ['20'],
 'fan_min_speed': ['10'],
 'filament_flow_ratio': ['0.98'],
 'filament_id': 'GFL99',
 'filament_max_volumetric_speed': ['21'],
 'from': 'system',
 'full_fan_speed_layer': ['3'],
 'hot_plate_temp': ['110'],
 'hot_plate_temp_initial_layer': ['110'],
 'inherits': 'Generic PC @System',
 'instantiation': 'true',
 'name': 'Sovol Zero PC',
 'nozzle_temperature': ['270'],
 'nozzle_temperature_initial_layer': ['290'],
 'nozzle_temperature_range_high': ['350'],
 'nozzle_temperature_range_low': ['190'],
 'overhang_fan_speed': ['20'],
 'overhang_fan_threshold': ['50%'],
 'setting_id': 'GFSA04',
 'slow_down_layer_time': ['5'],
 'slow_down_min_speed': ['10'],
 'temperature_vitrification': ['60'],
 'type': 'filament'}
