from __future__ import annotations

# source: profiles/Sovol/filament/Sovol SV08 PETG.json
DATA = {'close_fan_the_first_x_layers': ['3'],
 'compatible_printers': ['Sovol SV08 0.2 nozzle',
                         'Sovol SV08 0.4 nozzle',
                         'Sovol SV08 0.6 nozzle',
                         'Sovol SV08 0.8 nozzle'],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['70'],
 'fan_min_speed': ['30'],
 'filament_flow_ratio': ['0.98'],
 'filament_id': 'GFL99',
 'filament_max_volumetric_speed': ['17'],
 'filament_retraction_length': ['0.5'],
 'filament_z_hop': ['0.4'],
 'from': 'system',
 'full_fan_speed_layer': ['0'],
 'hot_plate_temp': ['75'],
 'hot_plate_temp_initial_layer': ['75'],
 'inherits': 'Generic PETG @System',
 'instantiation': 'true',
 'name': 'Sovol SV08 PETG',
 'nozzle_temperature': ['235'],
 'nozzle_temperature_initial_layer': ['255'],
 'nozzle_temperature_range_high': ['280'],
 'nozzle_temperature_range_low': ['230'],
 'overhang_fan_speed': ['70'],
 'overhang_fan_threshold': ['10%'],
 'setting_id': 'GFSA04',
 'slow_down_layer_time': ['5'],
 'slow_down_min_speed': ['10'],
 'temperature_vitrification': ['60'],
 'type': 'filament'}
