from __future__ import annotations

# source: profiles/Sovol/filament/Sovol Zero TPU.json
DATA = {'activate_air_filtration': '1',
 'additional_cooling_fan_speed': '50',
 'compatible_printers': ['Sovol Zero 0.4 nozzle'],
 'complete_print_exhaust_fan_speed': '50',
 'during_print_exhaust_fan_speed': '100',
 'fan_cooling_layer_time': ['50'],
 'fan_max_speed': ['100'],
 'fan_min_speed': ['80'],
 'filament_flow_ratio': ['0.98'],
 'filament_id': 'GFL99',
 'filament_max_volumetric_speed': ['3.2'],
 'filament_z_hop': ['0.4'],
 'from': 'system',
 'full_fan_speed_layer': ['3'],
 'hot_plate_temp': ['85'],
 'hot_plate_temp_initial_layer': ['85'],
 'inherits': 'Generic TPU @System',
 'instantiation': 'true',
 'name': 'Sovol Zero TPU',
 'nozzle_temperature': ['235'],
 'nozzle_temperature_initial_layer': ['250'],
 'nozzle_temperature_range_high': ['250'],
 'nozzle_temperature_range_low': ['190'],
 'overhang_fan_speed': ['100'],
 'overhang_fan_threshold': ['50%'],
 'setting_id': 'GFSA04',
 'slow_down_layer_time': ['5'],
 'slow_down_min_speed': ['10'],
 'temperature_vitrification': ['60'],
 'type': 'filament'}
