from __future__ import annotations

# source: profiles/Sovol/filament/Sovol SV08 ABS.json
DATA = {'activate_air_filtration': ['1'],
 'close_fan_the_first_x_layers': ['3'],
 'compatible_printers': ['Sovol SV08 0.2 nozzle',
                         'Sovol SV08 0.4 nozzle',
                         'Sovol SV08 0.6 nozzle',
                         'Sovol SV08 0.8 nozzle'],
 'complete_print_exhaust_fan_speed': ['60'],
 'during_print_exhaust_fan_speed': ['100'],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['30'],
 'fan_min_speed': ['10'],
 'filament_flow_ratio': ['0.98'],
 'filament_id': 'GFL99',
 'filament_max_volumetric_speed': ['21'],
 'from': 'system',
 'full_fan_speed_layer': ['0'],
 'hot_plate_temp': ['95'],
 'hot_plate_temp_initial_layer': ['95'],
 'inherits': 'Generic ABS @System',
 'instantiation': 'true',
 'name': 'Sovol SV08 ABS',
 'nozzle_temperature': ['270'],
 'nozzle_temperature_initial_layer': ['280'],
 'nozzle_temperature_range_high': ['280'],
 'nozzle_temperature_range_low': ['230'],
 'overhang_fan_speed': ['30'],
 'overhang_fan_threshold': ['25%'],
 'setting_id': 'GFSA04',
 'slow_down_layer_time': ['4'],
 'slow_down_min_speed': ['10'],
 'temperature_vitrification': ['60'],
 'type': 'filament'}
