from __future__ import annotations

# source: profiles/Sovol/filament/Sovol Zero ABS.json
DATA = {'activate_air_filtration': ['1'],
 'additional_cooling_fan_speed': ['0'],
 'close_fan_the_first_x_layers': ['1'],
 'compatible_printers': ['Sovol Zero 0.4 nozzle'],
 'complete_print_exhaust_fan_speed': ['50'],
 'during_print_exhaust_fan_speed': ['50'],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['30'],
 'fan_min_speed': ['10'],
 'filament_flow_ratio': ['0.98'],
 'filament_id': 'GFL99',
 'filament_max_volumetric_speed': ['21'],
 'from': 'system',
 'full_fan_speed_layer': ['3'],
 'hot_plate_temp': ['100'],
 'hot_plate_temp_initial_layer': ['100'],
 'inherits': 'Generic ABS @System',
 'instantiation': 'true',
 'name': 'Sovol Zero ABS',
 'nozzle_temperature': ['270'],
 'nozzle_temperature_initial_layer': ['280'],
 'nozzle_temperature_range_high': ['300'],
 'nozzle_temperature_range_low': ['230'],
 'overhang_fan_speed': ['30'],
 'overhang_fan_threshold': ['50%'],
 'setting_id': 'GFSA04',
 'slow_down_layer_time': ['5'],
 'slow_down_min_speed': ['10'],
 'temperature_vitrification': ['60'],
 'type': 'filament'}
