from __future__ import annotations

# source: profiles/Sovol/filament/Sovol SV08 TPU.json
DATA = {'compatible_printers': ['Sovol SV08 0.2 nozzle',
                         'Sovol SV08 0.4 nozzle',
                         'Sovol SV08 0.6 nozzle',
                         'Sovol SV08 0.8 nozzle'],
 'fan_cooling_layer_time': ['50'],
 'fan_max_speed': ['100'],
 'fan_min_speed': ['80'],
 'filament_flow_ratio': ['0.98'],
 'filament_id': 'GFL99',
 'filament_max_volumetric_speed': ['3.6'],
 'filament_z_hop': ['0.4'],
 'from': 'system',
 'full_fan_speed_layer': ['3'],
 'hot_plate_temp': ['65'],
 'hot_plate_temp_initial_layer': ['65'],
 'inherits': 'Generic TPU @System',
 'instantiation': 'true',
 'name': 'Sovol SV08 TPU',
 'nozzle_temperature': ['235'],
 'nozzle_temperature_initial_layer': ['240'],
 'nozzle_temperature_range_high': ['250'],
 'nozzle_temperature_range_low': ['190'],
 'overhang_fan_speed': ['100'],
 'overhang_fan_threshold': ['50%'],
 'setting_id': 'GFSA04',
 'slow_down_layer_time': ['5'],
 'slow_down_min_speed': ['10'],
 'temperature_vitrification': ['60'],
 'type': 'filament'}
