from __future__ import annotations

# source: profiles/Sovol/filament/Sovol Zero PLA Basic.json
DATA = {'activate_air_filtration': '1',
 'additional_cooling_fan_speed': '75%',
 'compatible_printers': ['Sovol Zero 0.4 nozzle'],
 'complete_print_exhaust_fan_speed': '80%',
 'dont_slow_down_outer_wall': '0',
 'during_print_exhaust_fan_speed': '80%',
 'enable_pressure_advance': '1',
 'fan_cooling_layer_time': ['80'],
 'fan_max_speed': ['100'],
 'fan_min_speed': ['70'],
 'filament_flow_ratio': ['0.98'],
 'filament_id': 'GFL99',
 'filament_max_volumetric_speed': ['21'],
 'from': 'system',
 'full_fan_speed_layer': ['3'],
 'hot_plate_temp': ['65'],
 'hot_plate_temp_initial_layer': ['65'],
 'inherits': 'Generic PLA @System',
 'instantiation': 'true',
 'name': 'Sovol Zero PLA Basic',
 'nozzle_temperature': ['210'],
 'nozzle_temperature_initial_layer': ['230'],
 'nozzle_temperature_range_high': ['250'],
 'nozzle_temperature_range_low': ['190'],
 'overhang_fan_speed': ['100'],
 'overhang_fan_threshold': ['50%'],
 'pressure_advance': '0.032',
 'setting_id': 'GFSA04',
 'slow_down_layer_time': ['5'],
 'slow_down_min_speed': ['10'],
 'temperature_vitrification': ['60'],
 'type': 'filament'}
