from __future__ import annotations

# source: profiles/FLSun/filament/FLSun T1 PETG.json
DATA = {'activate_air_filtration': ['1'],
 'compatible_printers': ['FLSun T1 0.4 nozzle'],
 'complete_print_exhaust_fan_speed': ['0'],
 'dont_slow_down_outer_wall': ['1'],
 'during_print_exhaust_fan_speed': ['100'],
 'fan_cooling_layer_time': ['100'],
 'fan_max_speed': ['60'],
 'fan_min_speed': ['50'],
 'filament_cost': ['0'],
 'filament_id': 'GFG99',
 'filament_max_volumetric_speed': ['15'],
 'from': 'system',
 'full_fan_speed_layer': ['2'],
 'hot_plate_temp': ['80'],
 'hot_plate_temp_initial_layer': ['80'],
 'inherits': 'FLSun Generic PETG',
 'instantiation': 'true',
 'name': 'FLSun T1 PETG',
 'nozzle_temperature': ['260'],
 'nozzle_temperature_initial_layer': ['260'],
 'nozzle_temperature_range_high': ['270'],
 'nozzle_temperature_range_low': ['230'],
 'overhang_fan_speed': ['35'],
 'setting_id': 'GFSA04',
 'slow_down_layer_time': ['2'],
 'slow_down_min_speed': ['30'],
 'temperature_vitrification': ['70'],
 'type': 'filament'}
