from __future__ import annotations

# source: profiles/FLSun/filament/FLSun S1 ABS.json
DATA = {'activate_air_filtration': ['1'],
 'compatible_printers': ['FLSun S1 0.4 nozzle'],
 'complete_print_exhaust_fan_speed': ['0'],
 'dont_slow_down_outer_wall': ['1'],
 'during_print_exhaust_fan_speed': ['0'],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['50'],
 'fan_min_speed': ['10'],
 'filament_cost': ['0'],
 'filament_density': ['1.05'],
 'filament_flow_ratio': '0.95',
 'filament_id': 'GFB99',
 'filament_max_volumetric_speed': ['20'],
 'from': 'system',
 'full_fan_speed_layer': ['3'],
 'hot_plate_temp': ['90'],
 'hot_plate_temp_initial_layer': ['90'],
 'inherits': 'FLSun Generic ABS',
 'instantiation': 'true',
 'name': 'FLSun S1 ABS',
 'nozzle_temperature': ['280'],
 'nozzle_temperature_initial_layer': ['280'],
 'nozzle_temperature_range_high': ['300'],
 'nozzle_temperature_range_low': ['240'],
 'overhang_fan_speed': ['50'],
 'setting_id': 'GFSA04',
 'slow_down_layer_time': ['12'],
 'slow_down_min_speed': ['30'],
 'temperature_vitrification': ['100'],
 'type': 'filament'}
