from __future__ import annotations

# source: profiles/FLSun/filament/FLSun S1 PLA Silk.json
DATA = {'activate_air_filtration': ['1'],
 'compatible_printers': ['FLSun S1 0.4 nozzle'],
 'complete_print_exhaust_fan_speed': ['0'],
 'dont_slow_down_outer_wall': ['1'],
 'during_print_exhaust_fan_speed': ['100'],
 'fan_cooling_layer_time': ['100'],
 'filament_cost': ['0'],
 'filament_density': ['1.32'],
 'filament_id': 'GFL99',
 'filament_max_volumetric_speed': ['25'],
 'from': 'system',
 'full_fan_speed_layer': ['3'],
 'hot_plate_temp': ['60'],
 'hot_plate_temp_initial_layer': ['60'],
 'inherits': 'FLSun Generic PLA',
 'instantiation': 'true',
 'name': 'FLSun S1 PLA Silk',
 'nozzle_temperature': ['230'],
 'nozzle_temperature_initial_layer': ['230'],
 'nozzle_temperature_range_high': ['240'],
 'nozzle_temperature_range_low': ['190'],
 'overhang_fan_speed': ['35'],
 'setting_id': 'GFSA04',
 'slow_down_layer_time': ['1'],
 'slow_down_min_speed': ['80'],
 'type': 'filament'}
