from __future__ import annotations

# source: profiles/FLSun/filament/FLSun Generic PETG.json
DATA = {'compatible_printers': ['FLSun Q5 0.4 nozzle',
                         'FLSun QQ-S Pro 0.4 nozzle',
                         'FLSun Super Racer 0.4 nozzle',
                         'FLSun V400 0.4 nozzle'],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['90'],
 'fan_min_speed': ['40'],
 'filament_flow_ratio': ['0.95'],
 'filament_id': 'GFG99',
 'filament_max_volumetric_speed': ['10'],
 'filament_start_gcode': ['; filament start gcode\n'],
 'from': 'system',
 'inherits': 'fdm_filament_pet',
 'instantiation': 'true',
 'name': 'FLSun Generic PETG',
 'overhang_fan_speed': ['90'],
 'overhang_fan_threshold': ['25%'],
 'reduce_fan_stop_start_freq': ['1'],
 'setting_id': 'GFSA04',
 'slow_down_for_layer_cooling': ['1'],
 'slow_down_layer_time': ['8'],
 'slow_down_min_speed': ['10'],
 'type': 'filament'}
