from __future__ import annotations

# source: profiles/Geeetech/process/0.20mm Strength @Geeetech common.json
DATA = {'compatible_printers': ['Geeetech A10 Pro 0.4 nozzle',
                         'Geeetech A10 M 0.4 nozzle',
                         'Geeetech A10 T 0.4 nozzle',
                         'Geeetech A20 0.4 nozzle',
                         'Geeetech A20 M 0.4 nozzle',
                         'Geeetech A20 T 0.4 nozzle',
                         'Geeetech A30 Pro 0.4 nozzle',
                         'Geeetech A30 M 0.4 nozzle',
                         'Geeetech A30 T 0.4 nozzle',
                         'Geeetech Mizar 0.4 nozzle',
                         'Geeetech Mizar S 0.4 nozzle',
                         'Geeetech Mizar Pro 0.4 nozzle',
                         'Geeetech Mizar Max 0.4 nozzle',
                         'Geeetech Mizar M 0.4 nozzle'],
 'from': 'system',
 'inherits': 'fdm_process_geeetech_0.20',
 'instantiation': 'true',
 'name': '0.20mm Strength @Geeetech common',
 'outer_wall_speed': '25',
 'setting_id': 'GP_Geeetech_019',
 'sparse_infill_density': '25%',
 'type': 'process',
 'wall_loops': '6'}
