from __future__ import annotations

# source: profiles/Geeetech/process/0.24mm Optimal @Geeetech M1 0.6 nozzle.json
DATA = {'compatible_printers': ['Geeetech M1 0.6 nozzle'],
 'default_acceleration': '2000',
 'default_jerk': '10',
 'from': 'system',
 'gap_infill_speed': '80',
 'infill_jerk': '10',
 'inherits': 'fdm_process_Geeetech_HS_0.24_nozzle_0.6',
 'initial_layer_acceleration': '500',
 'initial_layer_infill_speed': '50',
 'initial_layer_jerk': '10',
 'initial_layer_speed': '30',
 'inner_wall_acceleration': '3000',
 'inner_wall_jerk': '10',
 'inner_wall_speed': '80',
 'instantiation': 'true',
 'internal_solid_infill_speed': '100',
 'name': '0.24mm Optimal @Geeetech M1 0.6 nozzle',
 'outer_wall_acceleration': '1500',
 'outer_wall_jerk': '10',
 'outer_wall_speed': '50',
 'setting_id': 'GP_Geeetech_045',
 'sparse_infill_speed': '100',
 'top_surface_acceleration': '2000',
 'top_surface_jerk': '10',
 'top_surface_speed': '50',
 'travel_acceleration': '3000',
 'travel_jerk': '10',
 'travel_speed': '200',
 'type': 'process'}
