from __future__ import annotations

# source: profiles/Geeetech/process/fdm_process_Geeetech_HS.json
DATA = {'accel_to_decel_enable': '1',
 'accel_to_decel_factor': '50%',
 'bridge_speed': '25',
 'default_acceleration': '7000',
 'default_jerk': '9',
 'from': 'system',
 'gap_infill_speed': '150',
 'infill_jerk': '12',
 'inherits': 'fdm_process_geeetech_common',
 'initial_layer_acceleration': '500',
 'initial_layer_infill_speed': '80',
 'initial_layer_jerk': '9',
 'initial_layer_speed': '50',
 'inner_wall_acceleration': '7000',
 'inner_wall_jerk': '7',
 'inner_wall_speed': '150',
 'instantiation': 'false',
 'internal_solid_infill_speed': '180',
 'ironing_speed': '15',
 'name': 'fdm_process_Geeetech_HS',
 'outer_wall_acceleration': '5000',
 'outer_wall_jerk': '7',
 'outer_wall_speed': '100',
 'overhang_1_4_speed': '80',
 'overhang_2_4_speed': '50',
 'overhang_3_4_speed': '30',
 'overhang_4_4_speed': '10',
 'sparse_infill_speed': '250',
 'support_interface_speed': '100%',
 'support_speed': '80',
 'top_surface_acceleration': '5000',
 'top_surface_jerk': '9',
 'top_surface_speed': '120',
 'travel_acceleration': '10000',
 'travel_jerk': '12',
 'travel_speed': '300',
 'type': 'process'}
