from __future__ import annotations

# source: profiles/Qidi/machine/Qidi X-Smart 3 0.4 nozzle.json
DATA = {'auxiliary_fan': '1',
 'change_filament_gcode': '',
 'default_filament_profile': ['Qidi Generic PLA'],
 'default_print_profile': '0.20mm Standard @Qidi XSmart3',
 'deretraction_speed': ['0'],
 'from': 'system',
 'gcode_flavor': 'klipper',
 'inherits': 'fdm_qidi_x3_common',
 'instantiation': 'true',
 'machine_pause_gcode': 'M0',
 'max_layer_height': ['0.32'],
 'min_layer_height': ['0.07'],
 'name': 'Qidi X-Smart 3 0.4 nozzle',
 'nozzle_diameter': ['0.4'],
 'nozzle_type': 'hardened_steel',
 'printable_area': ['0x0', '175x0', '175x180', '0x180'],
 'printable_height': '170',
 'printer_model': 'Qidi X-Smart 3',
 'printer_settings_id': 'Qidi',
 'retract_length_toolchange': ['2'],
 'retraction_length': ['0.8'],
 'retraction_minimum_travel': ['1'],
 'setting_id': 'GM001',
 'single_extruder_multi_material': '1',
 'thumbnails': ['205x205/COLPIC', '140x140/COLPIC', '110x110/PNG'],
 'type': 'machine'}
