from __future__ import annotations

# source: profiles/Qidi/machine/Qidi X-Max 3 0.4 nozzle.json
DATA = {'auxiliary_fan': '1',
 'change_filament_gcode': '',
 'default_filament_profile': ['Qidi Generic PLA'],
 'default_print_profile': '0.20mm Standard @Qidi XMax3',
 'deretraction_speed': ['0'],
 'extruder_clearance_height_to_lid': '118',
 'extruder_clearance_height_to_rod': '30',
 'extruder_clearance_radius': '70',
 'from': 'system',
 'gcode_flavor': 'klipper',
 'inherits': 'fdm_qidi_x3_common',
 'instantiation': 'true',
 'machine_pause_gcode': 'M0',
 'max_layer_height': ['0.32'],
 'min_layer_height': ['0.08'],
 'name': 'Qidi X-Max 3 0.4 nozzle',
 'nozzle_diameter': ['0.4'],
 'nozzle_type': 'hardened_steel',
 'printable_area': ['0x0', '325x0', '325x325', '0x325'],
 'printable_height': '315',
 'printer_model': 'Qidi X-Max 3',
 'printer_settings_id': 'Qidi',
 'retract_length_toolchange': ['2'],
 'retraction_length': ['1'],
 'retraction_minimum_travel': ['1'],
 'setting_id': 'GM001',
 'single_extruder_multi_material': '1',
 'type': 'machine'}
