from __future__ import annotations

# source: profiles/Qidi/machine/Qidi X-Max 4 0.4 nozzle.json
DATA = {'bed_exclude_area': ['0x0, 16x0, 16x13, 0x13, 0x0, 0x0, 0x0, 0x0, 0x387, 53x387, 53x390, 0x390, 0x387, 0x387, 0x397, '
                      '0x390, 338x390, 338x384, 390x384, 390x390, 0x390'],
 'box_id': '3',
 'change_filament_gcode': 'G1 Z{max_layer_z + 3.0} F1200\n'
                          'TOOL_CHANGE_START F=[current_extruder] T=[next_extruder]\n'
                          'DISABLE_ALL_SENSOR\n'
                          'M104 S{old_filament_temp - 10}\n'
                          'M106 S255\n'
                          '{if long_retractions_when_cut[previous_extruder]}\n'
                          'G1 E-{retraction_distances_when_cut[previous_extruder]} F{old_filament_e_feedrate}\n'
                          '{else}\n'
                          'G1 E-2 F{old_filament_e_feedrate}\n'
                          '{endif}\n'
                          'M400\n'
                          'CUT_FILAMENT T=[current_extruder]\n'
                          'MOVE_TO_TRASH\n'
                          'M106 P2 S0\n'
                          'UNLOAD_T[current_extruder]\n'
                          'T[next_extruder]\n'
                          'M106 S0\n'
                          '{if nozzle_temperature_range_high[current_extruder] >= '
                          'nozzle_temperature_range_high[next_extruder]}\n'
                          'M104 S{nozzle_temperature_range_high[current_extruder]}\n'
                          'M109.0 S{(nozzle_temperature_range_high[current_extruder])-25}\n'
                          '{else}\n'
                          'M104 S{nozzle_temperature_range_high[next_extruder]}\n'
                          'M109.0 S{(nozzle_temperature_range_high[next_extruder])-25}\n'
                          '{endif}\n'
                          '{if long_retractions_when_cut[previous_extruder]}\n'
                          'G1 E{retraction_distances_when_cut[previous_extruder]} F{old_filament_e_feedrate}\n'
                          '{endif}\n'
                          '{if flush_length_1 > 1}\n'
                          '; FLUSH_START\n'
                          'G1 Y403.5 F2000\n'
                          'G1 E{flush_length_1} F{old_filament_e_feedrate *0.5}\n'
                          '; FLUSH_END\n'
                          '{endif}\n'
                          '{if flush_length_2 > 1}\n'
                          '; FLUSH_START\n'
                          'G1 E{flush_length_2} F{new_filament_e_feedrate * 0.5}\n'
                          '; FLUSH_END\n'
                          '{endif}\n'
                          '{if flush_length_3 > 1}\n'
                          '; FLUSH_START\n'
                          'G1 E{flush_length_3} F{new_filament_e_feedrate * 0.5}\n'
                          '; FLUSH_END\n'
                          '{endif}\n'
                          '{if flush_length_4 > 1}\n'
                          '; FLUSH_START\n'
                          'G1 E{flush_length_4} F{new_filament_e_feedrate * 0.5}\n'
                          '; FLUSH_END\n'
                          '{endif}\n'
                          'M400\n'
                          'M106 S180\n'
                          'M104 S{new_filament_temp - 10}\n'
                          'G1 E1 F10\n'
                          'M109.1 S{new_filament_temp - 10}\n'
                          'G1 E-4 F1000\n'
                          'G4 P2000\n'
                          'M204 S5000\n'
                          'G1 Y403 F2000\n'
                          'G1 X163 F8000\n'
                          'G1 X145 F5000\n'
                          'G1 X163 F3000\n'
                          'G1 X145 F2000\n'
                          'G1 X175 F6000\n'
                          'G1 X163\n'
                          'G1 X175\n'
                          'G1 X163\n'
                          'G1 X175\n'
                          'G1 X163\n'
                          'G1 X180 F8000\n'
                          'G1 Y380\n'
                          'G1 X116\n'
                          'G4 P2000\n'
                          'G1 Y403 F3000\n'
                          'G1 X130\n'
                          'G1 X100 F8000\n'
                          'G1 Y380\n'
                          'G1 X116\n'
                          'G1 Y403 F3000\n'
                          'G1 X130 F3000\n'
                          'G1 X100 F8000\n'
                          'G1 Y380\n'
                          'M104 S[new_filament_temp]\n'
                          'TOOL_CHANGE_END\n'
                          'G1 E{new_retract_length_toolchange + 1} F{new_filament_e_feedrate}\n'
                          'ENABLE_ALL_SENSOR\n',
 'default_filament_profile': ['QIDI PLA Rapido @Qidi X-Max 4 0.4 nozzle'],
 'default_print_profile': '0.20mm Standard @X-Max 4',
 'enable_long_retraction_when_cut': '2',
 'extruder_clearance_height_to_lid': '120',
 'extruder_clearance_height_to_rod': '40',
 'extruder_clearance_max_radius': '70',
 'fan_direction': 'left',
 'from': 'system',
 'gcode_flavor': 'klipper',
 'inherits': 'fdm_machine_x_common',
 'instantiation': 'true',
 'is_support_3mf': '1',
 'is_support_multi_box': '1',
 'is_support_timelapse': '1',
 'layer_change_gcode': '{if timelapse_type == 1} ; timelapse with wipe tower\n'
                       'G92 E0\n'
                       'G1 E-[retraction_length] F1800\n'
                       'G2 Z{layer_z + 0.4} I0.86 J0.86 P1 F20000 ; spiral lift a little\n'
                       'G1 Y380 F20000\n'
                       'G1 X128 F20000\n'
                       '{if layer_z <=25}\n'
                       'G1 Z25\n'
                       '{endif}\n'
                       'G1 Y403 F2000\n'
                       'G92 E0\n'
                       'M400\n'
                       'TIMELAPSE_TAKE_FRAME\n'
                       'G1 E[retraction_length] F300\n'
                       'G1 X180 F8000\n'
                       'G1 Y380 F8000\n'
                       '{if layer_z <=25}\n'
                       'G1 Z[layer_z]\n'
                       '{endif}\n'
                       '{elsif timelapse_type == 0} ; timelapse without wipe tower\n'
                       'TIMELAPSE_TAKE_FRAME\n'
                       '{endif}\n'
                       'G92 E0\n'
                       'SET_PRINT_STATS_INFO CURRENT_LAYER={layer_num + 1}',
 'machine_end_gcode': 'DISABLE_BOX_HEATER\n'
                      'M141 S0\n'
                      'M140 S0\n'
                      'DISABLE_ALL_SENSOR\n'
                      'G1 E-3 F1800\n'
                      'G0 Z{max_layer_z + 3} F600\n'
                      'UNLOAD_FILAMENT T=[current_extruder]\n'
                      'G0 Y380 F12000\n'
                      'G0 X128 Y380 F12000\n'
                      '{if max_layer_z < max_print_height / 2}G1 Z{max_print_height / 2 + 10} F600{else}G1 '
                      'Z{min(max_print_height, max_layer_z + 3)}{endif}\n'
                      'M104 S0\n'
                      'PRINT_END',
 'machine_max_acceleration_x': ['30000'],
 'machine_max_acceleration_y': ['30000'],
 'machine_max_jerk_e': ['4'],
 'machine_max_jerk_x': ['9'],
 'machine_max_jerk_y': ['9'],
 'machine_max_jerk_z': ['4'],
 'machine_max_speed_x': ['800'],
 'machine_max_speed_y': ['800'],
 'machine_max_speed_z': ['20'],
 'machine_pause_gcode': 'M0',
 'machine_start_gcode': ';===== PRINT_PHASE_INIT =====\n'
                        'SET_PRINT_MAIN_STATUS MAIN_STATUS=print_start\n'
                        'M220 S100\n'
                        'M221 S100\n'
                        'SET_INPUT_SHAPER SHAPER_TYPE_X=mzv\n'
                        'SET_INPUT_SHAPER SHAPER_TYPE_Y=mzv\n'
                        'DISABLE_ALL_SENSOR\n'
                        'M1002 R1\n'
                        'M107\n'
                        'CLEAR_PAUSE\n'
                        'M140 S[bed_temperature_initial_layer_single]\n'
                        'M141 S[chamber_temperature]\n'
                        'G29.0\n'
                        'G28\n'
                        '\n'
                        ';===== BOX_PREPAR =====\n'
                        'BOX_PRINT_START EXTRUDER=[initial_no_support_extruder] '
                        'HOTENDTEMP={nozzle_temperature_range_high[initial_tool]}\n'
                        'M400\n'
                        'EXTRUSION_AND_FLUSH HOTEND=[nozzle_temperature_initial_layer]\n'
                        '\n'
                        ';===== CLEAR_NOZZLE =====\n'
                        'G1 Z20 F480\n'
                        'MOVE_TO_TRASH\n'
                        'G1 Y403.5 F2000\n'
                        '{if chamber_temperature[0] == 0}\n'
                        'M106 P3 S[during_print_exhaust_fan_speed]\n'
                        '{else}\n'
                        'M106 P3 S0\n'
                        '{endif}\n'
                        'M1004\n'
                        'M106 S0\n'
                        'M109 S[nozzle_temperature_initial_layer]\n'
                        'G92 E0\n'
                        'M83\n'
                        'G1 E5 F80\n'
                        'G1 E250 F300\n'
                        'M400\n'
                        'M106 S255\n'
                        'G1 E-3 F1000\n'
                        'M104 S140\n'
                        'M109.1 S{nozzle_temperature_initial_layer[0]-30}\n'
                        'M204 S10000\n'
                        'G1 Y403 F2000\n'
                        'G1 X163 F8000\n'
                        'G1 X145 F5000\n'
                        'G1 X163 F8000\n'
                        'G1 X145 F5000\n'
                        'G1 X175 F6000\n'
                        'G1 X163\n'
                        'G1 X175\n'
                        'G1 X163\n'
                        'G1 X175\n'
                        'G1 X163\n'
                        'G1 X180 F10000\n'
                        'G1 Y395 F6000\n'
                        'G1 X188\n'
                        'G1 Z-0.2 F480\n'
                        'M106 S255\n'
                        'M109.1 S150\n'
                        'G91\n'
                        'G1 X15 F200\n'
                        'G1 Y2\n'
                        'G1 X-15\n'
                        'G1 Y-2\n'
                        'G1 X15\n'
                        'G90\n'
                        'G2 I0.5 J0.5 F480\n'
                        'G2 I0.5 J0.5\n'
                        'G2 I0.5 J0.5\n'
                        'G1 Z10\n'
                        'G1 Y383 F12000\n'
                        'G1 X116\n'
                        'G1 Y403\n'
                        'G1 X163 F8000\n'
                        'G1 X145 F5000\n'
                        'G1 X163 F8000\n'
                        'G1 X145 F5000\n'
                        'G1 X175 F6000\n'
                        'G1 X163\n'
                        'G1 X175\n'
                        'G1 X163\n'
                        'G1 X175\n'
                        'G1 X163\n'
                        'G1 X180 F10000\n'
                        'G1 Y383\n'
                        'M106 S0\n'
                        'M190 S[bed_temperature_initial_layer_single]\n'
                        'M191 S[chamber_temperature]\n'
                        'G1 Y0 F15000\n'
                        'G1 X15 F15000\n'
                        'G1 X3 F5000\n'
                        'G4 P1000\n'
                        'G1 X4 F1000\n'
                        'G1 X3 F5000\n'
                        'G4 P1000\n'
                        'G1 X15 F3000\n'
                        'G1 E-4 F1800\n'
                        'G1 X20 Y20 F15000\n'
                        'Z_TILT_ADJUST\n'
                        'G29\n'
                        'M1002 A1\n'
                        'G1 X380 Y5 F20000\n'
                        'M109 S[nozzle_temperature_initial_layer]\n'
                        'ENABLE_ALL_SENSOR\n'
                        '\n'
                        ';===== PRINT_START =====\n'
                        'SET_PRINT_MAIN_STATUS MAIN_STATUS=printing\n'
                        'SET_PRINT_STATS_INFO TOTAL_LAYER=[total_layer_count]\n'
                        'T[initial_tool]\n'
                        'M140 S[bed_temperature_initial_layer_single]\n'
                        'M104 S[nozzle_temperature_initial_layer]\n'
                        'M141 S[chamber_temperature]\n'
                        'G0 X200 Y1 F20000\n'
                        'G0 Z10 F480\n'
                        'G4 P3000\n'
                        'probe samples=1\n'
                        'G91\n'
                        'G0 Z5 F480\n'
                        'G90\n'
                        'G1 X173 Y1 F20000\n'
                        'G91\n'
                        'G0 Z{initial_layer_print_height-5} F480\n'
                        'G90\n'
                        'G0 X193 E8 F{outer_wall_volumetric_speed/(24/20) * 60}\n'
                        'G0 X198 E.3742 F{outer_wall_volumetric_speed/(0.3*0.5)/4 * 60}\n'
                        'G0 X203 E.3742 F{outer_wall_volumetric_speed/(0.3*0.5) * 60}\n'
                        'G0 X208 E.3742 F{outer_wall_volumetric_speed/(0.3*0.5)/4 * 60}\n'
                        'G0 X213 E.3742 F{outer_wall_volumetric_speed/(0.3*0.5) * 60}\n'
                        'G0 X218 E.3742 F{outer_wall_volumetric_speed/(0.3*0.5)/4 * 60}\n'
                        'G91\n'
                        'G1 X1 Z{-initial_layer_print_height-0.1}\n'
                        'G1 X4\n'
                        'G1 Z1 F480\n'
                        'G90\n'
                        'G1 X173 Y2.5 F20000\n'
                        'G91\n'
                        'G1 Z-0.7 F480\n'
                        'G90\n'
                        'G0 X193 E10 F{outer_wall_volumetric_speed/(24/20) * 60}\n'
                        'G0 X198 E.3742 F{outer_wall_volumetric_speed/(0.3*0.5)/4 * 60}\n'
                        'G0 X203 E.3742 F{outer_wall_volumetric_speed/(0.3*0.5) * 60}\n'
                        'G0 X208 E.3742 F{outer_wall_volumetric_speed/(0.3*0.5)/4 * 60}\n'
                        'G0 X213 E.3742 F{outer_wall_volumetric_speed/(0.3*0.5) * 60}\n'
                        'G0 X218 E.3742 F{outer_wall_volumetric_speed/(0.3*0.5)/4 * 60}\n'
                        'G91\n'
                        'G1 X1 Z{-initial_layer_print_height-0.1}\n'
                        'G1 X4\n'
                        'G1 Z1 F480\n'
                        'G90\n',
 'name': 'Qidi X-Max 4 0.4 nozzle',
 'nozzle_diameter': ['0.4'],
 'nozzle_volume': ['150'],
 'printable_area': ['0x0', '390x0', '390x390', '0x390'],
 'printable_height': '340',
 'printer_model': 'Qidi X-Max 4',
 'printer_settings_id': 'Qidi',
 'retract_lift_below': ['339'],
 'setting_id': 'GM001',
 'support_box_temp_control': '1',
 'thumbnail_size': ['50x50'],
 'type': 'machine'}
