from __future__ import annotations

# source: profiles/Elegoo/filament/ELEGOO/Elegoo PLA Matte @0.2 nozzle.json
DATA = {'compatible_printers': ['Elegoo Centauri 0.2 nozzle',
                         'Elegoo Centauri Carbon 0.2 nozzle',
                         'Elegoo Neptune 4 0.2 nozzle',
                         'Elegoo Neptune 4 Pro 0.2 nozzle',
                         'Elegoo Neptune 4 Plus 0.2 nozzle',
                         'Elegoo Neptune 4 Max 0.2 nozzle',
                         'Elegoo Neptune 3 Pro 0.2 nozzle',
                         'Elegoo Neptune 3 Plus 0.2 nozzle',
                         'Elegoo Neptune 3 Max 0.2 nozzle'],
 'fan_cooling_layer_time': ['80'],
 'fan_max_speed': ['80'],
 'fan_min_speed': ['60'],
 'filament_max_volumetric_speed': ['2'],
 'from': 'system',
 'hot_plate_temp': ['60'],
 'hot_plate_temp_initial_layer': ['60'],
 'inherits': 'Elegoo PLA Matte @base',
 'instantiation': 'true',
 'name': 'Elegoo PLA Matte @0.2 nozzle',
 'setting_id': 'EPLAM00020',
 'slow_down_layer_time': ['6'],
 'textured_plate_temp': ['65'],
 'textured_plate_temp_initial_layer': ['65'],
 'type': 'filament'}
