from __future__ import annotations

# source: profiles/Elegoo/filament/ELEGOO/Elegoo PETG PRO.json
DATA = {'compatible_printers': ['Elegoo Neptune 0.4 nozzle',
                         'Elegoo Neptune X 0.4 nozzle',
                         'Elegoo Neptune 2 0.4 nozzle',
                         'Elegoo Neptune 2S 0.4 nozzle',
                         'Elegoo Neptune 2D 0.4 nozzle',
                         'Elegoo Neptune 3 0.4 nozzle',
                         'Elegoo Neptune 3 Pro 0.4 nozzle',
                         'Elegoo Neptune 3 Plus 0.4 nozzle',
                         'Elegoo Neptune 3 Max 0.4 nozzle',
                         'Elegoo Neptune 4 (0.2 nozzle)',
                         'Elegoo Neptune 4 (0.4 nozzle)',
                         'Elegoo Neptune 4 (0.6 nozzle)',
                         'Elegoo Neptune 4 (0.8 nozzle)',
                         'Elegoo Neptune 4 Max (0.2 nozzle)',
                         'Elegoo Neptune 4 Max (0.4 nozzle)',
                         'Elegoo Neptune 4 Max (0.6 nozzle)',
                         'Elegoo Neptune 4 Max (0.8 nozzle)',
                         'Elegoo Neptune 4 Plus (0.2 nozzle)',
                         'Elegoo Neptune 4 Plus (0.4 nozzle)',
                         'Elegoo Neptune 4 Plus (0.6 nozzle)',
                         'Elegoo Neptune 4 Plus (0.8 nozzle)',
                         'Elegoo Neptune 4 Pro (0.2 nozzle)',
                         'Elegoo Neptune 4 Pro (0.4 nozzle)',
                         'Elegoo Neptune 4 Pro (0.6 nozzle)',
                         'Elegoo Neptune 4 Pro (0.8 nozzle)'],
 'from': 'system',
 'inherits': 'Elegoo PETG PRO @base',
 'instantiation': 'true',
 'name': 'Elegoo PETG PRO',
 'setting_id': 'EPETGPRO00',
 'type': 'filament'}
