from __future__ import annotations

# source: profiles/Elegoo/filament/ELEGOO/Elegoo PETG PRO @base.json
DATA = {'cool_plate_temp': ['0'],
 'cool_plate_temp_initial_layer': ['0'],
 'eng_plate_temp': ['70'],
 'eng_plate_temp_initial_layer': ['70'],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['40'],
 'fan_min_speed': ['10'],
 'filament_cost': ['0'],
 'filament_density': ['1.25'],
 'filament_end_gcode': ['; filament end gcode \n'],
 'filament_id': 'EPETGPROB00',
 'filament_max_volumetric_speed': ['8'],
 'filament_start_gcode': ['; Filament start gcode\n'],
 'filament_type': ['PETG'],
 'filament_vendor': ['Elegoo'],
 'from': 'system',
 'hot_plate_temp': ['70'],
 'hot_plate_temp_initial_layer': ['70'],
 'inherits': 'fdm_elegoo_filament_pet',
 'instantiation': 'false',
 'name': 'Elegoo PETG PRO @base',
 'nozzle_temperature': ['240'],
 'nozzle_temperature_initial_layer': ['240'],
 'nozzle_temperature_range_high': ['270'],
 'nozzle_temperature_range_low': ['230'],
 'overhang_fan_speed': ['90'],
 'overhang_fan_threshold': ['10%'],
 'slow_down_layer_time': ['12'],
 'textured_plate_temp': ['70'],
 'textured_plate_temp_initial_layer': ['70'],
 'type': 'filament'}
