from __future__ import annotations

# source: profiles/Elegoo/filament/ELEGOO/Elegoo PLA Silk.json
DATA = {'compatible_printers': ['Elegoo Neptune 0.4 nozzle',
                         'Elegoo Neptune X 0.4 nozzle',
                         'Elegoo Neptune 2 0.4 nozzle',
                         'Elegoo Neptune 2S 0.4 nozzle',
                         'Elegoo Neptune 2D 0.4 nozzle',
                         'Elegoo Neptune 3 0.4 nozzle',
                         'Elegoo Neptune 3 Pro 0.4 nozzle',
                         'Elegoo Neptune 3 Plus 0.4 nozzle',
                         'Elegoo Neptune 3 Max 0.4 nozzle',
                         'Elegoo Neptune 4 (0.2 nozzle)',
                         'Elegoo Neptune 4 (0.4 nozzle)',
                         'Elegoo Neptune 4 (0.6 nozzle)',
                         'Elegoo Neptune 4 (0.8 nozzle)',
                         'Elegoo Neptune 4 Max (0.2 nozzle)',
                         'Elegoo Neptune 4 Max (0.4 nozzle)',
                         'Elegoo Neptune 4 Max (0.6 nozzle)',
                         'Elegoo Neptune 4 Max (0.8 nozzle)',
                         'Elegoo Neptune 4 Plus (0.2 nozzle)',
                         'Elegoo Neptune 4 Plus (0.4 nozzle)',
                         'Elegoo Neptune 4 Plus (0.6 nozzle)',
                         'Elegoo Neptune 4 Plus (0.8 nozzle)',
                         'Elegoo Neptune 4 Pro (0.2 nozzle)',
                         'Elegoo Neptune 4 Pro (0.4 nozzle)',
                         'Elegoo Neptune 4 Pro (0.6 nozzle)',
                         'Elegoo Neptune 4 Pro (0.8 nozzle)'],
 'fan_cooling_layer_time': ['80'],
 'fan_max_speed': ['80'],
 'fan_min_speed': ['60'],
 'from': 'system',
 'hot_plate_temp': ['60'],
 'hot_plate_temp_initial_layer': ['60'],
 'inherits': 'Elegoo PLA Silk @base',
 'instantiation': 'true',
 'name': 'Elegoo PLA Silk',
 'setting_id': 'EPLAS00',
 'slow_down_layer_time': ['8'],
 'textured_plate_temp': ['60'],
 'textured_plate_temp_initial_layer': ['60'],
 'type': 'filament'}
