from __future__ import annotations

# source: profiles/Elegoo/filament/ELEGOO/fdm_elegoo_filament_pla.json
DATA = {'additional_cooling_fan_speed': ['0'],
 'close_fan_the_first_x_layers': ['1'],
 'cool_plate_temp': ['35'],
 'cool_plate_temp_initial_layer': ['35'],
 'eng_plate_temp': ['0'],
 'eng_plate_temp_initial_layer': ['0'],
 'fan_cooling_layer_time': ['80'],
 'fan_min_speed': ['50'],
 'filament_cost': ['0'],
 'filament_density': ['1.24'],
 'filament_end_gcode': ['; filament end gcode \n'],
 'filament_max_volumetric_speed': ['12'],
 'filament_start_gcode': ['; Filament start gcode\n'],
 'filament_type': ['PLA'],
 'from': 'system',
 'hot_plate_temp': ['60'],
 'hot_plate_temp_initial_layer': ['60'],
 'inherits': 'fdm_elegoo_filament_common',
 'instantiation': 'false',
 'name': 'fdm_elegoo_filament_pla',
 'nozzle_temperature': ['220'],
 'nozzle_temperature_initial_layer': ['220'],
 'nozzle_temperature_range_high': ['240'],
 'nozzle_temperature_range_low': ['190'],
 'overhang_fan_threshold': ['50%'],
 'reduce_fan_stop_start_freq': ['1'],
 'slow_down_layer_time': ['8'],
 'slow_down_min_speed': ['20'],
 'temperature_vitrification': ['45'],
 'textured_plate_temp': ['60'],
 'textured_plate_temp_initial_layer': ['60'],
 'type': 'filament'}
