from __future__ import annotations

# source: profiles/RH3D/filament/fdm_filament_abs.json
DATA = {'chamber_temperature': ['55'],
 'cool_plate_temp': ['100'],
 'cool_plate_temp_initial_layer': ['100'],
 'eng_plate_temp': ['115'],
 'eng_plate_temp_initial_layer': ['115'],
 'fan_cooling_layer_time': ['10'],
 'fan_max_speed': ['60'],
 'fan_min_speed': ['20'],
 'filament_cost': ['20'],
 'filament_density': ['1.04'],
 'filament_flow_ratio': ['0.94'],
 'filament_id': 'GFRH01',
 'filament_max_volumetric_speed': ['32'],
 'filament_shrink': ['99.487'],
 'filament_type': ['ABS'],
 'from': 'system',
 'hot_plate_temp': ['115'],
 'hot_plate_temp_initial_layer': ['115'],
 'idle_temperature': '200',
 'inherits': 'fdm_filament_common',
 'instantiation': 'false',
 'name': 'fdm_filament_abs',
 'nozzle_temperature': ['265'],
 'nozzle_temperature_initial_layer': ['265'],
 'nozzle_temperature_range_high': ['275'],
 'nozzle_temperature_range_low': ['250'],
 'overhang_fan_speed': ['80'],
 'overhang_fan_threshold': ['25%'],
 'slow_down_layer_time': ['2'],
 'slow_down_min_speed': ['10'],
 'temperature_vitrification': ['110'],
 'type': 'filament'}
