from __future__ import annotations

# source: profiles/RH3D/filament/fdm_filament_tpu.json
DATA = {'cool_plate_temp': ['30'],
 'cool_plate_temp_initial_layer': ['30'],
 'eng_plate_temp': ['50'],
 'eng_plate_temp_initial_layer': ['50'],
 'fan_cooling_layer_time': ['50'],
 'fan_max_speed': ['1000'],
 'fan_min_speed': ['80'],
 'filament_cost': ['20'],
 'filament_density': ['1.24'],
 'filament_flow_ratio': ['0.96'],
 'filament_id': 'GFRH05',
 'filament_max_volumetric_speed': ['10'],
 'filament_shrink': ['99.95'],
 'filament_type': ['TPU'],
 'from': 'system',
 'hot_plate_temp': ['50'],
 'hot_plate_temp_initial_layer': ['50'],
 'idle_temperature': '170',
 'inherits': 'fdm_filament_common',
 'instantiation': 'false',
 'name': 'fdm_filament_tpu',
 'nozzle_temperature': ['240'],
 'nozzle_temperature_initial_layer': ['240'],
 'nozzle_temperature_range_high': ['250'],
 'nozzle_temperature_range_low': ['230'],
 'overhang_fan_speed': ['100'],
 'overhang_fan_threshold': ['25%'],
 'slow_down_layer_time': ['5'],
 'slow_down_min_speed': ['15'],
 'temperature_vitrification': ['60'],
 'type': 'filament'}
