from __future__ import annotations

# source: profiles/RH3D/filament/fdm_filament_pla.json
DATA = {'cool_plate_temp': ['40'],
 'cool_plate_temp_initial_layer': ['45'],
 'eng_plate_temp': ['67'],
 'eng_plate_temp_initial_layer': ['70'],
 'fan_cooling_layer_time': ['15'],
 'fan_max_speed': ['100'],
 'fan_min_speed': ['80'],
 'filament_cost': ['20'],
 'filament_density': ['1.24'],
 'filament_flow_ratio': ['0.92'],
 'filament_id': 'GFRH04',
 'filament_max_volumetric_speed': ['24'],
 'filament_shrink': ['99.95'],
 'filament_type': ['PLA'],
 'from': 'system',
 'hot_plate_temp': ['67'],
 'hot_plate_temp_initial_layer': ['70'],
 'idle_temperature': '180',
 'inherits': 'fdm_filament_common',
 'instantiation': 'false',
 'name': 'fdm_filament_pla',
 'nozzle_temperature': ['230'],
 'nozzle_temperature_initial_layer': ['230'],
 'nozzle_temperature_range_high': ['250'],
 'nozzle_temperature_range_low': ['210'],
 'overhang_fan_speed': ['100'],
 'overhang_fan_threshold': ['25%'],
 'slow_down_layer_time': ['6'],
 'slow_down_min_speed': ['10'],
 'temperature_vitrification': ['60'],
 'type': 'filament'}
