from __future__ import annotations

# source: profiles/RH3D/filament/fdm_filament_pccf.json
DATA = {'chamber_temperature': ['55'],
 'cool_plate_temp': ['0'],
 'cool_plate_temp_initial_layer': ['0'],
 'eng_plate_temp': ['90'],
 'eng_plate_temp_initial_layer': ['90'],
 'fan_cooling_layer_time': ['10'],
 'fan_max_speed': ['40'],
 'fan_min_speed': ['25'],
 'filament_cost': ['40'],
 'filament_density': ['1.04'],
 'filament_flow_ratio': ['0.9'],
 'filament_id': 'GFRH06',
 'filament_max_volumetric_speed': ['8'],
 'filament_shrink': ['99.85'],
 'filament_type': ['PC-CF'],
 'from': 'system',
 'hot_plate_temp': ['90'],
 'hot_plate_temp_initial_layer': ['90'],
 'idle_temperature': '240',
 'inherits': 'fdm_filament_common',
 'instantiation': 'false',
 'name': 'fdm_filament_pccf',
 'nozzle_temperature': ['320'],
 'nozzle_temperature_initial_layer': ['300'],
 'nozzle_temperature_range_high': ['330'],
 'nozzle_temperature_range_low': ['290'],
 'overhang_fan_speed': ['60'],
 'overhang_fan_threshold': ['25%'],
 'slow_down_layer_time': ['2'],
 'slow_down_min_speed': ['10'],
 'temperature_vitrification': ['140'],
 'type': 'filament'}
