from __future__ import annotations

# source: profiles/RH3D/filament/fdm_filament_petg.json
DATA = {'cool_plate_temp': ['70'],
 'cool_plate_temp_initial_layer': ['70'],
 'eng_plate_temp': ['0'],
 'eng_plate_temp_initial_layer': ['0'],
 'fan_cooling_layer_time': ['10'],
 'fan_max_speed': ['60'],
 'fan_min_speed': ['20'],
 'filament_cost': ['30'],
 'filament_density': ['1.27'],
 'filament_flow_ratio': ['0.96'],
 'filament_id': 'GFRH03',
 'filament_max_volumetric_speed': ['26'],
 'filament_shrink': ['99.85'],
 'filament_type': ['PETG'],
 'from': 'system',
 'hot_plate_temp': ['90'],
 'hot_plate_temp_initial_layer': ['90'],
 'idle_temperature': '190',
 'inherits': 'fdm_filament_common',
 'instantiation': 'false',
 'name': 'fdm_filament_petg',
 'nozzle_temperature': ['250'],
 'nozzle_temperature_initial_layer': ['250'],
 'nozzle_temperature_range_high': ['260'],
 'nozzle_temperature_range_low': ['230'],
 'overhang_fan_speed': ['100'],
 'overhang_fan_threshold': ['25%'],
 'slow_down_layer_time': ['3'],
 'slow_down_min_speed': ['12'],
 'temperature_vitrification': ['80'],
 'type': 'filament'}
