from __future__ import annotations

# source: profiles/WEMAKE3D/process/0.08mm ExtraFine @WEMAKE3D PhoenixProV1 0.3mm nozzle.json
DATA = {'bottom_shell_layers': '4',
 'compatible_printers': ['WEMAKE3D PhoenixProV1 0.3mm nozzle'],
 'counterbore_hole_bridging': 'partiallybridge',
 'default_acceleration': '3000',
 'from': 'system',
 'gap_infill_speed': '200',
 'inherits': 'fdm_process_phoenixProV1_common',
 'initial_layer_acceleration': '1000',
 'initial_layer_infill_speed': '80',
 'initial_layer_line_width': '0.38',
 'initial_layer_speed': '80',
 'inner_wall_acceleration': '2500',
 'inner_wall_speed': '200',
 'instantiation': 'true',
 'internal_solid_infill_line_width': '0.32',
 'internal_solid_infill_speed': '200',
 'is_custom_defined': '0',
 'layer_height': '0.08',
 'line_width': '0.32',
 'name': '0.08mm Extra Fine @WEMAKE3D PhoenixProV1 0.3mm nozzle',
 'outer_wall_acceleration': '2000',
 'outer_wall_line_width': '0.32',
 'outer_wall_speed': '150',
 'print_settings_id': '0.08mm Extra Fine @WEMAKE3D PhoenixProV1 0.3mm nozzle',
 'slow_down_layers': '2',
 'sparse_infill_pattern': 'rectilinear',
 'sparse_infill_speed': '200',
 'support_line_width': '0.32',
 'thick_bridges': '1',
 'top_shell_layers': '4',
 'top_surface_acceleration': '2000',
 'top_surface_line_width': '0.32',
 'top_surface_speed': '150',
 'travel_acceleration': '3000',
 'travel_speed': '250',
 'version': '2.3.1.10',
 'wall_sequence': 'inner-outer-inner wall'}
