apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "printnet.fullname" . }}-backend-config
  namespace: {{ include "printnet.namespace" . }}
  labels:
    {{- include "printnet.labels" . | nindent 4 }}
data:
  BACKEND_APP_NAME: {{ .Values.backend.env.appName | quote }}
  BACKEND_APP_VERSION: {{ .Values.backend.env.appVersion | quote }}
  BACKEND_API_PREFIX: {{ .Values.backend.env.apiPrefix | quote }}
  BACKEND_QUEUE_NAME: {{ .Values.backend.env.queueName | quote }}
  BACKEND_QUEUE_WORKER_MAX_JOBS_PER_TICK: {{ .Values.backend.env.queueWorkerMaxJobsPerTick | quote }}
  BACKEND_QUEUE_WORKER_HEARTBEAT_TTL_SECONDS: {{ .Values.backend.env.queueWorkerHeartbeatTtlSeconds | quote }}
