apiVersion: v1
kind: Secret
metadata:
  name: {{ include "printnet.fullname" . }}-backend-secret
  namespace: {{ include "printnet.namespace" . }}
  labels:
    {{- include "printnet.labels" . | nindent 4 }}
type: Opaque
data:
  BACKEND_MONGO_URI: {{ .Values.backend.secretEnv.mongoUri | b64enc | quote }}
  BACKEND_REDIS_URI: {{ .Values.backend.secretEnv.redisUri | b64enc | quote }}
