{{- if .Values.mongo.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "printnet.fullname" . }}-mongo
  namespace: {{ include "printnet.namespace" . }}
  labels:
    {{- include "printnet.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongo
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: mongo
  ports:
    - name: mongo
      port: {{ .Values.mongo.service.port }}
      targetPort: {{ .Values.mongo.service.port }}
{{- end }}
