apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "printnet.fullname" . }}-worker
  namespace: {{ include "printnet.namespace" . }}
  labels:
    {{- include "printnet.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "printnet.labels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          command:
            {{- toYaml .Values.worker.command | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "printnet.fullname" . }}-backend-config
            - secretRef:
                name: {{ include "printnet.fullname" . }}-backend-secret
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
