from __future__ import annotations

# source: profiles/SecKit/machine/fdm_klipper_common.json
DATA = {'auxiliary_fan': '0',
 'bed_exclude_area': ['0x0'],
 'before_layer_change_gcode': ';BEFORE_LAYER_CHANGE\n;[layer_z]\nG92 E0\n',
 'change_filament_gcode': 'M600',
 'default_filament_profile': ['SecKit Generic PETG'],
 'default_print_profile': '0.20mm Standard @SecKit',
 'deretraction_speed': ['120'],
 'extruder_clearance_height_to_lid': '140',
 'extruder_clearance_height_to_rod': '44',
 'extruder_clearance_radius': '46',
 'from': 'system',
 'gcode_flavor': 'klipper',
 'inherits': 'fdm_machine_common',
 'instantiation': 'false',
 'layer_change_gcode': ';AFTER_LAYER_CHANGE\n;[layer_z]',
 'machine_end_gcode': 'END_PRINT',
 'machine_max_acceleration_e': ['8000', '8000'],
 'machine_max_acceleration_extruding': ['3500', '3500'],
 'machine_max_acceleration_retracting': ['3500', '3500'],
 'machine_max_acceleration_travel': ['3500', '3500'],
 'machine_max_acceleration_x': ['3500', '3500'],
 'machine_max_acceleration_y': ['3500', '3500'],
 'machine_max_acceleration_z': ['200', '200'],
 'machine_max_jerk_e': ['8', '8'],
 'machine_max_jerk_x': ['14.14', '14.14'],
 'machine_max_jerk_y': ['14.14', '14.14'],
 'machine_max_jerk_z': ['2', '2'],
 'machine_max_speed_e': ['180', '180'],
 'machine_max_speed_x': ['300', '300'],
 'machine_max_speed_y': ['300', '300'],
 'machine_max_speed_z': ['12', '12'],
 'machine_min_extruding_rate': ['0', '0'],
 'machine_min_travel_rate': ['0', '0'],
 'machine_pause_gcode': 'M601',
 'machine_start_gcode': 'START_PRINT EXTRUDER_TEMP=[nozzle_temperature_initial_layer] '
                        'BED_TEMP=[bed_temperature_initial_layer_single]\n'
                        'G90\n'
                        'G92 E0',
 'max_layer_height': ['0.35'],
 'min_layer_height': ['0.05'],
 'name': 'fdm_klipper_common',
 'nozzle_type': 'undefine',
 'printable_height': '400',
 'printer_settings_id': '',
 'printer_technology': 'FFF',
 'printer_variant': '0.4',
 'retract_before_wipe': ['70%'],
 'retract_length_toolchange': ['1'],
 'retract_restart_extra': ['0'],
 'retract_restart_extra_toolchange': ['0'],
 'retract_when_changing_layer': ['1'],
 'retraction_length': ['1.2'],
 'retraction_minimum_travel': ['2'],
 'retraction_speed': ['120'],
 'scan_first_layer': '0',
 'silent_mode': '0',
 'single_extruder_multi_material': '1',
 'type': 'machine',
 'wipe': ['1'],
 'z_hop': ['0.25'],
 'z_hop_types': 'Normal Lift'}
