from __future__ import annotations

# source: profiles/RH3D/machine/fdm_machine_common.json
DATA = {'before_layer_change_gcode': ';BEFORE_LAYER_CHANGE\nG92 E0',
 'change_filament_gcode': 'PAUSE\nG1 E1.0 F300 ; prime after color change',
 'default_filament_profile': 'Generic PLA @E3NG v1.2S',
 'deretraction_speed': '60',
 'emit_machine_limits_to_gcode': '0',
 'extruder_colour': '#02aba2',
 'extruder_offset': '0x0',
 'from': 'system',
 'gcode_flavor': 'klipper',
 'instantiation': 'false',
 'layer_change_gcode': ';AFTER_LAYER_CHANGE',
 'machine_end_gcode': 'PRINT_END',
 'machine_min_extruding_rate': ['0', '0'],
 'machine_min_travel_rate': ['0', '0'],
 'machine_pause_gcode': 'PAUSE\n',
 'machine_start_gcode': 'M104 S0 ; Stops EONSlicer from sending temp waits separately\n'
                        'M140 S0\n'
                        'PRINT_START EXTRUDER=[first_layer_temperature] BED=[first_layer_bed_temperature]\n'
                        '; Start of actual GCode for the print',
 'max_layer_height': '0.30',
 'min_layer_height': '0.10',
 'name': 'fdm_machine_common',
 'nozzle_diameter': '0.4',
 'printer_settings_id': '',
 'printer_structure': 'corexy',
 'printer_technology': 'FFF',
 'printer_variant': '0.4',
 'retract_length_toolchange': '2',
 'retract_restart_extra': '0',
 'retract_restart_extra_toolchange': '0',
 'retract_when_changing_layer': '1',
 'retraction_length': '0.6',
 'retraction_minimum_travel': '1',
 'retraction_speed': '40',
 'single_extruder_multi_material': '0',
 'thumbnails': ['16x16/QOI', '313x173/QOI', '440x240/QOI', '480x240/QOI', '32x32/PNG', '320x240/PNG', '640x480/PNG'],
 'type': 'machine',
 'use_firmware_retraction': '1',
 'use_relative_e_distances': '1',
 'wipe': '1',
 'z_hop': '0.0',
 'z_hop_types': 'Slope Lift'}
