from __future__ import annotations

# source: profiles/Artillery/filament/Artillery PA-CF @Artillery M1 Pro 0.4 nozzle.json
DATA = {'additional_cooling_fan_speed': ['100'],
 'chamber_temperature': ['55'],
 'close_fan_the_first_x_layers': ['3'],
 'compatible_printers': ['Artillery M1 Pro 0.4 nozzle'],
 'complete_print_exhaust_fan_speed': ['0'],
 'cool_plate_temp': ['110'],
 'cool_plate_temp_initial_layer': ['110'],
 'during_print_exhaust_fan_speed': ['0'],
 'enable_pressure_advance': ['1'],
 'fan_cooling_layer_time': ['5'],
 'fan_max_speed': ['30'],
 'fan_min_speed': ['30'],
 'filament_deretraction_speed': ['30'],
 'filament_flow_ratio': ['0.93'],
 'filament_max_volumetric_speed': ['6'],
 'filament_retract_lift_below': ['259'],
 'filament_retraction_length': ['0.8'],
 'filament_retraction_speed': ['30'],
 'filament_settings_id': ['Artillery PA-CF @Artillery M1 Pro 0.4 nozzle'],
 'filament_start_gcode': [''],
 'filament_type': ['PA-CF'],
 'filament_vendor': ['Artillery'],
 'filament_z_hop': ['0.6'],
 'filament_z_hop_types': ['Normal Lift'],
 'from': 'system',
 'hot_plate_temp': ['50'],
 'hot_plate_temp_initial_layer': ['50'],
 'inherits': 'Artillery Generic PLA',
 'instantiation': 'true',
 'is_custom_defined': '0',
 'name': 'Artillery PA-CF @Artillery M1 Pro 0.4 nozzle',
 'nozzle_temperature': ['250'],
 'nozzle_temperature_initial_layer': ['250'],
 'nozzle_temperature_range_high': ['280'],
 'nozzle_temperature_range_low': ['230'],
 'overhang_fan_speed': ['80'],
 'overhang_fan_threshold': ['0%'],
 'pressure_advance': ['0.092'],
 'reduce_fan_stop_start_freq': ['0'],
 'slow_down_layer_time': ['2'],
 'slow_down_min_speed': ['10'],
 'temperature_vitrification': ['108'],
 'textured_plate_temp': ['100'],
 'textured_plate_temp_initial_layer': ['100'],
 'version': '2.1.2.2'}
