from __future__ import annotations

# source: profiles/Artillery/filament/Artillery PLA Matte @Artillery M1 Pro 0.4 nozzle.json
DATA = {'additional_cooling_fan_speed': ['50'],
 'compatible_printers': ['Artillery M1 Pro 0.4 nozzle'],
 'complete_print_exhaust_fan_speed': ['0'],
 'cool_plate_temp': ['50'],
 'cool_plate_temp_initial_layer': ['50'],
 'during_print_exhaust_fan_speed': ['60'],
 'enable_pressure_advance': ['1'],
 'fan_cooling_layer_time': ['100'],
 'fan_max_speed': ['100'],
 'fan_min_speed': ['100'],
 'filament_flow_ratio': ['1'],
 'filament_max_volumetric_speed': ['27'],
 'filament_retraction_length': ['1.3'],
 'filament_retraction_speed': ['40'],
 'filament_settings_id': ['Artillery PLA Matte @Artillery M1 Pro 0.4 nozzle'],
 'filament_start_gcode': [''],
 'filament_type': ['PLA Matte'],
 'filament_vendor': ['Artillery'],
 'filament_z_hop': ['0.6'],
 'from': 'system',
 'inherits': 'Artillery Generic PLA',
 'instantiation': 'true',
 'is_custom_defined': '0',
 'name': 'Artillery PLA Matte @Artillery M1 Pro 0.4 nozzle',
 'nozzle_temperature': ['220'],
 'nozzle_temperature_initial_layer': ['220'],
 'pressure_advance': ['0.038'],
 'slow_down_layer_time': ['6'],
 'slow_down_min_speed': ['15'],
 'temperature_vitrification': ['60'],
 'textured_plate_temp': ['55'],
 'textured_plate_temp_initial_layer': ['55'],
 'type': 'filament',
 'version': '2.1.2.2'}
