from __future__ import annotations

# source: profiles/Artillery/filament/Artillery ABS @Artillery M1 Pro 0.4 nozzle.json
DATA = {'additional_cooling_fan_speed': ['0'],
 'chamber_temperature': ['50'],
 'close_fan_the_first_x_layers': ['3'],
 'compatible_printers': ['Artillery M1 Pro 0.4 nozzle'],
 'complete_print_exhaust_fan_speed': ['0'],
 'cool_plate_temp': ['100'],
 'cool_plate_temp_initial_layer': ['100'],
 'during_print_exhaust_fan_speed': ['0'],
 'enable_pressure_advance': ['1'],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['60'],
 'fan_min_speed': ['10'],
 'filament_max_volumetric_speed': ['16'],
 'filament_retraction_length': ['0.8'],
 'filament_retraction_speed': ['40'],
 'filament_settings_id': ['Artillery ABS @Artillery M1 Pro 0.4 nozzle'],
 'filament_start_gcode': [''],
 'filament_type': ['ABS'],
 'filament_vendor': ['Artillery'],
 'filament_z_hop': ['0.4'],
 'from': 'system',
 'hot_plate_temp': ['100'],
 'hot_plate_temp_initial_layer': ['100'],
 'inherits': 'Artillery Generic PLA',
 'instantiation': 'true',
 'is_custom_defined': '0',
 'name': 'Artillery ABS @Artillery M1 Pro 0.4 nozzle',
 'nozzle_temperature': ['260'],
 'nozzle_temperature_initial_layer': ['260'],
 'nozzle_temperature_range_high': ['270'],
 'nozzle_temperature_range_low': ['240'],
 'overhang_fan_speed': ['80'],
 'overhang_fan_threshold': ['25%'],
 'pressure_advance': ['0.05'],
 'slow_down_layer_time': ['12'],
 'temperature_vitrification': ['220'],
 'textured_plate_temp': ['100'],
 'textured_plate_temp_initial_layer': ['100'],
 'type': 'filament',
 'version': '2.1.2.2'}
