from __future__ import annotations

# source: profiles/Artillery/filament/Artillery TPU.json
DATA = {'compatible_printers': ['Artillery Sidewinder X3 Pro 0.4 nozzle',
                         'Artillery Sidewinder X3 Plus 0.4 nozzle',
                         'Artillery Sidewinder X4 Pro 0.4 nozzle',
                         'Artillery Sidewinder X4 Plus 0.4 nozzle'],
 'enable_pressure_advance': ['1'],
 'fan_cooling_layer_time': ['100'],
 'fan_max_speed': ['100'],
 'fan_min_speed': ['100'],
 'filament_density': ['1.22'],
 'filament_max_volumetric_speed': ['3.6'],
 'filament_retraction_length': ['1.3'],
 'filament_retraction_speed': ['40'],
 'filament_settings_id': ['Artillery TPU'],
 'filament_start_gcode': [''],
 'filament_type': ['TPU'],
 'filament_vendor': ['Artillery'],
 'filament_z_hop': ['0.4'],
 'from': 'system',
 'hot_plate_temp': ['45'],
 'hot_plate_temp_initial_layer': ['45'],
 'inherits': 'Artillery Generic PLA',
 'instantiation': 'true',
 'name': 'Artillery TPU',
 'nozzle_temperature': ['220'],
 'nozzle_temperature_initial_layer': ['220'],
 'nozzle_temperature_range_high': ['250'],
 'nozzle_temperature_range_low': ['200'],
 'overhang_fan_threshold': ['95%'],
 'pressure_advance': ['0.06'],
 'slow_down_layer_time': ['8'],
 'temperature_vitrification': ['190'],
 'type': 'filament',
 'version': '2.0.2.0'}
