from __future__ import annotations

# source: profiles/Artillery/filament/Artillery PC @Artillery M1 Pro 0.4 nozzle.json
DATA = {'additional_cooling_fan_speed': ['0'],
 'chamber_temperature': ['50'],
 'close_fan_the_first_x_layers': ['3'],
 'compatible_printers': ['Artillery M1 Pro 0.4 nozzle'],
 'complete_print_exhaust_fan_speed': ['0'],
 'cool_plate_temp': ['110'],
 'cool_plate_temp_initial_layer': ['110'],
 'during_print_exhaust_fan_speed': ['0'],
 'enable_pressure_advance': ['1'],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['0'],
 'fan_min_speed': ['0'],
 'filament_deretraction_speed': ['30'],
 'filament_flow_ratio': ['0.94'],
 'filament_max_volumetric_speed': ['6'],
 'filament_retract_lift_below': ['259'],
 'filament_retraction_length': ['0.8'],
 'filament_retraction_speed': ['30'],
 'filament_settings_id': ['Artillery PC @Artillery M1 Pro 0.4 nozzle'],
 'filament_start_gcode': [''],
 'filament_type': ['PC'],
 'filament_vendor': ['Artillery'],
 'filament_z_hop': ['0.4'],
 'from': 'system',
 'hot_plate_temp': ['50'],
 'hot_plate_temp_initial_layer': ['50'],
 'inherits': 'Artillery Generic PLA',
 'instantiation': 'true',
 'is_custom_defined': '0',
 'name': 'Artillery PC @Artillery M1 Pro 0.4 nozzle',
 'nozzle_temperature': ['295'],
 'nozzle_temperature_initial_layer': ['295'],
 'nozzle_temperature_range_high': ['300'],
 'nozzle_temperature_range_low': ['250'],
 'overhang_fan_speed': ['60'],
 'overhang_fan_threshold': ['25%'],
 'pressure_advance': ['0.03'],
 'reduce_fan_stop_start_freq': ['0'],
 'slow_down_layer_time': ['2'],
 'slow_down_min_speed': ['0'],
 'temperature_vitrification': ['120'],
 'textured_plate_temp': ['110'],
 'textured_plate_temp_initial_layer': ['110'],
 'type': 'filament',
 'version': '2.1.2.2'}
