from __future__ import annotations

# source: profiles/Artillery/filament/Artillery PET @Artillery M1 Pro 0.4 nozzle.json
DATA = {'additional_cooling_fan_speed': ['50'],
 'chamber_temperature': ['0'],
 'close_fan_the_first_x_layers': ['3'],
 'compatible_printers': ['Artillery M1 Pro 0.4 nozzle'],
 'complete_print_exhaust_fan_speed': ['0'],
 'cool_plate_temp': ['80'],
 'cool_plate_temp_initial_layer': ['80'],
 'during_print_exhaust_fan_speed': ['60'],
 'enable_pressure_advance': ['1'],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['90'],
 'fan_min_speed': ['40'],
 'filament_deretraction_speed': ['30'],
 'filament_flow_ratio': ['0.97'],
 'filament_max_volumetric_speed': ['12'],
 'filament_retraction_length': ['0.8'],
 'filament_retraction_speed': ['30'],
 'filament_settings_id': ['Artillery PET @Artillery M1 Pro 0.4 nozzle'],
 'filament_start_gcode': ['; filament start gcode '],
 'filament_type': ['PET'],
 'filament_vendor': ['Artillery'],
 'filament_z_hop': ['0.4'],
 'from': 'system',
 'hot_plate_temp': ['100'],
 'hot_plate_temp_initial_layer': ['100'],
 'inherits': 'Artillery Generic PLA',
 'instantiation': 'true',
 'is_custom_defined': '0',
 'name': 'Artillery PET @Artillery M1 Pro 0.4 nozzle',
 'nozzle_temperature': ['240'],
 'nozzle_temperature_initial_layer': ['240'],
 'nozzle_temperature_range_high': ['270'],
 'nozzle_temperature_range_low': ['230'],
 'overhang_fan_speed': ['100'],
 'overhang_fan_threshold': ['10%'],
 'pressure_advance': ['0.08'],
 'slow_down_layer_time': ['12'],
 'slow_down_min_speed': ['20'],
 'temperature_vitrification': ['70'],
 'textured_plate_temp': ['80'],
 'textured_plate_temp_initial_layer': ['80'],
 'type': 'filament',
 'version': '2.1.2.2'}
