from __future__ import annotations

# source: profiles/Artillery/filament/Artillery PLA Basic+ @Artillery M1 Pro 0.4 nozzle.json
DATA = {'additional_cooling_fan_speed': ['50'],
 'compatible_printers': ['Artillery M1 Pro 0.4 nozzle'],
 'complete_print_exhaust_fan_speed': ['100'],
 'during_print_exhaust_fan_speed': ['100'],
 'enable_pressure_advance': ['1'],
 'fan_cooling_layer_time': ['100'],
 'fan_max_speed': ['100'],
 'fan_min_speed': ['100'],
 'filament_flow_ratio': ['1.029'],
 'filament_max_volumetric_speed': ['21'],
 'filament_retraction_length': ['1.3'],
 'filament_retraction_speed': ['40'],
 'filament_settings_id': ['Artillery PLA Basic+ @Artillery M1 Pro 0.4 nozzle'],
 'filament_start_gcode': [''],
 'filament_type': ['PLA Basic+'],
 'filament_vendor': ['Artillery'],
 'filament_z_hop': ['0.4'],
 'from': 'system',
 'inherits': 'Artillery Generic PLA',
 'instantiation': 'true',
 'is_custom_defined': '0',
 'name': 'Artillery PLA Basic+ @Artillery M1 Pro 0.4 nozzle',
 'nozzle_temperature': ['210'],
 'nozzle_temperature_initial_layer': ['210'],
 'pressure_advance': ['0.032'],
 'slow_down_layer_time': ['6'],
 'temperature_vitrification': ['190'],
 'type': 'filament',
 'version': '2.1.1.0'}
