from __future__ import annotations

# source: profiles/Artillery/filament/Artillery TPU @Artillery M1 Pro 0.4 nozzle.json
DATA = {'additional_cooling_fan_speed': ['50'],
 'close_fan_the_first_x_layers': ['1'],
 'compatible_printers': ['Artillery M1 Pro 0.4 nozzle'],
 'complete_print_exhaust_fan_speed': ['0'],
 'cool_plate_temp': ['60'],
 'cool_plate_temp_initial_layer': ['60'],
 'during_print_exhaust_fan_speed': ['60'],
 'enable_pressure_advance': ['1'],
 'fan_cooling_layer_time': ['100'],
 'fan_max_speed': ['100'],
 'fan_min_speed': ['100'],
 'filament_density': ['1.24'],
 'filament_deretraction_speed': ['30'],
 'filament_flow_ratio': ['1.067'],
 'filament_max_volumetric_speed': ['2'],
 'filament_retract_lift_below': ['259'],
 'filament_retraction_length': ['0.4'],
 'filament_retraction_speed': ['30'],
 'filament_settings_id': ['Artillery TPU @Artillery M1 Pro 0.4 nozzle'],
 'filament_start_gcode': [''],
 'filament_type': ['TPU'],
 'filament_vendor': ['Artillery'],
 'filament_z_hop': ['0.4'],
 'from': 'system',
 'hot_plate_temp': ['60'],
 'hot_plate_temp_initial_layer': ['60'],
 'inherits': 'Artillery Generic PLA',
 'instantiation': 'true',
 'is_custom_defined': '0',
 'name': 'Artillery TPU @Artillery M1 Pro 0.4 nozzle',
 'nozzle_temperature': ['230'],
 'nozzle_temperature_initial_layer': ['230'],
 'nozzle_temperature_range_high': ['250'],
 'nozzle_temperature_range_low': ['210'],
 'overhang_fan_threshold': ['95%'],
 'pressure_advance': ['0.08'],
 'slow_down_layer_time': ['8'],
 'temperature_vitrification': ['60'],
 'textured_plate_temp': ['60'],
 'textured_plate_temp_initial_layer': ['60'],
 'type': 'filament',
 'version': '2.1.2.2'}
