from __future__ import annotations

# source: profiles/Artillery/filament/Artillery PLA Matte.json
DATA = {'compatible_printers': ['Artillery Sidewinder X3 Pro 0.4 nozzle',
                         'Artillery Sidewinder X3 Plus 0.4 nozzle',
                         'Artillery Sidewinder X4 Pro 0.4 nozzle',
                         'Artillery Sidewinder X4 Plus 0.4 nozzle'],
 'enable_pressure_advance': ['1'],
 'fan_cooling_layer_time': ['80'],
 'fan_max_speed': ['80'],
 'fan_min_speed': ['60'],
 'filament_max_volumetric_speed': ['22'],
 'filament_retraction_length': ['1.3'],
 'filament_retraction_speed': ['40'],
 'filament_settings_id': ['Artillery PLA Matte'],
 'filament_start_gcode': [''],
 'filament_type': ['PLA Matte'],
 'filament_vendor': ['Artillery'],
 'filament_z_hop': ['0.4'],
 'from': 'system',
 'inherits': 'Artillery Generic PLA',
 'instantiation': 'true',
 'name': 'Artillery PLA Matte',
 'nozzle_temperature': ['210'],
 'nozzle_temperature_initial_layer': ['210'],
 'pressure_advance': ['0.046'],
 'slow_down_layer_time': ['8'],
 'temperature_vitrification': ['190'],
 'type': 'filament',
 'version': '2.0.2.0'}
