from __future__ import annotations

# source: profiles/Creality/filament/Creality Generic TPU @Ender-3V3-all.json
DATA = {'compatible_printers': ['Creality Ender-3 V3 SE 0.2 nozzle',
                         'Creality Ender-3 V3 SE 0.4 nozzle',
                         'Creality Ender-3 V3 SE 0.6 nozzle',
                         'Creality Ender-3 V3 SE 0.8 nozzle',
                         'Creality Ender-3 V3 KE 0.4 nozzle',
                         'Creality Ender-3 V3 0.4 nozzle',
                         'Creality Ender-3 V3 0.6 nozzle',
                         'Creality Ender-3 V3 Plus 0.4 nozzle',
                         'Creality Ender-3 V3 Plus 0.6 nozzle'],
 'filament_max_volumetric_speed': ['3.5'],
 'from': 'system',
 'hot_plate_temp': ['30'],
 'hot_plate_temp_initial_layer': ['30'],
 'inherits': 'Creality Generic TPU',
 'instantiation': 'true',
 'name': 'Creality Generic TPU @Ender-3V3-all',
 'nozzle_temperature': ['230'],
 'nozzle_temperature_initial_layer': ['230'],
 'setting_id': 'GFU99_CREALITY_00',
 'slow_down_layer_time': ['5'],
 'textured_plate_temp': ['30'],
 'textured_plate_temp_initial_layer': ['30'],
 'type': 'filament'}
