from __future__ import annotations

# source: profiles/Creality/filament/Creality Generic TPU.json
DATA = {'compatible_printers': ['Creality CR-10 V3 0.4 nozzle',
                         'Creality CR-10 V3 0.6 nozzle',
                         'Creality K1 (0.4 nozzle)',
                         'Creality K1 (0.6 nozzle)',
                         'Creality K1 (0.8 nozzle)',
                         'Creality K1 Max (0.4 nozzle)',
                         'Creality K1 Max (0.6 nozzle)',
                         'Creality K1 Max (0.8 nozzle)',
                         'Creality Sermoon V1 0.4 nozzle',
                         'Creality CR-10 SE 0.2 nozzle',
                         'Creality CR-10 SE 0.4 nozzle',
                         'Creality CR-10 SE 0.6 nozzle',
                         'Creality CR-10 SE 0.8 nozzle',
                         'Creality Ender-3 S1 Pro 0.4 nozzle',
                         'Creality Ender-3 S1 0.4 nozzle'],
 'filament_id': 'GFU99',
 'filament_max_volumetric_speed': ['3.2'],
 'from': 'system',
 'inherits': 'fdm_filament_tpu',
 'instantiation': 'true',
 'name': 'Creality Generic TPU',
 'setting_id': 'GFSA04',
 'type': 'filament'}
