from __future__ import annotations

# source: profiles/Creality/filament/Creality Generic PA-CF.json
DATA = {'compatible_printers': ['Creality CR-10 V2 0.4 nozzle',
                         'Creality CR-10 V3 0.4 nozzle',
                         'Creality CR-10 V3 0.6 nozzle',
                         'Creality CR-10 Max 0.4 nozzle',
                         'Creality CR-6 SE 0.2 nozzle',
                         'Creality CR-6 SE 0.4 nozzle',
                         'Creality CR-6 SE 0.6 nozzle',
                         'Creality CR-6 SE 0.8 nozzle',
                         'Creality CR-6 Max 0.2 nozzle',
                         'Creality CR-6 Max 0.4 nozzle',
                         'Creality CR-6 Max 0.6 nozzle',
                         'Creality CR-6 Max 0.8 nozzle',
                         'Creality Ender-3 0.2 nozzle',
                         'Creality Ender-3 0.4 nozzle',
                         'Creality Ender-3 0.6 nozzle',
                         'Creality Ender-3 0.8 nozzle',
                         'Creality Ender-3 Pro 0.2 nozzle',
                         'Creality Ender-3 Pro 0.4 nozzle',
                         'Creality Ender-3 Pro 0.6 nozzle',
                         'Creality Ender-3 Pro 0.8 nozzle',
                         'Creality Ender-3 V2 0.4 nozzle',
                         'Creality Ender-3 V2 Neo 0.4 nozzle',
                         'Creality Ender-3 S1 0.4 nozzle',
                         'Creality Ender-3 S1 Pro 0.4 nozzle',
                         'Creality Ender-5 0.4 nozzle',
                         'Creality Ender-5 Plus 0.4 nozzle',
                         'Creality Ender-5 Pro (2019) 0.2 nozzle',
                         'Creality Ender-5 Pro (2019) 0.25 nozzle',
                         'Creality Ender-5 Pro (2019) 0.3 nozzle',
                         'Creality Ender-5 Pro (2019) 0.4 nozzle',
                         'Creality Ender-5 Pro (2019) 0.5 nozzle',
                         'Creality Ender-5 Pro (2019) 0.6 nozzle',
                         'Creality Ender-5 Pro (2019) 0.8 nozzle',
                         'Creality Ender-5 Pro (2019) 1.0 nozzle',
                         'Creality Ender-5S 0.4 nozzle',
                         'Creality Ender-5 S1 0.4 nozzle',
                         'Creality Ender-6 0.4 nozzle'],
 'enable_pressure_advance': ['1'],
 'fan_cooling_layer_time': ['5'],
 'fan_max_speed': ['30'],
 'fan_min_speed': ['10'],
 'filament_id': 'GFN98',
 'filament_max_volumetric_speed': ['8'],
 'filament_type': ['PA-CF'],
 'from': 'system',
 'full_fan_speed_layer': ['2'],
 'inherits': 'fdm_filament_pa',
 'instantiation': 'true',
 'name': 'Creality Generic PA-CF',
 'nozzle_temperature': ['290'],
 'nozzle_temperature_initial_layer': ['290'],
 'overhang_fan_speed': ['40'],
 'overhang_fan_threshold': ['0%'],
 'pressure_advance': ['0.01'],
 'setting_id': 'GFSN99',
 'type': 'filament'}
