from __future__ import annotations

# source: profiles/Creality/filament/Creality Generic PETG @Ender-3V3-all.json
DATA = {'compatible_printers': ['Creality Ender-3 V3 SE 0.2 nozzle',
                         'Creality Ender-3 V3 SE 0.4 nozzle',
                         'Creality Ender-3 V3 SE 0.6 nozzle',
                         'Creality Ender-3 V3 SE 0.8 nozzle',
                         'Creality Ender-3 V3 KE 0.4 nozzle',
                         'Creality Ender-3 V3 0.4 nozzle',
                         'Creality Ender-3 V3 0.6 nozzle',
                         'Creality Ender-3 V3 Plus 0.4 nozzle',
                         'Creality Ender-3 V3 Plus 0.6 nozzle'],
 'cool_plate_temp': ['70'],
 'cool_plate_temp_initial_layer': ['70'],
 'eng_plate_temp': ['70'],
 'eng_plate_temp_initial_layer': ['70'],
 'filament_max_volumetric_speed': ['9'],
 'from': 'system',
 'hot_plate_temp': ['70'],
 'hot_plate_temp_initial_layer': ['70'],
 'inherits': 'Creality Generic PETG',
 'instantiation': 'true',
 'name': 'Creality Generic PETG @Ender-3V3-all',
 'nozzle_temperature': ['250'],
 'nozzle_temperature_initial_layer': ['250'],
 'setting_id': 'GFSG99_00',
 'slow_down_layer_time': ['5'],
 'textured_plate_temp': ['70'],
 'textured_plate_temp_initial_layer': ['70'],
 'type': 'filament'}
