from __future__ import annotations

# source: profiles/FlyingBear/filament/S1/fdm_filament_pa_other @S1.json
DATA = {'activate_air_filtration': ['1'],
 'close_fan_the_first_x_layers': ['3'],
 'complete_print_exhaust_fan_speed': ['80'],
 'cool_plate_temp': ['0'],
 'cool_plate_temp_initial_layer': ['0'],
 'during_print_exhaust_fan_speed': ['100'],
 'eng_plate_temp': ['110'],
 'eng_plate_temp_initial_layer': ['110'],
 'fan_cooling_layer_time': ['5'],
 'fan_max_speed': ['30'],
 'fan_min_speed': ['10'],
 'filament_cost': ['20'],
 'filament_density': ['1.04'],
 'filament_max_volumetric_speed': ['8'],
 'filament_type': ['PA'],
 'filament_vendor': ['Other'],
 'from': 'system',
 'hot_plate_temp': ['110'],
 'hot_plate_temp_initial_layer': ['110'],
 'inherits': 'fdm_filament_common_S1',
 'instantiation': 'false',
 'name': 'fdm_filament_pa_other @S1',
 'nozzle_temperature': ['270'],
 'nozzle_temperature_initial_layer': ['270'],
 'nozzle_temperature_range_high': ['280'],
 'nozzle_temperature_range_low': ['240'],
 'overhang_fan_speed': ['40'],
 'reduce_fan_stop_start_freq': ['0'],
 'slow_down_for_layer_cooling': ['1'],
 'slow_down_layer_time': ['2'],
 'slow_down_min_speed': ['20'],
 'temperature_vitrification': ['108'],
 'textured_plate_temp': ['110'],
 'textured_plate_temp_initial_layer': ['110'],
 'type': 'filament'}
