from __future__ import annotations

# source: profiles/FlyingBear/filament/S1/fdm_filament_tpu_other @S1.json
DATA = {'additional_cooling_fan_speed': ['100'],
 'close_fan_the_first_x_layers': ['1'],
 'cool_plate_temp': ['30'],
 'cool_plate_temp_initial_layer': ['30'],
 'eng_plate_temp': ['30'],
 'eng_plate_temp_initial_layer': ['30'],
 'fan_cooling_layer_time': ['100'],
 'fan_max_speed': ['100'],
 'fan_min_speed': ['100'],
 'filament_cost': ['20'],
 'filament_density': ['1.24'],
 'filament_max_volumetric_speed': ['3.2'],
 'filament_start_gcode': ['; filament start gcode\n'],
 'filament_type': ['TPU'],
 'filament_vendor': ['Other'],
 'filament_z_hop': ['0'],
 'from': 'system',
 'hot_plate_temp': ['40'],
 'hot_plate_temp_initial_layer': ['40'],
 'inherits': 'fdm_filament_common_S1',
 'instantiation': 'false',
 'name': 'fdm_filament_tpu_other @S1',
 'nozzle_temperature': ['230'],
 'nozzle_temperature_initial_layer': ['230'],
 'nozzle_temperature_range_high': ['250'],
 'nozzle_temperature_range_low': ['200'],
 'overhang_fan_speed': ['100'],
 'overhang_fan_threshold': ['95%'],
 'reduce_fan_stop_start_freq': ['1'],
 'slow_down_for_layer_cooling': ['1'],
 'slow_down_layer_time': ['10'],
 'temperature_vitrification': ['60'],
 'textured_plate_temp': ['35'],
 'textured_plate_temp_initial_layer': ['35'],
 'type': 'filament'}
