PRINTER_CATALOG = [
    {
        "name": "Prusa Original Prusa MK4S",
        "brand": "Prusa",
        "model": "Original Prusa MK4S",
        "year": 2024,
        "technology": "FFF",
        "bed_x": 250.0,
        "bed_y": 210.0,
        "bed_z": 220.0,
        "print_speed": "Up to 200 mm/s (fast profiles)",
        "travel_speed": "Up to 200+ mm/s",
        "supported_materials": "PLA, PETG, ABS, ASA, TPU, nylon, composites",
        "nozzle_diameter": "0.4 mm (default), supports 0.25-0.8 mm",
        "filament_diameter": "1.75 mm",
        "max_hotend_temp": "290 C",
        "max_bed_temp": "120 C",
        "connectivity": "USB drive, LAN (Ethernet), optional Wi-Fi module",
        "firmware": "Custom 32-bit STM32 (Prusa xBuddy)",
        "open_source": "Yes",
        "octoprint_url": "",
        "octoprint_api_key": "",
    },
    {
        "name": "Prusa Original Prusa XL (Single Toolhead)",
        "brand": "Prusa",
        "model": "Original Prusa XL (Single Toolhead)",
        "year": 2023,
        "technology": "FFF (CoreXY)",
        "bed_x": 360.0,
        "bed_y": 360.0,
        "bed_z": 360.0,
        "print_speed": "Up to 200 mm/s (default profiles slower for quality)",
        "travel_speed": "Up to 300 mm/s (estimated)",
        "supported_materials": "PLA, PETG, ABS, ASA, PC, Nylon, composites (enclosed)",
        "nozzle_diameter": "0.6 mm (default), quick-change toolheads",
        "filament_diameter": "1.75 mm",
        "max_hotend_temp": "300 C",
        "max_bed_temp": "120 C",
        "connectivity": "Ethernet, Wi-Fi, USB",
        "firmware": "Custom 32-bit (Prusa) firmware",
        "open_source": "Yes",
        "octoprint_url": "",
        "octoprint_api_key": "",
    },
    {
        "name": "Bambu Lab X1 Carbon",
        "brand": "Bambu Lab",
        "model": "X1 Carbon",
        "year": 2022,
        "technology": "FFF (CoreXY high-speed)",
        "bed_x": 256.0,
        "bed_y": 256.0,
        "bed_z": 256.0,
        "print_speed": "Up to 500 mm/s",
        "travel_speed": "Up to 500 mm/s",
        "supported_materials": "PLA, PETG, ABS, ASA, PC, TPU, Nylon, CF/GF composites",
        "nozzle_diameter": "0.4 mm (default), supports 0.2-0.6 mm",
        "filament_diameter": "1.75 mm",
        "max_hotend_temp": "300 C",
        "max_bed_temp": "120 C",
        "connectivity": "Wi-Fi, SD card, cloud print",
        "firmware": "Customized firmware (closed-source control)",
        "open_source": "Partially",
        "octoprint_url": "",
        "octoprint_api_key": "",
    },
    {
        "name": "Bambu Lab P1P",
        "brand": "Bambu Lab",
        "model": "P1P",
        "year": 2022,
        "technology": "FFF (CoreXY high-speed)",
        "bed_x": 256.0,
        "bed_y": 256.0,
        "bed_z": 256.0,
        "print_speed": "Up to 500 mm/s",
        "travel_speed": "Up to 500 mm/s",
        "supported_materials": "PLA, PETG, ABS, ASA, TPU, Nylon",
        "nozzle_diameter": "0.4 mm (default)",
        "filament_diameter": "1.75 mm",
        "max_hotend_temp": "300 C",
        "max_bed_temp": "100 C",
        "connectivity": "Wi-Fi, SD card",
        "firmware": "Customized 32-bit firmware",
        "open_source": "Partially",
        "octoprint_url": "",
        "octoprint_api_key": "",
    },
    {
        "name": "Creality K1 Max",
        "brand": "Creality",
        "model": "K1 Max",
        "year": 2023,
        "technology": "FFF (CoreXY high-speed, Klipper)",
        "bed_x": 300.0,
        "bed_y": 300.0,
        "bed_z": 300.0,
        "print_speed": "Up to 600 mm/s",
        "travel_speed": "Up to 600 mm/s",
        "supported_materials": "PLA, PETG, ABS, ASA, TPU",
        "nozzle_diameter": "0.4 mm (volcano-type)",
        "filament_diameter": "1.75 mm",
        "max_hotend_temp": "300 C",
        "max_bed_temp": "110 C",
        "connectivity": "Wi-Fi, Ethernet, USB",
        "firmware": "Klipper-based",
        "open_source": "Partially",
        "octoprint_url": "",
        "octoprint_api_key": "",
    },
    {
        "name": "Creality Ender-3 S1 Pro",
        "brand": "Creality",
        "model": "Ender-3 S1 Pro",
        "year": 2022,
        "technology": "FFF (Cartesian, direct-drive)",
        "bed_x": 220.0,
        "bed_y": 220.0,
        "bed_z": 270.0,
        "print_speed": "Up to 150 mm/s",
        "travel_speed": "200 mm/s",
        "supported_materials": "PLA, PETG, ABS, TPU, Nylon",
        "nozzle_diameter": "0.4 mm",
        "filament_diameter": "1.75 mm",
        "max_hotend_temp": "300 C",
        "max_bed_temp": "110 C",
        "connectivity": "MicroSD, USB-C",
        "firmware": "Marlin",
        "open_source": "Yes",
        "octoprint_url": "",
        "octoprint_api_key": "",
    },
    {
        "name": "Creality Ender-3",
        "brand": "Creality",
        "model": "Ender-3",
        "year": 2018,
        "technology": "FFF (Cartesian, Bowden)",
        "bed_x": 220.0,
        "bed_y": 220.0,
        "bed_z": 250.0,
        "print_speed": "50-70 mm/s typical",
        "travel_speed": "180-200 mm/s",
        "supported_materials": "PLA, TPU, ABS",
        "nozzle_diameter": "0.4 mm (MK8)",
        "filament_diameter": "1.75 mm",
        "max_hotend_temp": "260 C",
        "max_bed_temp": "110 C",
        "connectivity": "microSD, USB",
        "firmware": "Marlin",
        "open_source": "Yes",
        "octoprint_url": "",
        "octoprint_api_key": "",
    },
    {
        "name": "Creality CR-10",
        "brand": "Creality",
        "model": "CR-10",
        "year": 2017,
        "technology": "FFF (Cartesian, Bowden)",
        "bed_x": 300.0,
        "bed_y": 300.0,
        "bed_z": 400.0,
        "print_speed": "50-80 mm/s typical",
        "travel_speed": "150 mm/s",
        "supported_materials": "PLA, ABS, PETG, TPU",
        "nozzle_diameter": "0.4 mm",
        "filament_diameter": "1.75 mm",
        "max_hotend_temp": "250 C",
        "max_bed_temp": "100 C",
        "connectivity": "microSD, USB",
        "firmware": "Marlin-based",
        "open_source": "Yes",
        "octoprint_url": "",
        "octoprint_api_key": "",
    },
    {
        "name": "Creality CR-30 (3DPrintMill)",
        "brand": "Creality",
        "model": "CR-30 (3DPrintMill)",
        "year": 2021,
        "technology": "FFF (Belt printer)",
        "bed_x": 200.0,
        "bed_y": 170.0,
        "bed_z": 170.0,
        "print_speed": "Up to 100 mm/s",
        "travel_speed": "150 mm/s",
        "supported_materials": "PLA, PETG, TPU",
        "nozzle_diameter": "0.4 mm",
        "filament_diameter": "1.75 mm",
        "max_hotend_temp": "240 C",
        "max_bed_temp": "100 C",
        "connectivity": "SD card, USB",
        "firmware": "Marlin (belt kinematics)",
        "open_source": "Yes",
        "octoprint_url": "",
        "octoprint_api_key": "",
    },
    {
        "name": "Creality Halot-One",
        "brand": "Creality",
        "model": "Halot-One",
        "year": 2021,
        "technology": "MSLA (resin)",
        "bed_x": 130.0,
        "bed_y": 82.0,
        "bed_z": 160.0,
        "print_speed": "30-50 mm/h",
        "travel_speed": "N/A",
        "supported_materials": "405 nm UV resins",
        "nozzle_diameter": "N/A",
        "filament_diameter": "N/A",
        "max_hotend_temp": "N/A",
        "max_bed_temp": "N/A",
        "connectivity": "USB, Wi-Fi",
        "firmware": "Proprietary",
        "open_source": "No",
        "octoprint_url": "",
        "octoprint_api_key": "",
    },
    {
        "name": "Creality Halot-Mage",
        "brand": "Creality",
        "model": "Halot-Mage",
        "year": 2023,
        "technology": "MSLA (resin)",
        "bed_x": 228.0,
        "bed_y": 128.0,
        "bed_z": 230.0,
        "print_speed": "Up to 70 mm/h",
        "travel_speed": "N/A",
        "supported_materials": "405 nm UV resin",
        "nozzle_diameter": "N/A",
        "filament_diameter": "N/A",
        "max_hotend_temp": "N/A",
        "max_bed_temp": "N/A",
        "connectivity": "USB, Wi-Fi",
        "firmware": "Proprietary",
        "open_source": "No",
        "octoprint_url": "",
        "octoprint_api_key": "",
    },
    {
        "name": "Anycubic Kobra Max",
        "brand": "Anycubic",
        "model": "Kobra Max",
        "year": 2022,
        "technology": "FFF (Cartesian, Bowden)",
        "bed_x": 400.0,
        "bed_y": 400.0,
        "bed_z": 450.0,
        "print_speed": "50-100 mm/s",
        "travel_speed": "150 mm/s",
        "supported_materials": "PLA, PETG, ABS, TPU",
        "nozzle_diameter": "0.4 mm",
        "filament_diameter": "1.75 mm",
        "max_hotend_temp": "260 C",
        "max_bed_temp": "90 C",
        "connectivity": "MicroSD, USB",
        "firmware": "Marlin 8-bit",
        "open_source": "Yes",
        "octoprint_url": "",
        "octoprint_api_key": "",
    },
    {
        "name": "Anycubic Photon Mono X",
        "brand": "Anycubic",
        "model": "Photon Mono X",
        "year": 2020,
        "technology": "MSLA (resin)",
        "bed_x": 192.0,
        "bed_y": 120.0,
        "bed_z": 245.0,
        "print_speed": "60 mm/h",
        "travel_speed": "N/A",
        "supported_materials": "405 nm UV resins",
        "nozzle_diameter": "N/A",
        "filament_diameter": "N/A",
        "max_hotend_temp": "N/A",
        "max_bed_temp": "N/A",
        "connectivity": "USB, Wi-Fi",
        "firmware": "ChiTu (closed)",
        "open_source": "No",
        "octoprint_url": "",
        "octoprint_api_key": "",
    },
    {
        "name": "Anycubic Photon M3 Plus",
        "brand": "Anycubic",
        "model": "Photon M3 Plus",
        "year": 2022,
        "technology": "MSLA (resin)",
        "bed_x": 197.0,
        "bed_y": 122.0,
        "bed_z": 245.0,
        "print_speed": "60 mm/h",
        "travel_speed": "N/A",
        "supported_materials": "405 nm UV resins",
        "nozzle_diameter": "N/A",
        "filament_diameter": "N/A",
        "max_hotend_temp": "N/A",
        "max_bed_temp": "N/A",
        "connectivity": "USB, Wi-Fi",
        "firmware": "Proprietary",
        "open_source": "No",
        "octoprint_url": "",
        "octoprint_api_key": "",
    },
    {
        "name": "FlashForge Adventurer 4",
        "brand": "FlashForge",
        "model": "Adventurer 4",
        "year": 2021,
        "technology": "FFF (Cartesian, enclosed)",
        "bed_x": 220.0,
        "bed_y": 200.0,
        "bed_z": 250.0,
        "print_speed": "Up to 150 mm/s",
        "travel_speed": "180 mm/s",
        "supported_materials": "PLA, ABS, PETG, PC, PLA-CF",
        "nozzle_diameter": "0.4 mm (quick-swap)",
        "filament_diameter": "1.75 mm",
        "max_hotend_temp": "265 C",
        "max_bed_temp": "110 C",
        "connectivity": "Wi-Fi, Ethernet, USB",
        "firmware": "Proprietary",
        "open_source": "No",
        "octoprint_url": "",
        "octoprint_api_key": "",
    },
    {
        "name": "FlashForge Creator 3 (IDEX)",
        "brand": "FlashForge",
        "model": "Creator 3 (IDEX)",
        "year": 2018,
        "technology": "FFF (IDEX)",
        "bed_x": 300.0,
        "bed_y": 250.0,
        "bed_z": 200.0,
        "print_speed": "30-100 mm/s",
        "travel_speed": "150 mm/s",
        "supported_materials": "PLA, ABS, PETG, Nylon, TPU, PC",
        "nozzle_diameter": "0.4 mm",
        "filament_diameter": "1.75 mm",
        "max_hotend_temp": "300 C",
        "max_bed_temp": "120 C",
        "connectivity": "Wi-Fi, Ethernet, USB",
        "firmware": "Proprietary",
        "open_source": "No",
        "octoprint_url": "",
        "octoprint_api_key": "",
    },
    {
        "name": "MakerBot Method",
        "brand": "MakerBot",
        "model": "Method",
        "year": 2019,
        "technology": "FFF (Cartesian, heated chamber)",
        "bed_x": 190.0,
        "bed_y": 190.0,
        "bed_z": 196.0,
        "print_speed": "Up to 150 mm/s",
        "travel_speed": "250 mm/s",
        "supported_materials": "MakerBot PLA, Tough PLA, PETG, PVA",
        "nozzle_diameter": "0.4 mm (dual)",
        "filament_diameter": "1.75 mm",
        "max_hotend_temp": "280 C",
        "max_bed_temp": "100 C",
        "connectivity": "Ethernet, Wi-Fi, USB",
        "firmware": "Proprietary",
        "open_source": "No",
        "octoprint_url": "",
        "octoprint_api_key": "",
    },
    {
        "name": "MakerBot Replicator+",
        "brand": "MakerBot",
        "model": "Replicator+",
        "year": 2016,
        "technology": "FFF (Cartesian)",
        "bed_x": 295.0,
        "bed_y": 195.0,
        "bed_z": 165.0,
        "print_speed": "80-100 mm/s",
        "travel_speed": "150 mm/s",
        "supported_materials": "MakerBot PLA, Tough PLA",
        "nozzle_diameter": "0.4 mm",
        "filament_diameter": "1.75 mm",
        "max_hotend_temp": "240 C",
        "max_bed_temp": "N/A",
        "connectivity": "Wi-Fi, USB, Ethernet",
        "firmware": "Proprietary",
        "open_source": "No",
        "octoprint_url": "",
        "octoprint_api_key": "",
    },
    {
        "name": "Raise3D Pro3",
        "brand": "Raise3D",
        "model": "Pro3",
        "year": 2021,
        "technology": "FFF (Cartesian, dual)",
        "bed_x": 300.0,
        "bed_y": 300.0,
        "bed_z": 300.0,
        "print_speed": "50-150 mm/s",
        "travel_speed": "150 mm/s",
        "supported_materials": "PLA, ABS, PETG, ASA, PC, TPU, Nylon",
        "nozzle_diameter": "0.4 mm",
        "filament_diameter": "1.75 mm",
        "max_hotend_temp": "300 C",
        "max_bed_temp": "120 C",
        "connectivity": "Wi-Fi, Ethernet, USB",
        "firmware": "Proprietary",
        "open_source": "Partially",
        "octoprint_url": "",
        "octoprint_api_key": "",
    },
    {
        "name": "Raise3D E2",
        "brand": "Raise3D",
        "model": "E2",
        "year": 2019,
        "technology": "FFF (IDEX)",
        "bed_x": 330.0,
        "bed_y": 240.0,
        "bed_z": 240.0,
        "print_speed": "30-150 mm/s",
        "travel_speed": "150 mm/s",
        "supported_materials": "PLA, ABS, PETG, ASA, TPU, Nylon, PC",
        "nozzle_diameter": "0.4 mm",
        "filament_diameter": "1.75 mm",
        "max_hotend_temp": "300 C",
        "max_bed_temp": "110 C",
        "connectivity": "Wi-Fi, Ethernet, USB",
        "firmware": "Proprietary",
        "open_source": "Partially",
        "octoprint_url": "",
        "octoprint_api_key": "",
    },
    {
        "name": "Ultimaker S5",
        "brand": "Ultimaker",
        "model": "S5",
        "year": 2018,
        "technology": "FFF (Cartesian, dual)",
        "bed_x": 330.0,
        "bed_y": 240.0,
        "bed_z": 300.0,
        "print_speed": "Up to 150 mm/s",
        "travel_speed": "300 mm/s",
        "supported_materials": "PLA, Tough PLA, ABS, CPE, Nylon, TPU, PVA",
        "nozzle_diameter": "0.25/0.4/0.8 mm print cores",
        "filament_diameter": "2.85 mm",
        "max_hotend_temp": "280 C",
        "max_bed_temp": "140 C",
        "connectivity": "Wi-Fi, LAN, USB",
        "firmware": "Ultimaker firmware",
        "open_source": "Partially",
        "octoprint_url": "",
        "octoprint_api_key": "",
    },
    {
        "name": "Ultimaker S3",
        "brand": "Ultimaker",
        "model": "S3",
        "year": 2019,
        "technology": "FFF (Cartesian, dual)",
        "bed_x": 230.0,
        "bed_y": 190.0,
        "bed_z": 200.0,
        "print_speed": "Up to 150 mm/s",
        "travel_speed": "300 mm/s",
        "supported_materials": "PLA, Tough PLA, ABS, CPE, Nylon, TPU, PVA",
        "nozzle_diameter": "0.25/0.4/0.8 mm print cores",
        "filament_diameter": "2.85 mm",
        "max_hotend_temp": "280 C",
        "max_bed_temp": "140 C",
        "connectivity": "Wi-Fi, LAN, USB",
        "firmware": "Ultimaker firmware",
        "open_source": "Partially",
        "octoprint_url": "",
        "octoprint_api_key": "",
    },
    {
        "name": "Ultimaker 3",
        "brand": "Ultimaker",
        "model": "Ultimaker 3",
        "year": 2016,
        "technology": "FFF (Cartesian, dual)",
        "bed_x": 215.0,
        "bed_y": 215.0,
        "bed_z": 200.0,
        "print_speed": "30-200 mm/s",
        "travel_speed": "300 mm/s",
        "supported_materials": "PLA, ABS, CPE, Nylon, PVA",
        "nozzle_diameter": "0.4 mm",
        "filament_diameter": "2.85 mm",
        "max_hotend_temp": "280 C",
        "max_bed_temp": "100 C",
        "connectivity": "Wi-Fi, Ethernet, USB",
        "firmware": "Marlin-based (Ultimaker)",
        "open_source": "Yes",
        "octoprint_url": "",
        "octoprint_api_key": "",
    },
    {
        "name": "BCN3D Epsilon W50",
        "brand": "BCN3D",
        "model": "Epsilon W50",
        "year": 2020,
        "technology": "FFF (IDEX, enclosed)",
        "bed_x": 420.0,
        "bed_y": 300.0,
        "bed_z": 400.0,
        "print_speed": "Up to 120 mm/s",
        "travel_speed": "250 mm/s",
        "supported_materials": "PLA, PETG, ABS, PP, PA, TPU",
        "nozzle_diameter": "0.4 mm (0.4/0.6/0.8 mm available)",
        "filament_diameter": "2.85 mm",
        "max_hotend_temp": "300 C",
        "max_bed_temp": "120 C",
        "connectivity": "Wi-Fi, Ethernet, SD card",
        "firmware": "BCN3D firmware",
        "open_source": "Yes",
        "octoprint_url": "",
        "octoprint_api_key": "",
    },
    {
        "name": "BCN3D Sigma D25",
        "brand": "BCN3D",
        "model": "Sigma D25",
        "year": 2020,
        "technology": "FFF (IDEX)",
        "bed_x": 420.0,
        "bed_y": 300.0,
        "bed_z": 200.0,
        "print_speed": "Up to 100 mm/s",
        "travel_speed": "250 mm/s",
        "supported_materials": "PLA, PETG, ABS, ASA, TPU, PVA",
        "nozzle_diameter": "0.4 mm",
        "filament_diameter": "2.85 mm",
        "max_hotend_temp": "300 C",
        "max_bed_temp": "80 C",
        "connectivity": "Wi-Fi, SD card, USB",
        "firmware": "Marlin-based",
        "open_source": "Yes",
        "octoprint_url": "",
        "octoprint_api_key": "",
    },
    {
        "name": "Sindoh 3DWOX 2X",
        "brand": "Sindoh",
        "model": "3DWOX 2X",
        "year": 2018,
        "technology": "FFF (Cartesian, dual)",
        "bed_x": 228.0,
        "bed_y": 200.0,
        "bed_z": 300.0,
        "print_speed": "60 mm/s typical",
        "travel_speed": "180 mm/s",
        "supported_materials": "PLA, ABS, Flexible, PVA",
        "nozzle_diameter": "0.4 mm (dual)",
        "filament_diameter": "1.75 mm",
        "max_hotend_temp": "240 C",
        "max_bed_temp": "110 C",
        "connectivity": "Wi-Fi, Ethernet, USB",
        "firmware": "Proprietary",
        "open_source": "No",
        "octoprint_url": "",
        "octoprint_api_key": "",
    },
    {
        "name": "Sindoh 3DWOX 1",
        "brand": "Sindoh",
        "model": "3DWOX 1",
        "year": 2018,
        "technology": "FFF (Cartesian, single)",
        "bed_x": 210.0,
        "bed_y": 200.0,
        "bed_z": 195.0,
        "print_speed": "50-100 mm/s",
        "travel_speed": "150 mm/s",
        "supported_materials": "PLA, ABS, PETG, Flexible",
        "nozzle_diameter": "0.4 mm",
        "filament_diameter": "1.75 mm",
        "max_hotend_temp": "240 C",
        "max_bed_temp": "100 C",
        "connectivity": "Wi-Fi, Ethernet, USB",
        "firmware": "Proprietary",
        "open_source": "No",
        "octoprint_url": "",
        "octoprint_api_key": "",
    },
    {
        "name": "LulzBot TAZ Workhorse",
        "brand": "LulzBot",
        "model": "TAZ Workhorse",
        "year": 2019,
        "technology": "FFF (Cartesian)",
        "bed_x": 280.0,
        "bed_y": 280.0,
        "bed_z": 285.0,
        "print_speed": "40-150 mm/s",
        "travel_speed": "200 mm/s",
        "supported_materials": "PLA, ABS, PETG, Nylon, PC, TPU",
        "nozzle_diameter": "0.5 mm",
        "filament_diameter": "2.85 mm",
        "max_hotend_temp": "290 C",
        "max_bed_temp": "120 C",
        "connectivity": "SD card, USB",
        "firmware": "Marlin",
        "open_source": "Yes",
        "octoprint_url": "",
        "octoprint_api_key": "",
    },
    {
        "name": "LulzBot TAZ Pro",
        "brand": "LulzBot",
        "model": "TAZ Pro",
        "year": 2019,
        "technology": "FFF (Cartesian, dual)",
        "bed_x": 280.0,
        "bed_y": 280.0,
        "bed_z": 285.0,
        "print_speed": "30-100 mm/s",
        "travel_speed": "200 mm/s",
        "supported_materials": "PLA, ABS, PETG, Nylon, TPU",
        "nozzle_diameter": "0.5 mm",
        "filament_diameter": "2.85 mm",
        "max_hotend_temp": "290 C",
        "max_bed_temp": "120 C",
        "connectivity": "SD card, USB",
        "firmware": "Marlin",
        "open_source": "Yes",
        "octoprint_url": "",
        "octoprint_api_key": "",
    },
    {
        "name": "LulzBot Mini 2",
        "brand": "LulzBot",
        "model": "Mini 2",
        "year": 2018,
        "technology": "FFF (Cartesian)",
        "bed_x": 160.0,
        "bed_y": 160.0,
        "bed_z": 180.0,
        "print_speed": "30-100 mm/s",
        "travel_speed": "180 mm/s",
        "supported_materials": "PLA, ABS, PETG, TPU, Nylon",
        "nozzle_diameter": "0.5 mm",
        "filament_diameter": "2.85 mm",
        "max_hotend_temp": "290 C",
        "max_bed_temp": "120 C",
        "connectivity": "USB",
        "firmware": "Marlin",
        "open_source": "Yes",
        "octoprint_url": "",
        "octoprint_api_key": "",
    },
    {
        "name": "Elegoo Neptune 3 Pro",
        "brand": "Elegoo",
        "model": "Neptune 3 Pro",
        "year": 2022,
        "technology": "FFF (Cartesian)",
        "bed_x": 225.0,
        "bed_y": 225.0,
        "bed_z": 280.0,
        "print_speed": "50-150 mm/s",
        "travel_speed": "180 mm/s",
        "supported_materials": "PLA, PETG, ABS",
        "nozzle_diameter": "0.4 mm",
        "filament_diameter": "1.75 mm",
        "max_hotend_temp": "260 C",
        "max_bed_temp": "100 C",
        "connectivity": "MicroSD, USB",
        "firmware": "Marlin 32-bit",
        "open_source": "Yes",
        "octoprint_url": "",
        "octoprint_api_key": "",
    },
    {
        "name": "Elegoo Saturn 2",
        "brand": "Elegoo",
        "model": "Saturn 2",
        "year": 2022,
        "technology": "MSLA (resin)",
        "bed_x": 219.0,
        "bed_y": 123.0,
        "bed_z": 250.0,
        "print_speed": "30-70 mm/h",
        "travel_speed": "N/A",
        "supported_materials": "405 nm UV resins",
        "nozzle_diameter": "N/A",
        "filament_diameter": "N/A",
        "max_hotend_temp": "N/A",
        "max_bed_temp": "N/A",
        "connectivity": "USB, Ethernet",
        "firmware": "ChiTu (closed)",
        "open_source": "No",
        "octoprint_url": "",
        "octoprint_api_key": "",
    },
    {
        "name": "Elegoo Mars 3",
        "brand": "Elegoo",
        "model": "Mars 3",
        "year": 2021,
        "technology": "MSLA (resin)",
        "bed_x": 143.0,
        "bed_y": 89.0,
        "bed_z": 175.0,
        "print_speed": "50 mm/h",
        "travel_speed": "N/A",
        "supported_materials": "405 nm UV resins",
        "nozzle_diameter": "N/A",
        "filament_diameter": "N/A",
        "max_hotend_temp": "N/A",
        "max_bed_temp": "N/A",
        "connectivity": "USB",
        "firmware": "ChiTu (closed)",
        "open_source": "No",
        "octoprint_url": "",
        "octoprint_api_key": "",
    },
    {
        "name": "Phrozen Sonic Mini 8K",
        "brand": "Phrozen",
        "model": "Sonic Mini 8K",
        "year": 2021,
        "technology": "MSLA (resin)",
        "bed_x": 165.0,
        "bed_y": 72.0,
        "bed_z": 180.0,
        "print_speed": "50 mm/h",
        "travel_speed": "N/A",
        "supported_materials": "405 nm UV resins",
        "nozzle_diameter": "N/A",
        "filament_diameter": "N/A",
        "max_hotend_temp": "N/A",
        "max_bed_temp": "N/A",
        "connectivity": "USB",
        "firmware": "Proprietary",
        "open_source": "No",
        "octoprint_url": "",
        "octoprint_api_key": "",
    },
    {
        "name": "Phrozen Sonic Mega 8K",
        "brand": "Phrozen",
        "model": "Sonic Mega 8K",
        "year": 2021,
        "technology": "MSLA (resin)",
        "bed_x": 330.0,
        "bed_y": 185.0,
        "bed_z": 400.0,
        "print_speed": "20-50 mm/h",
        "travel_speed": "N/A",
        "supported_materials": "405 nm UV resins",
        "nozzle_diameter": "N/A",
        "filament_diameter": "N/A",
        "max_hotend_temp": "N/A",
        "max_bed_temp": "N/A",
        "connectivity": "USB, Ethernet",
        "firmware": "Proprietary",
        "open_source": "No",
        "octoprint_url": "",
        "octoprint_api_key": "",
    },
    {
        "name": "Formlabs Form 3+",
        "brand": "Formlabs",
        "model": "Form 3+",
        "year": 2022,
        "technology": "SLA",
        "bed_x": 145.0,
        "bed_y": 145.0,
        "bed_z": 185.0,
        "print_speed": "25 mm/h",
        "travel_speed": "N/A",
        "supported_materials": "Formlabs resins",
        "nozzle_diameter": "N/A",
        "filament_diameter": "N/A",
        "max_hotend_temp": "N/A",
        "max_bed_temp": "N/A",
        "connectivity": "Wi-Fi, Ethernet, USB",
        "firmware": "Proprietary",
        "open_source": "No",
        "octoprint_url": "",
        "octoprint_api_key": "",
    },
    {
        "name": "Formlabs Form 3L",
        "brand": "Formlabs",
        "model": "Form 3L",
        "year": 2020,
        "technology": "SLA",
        "bed_x": 335.0,
        "bed_y": 200.0,
        "bed_z": 300.0,
        "print_speed": "25 mm/h",
        "travel_speed": "N/A",
        "supported_materials": "Formlabs resins",
        "nozzle_diameter": "N/A",
        "filament_diameter": "N/A",
        "max_hotend_temp": "N/A",
        "max_bed_temp": "N/A",
        "connectivity": "Wi-Fi, Ethernet, USB",
        "firmware": "Proprietary",
        "open_source": "No",
        "octoprint_url": "",
        "octoprint_api_key": "",
    },
    {
        "name": "Peopoly Phenom",
        "brand": "Peopoly",
        "model": "Phenom",
        "year": 2019,
        "technology": "MSLA (resin)",
        "bed_x": 276.0,
        "bed_y": 155.0,
        "bed_z": 400.0,
        "print_speed": "20 mm/h",
        "travel_speed": "N/A",
        "supported_materials": "405 nm UV resins",
        "nozzle_diameter": "N/A",
        "filament_diameter": "N/A",
        "max_hotend_temp": "N/A",
        "max_bed_temp": "N/A",
        "connectivity": "USB",
        "firmware": "ChiTu (closed)",
        "open_source": "No",
        "octoprint_url": "",
        "octoprint_api_key": "",
    },
]
