from __future__ import annotations

# source: profiles/Prusa/machine/Prusa MK4S HF0.4 nozzle.json
DATA = {'default_filament_profile': 'Prusa Generic PLA @MK4S HF0.4',
 'default_print_profile': '0.20mm SPEED @MK4S HF0.4',
 'from': 'system',
 'inherits': 'Prusa MK4S 0.4 nozzle',
 'instantiation': 'true',
 'machine_start_gcode': ['M17 ; enable steppers\n'
                         'M862.1 P[nozzle_diameter] ; nozzle check\n'
                         'M862.3 P "MK4S" ; printer model check\n'
                         'M862.5 P2 ; g-code level check\n'
                         'M862.6 P"Input shaper" ; FW feature check\n'
                         'M115 U6.1.3+7898\n'
                         '\n'
                         'M555 X{(min(print_bed_max[0], first_layer_print_min[0] + 32) - 32)} Y{(max(0, '
                         'first_layer_print_min[1]) - 4)} W{((min(print_bed_max[0], max(first_layer_print_min[0] + 32, '
                         'first_layer_print_max[0])))) - ((min(print_bed_max[0], first_layer_print_min[0] + 32) - '
                         '32))} H{((first_layer_print_max[1])) - ((max(0, first_layer_print_min[1]) - 4))}\n'
                         '\n'
                         'G90 ; use absolute coordinates\n'
                         'M83 ; extruder relative mode\n'
                         '\n'
                         'M140 S[first_layer_bed_temperature] ; set bed temp\n'
                         'M104 T0 S{((filament_notes[0]=~/.*HT_MBL10.*/) ? (first_layer_temperature[0] - 10) : '
                         '(filament_type[0] == "PC" or filament_type[0] == "PA") ? (first_layer_temperature[0] - 25) : '
                         '(filament_type[0] == "FLEX") ? 210 : (filament_type[0]=~/.*PET.*/) ? 175 : 170)} ; set '
                         'extruder temp for bed leveling\n'
                         'M109 T0 R{((filament_notes[0]=~/.*HT_MBL10.*/) ? (first_layer_temperature[0] - 10) : '
                         '(filament_type[0] == "PC" or filament_type[0] == "PA") ? (first_layer_temperature[0] - 25) : '
                         '(filament_type[0] == "FLEX") ? 210 : (filament_type[0]=~/.*PET.*/) ? 175 : 170)} ; wait for '
                         'temp\n'
                         '\n'
                         'M84 E ; turn off E motor\n'
                         '\n'
                         'G28 ; home all without mesh bed level\n'
                         '\n'
                         'G1 X42 Y-4 Z5 F4800\n'
                         '\n'
                         'M302 S160 ; lower cold extrusion limit to 160C\n'
                         '\n'
                         '{if filament_type[initial_tool]=="FLEX"}\n'
                         'G1 E-4 F2400 ; retraction\n'
                         '{else}\n'
                         'G1 E-2 F2400 ; retraction\n'
                         '{endif}\n'
                         '\n'
                         'M84 E ; turn off E motor\n'
                         '\n'
                         'G29 P9 X10 Y-4 W32 H4\n'
                         '\n'
                         '{if first_layer_bed_temperature[initial_tool]<=60}M106 S100{endif}\n'
                         '\n'
                         'G0 Z40 F10000\n'
                         '\n'
                         'M190 S[first_layer_bed_temperature] ; wait for bed temp\n'
                         '\n'
                         'M107\n'
                         '\n'
                         ';\n'
                         '; MBL\n'
                         ';\n'
                         'M84 E ; turn off E motor\n'
                         'G29 P1 ; invalidate mbl & probe print area\n'
                         'G29 P1 X0 Y0 W50 H20 C ; probe near purge place\n'
                         'G29 P3.2 ; interpolate mbl probes\n'
                         'G29 P3.13 ; extrapolate mbl outside probe area\n'
                         'G29 A ; activate mbl\n'
                         '\n'
                         '; prepare for purge\n'
                         'M104 S{first_layer_temperature[0]}\n'
                         'G0 X0 Y-4 Z15 F4800 ; move away and ready for the purge\n'
                         'M109 S{first_layer_temperature[0]}\n'
                         '\n'
                         'G92 E0\n'
                         'M569 S0 E ; set spreadcycle mode for extruder\n'
                         '\n'
                         ';\n'
                         '; Extrude purge line\n'
                         ';\n'
                         'G92 E0 ; reset extruder position\n'
                         'G1 E{(filament_type[0] == "FLEX" ? 4 : 2)} F2400 ; deretraction after the initial one before '
                         'nozzle cleaning\n'
                         'G0 E7 X15 Z0.2 F500 ; purge\n'
                         'G0 X25 E4 F500 ; purge\n'
                         'G0 X35 E4 F650 ; purge\n'
                         'G0 X45 E4 F800 ; purge\n'
                         'G0 X48 Z0.05 F8000 ; wipe, move close to the bed\n'
                         'G0 X51 Z0.2 F8000 ; wipe, move quickly away from the bed\n'
                         '\n'
                         'G92 E0\n'
                         'M221 S100 ; set flow to 100%'],
 'name': 'Prusa MK4S HF0.4 nozzle',
 'nozzle_diameter': ['0.4'],
 'printer_model': 'Prusa MK4S HF',
 'printer_notes': ['Don\'t remove the following keywords! These keywords are used in the "compatible printer" '
                   'condition of the print and filament profiles to link the particular print and filament profiles to '
                   'this printer profile.\n'
                   'PRINTER_MODEL_MK4S\n'
                   'PG\n'
                   'HF_NOZZLE\n'
                   'NO_TEMPLATES'],
 'printer_variant': '0.4',
 'type': 'machine'}
