from __future__ import annotations

# source: profiles/Lulzbot/machine/Lulzbot Taz Pro Dual 0.5 nozzle.json
DATA = {'default_filament_profile': ['Lulzbot 2.85mm PLA'],
 'default_print_profile': '0.25mm Standard @Lulzbot Taz Pro Dual',
 'extruders_count': '2',
 'from': 'system',
 'inherits': 'Lulzbot Taz Pro Common',
 'instantiation': 'true',
 'machine_end_gcode': 'M400; wait for moves to finish\n'
                      'M140 S0; start cooling bed\n'
                      'M107; fans off\n'
                      'G91 ; relative positioning\n'
                      'G1 E-1 F300 ; retract the filament a bit before lifting the nozzle, to release some of the '
                      'pressure\n'
                      'G1 Z25 E-1 X20 Y20 F2000; move Z up a bit and retract filament even more\n'
                      'M104 S{nozzle_temperature[0]} T0 ; T0 to print temp\n'
                      'M104 S{nozzle_temperature[1]} T1 ; T1 to print temp\n'
                      'G90 ; absolute positioning\n'
                      'G0 X285 Y-30 F3000; move to cooling position\n'
                      'G91 ; relative positioning\n'
                      'M117 Purging for next print;progress indicator message\n'
                      'T0\n'
                      'M109 S{nozzle_temperature[0]}; wait for temp\n'
                      'G92 E0; set extruder position to purge amount\n'
                      'G1 E15 F75; purge\n'
                      'M400; wait for purge\n'
                      'M104 S0 ; T0 hotend off\n'
                      'T1\n'
                      'M109 S{nozzle_temperature[1]}; wait for temp\n'
                      'G92 E0; set extruder position to purge amount\n'
                      'G1 E15 F75; purge\n'
                      'M400; wait for purge\n'
                      'M104 S0 ; T1 hotend off\n'
                      'T0\n'
                      'M117 Cooling, please wait;progress indicator message\n'
                      'M190 S0; cool off bed\n'
                      'G0 Y280 F3000 ; present finished print\n'
                      'M77; stop GLCD timer\n'
                      'M18 X Y E; turn off x y and e axis\n'
                      'G90 ; absolute positioning\n'
                      'M117 Print complete; progress indicator message',
 'machine_start_gcode': ';This G-Code has been translated from Cura startup from CuraLE 4.13.10 to EONSlicer by '
                        'Wrathernaut\n'
                        'T0\n'
                        'M82; absolute extrusion mode\n'
                        'M73 P0; clear GLCD progress bar\n'
                        'M75; start GLCD timer\n'
                        'M107; disable fans\n'
                        'G90; absolute positioning\n'
                        'M420 S0; disable previous leveling matrix\n'
                        'M140 S{bed_temperature_initial_layer[initial_tool]}; begin bed temping up (w)\n'
                        'M104 {if filament_type[initial_tool] == "PLA"}S180\n'
                        '{elsif filament_type[initial_tool] == "ABS"}S190\n'
                        '{elsif filament_type[initial_tool] == "ABS-GF"}S190\n'
                        '{elsif filament_type[initial_tool] == "ASA"}S190\n'
                        '{elsif filament_type[initial_tool] == "ASA-Aero"}S190\n'
                        '{elsif filament_type[initial_tool] == "BVOH"}S170\n'
                        '{elsif filament_type[initial_tool] == "EVA"}S170\n'
                        '{elsif filament_type[initial_tool] == "PA"}R220\n'
                        '{elsif filament_type[initial_tool] == "PA-CF"}R220\n'
                        '{elsif filament_type[initial_tool] == "PA-GF"}R220\n'
                        '{elsif filament_type[initial_tool] == "PA6-CF"}R220\n'
                        '{elsif filament_type[initial_tool] == "PA11-CF"}R220\n'
                        '{elsif filament_type[initial_tool] == "ASA-Aero"}S170\n'
                        '{elsif filament_type[initial_tool] == "PC"}R220\n'
                        '{elsif filament_type[initial_tool] == "PC-CF"}R220\n'
                        '{elsif filament_type[initial_tool] == "PCTG"}S180\n'
                        '{elsif filament_type[initial_tool] == "PE"}S190\n'
                        '{elsif filament_type[initial_tool] == "PE-CF"}S190\n'
                        '{elsif filament_type[initial_tool] == "PET-CF"}S190\n'
                        '{elsif filament_type[initial_tool] == "PETG"}S190\n'
                        '{elsif filament_type[initial_tool] == "PETG-CF10"}S190\n'
                        '{elsif filament_type[initial_tool] == "PHA"}S180\n'
                        '{elsif filament_type[initial_tool] == "PLA-AERO"}S180\n'
                        '{elsif filament_type[initial_tool] == "PLA-CF"}S180\n'
                        '{elsif filament_type[initial_tool] == "PP"}S180\n'
                        '{elsif filament_type[initial_tool] == "PP-CF"}S180\n'
                        '{elsif filament_type[initial_tool] == "PP-GF"}S180\n'
                        '{elsif filament_type[initial_tool] == "PPS"}S180\n'
                        '{elsif filament_type[initial_tool] == "PPS-CF"}S180\n'
                        '{elsif filament_type[initial_tool] == "PVA"}S180\n'
                        '{elsif filament_type[initial_tool] == "PVB"}S180\n'
                        '{elsif filament_type[initial_tool] == "SBS"}S180\n'
                        '{elsif filament_type[initial_tool] == "TPU"}S180\n'
                        '{elsif filament_type[initial_tool] == "FLEX"}S180\n'
                        '{elsif filament_type[initial_tool] == "PET"}S170\n'
                        '{elsif filament_type[initial_tool] == "HIPS"}S170\n'
                        '{elsif filament_type[initial_tool] == "NYLON"}R220\n'
                        '{else}S190; unknown filament type soften temp before homing Z\n'
                        '{endif}G28; home\n'
                        'G0 X50 Y25 Z10 F2000\n'
                        'M117 Heating...\n'
                        'M109 {if filament_type[0] == "PLA"}R180\n'
                        '{elsif filament_type[0] == "ABS"}R190\n'
                        '{elsif filament_type[0] == "ABS-GF"}R190\n'
                        '{elsif filament_type[0] == "ASA"}R190\n'
                        '{elsif filament_type[0] == "ASA-Aero"}R190\n'
                        '{elsif filament_type[0] == "BVOH"}R170\n'
                        '{elsif filament_type[0] == "EVA"}R170\n'
                        '{elsif filament_type[0] == "PA"}R220\n'
                        '{elsif filament_type[0] == "PA-CF"}R220\n'
                        '{elsif filament_type[0] == "PA-GF"}R220\n'
                        '{elsif filament_type[0] == "PA6-CF"}R220\n'
                        '{elsif filament_type[0] == "PA11-CF"}R220\n'
                        '{elsif filament_type[0] == "ASA-Aero"}R170\n'
                        '{elsif filament_type[0] == "PC"}R220\n'
                        '{elsif filament_type[0] == "PC-CF"}R220\n'
                        '{elsif filament_type[0] == "PCTG"}R180\n'
                        '{elsif filament_type[0] == "PE"}R190\n'
                        '{elsif filament_type[0] == "PE-CF"}R190\n'
                        '{elsif filament_type[0] == "PET-CF"}R190\n'
                        '{elsif filament_type[0] == "PETG"}R190\n'
                        '{elsif filament_type[0] == "PETG-CF10"}R190\n'
                        '{elsif filament_type[0] == "PHA"}R180\n'
                        '{elsif filament_type[0] == "PLA-AERO"}R180\n'
                        '{elsif filament_type[0] == "PLA-CF"}R180\n'
                        '{elsif filament_type[0] == "PP"}R180\n'
                        '{elsif filament_type[0] == "PP-CF"}R180\n'
                        '{elsif filament_type[0] == "PP-GF"}R180\n'
                        '{elsif filament_type[0] == "PPS"}R180\n'
                        '{elsif filament_type[0] == "PPS-CF"}R180\n'
                        '{elsif filament_type[0] == "PVA"}R180\n'
                        '{elsif filament_type[0] == "PVB"}R180\n'
                        '{elsif filament_type[0] == "SBS"}R180\n'
                        '{elsif filament_type[0] == "TPU"}R180\n'
                        '{elsif filament_type[0] == "FLEX"}R180\n'
                        '{elsif filament_type[0] == "PET"}R170\n'
                        '{elsif filament_type[0] == "HIPS"}R170\n'
                        '{elsif filament_type[0] == "NYLON"}R220\n'
                        '{else}R190; unknown filament type soften temp before homing Z{endif}\n'
                        'M82; set extruder to absolute mode\n'
                        'G92 E0; set extruder to zero\n'
                        'G1 E-7 F100; retract 7mm of filament on first extruder\n'
                        'M106; turn on fans to speed cooling\n'
                        'M117 Wiping...\n'
                        'M109 {if filament_type[0] == "PLA"}R180\n'
                        '{elsif filament_type[0] == "ABS"}R190\n'
                        '{elsif filament_type[0] == "ABS-GF"}R190\n'
                        '{elsif filament_type[0] == "ASA"}R190\n'
                        '{elsif filament_type[0] == "ASA-Aero"}R190\n'
                        '{elsif filament_type[0] == "BVOH"}R170\n'
                        '{elsif filament_type[0] == "EVA"}R170\n'
                        '{elsif filament_type[0] == "PA"}R220\n'
                        '{elsif filament_type[0] == "PA-CF"}R220\n'
                        '{elsif filament_type[0] == "PA-GF"}R220\n'
                        '{elsif filament_type[0] == "PA6-CF"}R220\n'
                        '{elsif filament_type[0] == "PA11-CF"}R220\n'
                        '{elsif filament_type[0] == "ASA-Aero"}R170\n'
                        '{elsif filament_type[0] == "PC"}R220\n'
                        '{elsif filament_type[0] == "PC-CF"}R220\n'
                        '{elsif filament_type[0] == "PCTG"}R190\n'
                        '{elsif filament_type[0] == "PE"}R190\n'
                        '{elsif filament_type[0] == "PE-CF"}R190\n'
                        '{elsif filament_type[0] == "PET-CF"}R190\n'
                        '{elsif filament_type[0] == "PETG"}R190\n'
                        '{elsif filament_type[0] == "PETG-CF10"}R190\n'
                        '{elsif filament_type[0] == "PHA"}R180\n'
                        '{elsif filament_type[0] == "PLA-AERO"}R180\n'
                        '{elsif filament_type[0] == "PLA-CF"}R180\n'
                        '{elsif filament_type[0] == "PP"}R180\n'
                        '{elsif filament_type[0] == "PP-CF"}R180\n'
                        '{elsif filament_type[0] == "PP-GF"}R180\n'
                        '{elsif filament_type[0] == "PPS"}R180\n'
                        '{elsif filament_type[0] == "PPS-CF"}R180\n'
                        '{elsif filament_type[0] == "PVA"}R180\n'
                        '{elsif filament_type[0] == "PVB"}R180\n'
                        '{elsif filament_type[0] == "SBS"}R180\n'
                        '{elsif filament_type[0] == "TPU"}R180\n'
                        '{elsif filament_type[0] == "FLEX"}R180\n'
                        '{elsif filament_type[0] == "PET"}R170\n'
                        '{elsif filament_type[0] == "HIPS"}R180\n'
                        '{elsif filament_type[0] == "NYLON"}R220\n'
                        '{else}R170; unknown filament type wipe temp{endif}\n'
                        'M109 {if filament_type[0] == "PLA"}R160\n'
                        '{elsif filament_type[0] == "ABS"}R170\n'
                        '{elsif filament_type[0] == "ABS-GF"}R170\n'
                        '{elsif filament_type[0] == "ASA"}R170\n'
                        '{elsif filament_type[0] == "ASA-Aero"}R170\n'
                        '{elsif filament_type[0] == "BVOH"}R170\n'
                        '{elsif filament_type[0] == "EVA"}R170\n'
                        '{elsif filament_type[0] == "PA"}R200\n'
                        '{elsif filament_type[0] == "PA-CF"}R200\n'
                        '{elsif filament_type[0] == "PA-GF"}R170\n'
                        '{elsif filament_type[0] == "PA6-CF"}R170\n'
                        '{elsif filament_type[0] == "PA11-CF"}R200\n'
                        '{elsif filament_type[0] == "ASA-Aero"}R170\n'
                        '{elsif filament_type[0] == "PC"}R200\n'
                        '{elsif filament_type[0] == "PC-CF"}R200\n'
                        '{elsif filament_type[0] == "PCTG"}R180\n'
                        '{elsif filament_type[0] == "PE"}R180\n'
                        '{elsif filament_type[0] == "PE-CF"}R180\n'
                        '{elsif filament_type[0] == "PET-CF"}R170\n'
                        '{elsif filament_type[0] == "PETG"}R170\n'
                        '{elsif filament_type[0] == "PETG-CF10"}R170\n'
                        '{elsif filament_type[0] == "PHA"}R180\n'
                        '{elsif filament_type[0] == "PLA-AERO"}R180\n'
                        '{elsif filament_type[0] == "PLA-CF"}R180\n'
                        '{elsif filament_type[0] == "PP"}R180\n'
                        '{elsif filament_type[0] == "PP-CF"}R180\n'
                        '{elsif filament_type[0] == "PP-GF"}R180\n'
                        '{elsif filament_type[0] == "PPS"}R180\n'
                        '{elsif filament_type[0] == "PPS-CF"}R180\n'
                        '{elsif filament_type[0] == "PVA"}R160\n'
                        '{elsif filament_type[0] == "PVB"}R160\n'
                        '{elsif filament_type[0] == "SBS"}R180\n'
                        '{elsif filament_type[0] == "TPU"}R160\n'
                        '{elsif filament_type[0] == "FLEX"}R160\n'
                        '{elsif filament_type[0] == "PET"}R170\n'
                        '{elsif filament_type[0] == "HIPS"}R160\n'
                        '{elsif filament_type[0] == "NYLON"}R200\n'
                        '{else}R170; unknown filament type probe temp{endif}; cool to probe temp\n'
                        'G12; wipe sequence\n'
                        'M107; turn off fan\n'
                        'G29; probe sequence (for auto-leveling)\n'
                        'M420 S1; enable leveling matrix\n'
                        "T{initial_tool}; ensure we're using the first extruder\n"
                        'M104 S{first_layer_temperature[initial_tool]}; set extruder temp\n'
                        'G0 X5 Y15 Z10 F5000; move to start location\n'
                        'M400; clear buffer\n'
                        'M117 Heating...\n'
                        'M109 R{first_layer_temperature[initial_tool]}; set extruder temp and waitnM190 '
                        'R{bed_temperature_initial_layer[initial_tool]}; get bed temping up during first layer\n'
                        'G1 Z2 E0 F75; raise head and 0 extruder\n'
                        'M82; set to absolute mode\n'
                        'M400; clear buffer\n'
                        'M300 T; play sound at start of first layer\n'
                        'M117 Printing ...\n'
                        ';Start G-Code End',
 'name': 'Lulzbot Taz Pro Dual 0.5 nozzle',
 'nozzle_diameter': ['0.5', '0.5'],
 'printer_model': 'Lulzbot Taz Pro Dual',
 'printer_settings_id': 'LulzbotPro-Dual',
 'setting_id': 'LZPD001',
 'single_extruder_multi_material': '0',
 'type': 'machine'}
