from __future__ import annotations

# source: profiles/Lulzbot/machine/Lulzbot Taz Pro Common.json
DATA = {'auxiliary_fan': '0',
 'before_layer_change_gcode': ';BEFORE_LAYER_CHANGE\n;[layer_z]\nG92 E0; reset relative extrusion',
 'change_filament_gcode': '',
 'cooling_tube_length': '0',
 'cooling_tube_retraction': '0',
 'deretraction_speed': ['10'],
 'emit_machine_limits_to_gcode': '1',
 'extra_loading_move': '0',
 'from': 'system',
 'inherits': 'fdm_machine_common',
 'instantiation': 'false',
 'layer_change_gcode': ';AFTER_LAYER_CHANGE\n'
                       ';LAYER:{layer_num}\n'
                       ';[layer_z]\n'
                       'M117 Layer: {layer_num +1} / [total_layer_count]',
 'machine_load_filament_time': '1',
 'machine_max_acceleration_extruding': ['1000', '1000'],
 'machine_max_acceleration_retracting': ['3000', '3000'],
 'machine_max_acceleration_travel': ['500', '500'],
 'machine_max_acceleration_x': ['500', '500'],
 'machine_max_acceleration_y': ['500', '500'],
 'machine_max_acceleration_z': ['100', '100'],
 'machine_max_jerk_e': ['10', '10'],
 'machine_max_jerk_x': ['8', '8'],
 'machine_max_jerk_y': ['8', '8'],
 'machine_max_jerk_z': ['0.4', '0.4'],
 'machine_max_speed_e': ['60', '60'],
 'machine_max_speed_x': ['300', '300'],
 'machine_max_speed_y': ['300', '300'],
 'machine_max_speed_z': ['25', '25'],
 'machine_pause_gcode': 'M600 B10',
 'machine_tool_change_time': '3',
 'machine_unload_filament_time': '1',
 'max_layer_height': ['0.38', '0.38'],
 'min_layer_height': ['0.08', '0.08'],
 'name': 'Lulzbot Taz Pro Common',
 'nozzle_type': 'undefine',
 'parking_pos_retraction': '0',
 'printable_area': ['0x0', '280x0', '280x280', '0x280'],
 'printable_height': '280',
 'printer_model': 'Lulzbot Taz Pro Common',
 'printer_settings_id': 'LulzbotPro-Common',
 'printer_structure': 'i3',
 'retract_before_wipe': ['70%', '70%'],
 'retract_length_toolchange': ['1', '1'],
 'retraction_length': ['1', '1'],
 'retraction_minimum_travel': ['1', '1'],
 'retraction_speed': ['10'],
 'scan_first_layer': '0',
 'setting_id': 'LZPC001',
 'support_air_filtration': '0',
 'support_chamber_temp_control': '0',
 'support_multi_bed_types': '1',
 'type': 'machine'}
