from __future__ import annotations

# source: profiles/Lulzbot/machine/Lulzbot Taz Pro S 0.5 nozzle.json
DATA = {'default_filament_profile': ['Generic PLA @System'],
 'default_print_profile': '0.25mm Standard @Lulzbot Taz Pro S',
 'extruders_count': '1',
 'from': 'system',
 'inherits': 'Lulzbot Taz Pro Common',
 'instantiation': 'true',
 'machine_end_gcode': 'M400; wait for moves to finish\n'
                      'M140 S0; start cooling bed\n'
                      'M107; fans off\n'
                      'G91 ; relative positioning\n'
                      'G1 E-1 F300 ; retract the filament a bit before lifting the nozzle, to release some of the '
                      'pressure\n'
                      'G1 Z25 E-1 X20 Y20 F2000; move Z up a bit and retract filament even more\n'
                      'M104 S{nozzle_temperature[0]} T0 ; T0 to print temp\n'
                      'M104 S{nozzle_temperature[1]} T1 ; T1 to print temp\n'
                      'G90 ; absolute positioning\n'
                      'G0 X285 Y-30 F3000; move to cooling position\n'
                      'G91 ; relative positioning\n'
                      'M117 Purging for next print;progress indicator message\n'
                      'T0\n'
                      'M109 S{nozzle_temperature[0]}; wait for temp\n'
                      'G92 E0; set extruder position to purge amount\n'
                      'G1 E15 F75; purge\n'
                      'M400; wait for purge\n'
                      'M104 S0 ; T0 hotend off\n'
                      'T1\n'
                      'M109 S{nozzle_temperature[1]}; wait for temp\n'
                      'G92 E0; set extruder position to purge amount\n'
                      'G1 E15 F75; purge\n'
                      'M400; wait for purge\n'
                      'M104 S0 ; T1 hotend off\n'
                      'T0\n'
                      'M117 Cooling, please wait;progress indicator message\n'
                      'M190 S0; cool off bed\n'
                      'G0 Y280 F3000 ; present finished print\n'
                      'M77; stop GLCD timer\n'
                      'M18 X Y E; turn off x y and e axis\n'
                      'G90 ; absolute positioning\n'
                      'M117 Print complete; progress indicator message',
 'machine_start_gcode': ';This G-Code has been translated from Cura startup from CuraLE 4.13.10 to EONSlicer by '
                        'Wrathernaut\n'
                        'G4 S1 ; delay for 1 seconds to display file name\n'
                        'M140 S{bed_temperature_initial_layer[initial_tool]}; begin bed temping up (w)\n'
                        'M104 {if filament_type[initial_tool] == "PLA"}S180\n'
                        '{elsif filament_type[initial_tool] == "ABS"}S190\n'
                        '{elsif filament_type[initial_tool] == "ABS-GF"}S190\n'
                        '{elsif filament_type[initial_tool] == "ASA"}S190\n'
                        '{elsif filament_type[initial_tool] == "ASA-Aero"}S190\n'
                        '{elsif filament_type[initial_tool] == "BVOH"}S170\n'
                        '{elsif filament_type[initial_tool] == "EVA"}S170\n'
                        '{elsif filament_type[initial_tool] == "PA"}R220\n'
                        '{elsif filament_type[initial_tool] == "PA-CF"}R220\n'
                        '{elsif filament_type[initial_tool] == "PA-GF"}R220\n'
                        '{elsif filament_type[initial_tool] == "PA6-CF"}R220\n'
                        '{elsif filament_type[initial_tool] == "PA11-CF"}R220\n'
                        '{elsif filament_type[initial_tool] == "ASA-Aero"}S170\n'
                        '{elsif filament_type[initial_tool] == "PC"}R220\n'
                        '{elsif filament_type[initial_tool] == "PC-CF"}R220\n'
                        '{elsif filament_type[initial_tool] == "PCTG"}S180\n'
                        '{elsif filament_type[initial_tool] == "PE"}S190\n'
                        '{elsif filament_type[initial_tool] == "PE-CF"}S190\n'
                        '{elsif filament_type[initial_tool] == "PET-CF"}S190\n'
                        '{elsif filament_type[initial_tool] == "PETG"}S190\n'
                        '{elsif filament_type[initial_tool] == "PETG-CF10"}S190\n'
                        '{elsif filament_type[initial_tool] == "PHA"}S180\n'
                        '{elsif filament_type[initial_tool] == "PLA-AERO"}S180\n'
                        '{elsif filament_type[initial_tool] == "PLA-CF"}S180\n'
                        '{elsif filament_type[initial_tool] == "PP"}S180\n'
                        '{elsif filament_type[initial_tool] == "PP-CF"}S180\n'
                        '{elsif filament_type[initial_tool] == "PP-GF"}S180\n'
                        '{elsif filament_type[initial_tool] == "PPS"}S180\n'
                        '{elsif filament_type[initial_tool] == "PPS-CF"}S180\n'
                        '{elsif filament_type[initial_tool] == "PVA"}S180\n'
                        '{elsif filament_type[initial_tool] == "PVB"}S180\n'
                        '{elsif filament_type[initial_tool] == "SBS"}S180\n'
                        '{elsif filament_type[initial_tool] == "TPU"}S180\n'
                        '{elsif filament_type[initial_tool] == "FLEX"}S180\n'
                        '{elsif filament_type[initial_tool] == "PET"}S170\n'
                        '{elsif filament_type[initial_tool] == "HIPS"}S170\n'
                        '{elsif filament_type[initial_tool] == "NYLON"}R220\n'
                        '{else}S190; unknown filament type soften temp before homing Z\n'
                        '{endif}G28O; home all axes (if needed)\n'
                        'M73 P0 ; clear LCD progress bar\n'
                        'M75; start LCD print timer\n'
                        'M107;disable fans\n'
                        'M420 S0; disable leveling matrix\n'
                        '{if enable_pressure_advance == 1}M900 K{pressure_advance[0]}; set pressure advance\n'
                        '{endif}G90; absolute positioning\n'
                        'M82; set extruder to absolute mode\n'
                        'G92 E0; set extruder position to 0\n'
                        'G0 X145 Y187 Z156 F3000; move away from endstops\n'
                        'M117 Heating Nozzle...; progress indicator message on LCD\n'
                        'M109 {if filament_type[0] == "PLA"}R180\n'
                        '{elsif filament_type[0] == "ABS"}R190\n'
                        '{elsif filament_type[0] == "ABS-GF"}R190\n'
                        '{elsif filament_type[0] == "ASA"}R190\n'
                        '{elsif filament_type[0] == "ASA-Aero"}R190\n'
                        '{elsif filament_type[0] == "BVOH"}R170\n'
                        '{elsif filament_type[0] == "EVA"}R170\n'
                        '{elsif filament_type[0] == "PA"}R220\n'
                        '{elsif filament_type[0] == "PA-CF"}R220\n'
                        '{elsif filament_type[0] == "PA-GF"}R220\n'
                        '{elsif filament_type[0] == "PA6-CF"}R220\n'
                        '{elsif filament_type[0] == "PA11-CF"}R220\n'
                        '{elsif filament_type[0] == "ASA-Aero"}R170\n'
                        '{elsif filament_type[0] == "PC"}R220\n'
                        '{elsif filament_type[0] == "PC-CF"}R220\n'
                        '{elsif filament_type[0] == "PCTG"}R180\n'
                        '{elsif filament_type[0] == "PE"}R190\n'
                        '{elsif filament_type[0] == "PE-CF"}R190\n'
                        '{elsif filament_type[0] == "PET-CF"}R190\n'
                        '{elsif filament_type[0] == "PETG"}R190\n'
                        '{elsif filament_type[0] == "PETG-CF10"}R190\n'
                        '{elsif filament_type[0] == "PHA"}R180\n'
                        '{elsif filament_type[0] == "PLA-AERO"}R180\n'
                        '{elsif filament_type[0] == "PLA-CF"}R180\n'
                        '{elsif filament_type[0] == "PP"}R180\n'
                        '{elsif filament_type[0] == "PP-CF"}R180\n'
                        '{elsif filament_type[0] == "PP-GF"}R180\n'
                        '{elsif filament_type[0] == "PPS"}R180\n'
                        '{elsif filament_type[0] == "PPS-CF"}R180\n'
                        '{elsif filament_type[0] == "PVA"}R180\n'
                        '{elsif filament_type[0] == "PVB"}R180\n'
                        '{elsif filament_type[0] == "SBS"}R180\n'
                        '{elsif filament_type[0] == "TPU"}R180\n'
                        '{elsif filament_type[0] == "FLEX"}R180\n'
                        '{elsif filament_type[0] == "PET"}R170\n'
                        '{elsif filament_type[0] == "HIPS"}R170\n'
                        '{elsif filament_type[0] == "NYLON"}R220\n'
                        '{else}R190; unknown filament type soften temp before homing Z{endif};soften filament before '
                        'retraction\n'
                        'G1 E-7 F75; retract filament\n'
                        'G92 E-12 ; set extruder position to -12 to account for 5mm retract at end of previous print\n'
                        'M109 {if filament_type[0] == "PLA"}R180\n'
                        '{elsif filament_type[0] == "ABS"}R190\n'
                        '{elsif filament_type[0] == "ABS-GF"}R190\n'
                        '{elsif filament_type[0] == "ASA"}R190\n'
                        '{elsif filament_type[0] == "ASA-Aero"}R190\n'
                        '{elsif filament_type[0] == "BVOH"}R170\n'
                        '{elsif filament_type[0] == "EVA"}R170\n'
                        '{elsif filament_type[0] == "PA"}R220\n'
                        '{elsif filament_type[0] == "PA-CF"}R220\n'
                        '{elsif filament_type[0] == "PA-GF"}R220\n'
                        '{elsif filament_type[0] == "PA6-CF"}R220\n'
                        '{elsif filament_type[0] == "PA11-CF"}R220\n'
                        '{elsif filament_type[0] == "ASA-Aero"}R170\n'
                        '{elsif filament_type[0] == "PC"}R220\n'
                        '{elsif filament_type[0] == "PC-CF"}R220\n'
                        '{elsif filament_type[0] == "PCTG"}R190\n'
                        '{elsif filament_type[0] == "PE"}R190\n'
                        '{elsif filament_type[0] == "PE-CF"}R190\n'
                        '{elsif filament_type[0] == "PET-CF"}R190\n'
                        '{elsif filament_type[0] == "PETG"}R190\n'
                        '{elsif filament_type[0] == "PETG-CF10"}R190\n'
                        '{elsif filament_type[0] == "PHA"}R180\n'
                        '{elsif filament_type[0] == "PLA-AERO"}R180\n'
                        '{elsif filament_type[0] == "PLA-CF"}R180\n'
                        '{elsif filament_type[0] == "PP"}R180\n'
                        '{elsif filament_type[0] == "PP-CF"}R180\n'
                        '{elsif filament_type[0] == "PP-GF"}R180\n'
                        '{elsif filament_type[0] == "PPS"}R180\n'
                        '{elsif filament_type[0] == "PPS-CF"}R180\n'
                        '{elsif filament_type[0] == "PVA"}R180\n'
                        '{elsif filament_type[0] == "PVB"}R180\n'
                        '{elsif filament_type[0] == "SBS"}R180\n'
                        '{elsif filament_type[0] == "TPU"}R180\n'
                        '{elsif filament_type[0] == "FLEX"}R180\n'
                        '{elsif filament_type[0] == "PET"}R170\n'
                        '{elsif filament_type[0] == "HIPS"}R180\n'
                        '{elsif filament_type[0] == "NYLON"}R220\n'
                        '{else}R170; unknown filament type wipe temp{endif};wait for extruder to reach wiping temp\n'
                        'M104 {if filament_type[0] == "PLA"}R160\n'
                        '{elsif filament_type[0] == "ABS"}R170\n'
                        '{elsif filament_type[0] == "ABS-GF"}R170\n'
                        '{elsif filament_type[0] == "ASA"}R170\n'
                        '{elsif filament_type[0] == "ASA-Aero"}R170\n'
                        '{elsif filament_type[0] == "BVOH"}R170\n'
                        '{elsif filament_type[0] == "EVA"}R170\n'
                        '{elsif filament_type[0] == "PA"}R200\n'
                        '{elsif filament_type[0] == "PA-CF"}R200\n'
                        '{elsif filament_type[0] == "PA-GF"}R170\n'
                        '{elsif filament_type[0] == "PA6-CF"}R170\n'
                        '{elsif filament_type[0] == "PA11-CF"}R200\n'
                        '{elsif filament_type[0] == "ASA-Aero"}R170\n'
                        '{elsif filament_type[0] == "PC"}R200\n'
                        '{elsif filament_type[0] == "PC-CF"}R200\n'
                        '{elsif filament_type[0] == "PCTG"}R180\n'
                        '{elsif filament_type[0] == "PE"}R180\n'
                        '{elsif filament_type[0] == "PE-CF"}R180\n'
                        '{elsif filament_type[0] == "PET-CF"}R170\n'
                        '{elsif filament_type[0] == "PETG"}R170\n'
                        '{elsif filament_type[0] == "PETG-CF10"}R170\n'
                        '{elsif filament_type[0] == "PHA"}R180\n'
                        '{elsif filament_type[0] == "PLA-AERO"}R180\n'
                        '{elsif filament_type[0] == "PLA-CF"}R180\n'
                        '{elsif filament_type[0] == "PP"}R180\n'
                        '{elsif filament_type[0] == "PP-CF"}R180\n'
                        '{elsif filament_type[0] == "PP-GF"}R180\n'
                        '{elsif filament_type[0] == "PPS"}R180\n'
                        '{elsif filament_type[0] == "PPS-CF"}R180\n'
                        '{elsif filament_type[0] == "PVA"}R160\n'
                        '{elsif filament_type[0] == "PVB"}R160\n'
                        '{elsif filament_type[0] == "SBS"}R180\n'
                        '{elsif filament_type[0] == "TPU"}R160\n'
                        '{elsif filament_type[0] == "FLEX"}R160\n'
                        '{elsif filament_type[0] == "PET"}R170\n'
                        '{elsif filament_type[0] == "HIPS"}R160\n'
                        '{elsif filament_type[0] == "NYLON"}R200\n'
                        '{else}R170; unknown filament type probe temp{endif}; start cooling to probe temp during wipe\n'
                        'M106 S255 ; turn fan on to help drop temp\n'
                        '; Use M206 below to adjust nozzle wipe position (Replace "z_offset" to adjust Z value)\n'
                        '; X ~ (+)left/(-)right, Y ~ (+)front/(-)back, Z ~ (+)down/(-)up\n'
                        'M206 X0 Y0 Z[z_offset] ; restoring offsets and adjusting offset if AST285 is enabled\n'
                        'M117 Wiping Nozzle...;progress indicator on LCD\n'
                        'G12; wiping sequence\n'
                        'M206 X0 Y0 Z0 ; reseting stock nozzle position # # #  CAUTION:  changing this line can affect '
                        'print quality # # #\n'
                        'M107; turn off part cooling fan\n'
                        'M104 {if filament_type[0] == "PLA"}R160\n'
                        '{elsif filament_type[0] == "ABS"}R170\n'
                        '{elsif filament_type[0] == "ABS-GF"}R170\n'
                        '{elsif filament_type[0] == "ASA"}R170\n'
                        '{elsif filament_type[0] == "ASA-Aero"}R170\n'
                        '{elsif filament_type[0] == "BVOH"}R170\n'
                        '{elsif filament_type[0] == "EVA"}R170\n'
                        '{elsif filament_type[0] == "PA"}R200\n'
                        '{elsif filament_type[0] == "PA-CF"}R200\n'
                        '{elsif filament_type[0] == "PA-GF"}R170\n'
                        '{elsif filament_type[0] == "PA6-CF"}R170\n'
                        '{elsif filament_type[0] == "PA11-CF"}R200\n'
                        '{elsif filament_type[0] == "ASA-Aero"}R170\n'
                        '{elsif filament_type[0] == "PC"}R200\n'
                        '{elsif filament_type[0] == "PC-CF"}R200\n'
                        '{elsif filament_type[0] == "PCTG"}R180\n'
                        '{elsif filament_type[0] == "PE"}R180\n'
                        '{elsif filament_type[0] == "PE-CF"}R180\n'
                        '{elsif filament_type[0] == "PET-CF"}R170\n'
                        '{elsif filament_type[0] == "PETG"}R170\n'
                        '{elsif filament_type[0] == "PETG-CF10"}R170\n'
                        '{elsif filament_type[0] == "PHA"}R180\n'
                        '{elsif filament_type[0] == "PLA-AERO"}R180\n'
                        '{elsif filament_type[0] == "PLA-CF"}R180\n'
                        '{elsif filament_type[0] == "PP"}R180\n'
                        '{elsif filament_type[0] == "PP-CF"}R180\n'
                        '{elsif filament_type[0] == "PP-GF"}R180\n'
                        '{elsif filament_type[0] == "PPS"}R180\n'
                        '{elsif filament_type[0] == "PPS-CF"}R180\n'
                        '{elsif filament_type[0] == "PVA"}R160\n'
                        '{elsif filament_type[0] == "PVB"}R160\n'
                        '{elsif filament_type[0] == "SBS"}R180\n'
                        '{elsif filament_type[0] == "TPU"}R160\n'
                        '{elsif filament_type[0] == "FLEX"}R160\n'
                        '{elsif filament_type[0] == "PET"}R170\n'
                        '{elsif filament_type[0] == "HIPS"}R160\n'
                        '{elsif filament_type[0] == "NYLON"}R200\n'
                        '{else}R170; unknown filament type probe temp{endif}; set probe temp\n'
                        'M117 Leveling Print Bed...; progress indicator message on LCD\n'
                        'G29; start auto-leveling sequence\n'
                        'M420 S1; enable leveling matrix\n'
                        'G1 X5 Y15 Z10 F8000; move up off last probe point\n'
                        'G4 S1; pause\n'
                        'M400 wait for moves to finish\n'
                        'M117 Final Heating... Please Wait.\n'
                        'M109 S{first_layer_temperature[initial_tool]}; set extruder temp and wait\n'
                        'M190 R{bed_temperature_initial_layer[initial_tool]}; get bed temping up during first layer\n'
                        'G1 Z2 E0 F75; prime tiny bit of filament into the nozzle\n'
                        'M300 T; play sound at start of first layer\n'
                        'M117 Printing ...\n'
                        ';Start G-Code End',
 'name': 'Lulzbot Taz Pro S 0.5 nozzle',
 'nozzle_diameter': ['0.5'],
 'printer_model': 'Lulzbot Taz Pro S',
 'printer_settings_id': 'LulzbotPro-S',
 'setting_id': 'LZPS001',
 'single_extruder_multi_material': '1',
 'type': 'machine'}
