from __future__ import annotations

# source: profiles/OrcaFilamentLibrary/filament/Bambu/Bambu PETG HF @base.json
DATA = {'cool_plate_temp': ['0'],
 'cool_plate_temp_initial_layer': ['0'],
 'eng_plate_temp': ['70'],
 'eng_plate_temp_initial_layer': ['70'],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['40'],
 'fan_min_speed': ['10'],
 'filament_cost': ['24.99'],
 'filament_density': ['1.28'],
 'filament_flow_ratio': ['0.95'],
 'filament_id': 'OGFG02',
 'filament_max_volumetric_speed': ['12'],
 'filament_vendor': ['Bambu Lab'],
 'from': 'system',
 'hot_plate_temp': ['70'],
 'hot_plate_temp_initial_layer': ['70'],
 'inherits': 'fdm_filament_pet',
 'instantiation': 'false',
 'name': 'Bambu PETG HF @base',
 'nozzle_temperature': ['245'],
 'nozzle_temperature_initial_layer': ['230'],
 'nozzle_temperature_range_high': ['270'],
 'nozzle_temperature_range_low': ['230'],
 'overhang_fan_speed': ['90'],
 'overhang_fan_threshold': ['10%'],
 'slow_down_layer_time': ['12'],
 'textured_plate_temp': ['70'],
 'textured_plate_temp_initial_layer': ['70'],
 'type': 'filament'}
