from __future__ import annotations

# source: profiles/OrcaFilamentLibrary/filament/Bambu/Bambu ASA-CF @base.json
DATA = {'eng_plate_temp': ['100'],
 'eng_plate_temp_initial_layer': ['100'],
 'fan_max_speed': ['25'],
 'filament_cost': ['36.99'],
 'filament_density': ['1.02'],
 'filament_flow_ratio': ['0.9'],
 'filament_id': 'OGFB51',
 'filament_max_volumetric_speed': ['12'],
 'filament_type': ['ASA-CF'],
 'filament_vendor': ['Bambu Lab'],
 'from': 'system',
 'hot_plate_temp': ['100'],
 'hot_plate_temp_initial_layer': ['100'],
 'inherits': 'fdm_filament_asa',
 'instantiation': 'false',
 'name': 'Bambu ASA-CF @base',
 'nozzle_temperature': ['275'],
 'nozzle_temperature_initial_layer': ['275'],
 'nozzle_temperature_range_low': ['250'],
 'slow_down_layer_time': ['12'],
 'temperature_vitrification': ['108'],
 'textured_plate_temp': ['100'],
 'textured_plate_temp_initial_layer': ['100'],
 'type': 'filament'}
