from __future__ import annotations

# source: profiles/Wanhao France/filament/YUMI PLA Direct Drive.json
DATA = {'compatible_printers': ['D12 230 PRO M2 DIRECT 0.4 nozzle',
                         'D12 230 PRO SMARTPAD DIRECT 0.4 nozzle',
                         'D12 300 PRO M2 DIRECT 0.4 nozzle',
                         'D12 300 PRO SMARTPAD DIRECT 0.4 nozzle',
                         'D12 500 PRO M2 DIRECT 0.4 nozzle',
                         'D12 500 PRO SMARTPAD DIRECT 0.4 nozzle'],
 'cool_plate_temp': ['60'],
 'cool_plate_temp_initial_layer': ['60'],
 'enable_pressure_advance': ['1'],
 'eng_plate_temp': ['60'],
 'eng_plate_temp_initial_layer': ['60'],
 'filament_flow_ratio': ['0.98'],
 'filament_id': 'GFU99',
 'filament_max_volumetric_speed': ['12'],
 'filament_vendor': ['Yumi'],
 'from': 'system',
 'hot_plate_temp': ['60'],
 'hot_plate_temp_initial_layer': ['60'],
 'inherits': 'Yumi Generic PLA',
 'instantiation': 'true',
 'name': 'YUMI PLA Direct Drive',
 'pressure_advance': ['0.02'],
 'setting_id': 'GFSR99',
 'slow_down_layer_time': ['8'],
 'slow_down_min_speed': ['20'],
 'textured_plate_temp': ['60'],
 'textured_plate_temp_initial_layer': ['60'],
 'type': 'filament'}
