from __future__ import annotations

# source: profiles/BBL/process/fdm_process_single_common.json
DATA = {'bridge_speed': ['50'],
 'enable_height_slowdown': ['0'],
 'enable_overhang_speed': ['1'],
 'from': 'system',
 'gap_infill_speed': ['50'],
 'inherits': 'fdm_process_common',
 'initial_layer_acceleration': ['500'],
 'initial_layer_infill_speed': ['60'],
 'initial_layer_speed': ['30'],
 'inner_wall_acceleration': ['0'],
 'inner_wall_speed': ['150'],
 'instantiation': 'false',
 'internal_solid_infill_speed': ['150'],
 'name': 'fdm_process_single_common',
 'outer_wall_acceleration': ['5000'],
 'overhang_1_4_speed': ['0'],
 'overhang_2_4_speed': ['50'],
 'overhang_3_4_speed': ['30'],
 'overhang_4_4_speed': ['10'],
 'print_extruder_id': ['1'],
 'print_extruder_variant': ['Direct Drive Standard'],
 'slowdown_end_acc': ['100000'],
 'slowdown_end_height': ['400'],
 'slowdown_end_speed': ['1000'],
 'slowdown_start_acc': ['100000'],
 'slowdown_start_height': ['0'],
 'slowdown_start_speed': ['1000'],
 'small_perimeter_speed': ['50%'],
 'small_perimeter_threshold': ['0'],
 'sparse_infill_acceleration': ['100%'],
 'sparse_infill_speed': ['250'],
 'support_speed': ['150'],
 'top_surface_acceleration': ['2000'],
 'top_surface_speed': ['200'],
 'travel_speed': ['500'],
 'travel_speed_z': ['0'],
 'type': 'process',
 'vertical_shell_speed': ['80%']}
