from __future__ import annotations

# source: profiles/BBL/filament/Bambu TPU 90A @BBL H2S.json
DATA = {'additional_cooling_fan_speed': ['100'],
 'compatible_printers': ['Bambu Lab H2S 0.4 nozzle'],
 'eng_plate_temp': ['35'],
 'eng_plate_temp_initial_layer': ['35'],
 'filament_adaptive_volumetric_speed': ['0', '0'],
 'filament_deretraction_speed': ['10', '10'],
 'filament_end_gcode': ['; filament end gcode \n'],
 'filament_extruder_variant': ['Direct Drive Standard', 'Direct Drive High Flow'],
 'filament_flow_ratio': ['1', '1'],
 'filament_flush_temp': ['0', '0'],
 'filament_flush_volumetric_speed': ['0', '0'],
 'filament_long_retractions_when_cut': ['nil', 'nil'],
 'filament_max_volumetric_speed': ['5.6', '5.6'],
 'filament_pre_cooling_temperature': ['0', '0'],
 'filament_ramming_travel_time': ['0', '0'],
 'filament_ramming_volumetric_speed': ['0.7', '0.7'],
 'filament_retract_before_wipe': ['nil', 'nil'],
 'filament_retract_restart_extra': ['nil', 'nil'],
 'filament_retract_when_changing_layer': ['nil', 'nil'],
 'filament_retraction_distances_when_cut': ['nil', 'nil'],
 'filament_retraction_length': ['2', '2'],
 'filament_retraction_minimum_travel': ['nil', 'nil'],
 'filament_retraction_speed': ['10', '10'],
 'filament_start_gcode': ['; filament start gcode\n'],
 'filament_wipe': ['1', '1'],
 'filament_wipe_distance': ['1', '1'],
 'filament_z_hop': ['nil', 'nil'],
 'filament_z_hop_types': ['Spiral Lift', 'Spiral Lift'],
 'from': 'system',
 'inherits': 'Bambu TPU 90A @base',
 'instantiation': 'true',
 'long_retractions_when_ec': ['0', '0'],
 'name': 'Bambu TPU 90A @BBL H2S',
 'nozzle_temperature': ['225', '225'],
 'nozzle_temperature_initial_layer': ['225', '225'],
 'pre_start_fan_time': ['2'],
 'retraction_distances_when_ec': ['0', '0'],
 'setting_id': 'GFSU03_11',
 'slow_down_min_speed': ['30'],
 'type': 'filament',
 'volumetric_speed_coefficients': ['-20.9250 -1.8134 71.7462 1.9816 0.5060 -0.1901',
                                   '-20.9250 -1.8134 71.7462 1.9816 0.5060 -0.1901']}
