from __future__ import annotations

# source: profiles/BBL/filament/Bambu PC @BBL H2D 0.8 nozzle.json
DATA = {'chamber_temperatures': ['60'],
 'compatible_printers': ['Bambu Lab H2D 0.8 nozzle'],
 'fan_max_speed': ['40'],
 'filament_adaptive_volumetric_speed': ['0', '0'],
 'filament_deretraction_speed': ['nil', 'nil'],
 'filament_end_gcode': ['; filament end gcode \n'],
 'filament_extruder_variant': ['Direct Drive Standard', 'Direct Drive High Flow'],
 'filament_flow_ratio': ['0.94', '0.94'],
 'filament_flush_temp': ['0', '0'],
 'filament_flush_volumetric_speed': ['0', '0'],
 'filament_long_retractions_when_cut': ['nil', 'nil'],
 'filament_max_volumetric_speed': ['25', '35'],
 'filament_pre_cooling_temperature': ['0', '0'],
 'filament_ramming_travel_time': ['0', '0'],
 'filament_ramming_volumetric_speed': ['-1', '-1'],
 'filament_retract_before_wipe': ['nil', 'nil'],
 'filament_retract_restart_extra': ['nil', 'nil'],
 'filament_retract_when_changing_layer': ['nil', 'nil'],
 'filament_retraction_distances_when_cut': ['nil', 'nil'],
 'filament_retraction_length': ['0.4', '0.4'],
 'filament_retraction_minimum_travel': ['nil', 'nil'],
 'filament_retraction_speed': ['nil', 'nil'],
 'filament_start_gcode': ['; filament start gcode\n'],
 'filament_wipe': ['1', '1'],
 'filament_wipe_distance': ['1', '1'],
 'filament_z_hop': ['nil', 'nil'],
 'filament_z_hop_types': ['Spiral Lift', 'Spiral Lift'],
 'from': 'system',
 'inherits': 'Bambu PC @base',
 'instantiation': 'true',
 'long_retractions_when_ec': ['1', '1'],
 'name': 'Bambu PC @BBL H2D 0.8 nozzle',
 'nozzle_temperature': ['260', '260'],
 'nozzle_temperature_initial_layer': ['270', '270'],
 'retraction_distances_when_ec': ['10', '10'],
 'setting_id': 'GFSC00_22',
 'slow_down_layer_time': ['12'],
 'type': 'filament',
 'volumetric_speed_coefficients': ['0 0 0 0 0 0', '0 0 0 0 0 0']}
