from __future__ import annotations

# source: profiles/BBL/filament/Bambu PETG Basic @BBL X1C 0.2 nozzle.json
DATA = {'compatible_printers': ['Bambu Lab X1 Carbon 0.2 nozzle',
                         'Bambu Lab X1 0.2 nozzle',
                         'Bambu Lab P1P 0.2 nozzle',
                         'Bambu Lab P1S 0.2 nozzle',
                         'Bambu Lab X1E 0.2 nozzle'],
 'fan_max_speed': ['50'],
 'fan_min_speed': ['20'],
 'filament_adaptive_volumetric_speed': ['0', '0'],
 'filament_deretraction_speed': ['nil', 'nil'],
 'filament_extruder_variant': ['Direct Drive Standard', 'Direct Drive High Flow'],
 'filament_flow_ratio': ['0.95', '0.95'],
 'filament_flush_temp': ['0', '0'],
 'filament_flush_volumetric_speed': ['0', '0'],
 'filament_long_retractions_when_cut': ['1', '1'],
 'filament_max_volumetric_speed': ['1', '1'],
 'filament_pre_cooling_temperature': ['0', '0'],
 'filament_ramming_travel_time': ['0', '0'],
 'filament_ramming_volumetric_speed': ['-1', '-1'],
 'filament_retract_before_wipe': ['nil', 'nil'],
 'filament_retract_restart_extra': ['nil', 'nil'],
 'filament_retract_when_changing_layer': ['nil', 'nil'],
 'filament_retraction_distances_when_cut': ['18', '18'],
 'filament_retraction_length': ['nil', 'nil'],
 'filament_retraction_minimum_travel': ['nil', 'nil'],
 'filament_retraction_speed': ['nil', 'nil'],
 'filament_wipe': ['nil', 'nil'],
 'filament_wipe_distance': ['nil', 'nil'],
 'filament_z_hop': ['nil', 'nil'],
 'filament_z_hop_types': ['nil', 'nil'],
 'from': 'system',
 'inherits': 'Bambu PETG Basic @base',
 'instantiation': 'true',
 'long_retractions_when_ec': ['0', '0'],
 'name': 'Bambu PETG Basic @BBL X1C 0.2 nozzle',
 'nozzle_temperature': ['255', '255'],
 'nozzle_temperature_initial_layer': ['245', '245'],
 'overhang_fan_threshold': ['25%'],
 'override_process_overhang_speed': ['0', '0'],
 'retraction_distances_when_ec': ['0', '0'],
 'setting_id': 'GFSG00_00',
 'type': 'filament',
 'volumetric_speed_coefficients': ['0 0 0 0 0 0', '0 0 0 0 0 0']}
