from __future__ import annotations

# source: profiles/BBL/filament/Bambu ASA @BBL H2S.json
DATA = {'chamber_temperatures': ['60'],
 'compatible_printers': ['Bambu Lab H2S 0.4 nozzle'],
 'filament_adaptive_volumetric_speed': ['0', '0'],
 'filament_deretraction_speed': ['nil', 'nil'],
 'filament_end_gcode': ['; filament end gcode \n'],
 'filament_extruder_variant': ['Direct Drive Standard', 'Direct Drive High Flow'],
 'filament_flow_ratio': ['0.95', '0.95'],
 'filament_flush_temp': ['0', '0'],
 'filament_flush_volumetric_speed': ['0', '0'],
 'filament_long_retractions_when_cut': ['nil', 'nil'],
 'filament_max_volumetric_speed': ['20', '35'],
 'filament_pre_cooling_temperature': ['0', '0'],
 'filament_ramming_travel_time': ['0', '0'],
 'filament_ramming_volumetric_speed': ['-1', '-1'],
 'filament_retract_before_wipe': ['nil', 'nil'],
 'filament_retract_restart_extra': ['nil', 'nil'],
 'filament_retract_when_changing_layer': ['nil', 'nil'],
 'filament_retraction_distances_when_cut': ['nil', 'nil'],
 'filament_retraction_length': ['0.4', '0.4'],
 'filament_retraction_minimum_travel': ['nil', 'nil'],
 'filament_retraction_speed': ['nil', 'nil'],
 'filament_start_gcode': ['; filament start gcode\n'],
 'filament_wipe': ['1', '1'],
 'filament_wipe_distance': ['1', '1'],
 'filament_z_hop': ['nil', 'nil'],
 'filament_z_hop_types': ['Spiral Lift', 'Spiral Lift'],
 'from': 'system',
 'inherits': 'Bambu ASA @base',
 'instantiation': 'true',
 'long_retractions_when_ec': ['0', '0'],
 'name': 'Bambu ASA @BBL H2S',
 'nozzle_temperature': ['270', '270'],
 'nozzle_temperature_initial_layer': ['270', '270'],
 'overhang_fan_speed': ['100'],
 'pre_start_fan_time': ['2'],
 'retraction_distances_when_ec': ['0', '0'],
 'setting_id': 'GFSB01_26',
 'type': 'filament',
 'volumetric_speed_coefficients': ['0 0 0 0 0 0', '0 0 0 0 0 0']}
