from __future__ import annotations

# source: profiles/BBL/filament/Bambu PLA Translucent @BBL X1C 0.8 nozzle.json
DATA = {'compatible_printers': ['Bambu Lab X1 Carbon 0.6 nozzle',
                         'Bambu Lab X1 Carbon 0.8 nozzle',
                         'Bambu Lab X1 0.6 nozzle',
                         'Bambu Lab X1 0.8 nozzle',
                         'Bambu Lab P1S 0.6 nozzle',
                         'Bambu Lab P1S 0.8 nozzle',
                         'Bambu Lab X1E 0.6 nozzle',
                         'Bambu Lab X1E 0.8 nozzle'],
 'filament_adaptive_volumetric_speed': ['0', '0'],
 'filament_deretraction_speed': ['nil', 'nil'],
 'filament_extruder_variant': ['Direct Drive Standard', 'Direct Drive High Flow'],
 'filament_flow_ratio': ['0.98', '0.98'],
 'filament_flush_temp': ['0', '0'],
 'filament_flush_volumetric_speed': ['0', '0'],
 'filament_long_retractions_when_cut': ['nil', 'nil'],
 'filament_max_volumetric_speed': ['12', '12'],
 'filament_pre_cooling_temperature': ['0', '0'],
 'filament_ramming_travel_time': ['0', '0'],
 'filament_ramming_volumetric_speed': ['-1', '-1'],
 'filament_retract_before_wipe': ['0', '0'],
 'filament_retract_restart_extra': ['nil', 'nil'],
 'filament_retract_when_changing_layer': ['nil', 'nil'],
 'filament_retraction_distances_when_cut': ['nil', 'nil'],
 'filament_retraction_length': ['nil', 'nil'],
 'filament_retraction_minimum_travel': ['nil', 'nil'],
 'filament_retraction_speed': ['nil', 'nil'],
 'filament_wipe': ['nil', 'nil'],
 'filament_wipe_distance': ['nil', 'nil'],
 'filament_z_hop': ['nil', 'nil'],
 'filament_z_hop_types': ['nil', 'nil'],
 'from': 'system',
 'inherits': 'Bambu PLA Translucent @base',
 'instantiation': 'true',
 'long_retractions_when_ec': ['0', '0'],
 'name': 'Bambu PLA Translucent @BBL X1C 0.8 nozzle',
 'nozzle_temperature': ['220', '220'],
 'nozzle_temperature_initial_layer': ['220', '220'],
 'nozzle_temperature_range_low': ['200'],
 'retraction_distances_when_ec': ['0', '0'],
 'setting_id': 'GFSA17_01',
 'textured_plate_temp_initial_layer': ['60'],
 'type': 'filament',
 'volumetric_speed_coefficients': ['0 0 0 0 0 0', '0 0 0 0 0 0']}
