from __future__ import annotations

# source: profiles/BBL/filament/Generic PP-CF @BBL X1C.json
DATA = {'compatible_printers': ['Bambu Lab P1P 0.4 nozzle',
                         'Bambu Lab P1P 0.6 nozzle',
                         'Bambu Lab P1P 0.8 nozzle',
                         'Bambu Lab P1S 0.4 nozzle',
                         'Bambu Lab P1S 0.6 nozzle',
                         'Bambu Lab P1S 0.8 nozzle',
                         'Bambu Lab X1 0.4 nozzle',
                         'Bambu Lab X1 0.6 nozzle',
                         'Bambu Lab X1 0.8 nozzle',
                         'Bambu Lab X1 Carbon 0.4 nozzle',
                         'Bambu Lab X1 Carbon 0.6 nozzle',
                         'Bambu Lab X1 Carbon 0.8 nozzle',
                         'Bambu Lab X1E 0.4 nozzle',
                         'Bambu Lab X1E 0.6 nozzle',
                         'Bambu Lab X1E 0.8 nozzle'],
 'description': 'This is neither a commonly used filament, nor one of Bambu filaments, and it varies a lot from brand '
                "to brand. So, it's highly recommended to ask its vendor for suitable profile before printing and "
                'adjust some parameters according to its performances.',
 'filament_adaptive_volumetric_speed': ['0', '0'],
 'filament_deretraction_speed': ['nil', 'nil'],
 'filament_extruder_variant': ['Direct Drive Standard', 'Direct Drive High Flow'],
 'filament_flow_ratio': ['1', '1'],
 'filament_flush_temp': ['0', '0'],
 'filament_flush_volumetric_speed': ['0', '0'],
 'filament_long_retractions_when_cut': ['nil', 'nil'],
 'filament_max_volumetric_speed': ['6', '6'],
 'filament_pre_cooling_temperature': ['0', '0'],
 'filament_ramming_travel_time': ['0', '0'],
 'filament_ramming_volumetric_speed': ['-1', '-1'],
 'filament_retract_before_wipe': ['nil', 'nil'],
 'filament_retract_restart_extra': ['nil', 'nil'],
 'filament_retract_when_changing_layer': ['nil', 'nil'],
 'filament_retraction_distances_when_cut': ['nil', 'nil'],
 'filament_retraction_length': ['nil', 'nil'],
 'filament_retraction_minimum_travel': ['nil', 'nil'],
 'filament_retraction_speed': ['nil', 'nil'],
 'filament_wipe': ['nil', 'nil'],
 'filament_wipe_distance': ['nil', 'nil'],
 'filament_z_hop': ['nil', 'nil'],
 'filament_z_hop_types': ['nil', 'nil'],
 'from': 'system',
 'inherits': 'Generic PP-CF @base',
 'instantiation': 'true',
 'long_retractions_when_ec': ['0', '0'],
 'name': 'Generic PP-CF @BBL X1C',
 'nozzle_temperature': ['235', '235'],
 'nozzle_temperature_initial_layer': ['235', '235'],
 'retraction_distances_when_ec': ['0', '0'],
 'setting_id': 'GFSP96_00',
 'type': 'filament',
 'volumetric_speed_coefficients': ['0 0 0 0 0 0', '0 0 0 0 0 0']}
