from __future__ import annotations

# source: profiles/BBL/filament/Generic PETG-CF @BBL H2S.json
DATA = {'compatible_printers': ['Bambu Lab H2S 0.4 nozzle', 'Bambu Lab H2S 0.6 nozzle', 'Bambu Lab H2S 0.8 nozzle'],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['40'],
 'fan_min_speed': ['5'],
 'filament_adaptive_volumetric_speed': ['0', '0'],
 'filament_deretraction_speed': ['nil', 'nil'],
 'filament_end_gcode': ['; filament end gcode \n'],
 'filament_extruder_variant': ['Direct Drive Standard', 'Direct Drive High Flow'],
 'filament_flow_ratio': ['0.95', '0.95'],
 'filament_flush_temp': ['0', '0'],
 'filament_flush_volumetric_speed': ['0', '0'],
 'filament_long_retractions_when_cut': ['nil', '0'],
 'filament_max_volumetric_speed': ['11.5', '11.5'],
 'filament_pre_cooling_temperature': ['0', '0'],
 'filament_ramming_travel_time': ['0', '0'],
 'filament_ramming_volumetric_speed': ['-1', '-1'],
 'filament_retract_before_wipe': ['nil', 'nil'],
 'filament_retract_restart_extra': ['nil', 'nil'],
 'filament_retract_when_changing_layer': ['nil', 'nil'],
 'filament_retraction_distances_when_cut': ['nil', 'nil'],
 'filament_retraction_length': ['nil', 'nil'],
 'filament_retraction_minimum_travel': ['nil', 'nil'],
 'filament_retraction_speed': ['nil', 'nil'],
 'filament_start_gcode': ['; filament start gcode\n'],
 'filament_wipe': ['nil', 'nil'],
 'filament_wipe_distance': ['nil', 'nil'],
 'filament_z_hop': ['nil', 'nil'],
 'filament_z_hop_types': ['nil', 'nil'],
 'from': 'system',
 'inherits': 'Generic PETG-CF @base',
 'instantiation': 'true',
 'long_retractions_when_ec': ['0', '0'],
 'name': 'Generic PETG-CF @BBL H2S',
 'nozzle_temperature': ['255', '255'],
 'nozzle_temperature_initial_layer': ['255', '255'],
 'overhang_fan_speed': ['100'],
 'retraction_distances_when_ec': ['0', '0'],
 'setting_id': 'GFSG98_04',
 'type': 'filament',
 'volumetric_speed_coefficients': ['0 0 0 0 0 0', '0 0 0 0 0 0']}
