from __future__ import annotations

# source: profiles/WonderMaker/machine/fdm_machine_common.json
DATA = {'before_layer_change_gcode': ';BEFORE_LAYER_CHANGE\n;[layer_z]\nG92 E0\n',
 'default_filament_profile': [],
 'default_print_profile': '',
 'deretraction_speed': ['40'],
 'enable_long_retraction_when_cut': '0',
 'extruder_clearance_height_to_lid': '140',
 'extruder_clearance_height_to_rod': '34',
 'extruder_clearance_radius': '65',
 'extruder_colour': ['#FCE94F'],
 'extruder_offset': ['0x0'],
 'from': 'system',
 'gcode_flavor': 'klipper',
 'instantiation': 'false',
 'long_retractions_when_cut': ['0'],
 'machine_end_gcode': ';PRINT_END',
 'machine_max_acceleration_e': ['5000'],
 'machine_max_acceleration_extruding': ['10000'],
 'machine_max_acceleration_retracting': ['1000'],
 'machine_max_acceleration_x': ['10000'],
 'machine_max_acceleration_y': ['10000'],
 'machine_max_acceleration_z': ['100'],
 'machine_max_jerk_e': ['5'],
 'machine_max_jerk_x': ['8'],
 'machine_max_jerk_y': ['8'],
 'machine_max_jerk_z': ['3'],
 'machine_max_speed_e': ['60'],
 'machine_max_speed_x': ['500'],
 'machine_max_speed_y': ['500'],
 'machine_max_speed_z': ['10'],
 'machine_min_extruding_rate': ['0'],
 'machine_min_travel_rate': ['0'],
 'machine_start_gcode': 'START_PRINT EXTRUDER=[nozzle_temperature_initial_layer] '
                        'BED=[bed_temperature_initial_layer_single] CHAMBER=[chamber_temperature] '
                        'INITIAL_TOOL=[initial_tool]  MESH_MIN_X={adaptive_bed_mesh_min[0]}  '
                        'MESH_MIN_Y={adaptive_bed_mesh_min[1]} MESH_MAX_X={adaptive_bed_mesh_max[0]} '
                        'MESH_MAX_Y={adaptive_bed_mesh_max[1]} PROBE_COUNT_X={bed_mesh_probe_count[0]} '
                        'PROBE_COUNT_Y={bed_mesh_probe_count[1]}\n',
 'max_layer_height': ['0.28'],
 'min_layer_height': ['0.08'],
 'name': 'fdm_machine_common',
 'nozzle_diameter': ['0.4'],
 'printable_height': '300',
 'printer_settings_id': '',
 'printer_technology': 'FFF',
 'printer_variant': '0.4',
 'retract_before_wipe': ['70%'],
 'retract_length_toolchange': ['1'],
 'retract_restart_extra': ['0'],
 'retract_restart_extra_toolchange': ['0'],
 'retract_when_changing_layer': ['1'],
 'retraction_distances_when_cut': ['18'],
 'retraction_length': ['1'],
 'retraction_minimum_travel': ['2'],
 'retraction_speed': ['60'],
 'silent_mode': '0',
 'single_extruder_multi_material': '0',
 'support_air_filtration': '0',
 'support_chamber_temp_control': '0',
 'type': 'machine',
 'upward_compatible_machine': [],
 'wipe': ['1'],
 'z_hop': ['0']}
