from __future__ import annotations

# source: profiles/Co Print/process/0.2mm Fast @Co Print ChromaSet 0.4.json
DATA = {'bridge_acceleration': '80%',
 'compatible_printers': ['Co Print ChromaSet 0.4 nozzle fast',
                         'Co Print ChromaSet 0.4 nozzle - Ender-3 V3',
                         'Co Print ChromaSet 0.4 nozzle - Ender-3 V3 Plus'],
 'default_acceleration': '10000',
 'default_jerk': '0',
 'elefant_foot_compensation': '0.1',
 'from': 'system',
 'gap_infill_speed': '300',
 'inherits': 'fdm_process_coprint_common',
 'initial_layer_acceleration': '1500',
 'initial_layer_infill_speed': '100',
 'initial_layer_speed': '60',
 'inner_wall_acceleration': '8000',
 'inner_wall_speed': '200',
 'instantiation': 'true',
 'internal_solid_infill_acceleration': '80%',
 'internal_solid_infill_speed': '300',
 'name': '0.2mm Fast @Co Print ChromaSet 0.4',
 'outer_wall_acceleration': '3000',
 'outer_wall_speed': '120',
 'setting_id': 'GP004',
 'small_perimeter_speed': '50%',
 'sparse_infill_acceleration': '80%',
 'top_surface_acceleration': '2000',
 'top_surface_speed': '150',
 'travel_acceleration': '10000',
 'travel_speed': '500',
 'type': 'process',
 'wipe_tower_max_purge_speed': '200'}
