from __future__ import annotations

# source: profiles/Raise3D/process/0.10mm Fine @Raise3D Pro3Plus.json
DATA = {'adaptive_layer_height': '1',
 'bottom_shell_layers': '6',
 'bottom_shell_thickness': '0',
 'bottom_surface_pattern': 'monotonic',
 'bridge_flow': '0.95',
 'bridge_no_support': '0',
 'bridge_speed': '10',
 'brim_object_gap': '0',
 'brim_width': '5',
 'compatible_printers': ['Raise3D Pro3 Plus 0.4 nozzle (Dual)',
                         'Raise3D Pro3 Plus 0.4 nozzle (Left)',
                         'Raise3D Pro3 Plus 0.4 nozzle (Right)'],
 'compatible_printers_condition': '',
 'default_acceleration': '0',
 'detect_overhang_wall': '1',
 'detect_thin_wall': '1',
 'draft_shield': 'disabled',
 'elefant_foot_compensation': '0.1',
 'enable_arc_fitting': '0',
 'enable_prime_tower': '0',
 'enable_support': '0',
 'filename_format': '{input_filename_base}_{filament_type[initial_tool]}_{print_time}.gcode',
 'from': 'system',
 'gap_infill_speed': '25',
 'infill_combination': '0',
 'infill_direction': '45',
 'infill_wall_overlap': '25%',
 'inherits': 'fdm_process_common',
 'initial_layer_acceleration': '0',
 'initial_layer_infill_speed': '35%',
 'initial_layer_line_width': '0.4',
 'initial_layer_print_height': '0.3',
 'initial_layer_speed': '35%',
 'inner_wall_acceleration': '0',
 'inner_wall_line_width': '0.4',
 'inner_wall_speed': '20',
 'instantiation': 'true',
 'interface_shells': '0',
 'internal_solid_infill_line_width': '0.4',
 'internal_solid_infill_speed': '70',
 'ironing_flow': '5%',
 'ironing_spacing': '0.1',
 'ironing_speed': '10',
 'ironing_type': 'no ironing',
 'layer_height': '0.1',
 'line_width': '0.4',
 'max_travel_detour_distance': '0',
 'minimum_sparse_infill_area': '10',
 'name': '0.10mm Fine @Raise3D Pro3Plus',
 'outer_wall_line_width': '0.4',
 'outer_wall_speed': '15',
 'overhang_1_4_speed': '0',
 'overhang_2_4_speed': '20',
 'overhang_3_4_speed': '15',
 'overhang_4_4_speed': '10',
 'prime_tower_width': '40',
 'print_sequence': 'by layer',
 'print_settings_id': '',
 'raft_layers': '0',
 'reduce_crossing_wall': '0',
 'reduce_infill_retraction': '1',
 'resolution': '0.012',
 'seam_position': 'aligned',
 'setting_id': 'GP004',
 'skirt_distance': '3',
 'skirt_height': '1',
 'skirt_loops': '2',
 'sparse_infill_density': '15%',
 'sparse_infill_line_width': '0.4',
 'sparse_infill_pattern': 'crosshatch',
 'sparse_infill_speed': '60',
 'spiral_mode': '0',
 'standby_temperature_delta': '-20',
 'support_base_pattern': 'rectilinear',
 'support_base_pattern_spacing': '0.1',
 'support_filament': '0',
 'support_interface_bottom_layers': '-1',
 'support_interface_filament': '0',
 'support_interface_loop_pattern': '0',
 'support_interface_spacing': '0.1',
 'support_interface_speed': '100%',
 'support_interface_top_layers': '3',
 'support_line_width': '0.38',
 'support_object_xy_distance': '60%',
 'support_on_build_plate_only': '0',
 'support_speed': '60',
 'support_style': 'grid',
 'support_threshold_angle': '30',
 'support_top_z_distance': '0.08',
 'support_type': 'normal(auto)',
 'top_shell_layers': '5',
 'top_shell_thickness': '0.8',
 'top_surface_acceleration': '0',
 'top_surface_line_width': '0.38',
 'top_surface_pattern': 'monotonicline',
 'top_surface_speed': '35',
 'travel_acceleration': '0',
 'travel_speed': '150',
 'tree_support_branch_angle': '40',
 'tree_support_wall_count': '0',
 'type': 'process',
 'wall_infill_order': 'inner wall/outer wall/infill',
 'wall_loops': '3',
 'wipe_tower_no_sparse_layers': '0',
 'xy_contour_compensation': '0',
 'xy_hole_compensation': '0'}
