from __future__ import annotations

# source: profiles/Qidi/filament/Bambu PETG @0.8 nozzle.json
DATA = {'compatible_printers': ['Qidi X-Plus 0.8 nozzle',
                         'Qidi X-Max 0.8 nozzle',
                         'Qidi X-CF Pro 0.8 nozzle',
                         'Qidi X-Smart 3 0.8 nozzle',
                         'Qidi X-Plus 3 0.8 nozzle',
                         'Qidi X-Max 3 0.8 nozzle'],
 'enable_pressure_advance': ['1'],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['40'],
 'fan_min_speed': ['10'],
 'filament_flow_ratio': ['0.95'],
 'filament_id': 'GFG99',
 'filament_max_volumetric_speed': ['16'],
 'from': 'system',
 'inherits': 'Bambu PETG',
 'instantiation': 'true',
 'name': 'Bambu PETG @0.8 nozzle',
 'overhang_fan_speed': ['90'],
 'overhang_fan_threshold': ['10%'],
 'pressure_advance': ['0.04'],
 'reduce_fan_stop_start_freq': ['1'],
 'setting_id': 'GFSG99',
 'slow_down_for_layer_cooling': ['1'],
 'slow_down_layer_time': ['8'],
 'slow_down_min_speed': ['10'],
 'type': 'filament'}
