from __future__ import annotations

# source: profiles/Qidi/filament/fdm_filament_pet.json
DATA = {'close_fan_the_first_x_layers': ['3'],
 'cool_plate_temp': ['80'],
 'cool_plate_temp_initial_layer': ['80'],
 'eng_plate_temp': ['80'],
 'eng_plate_temp_initial_layer': ['80'],
 'fan_cooling_layer_time': ['20'],
 'fan_max_speed': ['80'],
 'fan_min_speed': ['10'],
 'filament_cost': ['30'],
 'filament_density': ['1.27'],
 'filament_max_volumetric_speed': ['25'],
 'filament_type': ['PETG'],
 'from': 'system',
 'hot_plate_temp': ['80'],
 'hot_plate_temp_initial_layer': ['70'],
 'inherits': 'fdm_filament_common',
 'instantiation': 'false',
 'name': 'fdm_filament_pet',
 'nozzle_temperature': ['250'],
 'nozzle_temperature_initial_layer': ['240'],
 'nozzle_temperature_range_high': ['280'],
 'nozzle_temperature_range_low': ['240'],
 'overhang_fan_speed': ['100'],
 'reduce_fan_stop_start_freq': ['1'],
 'slow_down_for_layer_cooling': ['1'],
 'temperature_vitrification': ['70'],
 'textured_plate_temp': ['80'],
 'textured_plate_temp_initial_layer': ['80'],
 'type': 'filament'}
