from __future__ import annotations

# source: profiles/Qidi/filament/fdm_filament_pla.json
DATA = {'additional_cooling_fan_speed': ['0'],
 'close_fan_the_first_x_layers': ['1'],
 'cool_plate_temp': ['60'],
 'cool_plate_temp_initial_layer': ['60'],
 'dont_slow_down_outer_wall': ['0'],
 'enable_overhang_bridge_fan': ['1'],
 'eng_plate_temp': ['60'],
 'eng_plate_temp_initial_layer': ['60'],
 'fan_cooling_layer_time': ['60'],
 'fan_max_speed': ['100'],
 'fan_min_speed': ['100'],
 'filament_cost': ['20'],
 'filament_density': ['1.24'],
 'filament_max_volumetric_speed': ['12'],
 'filament_type': ['PLA'],
 'from': 'system',
 'full_fan_speed_layer': ['3'],
 'hot_plate_temp': ['60'],
 'hot_plate_temp_initial_layer': ['60'],
 'inherits': 'fdm_filament_common',
 'instantiation': 'false',
 'name': 'fdm_filament_pla',
 'nozzle_temperature': ['220'],
 'nozzle_temperature_initial_layer': ['210'],
 'nozzle_temperature_range_high': ['240'],
 'nozzle_temperature_range_low': ['190'],
 'overhang_fan_speed': ['100'],
 'overhang_fan_threshold': ['50%'],
 'reduce_fan_stop_start_freq': ['1'],
 'slow_down_for_layer_cooling': ['1'],
 'slow_down_layer_time': ['8'],
 'slow_down_min_speed': ['20'],
 'temperature_vitrification': ['45'],
 'textured_plate_temp': ['60'],
 'textured_plate_temp_initial_layer': ['60'],
 'type': 'filament'}
