from __future__ import annotations

# source: profiles/Qidi/filament/fdm_filament_tpu.json
DATA = {'additional_cooling_fan_speed': ['0'],
 'close_fan_the_first_x_layers': ['1'],
 'cool_plate_temp': ['50'],
 'cool_plate_temp_initial_layer': ['05'],
 'enable_overhang_bridge_fan': ['1'],
 'eng_plate_temp': ['50'],
 'eng_plate_temp_initial_layer': ['50'],
 'fan_cooling_layer_time': ['60'],
 'fan_max_speed': ['100'],
 'fan_min_speed': ['100'],
 'filament_cost': ['40'],
 'filament_density': ['1.22'],
 'filament_max_volumetric_speed': ['15'],
 'filament_type': ['TPU'],
 'from': 'system',
 'hot_plate_temp': ['50'],
 'hot_plate_temp_initial_layer': ['60'],
 'inherits': 'fdm_filament_common',
 'instantiation': 'false',
 'name': 'fdm_filament_tpu',
 'nozzle_temperature': ['230'],
 'nozzle_temperature_initial_layer': ['230'],
 'nozzle_temperature_range_high': ['250'],
 'nozzle_temperature_range_low': ['200'],
 'overhang_fan_speed': ['100'],
 'reduce_fan_stop_start_freq': ['1'],
 'slow_down_for_layer_cooling': ['1'],
 'slow_down_min_speed': ['20'],
 'temperature_vitrification': ['30'],
 'textured_plate_temp': ['50'],
 'textured_plate_temp_initial_layer': ['50'],
 'type': 'filament'}
