from __future__ import annotations

# source: profiles/Qidi/filament/fdm_filament_asa.json
DATA = {'activate_air_filtration': ['1'],
 'activate_chamber_temp_control': ['0'],
 'close_fan_the_first_x_layers': ['3'],
 'cool_plate_temp': ['90'],
 'cool_plate_temp_initial_layer': ['90'],
 'during_print_exhaust_fan_speed': ['40'],
 'eng_plate_temp': ['90'],
 'eng_plate_temp_initial_layer': ['90'],
 'fan_cooling_layer_time': ['35'],
 'fan_max_speed': ['50'],
 'fan_min_speed': ['10'],
 'filament_cost': ['20'],
 'filament_density': ['1.04'],
 'filament_max_volumetric_speed': ['15'],
 'filament_type': ['ASA'],
 'from': 'system',
 'hot_plate_temp': ['90'],
 'hot_plate_temp_initial_layer': ['90'],
 'inherits': 'fdm_filament_common',
 'instantiation': 'false',
 'name': 'fdm_filament_asa',
 'nozzle_temperature': ['270'],
 'nozzle_temperature_initial_layer': ['250'],
 'nozzle_temperature_range_high': ['280'],
 'nozzle_temperature_range_low': ['240'],
 'overhang_fan_speed': ['80'],
 'overhang_fan_threshold': ['25%'],
 'reduce_fan_stop_start_freq': ['1'],
 'slow_down_for_layer_cooling': ['1'],
 'slow_down_layer_time': ['3'],
 'slow_down_min_speed': ['20'],
 'temperature_vitrification': ['100'],
 'textured_plate_temp': ['90'],
 'textured_plate_temp_initial_layer': ['90'],
 'type': 'filament'}
