from __future__ import annotations

# source: profiles/Qidi/filament/HATCHBOX PETG @Qidi 0.2 nozzle.json
DATA = {'compatible_printers': ['Qidi X-Plus 0.2 nozzle',
                         'Qidi X-Max 0.2 nozzle',
                         'Qidi X-CF Pro 0.2 nozzle',
                         'Qidi X-Smart 3 0.2 nozzle',
                         'Qidi X-Plus 3 0.2 nozzle',
                         'Qidi X-Max 3 0.2 nozzle',
                         'Qidi Q1 Pro 0.2 nozzle'],
 'enable_pressure_advance': ['1'],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['40'],
 'fan_min_speed': ['10'],
 'filament_flow_ratio': ['0.95'],
 'filament_id': 'GFG99',
 'filament_max_volumetric_speed': ['1'],
 'from': 'system',
 'inherits': 'HATCHBOX PETG @Qidi',
 'instantiation': 'true',
 'name': 'HATCHBOX PETG @0.2 nozzle',
 'overhang_fan_speed': ['90'],
 'overhang_fan_threshold': ['10%'],
 'pressure_advance': ['0.04'],
 'reduce_fan_stop_start_freq': ['1'],
 'setting_id': 'GFSG99',
 'slow_down_for_layer_cooling': ['1'],
 'slow_down_layer_time': ['8'],
 'slow_down_min_speed': ['20'],
 'type': 'filament'}
