from __future__ import annotations

# source: profiles/Qidi/filament/PolyLite ABS @Qidi.json
DATA = {'chamber_temperature': ['60'],
 'compatible_printers': ['Qidi X-Plus 0.4 nozzle',
                         'Qidi X-Max 0.4 nozzle',
                         'Qidi X-CF Pro 0.4 nozzle',
                         'Qidi X-Smart 3 0.4 nozzle',
                         'Qidi X-Plus 3 0.4 nozzle',
                         'Qidi X-Max 3 0.4 nozzle'],
 'enable_pressure_advance': ['1'],
 'fan_cooling_layer_time': ['60'],
 'fan_max_speed': ['80'],
 'fan_min_speed': ['20'],
 'filament_density': ['1.05'],
 'filament_flow_ratio': ['0.96'],
 'filament_id': 'GFB99',
 'filament_max_volumetric_speed': ['17'],
 'filament_type': ['ABS'],
 'filament_vendor': ['Polymaker'],
 'from': 'system',
 'inherits': 'fdm_filament_abs',
 'instantiation': 'true',
 'name': 'PolyLite ABS @Qidi',
 'nozzle_temperature': ['265'],
 'nozzle_temperature_initial_layer': ['260'],
 'overhang_fan_speed': ['80'],
 'pressure_advance': ['0.025'],
 'setting_id': 'GFSA04',
 'slow_down_layer_time': ['6'],
 'slow_down_min_speed': ['20'],
 'type': 'filament'}
