from __future__ import annotations

# source: profiles/Qidi/filament/Qidi Generic PETG @Qidi Q1 Pro 0.4 nozzle.json
DATA = {'compatible_printers': ['Qidi Q1 Pro 0.4 nozzle'],
 'enable_pressure_advance': ['1'],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['40'],
 'fan_min_speed': ['10'],
 'filament_flow_ratio': ['0.95'],
 'filament_id': 'GFB99',
 'filament_max_volumetric_speed': ['12'],
 'filament_settings_id': ['Qidi Generic PETG @Qidi Q1 Pro 0.4 nozzle'],
 'from': 'system',
 'hot_plate_temp_initial_layer': ['80'],
 'inherits': 'Qidi Generic PETG',
 'instantiation': 'true',
 'name': 'Qidi Generic PETG @Qidi Q1 Pro 0.4 nozzle',
 'overhang_fan_speed': ['90'],
 'pressure_advance': ['0.086'],
 'reduce_fan_stop_start_freq': ['1'],
 'setting_id': 'GFSA04',
 'slow_down_for_layer_cooling': ['1'],
 'slow_down_layer_time': ['12'],
 'slow_down_min_speed': ['20'],
 'type': 'filament'}
