from __future__ import annotations

# source: profiles/Qidi/filament/QIDI Support For PAHT.json
DATA = {'compatible_printers': ['Qidi X-CF Pro 0.4 nozzle'],
 'enable_pressure_advance': ['1'],
 'fan_cooling_layer_time': ['10'],
 'fan_max_speed': ['60'],
 'fan_min_speed': ['0'],
 'filament_density': ['1.26'],
 'filament_flow_ratio': ['0.94'],
 'filament_id': 'GFN98',
 'filament_is_support': ['1'],
 'filament_max_volumetric_speed': ['8'],
 'filament_type': ['PAHT-S'],
 'from': 'system',
 'full_fan_speed_layer': ['0'],
 'hot_plate_temp': ['80'],
 'hot_plate_temp_initial_layer': ['80'],
 'inherits': 'fdm_filament_pa',
 'instantiation': 'true',
 'name': 'QIDI Support For PAHT',
 'nozzle_temperature': ['280'],
 'nozzle_temperature_initial_layer': ['280'],
 'nozzle_temperature_range_high': ['280'],
 'nozzle_temperature_range_low': ['260'],
 'overhang_fan_speed': ['30'],
 'overhang_fan_threshold': ['95%'],
 'pressure_advance': ['0.02'],
 'setting_id': 'GFSN99',
 'slow_down_layer_time': ['6'],
 'slow_down_min_speed': ['20'],
 'temperature_vitrification': ['180'],
 'type': 'filament'}
