from __future__ import annotations

# source: profiles/Qidi/filament/QIDI PET-GF.json
DATA = {'compatible_printers': ['Qidi X-Plus 0.4 nozzle',
                         'Qidi X-Max 0.4 nozzle',
                         'Qidi X-CF Pro 0.4 nozzle',
                         'Qidi X-Smart 3 0.4 nozzle',
                         'Qidi X-Plus 3 0.4 nozzle',
                         'Qidi X-Max 3 0.4 nozzle'],
 'enable_pressure_advance': ['1'],
 'fan_cooling_layer_time': ['10'],
 'fan_max_speed': ['20'],
 'fan_min_speed': ['20'],
 'filament_density': ['1.38'],
 'filament_flow_ratio': ['0.97'],
 'filament_id': 'GFN98',
 'filament_max_volumetric_speed': ['12'],
 'filament_type': ['PET-GF'],
 'from': 'system',
 'full_fan_speed_layer': ['0'],
 'hot_plate_temp': ['80'],
 'hot_plate_temp_initial_layer': ['80'],
 'inherits': 'fdm_filament_pa',
 'instantiation': 'true',
 'name': 'QIDI PET-GF',
 'nozzle_temperature': ['310'],
 'nozzle_temperature_initial_layer': ['310'],
 'overhang_fan_speed': ['40'],
 'overhang_fan_threshold': ['0%'],
 'pressure_advance': ['0.023'],
 'setting_id': 'GFSN99',
 'slow_down_layer_time': ['8'],
 'slow_down_min_speed': ['20'],
 'type': 'filament'}
