from __future__ import annotations

# source: profiles/Qidi/filament/QIDI TPU-Aero.json
DATA = {'compatible_printers': ['Qidi X-Plus 0.4 nozzle',
                         'Qidi X-Max 0.4 nozzle',
                         'Qidi X-CF Pro 0.4 nozzle',
                         'Qidi X-Smart 3 0.4 nozzle',
                         'Qidi X-Plus 3 0.4 nozzle',
                         'Qidi X-Max 3 0.4 nozzle',
                         'Qidi X-Max 0.6 nozzle',
                         'Qidi X-CF Pro 0.6 nozzle',
                         'Qidi X-Smart 3 0.6 nozzle',
                         'Qidi X-Plus 3 0.6 nozzle',
                         'Qidi X-Max 3 0.6 nozzle'],
 'enable_pressure_advance': ['1'],
 'fan_cooling_layer_time': ['100'],
 'filament_density': ['1.15'],
 'filament_flow_ratio': ['0.5'],
 'filament_id': 'GFU99',
 'filament_max_volumetric_speed': ['6'],
 'filament_retraction_length': ['0'],
 'filament_type': ['TPU-AERO'],
 'from': 'system',
 'hot_plate_temp': ['35'],
 'hot_plate_temp_initial_layer': ['35'],
 'inherits': 'fdm_filament_tpu',
 'instantiation': 'true',
 'name': 'QIDI TPU-Aero',
 'nozzle_temperature': ['250'],
 'nozzle_temperature_initial_layer': ['250'],
 'nozzle_temperature_range_high': ['270'],
 'nozzle_temperature_range_low': ['230'],
 'pressure_advance': ['0.03'],
 'setting_id': 'GFSR99',
 'slow_down_layer_time': ['14'],
 'type': 'filament'}
