from __future__ import annotations

# source: profiles/Qidi/filament/Qidi Generic PA-CF.json
DATA = {'compatible_printers': ['Qidi X-Plus 0.4 nozzle',
                         'Qidi X-Max 0.4 nozzle',
                         'Qidi X-CF Pro 0.4 nozzle',
                         'Qidi X-Smart 3 0.4 nozzle',
                         'Qidi X-Plus 3 0.4 nozzle',
                         'Qidi X-Max 3 0.4 nozzle',
                         'Qidi X-Max 0.6 nozzle',
                         'Qidi X-CF Pro 0.6 nozzle',
                         'Qidi X-Smart 3 0.6 nozzle',
                         'Qidi X-Plus 3 0.6 nozzle',
                         'Qidi X-Max 3 0.6 nozzle',
                         'Qidi X-Plus 0.8 nozzle',
                         'Qidi X-Max 0.8 nozzle',
                         'Qidi X-CF Pro 0.8 nozzle',
                         'Qidi X-Smart 3 0.8 nozzle',
                         'Qidi X-Plus 3 0.8 nozzle',
                         'Qidi X-Max 3 0.8 nozzle',
                         'Qidi Q1 Pro 0.4 nozzle',
                         'Qidi Q1 Pro 0.6 nozzle',
                         'Qidi Q1 Pro 0.8 nozzle',
                         'Qidi X-Plus 4 0.4 nozzle',
                         'Qidi X-Plus 4 0.6 nozzle',
                         'Qidi X-Plus 4 0.8 nozzle',
                         'Qidi Q2 0.4 nozzle',
                         'Qidi Q2 0.6 nozzle',
                         'Qidi Q2 0.8 nozzle'],
 'enable_pressure_advance': ['1'],
 'fan_cooling_layer_time': ['5'],
 'fan_max_speed': ['40'],
 'fan_min_speed': ['20'],
 'filament_id': 'GFN98',
 'filament_max_volumetric_speed': ['10'],
 'filament_type': ['PA-CF'],
 'filament_vendor': ['Generic'],
 'from': 'system',
 'full_fan_speed_layer': ['2'],
 'inherits': 'fdm_filament_pa',
 'instantiation': 'true',
 'name': 'Qidi Generic PA-CF',
 'nozzle_temperature': ['290'],
 'nozzle_temperature_initial_layer': ['290'],
 'overhang_fan_speed': ['100'],
 'overhang_fan_threshold': ['0%'],
 'pressure_advance': ['0.01'],
 'setting_id': 'GFSN99',
 'type': 'filament'}
