from __future__ import annotations

# source: profiles/Qidi/filament/Qidi Generic PVA.json
DATA = {'compatible_printers': ['Qidi X-Plus 0.2 nozzle',
                         'Qidi X-Max 0.2 nozzle',
                         'Qidi X-CF Pro 0.2 nozzle',
                         'Qidi X-Smart 3 0.2 nozzle',
                         'Qidi X-Plus 3 0.2 nozzle',
                         'Qidi X-Max 3 0.2 nozzle',
                         'Qidi X-Plus 0.4 nozzle',
                         'Qidi X-Max 0.4 nozzle',
                         'Qidi X-CF Pro 0.4 nozzle',
                         'Qidi X-Smart 3 0.4 nozzle',
                         'Qidi X-Plus 3 0.4 nozzle',
                         'Qidi X-Max 3 0.4 nozzle',
                         'Qidi X-Plus 0.6 nozzle',
                         'Qidi X-Max 0.6 nozzle',
                         'Qidi X-CF Pro 0.6 nozzle',
                         'Qidi X-Smart 3 0.6 nozzle',
                         'Qidi X-Plus 3 0.6 nozzle',
                         'Qidi X-Max 3 0.6 nozzle',
                         'Qidi X-Plus 0.8 nozzle',
                         'Qidi X-Max 0.8 nozzle',
                         'Qidi X-CF Pro 0.8 nozzle',
                         'Qidi X-Smart 3 0.8 nozzle',
                         'Qidi X-Plus 3 0.8 nozzle',
                         'Qidi X-Max 3 0.8 nozzle',
                         'Qidi Q1 Pro 0.2 nozzle',
                         'Qidi Q1 Pro 0.4 nozzle',
                         'Qidi Q1 Pro 0.6 nozzle',
                         'Qidi Q1 Pro 0.8 nozzle',
                         'Qidi X-Plus 4 0.2 nozzle',
                         'Qidi X-Plus 4 0.4 nozzle',
                         'Qidi X-Plus 4 0.6 nozzle',
                         'Qidi X-Plus 4 0.8 nozzle',
                         'Qidi Q2 0.2 nozzle',
                         'Qidi Q2 0.4 nozzle',
                         'Qidi Q2 0.6 nozzle',
                         'Qidi Q2 0.8 nozzle'],
 'filament_flow_ratio': ['0.95'],
 'filament_id': 'GFS99',
 'filament_max_volumetric_speed': ['10'],
 'filament_type': ['PVA'],
 'filament_vendor': ['Generic'],
 'from': 'system',
 'inherits': 'fdm_filament_pva',
 'instantiation': 'true',
 'name': 'Qidi Generic PVA',
 'setting_id': 'GFSS99',
 'slow_down_layer_time': ['7'],
 'slow_down_min_speed': ['10'],
 'type': 'filament'}
