from __future__ import annotations

# source: profiles/Qidi/filament/Qidi Generic PC.json
DATA = {'activate_air_filtration': ['1'],
 'compatible_printers': ['Qidi X-Plus 0.4 nozzle',
                         'Qidi X-Max 0.4 nozzle',
                         'Qidi X-CF Pro 0.4 nozzle',
                         'Qidi X-Smart 3 0.4 nozzle',
                         'Qidi X-Plus 3 0.4 nozzle',
                         'Qidi X-Max 3 0.4 nozzle',
                         'Qidi X-Max 0.6 nozzle',
                         'Qidi X-CF Pro 0.6 nozzle',
                         'Qidi X-Smart 3 0.6 nozzle',
                         'Qidi X-Plus 3 0.6 nozzle',
                         'Qidi X-Max 3 0.6 nozzle'],
 'during_print_exhaust_fan_speed': ['0'],
 'enable_pressure_advance': ['1'],
 'filament_flow_ratio': ['0.94'],
 'filament_id': 'GFC99',
 'filament_max_volumetric_speed': ['8'],
 'filament_type': ['PC'],
 'filament_vendor': ['Generic'],
 'from': 'system',
 'hot_plate_temp': ['110'],
 'hot_plate_temp_initial_layer': ['110'],
 'inherits': 'fdm_filament_pc',
 'instantiation': 'true',
 'name': 'Qidi Generic PC',
 'nozzle_temperature': ['280'],
 'nozzle_temperature_initial_layer': ['270'],
 'overhang_fan_speed': ['60'],
 'pressure_advance': ['0.03'],
 'setting_id': 'GFSC99',
 'slow_down_min_speed': ['20'],
 'type': 'filament'}
