from __future__ import annotations

# source: profiles/Qidi/filament/Qidi Generic PLA Silk.json
DATA = {'compatible_printers': ['Qidi X-Plus 0.4 nozzle',
                         'Qidi X-Max 0.4 nozzle',
                         'Qidi X-CF Pro 0.4 nozzle',
                         'Qidi X-Smart 3 0.4 nozzle',
                         'Qidi X-Plus 3 0.4 nozzle',
                         'Qidi X-Max 3 0.4 nozzle',
                         'Qidi X-Plus 0.6 nozzle',
                         'Qidi X-Max 0.6 nozzle',
                         'Qidi X-CF Pro 0.6 nozzle',
                         'Qidi X-Smart 3 0.6 nozzle',
                         'Qidi X-Plus 3 0.6 nozzle',
                         'Qidi X-Max 3 0.6 nozzle',
                         'Qidi X-Plus 0.8 nozzle',
                         'Qidi X-Max 0.8 nozzle',
                         'Qidi X-CF Pro 0.8 nozzle',
                         'Qidi X-Smart 3 0.8 nozzle',
                         'Qidi X-Plus 3 0.8 nozzle',
                         'Qidi X-Max 3 0.8 nozzle',
                         'Qidi Q1 Pro 0.6 nozzle',
                         'Qidi Q1 Pro 0.8 nozzle',
                         'Qidi X-Plus 4 0.6 nozzle',
                         'Qidi X-Plus 4 0.8 nozzle'],
 'enable_pressure_advance': '1',
 'filament_flow_ratio': ['0.98'],
 'filament_id': 'GFA05',
 'filament_max_volumetric_speed': ['7.5'],
 'filament_retraction_length': ['0.5'],
 'filament_type': ['PLA'],
 'filament_vendor': ['Generic'],
 'from': 'system',
 'hot_plate_temp': ['55'],
 'hot_plate_temp_initial_layer': ['55'],
 'inherits': 'fdm_filament_pla',
 'instantiation': 'true',
 'name': 'Qidi Generic PLA Silk',
 'nozzle_temperature_initial_layer': ['220'],
 'pressure_advance': ['0.014'],
 'setting_id': 'GFSL99_01',
 'slow_down_layer_time': ['8'],
 'type': 'filament'}
