from __future__ import annotations

# source: profiles/Qidi/filament/QIDI PPS-CF.json
DATA = {'chamber_temperature': ['60'],
 'compatible_printers': ['Qidi X-Plus 0.4 nozzle',
                         'Qidi X-Max 0.4 nozzle',
                         'Qidi X-CF Pro 0.4 nozzle',
                         'Qidi X-Smart 3 0.4 nozzle',
                         'Qidi X-Plus 3 0.4 nozzle',
                         'Qidi X-Max 3 0.4 nozzle'],
 'enable_pressure_advance': ['1'],
 'fan_cooling_layer_time': ['5'],
 'fan_max_speed': ['30'],
 'fan_min_speed': ['0'],
 'filament_density': ['1.26'],
 'filament_flow_ratio': ['0.97'],
 'filament_id': 'GFN98',
 'filament_max_volumetric_speed': ['6'],
 'filament_type': ['PPS-CF'],
 'from': 'system',
 'full_fan_speed_layer': ['0'],
 'hot_plate_temp': ['110'],
 'hot_plate_temp_initial_layer': ['110'],
 'inherits': 'fdm_filament_pa',
 'instantiation': 'true',
 'name': 'QIDI PPS-CF',
 'nozzle_temperature': ['320'],
 'nozzle_temperature_initial_layer': ['320'],
 'overhang_fan_speed': ['40'],
 'overhang_fan_threshold': ['0%'],
 'pressure_advance': ['0.03'],
 'setting_id': 'GFSN99',
 'slow_down_layer_time': ['2'],
 'type': 'filament'}
