from __future__ import annotations

# source: profiles/Qidi/filament/QIDI ABS Odorless.json
DATA = {'chamber_temperature': ['55'],
 'compatible_printers': ['Qidi X-Plus 0.4 nozzle',
                         'Qidi X-Max 0.4 nozzle',
                         'Qidi X-CF Pro 0.4 nozzle',
                         'Qidi X-Smart 3 0.4 nozzle',
                         'Qidi X-Plus 3 0.4 nozzle',
                         'Qidi X-Max 3 0.4 nozzle'],
 'enable_pressure_advance': ['1'],
 'fan_cooling_layer_time': ['60'],
 'fan_max_speed': ['80'],
 'fan_min_speed': ['10'],
 'filament_density': ['1.02'],
 'filament_flow_ratio': ['0.92'],
 'filament_id': 'GFB99',
 'filament_max_volumetric_speed': ['22'],
 'filament_type': ['ABS'],
 'from': 'system',
 'inherits': 'fdm_filament_abs',
 'instantiation': 'true',
 'name': 'QIDI ABS Odorless',
 'overhang_fan_speed': ['80'],
 'pressure_advance': ['0.021'],
 'setting_id': 'GFSA04',
 'type': 'filament'}
