from __future__ import annotations

# source: profiles/Qidi/filament/QIDI PETG-CF.json
DATA = {'compatible_printers': ['Qidi X-Plus 0.4 nozzle',
                         'Qidi X-Max 0.4 nozzle',
                         'Qidi X-CF Pro 0.4 nozzle',
                         'Qidi X-Smart 3 0.4 nozzle',
                         'Qidi X-Plus 3 0.4 nozzle',
                         'Qidi X-Max 3 0.4 nozzle',
                         'Qidi X-Max 0.6 nozzle',
                         'Qidi X-CF Pro 0.6 nozzle',
                         'Qidi X-Smart 3 0.6 nozzle',
                         'Qidi X-Plus 3 0.6 nozzle',
                         'Qidi X-Max 3 0.6 nozzle',
                         'Qidi X-Plus 0.8 nozzle',
                         'Qidi X-Max 0.8 nozzle',
                         'Qidi X-CF Pro 0.8 nozzle',
                         'Qidi X-Smart 3 0.8 nozzle',
                         'Qidi X-Plus 3 0.8 nozzle',
                         'Qidi X-Max 3 0.8 nozzle'],
 'enable_pressure_advance': ['1'],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['40'],
 'fan_min_speed': ['5'],
 'filament_density': ['1.24'],
 'filament_flow_ratio': ['0.95'],
 'filament_id': 'GFN98',
 'filament_max_volumetric_speed': ['11.5'],
 'filament_type': ['PETG-CF'],
 'from': 'system',
 'full_fan_speed_layer': ['0'],
 'hot_plate_temp': ['80'],
 'hot_plate_temp_initial_layer': ['80'],
 'inherits': 'fdm_filament_pet',
 'instantiation': 'true',
 'name': 'QIDI PETG-CF',
 'nozzle_temperature': ['255'],
 'nozzle_temperature_initial_layer': ['255'],
 'overhang_fan_speed': ['100'],
 'overhang_fan_threshold': ['10%'],
 'pressure_advance': ['0.048'],
 'setting_id': 'GFSN99',
 'slow_down_layer_time': ['6'],
 'slow_down_min_speed': ['20'],
 'type': 'filament'}
