from __future__ import annotations

# source: profiles/Qidi/filament/Qidi Generic PA.json
DATA = {'compatible_printers': ['Qidi X-Plus 0.4 nozzle',
                         'Qidi X-Max 0.4 nozzle',
                         'Qidi X-CF Pro 0.4 nozzle',
                         'Qidi X-Smart 3 0.4 nozzle',
                         'Qidi X-Plus 3 0.4 nozzle',
                         'Qidi X-Max 3 0.4 nozzle',
                         'Qidi X-Max 0.6 nozzle',
                         'Qidi X-CF Pro 0.6 nozzle',
                         'Qidi X-Smart 3 0.6 nozzle',
                         'Qidi X-Plus 3 0.6 nozzle',
                         'Qidi X-Max 3 0.6 nozzle',
                         'Qidi X-Plus 0.8 nozzle',
                         'Qidi X-Max 0.8 nozzle',
                         'Qidi X-CF Pro 0.8 nozzle',
                         'Qidi X-Smart 3 0.8 nozzle',
                         'Qidi X-Plus 3 0.8 nozzle',
                         'Qidi X-Max 3 0.8 nozzle',
                         'Qidi Q1 Pro 0.4 nozzle',
                         'Qidi Q1 Pro 0.6 nozzle',
                         'Qidi Q1 Pro 0.8 nozzle',
                         'Qidi X-Plus 4 0.4 nozzle',
                         'Qidi X-Plus 4 0.6 nozzle',
                         'Qidi X-Plus 4 0.8 nozzle',
                         'Qidi Q2 0.4 nozzle',
                         'Qidi Q2 0.6 nozzle',
                         'Qidi Q2 0.8 nozzle'],
 'enable_pressure_advance': ['1'],
 'filament_id': 'GFN99',
 'filament_max_volumetric_speed': ['14'],
 'filament_type': ['PA'],
 'filament_vendor': ['Generic'],
 'from': 'system',
 'inherits': 'fdm_filament_pa',
 'instantiation': 'true',
 'name': 'Qidi Generic PA',
 'nozzle_temperature': ['310'],
 'nozzle_temperature_initial_layer': ['310'],
 'pressure_advance': ['0.01'],
 'required_nozzle_HRC': ['3'],
 'setting_id': 'GFSN98',
 'type': 'filament'}
