from __future__ import annotations

# source: profiles/Qidi/filament/Qidi PC-ABS-FR.json
DATA = {'chamber_temperature': ['55'],
 'compatible_printers': ['Qidi X-Plus 0.4 nozzle',
                         'Qidi X-Max 0.4 nozzle',
                         'Qidi X-CF Pro 0.4 nozzle',
                         'Qidi X-Smart 3 0.4 nozzle',
                         'Qidi X-Plus 3 0.4 nozzle',
                         'Qidi X-Max 3 0.4 nozzle',
                         'Qidi X-Max 0.6 nozzle',
                         'Qidi X-CF Pro 0.6 nozzle',
                         'Qidi X-Smart 3 0.6 nozzle',
                         'Qidi X-Plus 3 0.6 nozzle',
                         'Qidi X-Max 3 0.6 nozzle',
                         'Qidi X-Plus 0.8 nozzle',
                         'Qidi X-Max 0.8 nozzle',
                         'Qidi X-CF Pro 0.8 nozzle',
                         'Qidi X-Smart 3 0.8 nozzle',
                         'Qidi X-Plus 3 0.8 nozzle',
                         'Qidi X-Max 3 0.8 nozzle'],
 'enable_pressure_advance': ['1'],
 'fan_max_speed': ['40'],
 'fan_min_speed': ['10'],
 'filament_density': ['1.19'],
 'filament_flow_ratio': ['0.92'],
 'filament_id': 'GFB99',
 'filament_max_volumetric_speed': ['8'],
 'filament_type': ['PC-ABS-FR'],
 'from': 'system',
 'hot_plate_temp': ['100'],
 'hot_plate_temp_initial_layer': ['100'],
 'inherits': 'fdm_filament_abs',
 'instantiation': 'true',
 'name': 'Qidi PC-ABS-FR',
 'overhang_fan_speed': ['90'],
 'overhang_fan_threshold': ['75%'],
 'pressure_advance': ['0.04'],
 'setting_id': 'GFSA04',
 'slow_down_layer_time': ['4'],
 'slow_down_min_speed': ['20'],
 'type': 'filament'}
