from __future__ import annotations

# source: profiles/Qidi/filament/Qidi Generic ASA.json
DATA = {'activate_chamber_temp_control': ['0'],
 'compatible_printers': ['Qidi X-Plus 0.2 nozzle',
                         'Qidi X-Max 0.2 nozzle',
                         'Qidi X-CF Pro 0.2 nozzle',
                         'Qidi X-Plus 0.4 nozzle',
                         'Qidi X-Max 0.4 nozzle',
                         'Qidi X-CF Pro 0.4 nozzle',
                         'Qidi X-Smart 3 0.4 nozzle',
                         'Qidi X-Plus 3 0.4 nozzle',
                         'Qidi X-Max 3 0.4 nozzle',
                         'Qidi X-Plus 0.6 nozzle',
                         'Qidi X-Max 0.6 nozzle',
                         'Qidi X-CF Pro 0.6 nozzle',
                         'Qidi X-Smart 3 0.6 nozzle',
                         'Qidi X-Plus 3 0.6 nozzle',
                         'Qidi X-Max 3 0.6 nozzle',
                         'Qidi X-Plus 0.8 nozzle',
                         'Qidi X-Max 0.8 nozzle',
                         'Qidi X-CF Pro 0.8 nozzle',
                         'Qidi X-Smart 3 0.8 nozzle',
                         'Qidi X-Plus 3 0.8 nozzle',
                         'Qidi X-Max 3 0.8 nozzle'],
 'enable_pressure_advance': ['1'],
 'fan_max_speed': ['50'],
 'fan_min_speed': ['10'],
 'filament_flow_ratio': ['0.92'],
 'filament_id': 'GFB99',
 'filament_max_volumetric_speed': ['16'],
 'filament_type': ['ASA'],
 'filament_vendor': ['Generic'],
 'from': 'system',
 'inherits': 'fdm_filament_asa',
 'instantiation': 'true',
 'name': 'Qidi Generic ASA',
 'nozzle_temperature': ['270'],
 'nozzle_temperature_initial_layer': ['250'],
 'pressure_advance': ['0.021'],
 'setting_id': 'GFSA04',
 'type': 'filament'}
