from __future__ import annotations

# source: profiles/Qidi/filament/QIDI ASA.json
DATA = {'chamber_temperature': ['55'],
 'compatible_printers': ['Qidi X-Plus 0.2 nozzle',
                         'Qidi X-Max 0.2 nozzle',
                         'Qidi X-CF Pro 0.2 nozzle',
                         'Qidi X-Plus 0.4 nozzle',
                         'Qidi X-Max 0.4 nozzle',
                         'Qidi X-CF Pro 0.4 nozzle',
                         'Qidi X-Smart 3 0.4 nozzle',
                         'Qidi X-Plus 3 0.4 nozzle',
                         'Qidi X-Max 3 0.4 nozzle',
                         'Qidi X-Plus 0.6 nozzle',
                         'Qidi X-Max 0.6 nozzle',
                         'Qidi X-CF Pro 0.6 nozzle',
                         'Qidi X-Smart 3 0.6 nozzle',
                         'Qidi X-Plus 3 0.6 nozzle',
                         'Qidi X-Max 3 0.6 nozzle',
                         'Qidi X-Plus 0.8 nozzle',
                         'Qidi X-Max 0.8 nozzle',
                         'Qidi X-CF Pro 0.8 nozzle',
                         'Qidi X-Smart 3 0.8 nozzle',
                         'Qidi X-Plus 3 0.8 nozzle',
                         'Qidi X-Max 3 0.8 nozzle'],
 'cool_plate_temp': ['90'],
 'cool_plate_temp_initial_layer': ['90'],
 'enable_pressure_advance': ['1'],
 'eng_plate_temp': ['90'],
 'eng_plate_temp_initial_layer': ['90'],
 'fan_cooling_layer_time': ['40'],
 'fan_max_speed': ['50'],
 'fan_min_speed': ['10'],
 'filament_density': ['1.07'],
 'filament_flow_ratio': ['0.92'],
 'filament_id': 'GFB99',
 'filament_max_volumetric_speed': ['16'],
 'filament_type': ['ASA'],
 'from': 'system',
 'hot_plate_temp': ['90'],
 'hot_plate_temp_initial_layer': ['90'],
 'inherits': 'fdm_filament_asa',
 'instantiation': 'true',
 'name': 'QIDI ASA',
 'nozzle_temperature': ['270'],
 'nozzle_temperature_initial_layer': ['250'],
 'overhang_fan_speed': ['80'],
 'pressure_advance': ['0.021'],
 'setting_id': 'GFSA04',
 'slow_down_layer_time': ['4'],
 'textured_plate_temp': ['90'],
 'textured_plate_temp_initial_layer': ['90'],
 'type': 'filament'}
