from __future__ import annotations

# source: profiles/Qidi/filament/Qidi TPU 95A-HF.json
DATA = {'compatible_printers': ['Qidi X-Plus 0.4 nozzle',
                         'Qidi X-Max 0.4 nozzle',
                         'Qidi X-CF Pro 0.4 nozzle',
                         'Qidi X-Smart 3 0.4 nozzle',
                         'Qidi X-Plus 3 0.4 nozzle',
                         'Qidi X-Max 3 0.4 nozzle',
                         'Qidi X-Max 0.6 nozzle',
                         'Qidi X-CF Pro 0.6 nozzle',
                         'Qidi X-Smart 3 0.6 nozzle',
                         'Qidi X-Plus 3 0.6 nozzle',
                         'Qidi X-Max 3 0.6 nozzle',
                         'Qidi X-Plus 0.8 nozzle',
                         'Qidi X-Max 0.8 nozzle',
                         'Qidi X-CF Pro 0.8 nozzle',
                         'Qidi X-Smart 3 0.8 nozzle',
                         'Qidi X-Plus 3 0.8 nozzle',
                         'Qidi X-Max 3 0.8 nozzle',
                         'Qidi Q1 Pro 0.6 nozzle',
                         'Qidi X-Plus 4 0.6 nozzle'],
 'enable_pressure_advance': ['1'],
 'filament_id': 'GFU99',
 'filament_max_volumetric_speed': ['4'],
 'filament_type': ['TPU'],
 'from': 'system',
 'hot_plate_temp': ['35'],
 'hot_plate_temp_initial_layer': ['35'],
 'inherits': 'fdm_filament_tpu',
 'instantiation': 'true',
 'name': 'Qidi TPU 95A-HF',
 'nozzle_temperature': ['230'],
 'nozzle_temperature_initial_layer': ['230'],
 'pressure_advance': ['0.1'],
 'setting_id': 'GFSR99',
 'type': 'filament'}
