from __future__ import annotations

# source: profiles/Qidi/filament/QIDI ABS-GF25.json
DATA = {'activate_air_filtration': ['1'],
 'chamber_temperature': ['55'],
 'compatible_printers': ['Qidi X-Plus 0.4 nozzle',
                         'Qidi X-Max 0.4 nozzle',
                         'Qidi X-CF Pro 0.4 nozzle',
                         'Qidi X-Smart 3 0.4 nozzle',
                         'Qidi X-Plus 3 0.4 nozzle',
                         'Qidi X-Max 3 0.4 nozzle',
                         'Qidi X-Max 0.6 nozzle',
                         'Qidi X-CF Pro 0.6 nozzle',
                         'Qidi X-Smart 3 0.6 nozzle',
                         'Qidi X-Plus 3 0.6 nozzle',
                         'Qidi X-Max 3 0.6 nozzle',
                         'Qidi X-Plus 0.8 nozzle',
                         'Qidi X-Max 0.8 nozzle',
                         'Qidi X-CF Pro 0.8 nozzle',
                         'Qidi X-Smart 3 0.8 nozzle',
                         'Qidi X-Plus 3 0.8 nozzle',
                         'Qidi X-Max 3 0.8 nozzle'],
 'during_print_exhaust_fan_speed': ['0'],
 'enable_pressure_advance': ['1'],
 'fan_max_speed': ['20'],
 'fan_min_speed': ['20'],
 'filament_flow_ratio': ['0.95'],
 'filament_id': 'GFB99',
 'filament_max_volumetric_speed': ['17'],
 'filament_type': ['ABS-GF'],
 'from': 'system',
 'hot_plate_temp': ['100'],
 'hot_plate_temp_initial_layer': ['100'],
 'inherits': 'fdm_filament_abs',
 'instantiation': 'true',
 'name': 'QIDI ABS-GF25',
 'nozzle_temperature': ['270'],
 'nozzle_temperature_initial_layer': ['270'],
 'overhang_fan_speed': ['100'],
 'pressure_advance': ['0.01'],
 'setting_id': 'GFSA04',
 'type': 'filament'}
