from __future__ import annotations

# source: profiles/Qidi/filament/QIDI PA-Ultra.json
DATA = {'close_fan_the_first_x_layers': ['1'],
 'compatible_printers': ['Qidi X-Plus 0.4 nozzle',
                         'Qidi X-Max 0.4 nozzle',
                         'Qidi X-CF Pro 0.4 nozzle',
                         'Qidi X-Smart 3 0.4 nozzle',
                         'Qidi X-Plus 3 0.4 nozzle',
                         'Qidi X-Max 3 0.4 nozzle',
                         'Qidi X-Max 0.6 nozzle',
                         'Qidi X-CF Pro 0.6 nozzle',
                         'Qidi X-Smart 3 0.6 nozzle',
                         'Qidi X-Plus 3 0.6 nozzle',
                         'Qidi X-Max 3 0.6 nozzle',
                         'Qidi X-Plus 0.8 nozzle',
                         'Qidi X-Max 0.8 nozzle',
                         'Qidi X-CF Pro 0.8 nozzle',
                         'Qidi X-Smart 3 0.8 nozzle',
                         'Qidi X-Plus 3 0.8 nozzle',
                         'Qidi X-Max 3 0.8 nozzle'],
 'enable_overhang_bridge_fan': ['0'],
 'enable_pressure_advance': ['1'],
 'fan_cooling_layer_time': ['60'],
 'fan_max_speed': ['40'],
 'fan_min_speed': ['20'],
 'filament_density': ['1.21'],
 'filament_flow_ratio': ['0.96'],
 'filament_id': 'GFN99',
 'filament_max_volumetric_speed': ['3'],
 'filament_type': ['UltraPA'],
 'from': 'system',
 'hot_plate_temp': ['80'],
 'hot_plate_temp_initial_layer': ['80'],
 'inherits': 'fdm_filament_pa',
 'instantiation': 'true',
 'name': 'QIDI PA-Ultra',
 'nozzle_temperature': ['280'],
 'nozzle_temperature_initial_layer': ['280'],
 'pressure_advance': ['0.03'],
 'required_nozzle_HRC': ['3'],
 'setting_id': 'GFSN98',
 'slow_down_layer_time': ['15'],
 'slow_down_min_speed': ['20'],
 'type': 'filament'}
