from __future__ import annotations

# source: profiles/Qidi/filament/QIDI ABS-GF @Qidi X-Plus 4 0.4 nozzle.json
DATA = {'activate_chamber_temp_control': ['0'],
 'chamber_temperature': ['55'],
 'compatible_printers': ['Qidi X-Plus 4 0.4 nozzle'],
 'fan_max_speed': ['20'],
 'fan_min_speed': ['20'],
 'filament_id': 'GFB99',
 'filament_max_volumetric_speed': ['22'],
 'filament_settings_id': ['QIDI ABS-GF @Qidi X-Plus 4 0.4 nozzle'],
 'from': 'system',
 'hot_plate_temp': ['100'],
 'hot_plate_temp_initial_layer': ['100'],
 'inherits': 'QIDI ABS-GF',
 'instantiation': 'true',
 'name': 'QIDI ABS-GF @Qidi X-Plus 4 0.4 nozzle',
 'nozzle_temperature': ['260'],
 'nozzle_temperature_initial_layer': ['260'],
 'overhang_fan_speed': ['80'],
 'pressure_advance': ['0.03'],
 'setting_id': 'GFSA04',
 'slow_down_layer_time': ['5'],
 'slow_down_min_speed': ['20'],
 'type': 'filament'}
