from __future__ import annotations

# source: profiles/Qidi/filament/QIDI UltraPA-CF25.json
DATA = {'compatible_printers': ['Qidi X-Plus 0.4 nozzle',
                         'Qidi X-Max 0.4 nozzle',
                         'Qidi X-CF Pro 0.4 nozzle',
                         'Qidi X-Smart 3 0.4 nozzle',
                         'Qidi X-Plus 3 0.4 nozzle',
                         'Qidi X-Max 3 0.4 nozzle',
                         'Qidi X-Max 0.6 nozzle',
                         'Qidi X-CF Pro 0.6 nozzle',
                         'Qidi X-Smart 3 0.6 nozzle',
                         'Qidi X-Plus 3 0.6 nozzle',
                         'Qidi X-Max 3 0.6 nozzle',
                         'Qidi X-Plus 0.8 nozzle',
                         'Qidi X-Max 0.8 nozzle',
                         'Qidi X-CF Pro 0.8 nozzle',
                         'Qidi X-Smart 3 0.8 nozzle',
                         'Qidi X-Plus 3 0.8 nozzle',
                         'Qidi X-Max 3 0.8 nozzle'],
 'enable_pressure_advance': ['1'],
 'fan_cooling_layer_time': ['5'],
 'fan_max_speed': ['40'],
 'fan_min_speed': ['20'],
 'filament_density': ['1.20'],
 'filament_flow_ratio': ['0.94'],
 'filament_id': 'GFN98',
 'filament_max_volumetric_speed': ['8'],
 'filament_type': ['UltraPA-CF25'],
 'from': 'system',
 'full_fan_speed_layer': ['0'],
 'hot_plate_temp': ['80'],
 'hot_plate_temp_initial_layer': ['80'],
 'inherits': 'fdm_filament_pa',
 'instantiation': 'true',
 'name': 'QIDI UltraPA-CF25',
 'nozzle_temperature': ['300'],
 'nozzle_temperature_initial_layer': ['300'],
 'overhang_fan_speed': ['40'],
 'overhang_fan_threshold': ['0%'],
 'pressure_advance': ['0.015'],
 'setting_id': 'GFSN99',
 'slow_down_layer_time': ['2'],
 'slow_down_min_speed': ['20'],
 'temperature_vitrification': ['180'],
 'type': 'filament'}
