from __future__ import annotations

# source: profiles/Qidi/filament/Qidi Generic ABS.json
DATA = {'activate_air_filtration': ['1'],
 'activate_chamber_temp_control': ['0'],
 'compatible_printers': ['Qidi X-Plus 0.2 nozzle',
                         'Qidi X-Max 0.2 nozzle',
                         'Qidi X-CF Pro 0.2 nozzle',
                         'Qidi X-Plus 0.4 nozzle',
                         'Qidi X-Max 0.4 nozzle',
                         'Qidi X-CF Pro 0.4 nozzle',
                         'Qidi X-Smart 3 0.4 nozzle',
                         'Qidi X-Plus 3 0.4 nozzle',
                         'Qidi X-Max 3 0.4 nozzle',
                         'Qidi X-Plus 0.6 nozzle',
                         'Qidi X-Max 0.6 nozzle',
                         'Qidi X-CF Pro 0.6 nozzle',
                         'Qidi X-Smart 3 0.6 nozzle',
                         'Qidi X-Plus 3 0.6 nozzle',
                         'Qidi X-Max 3 0.6 nozzle',
                         'Qidi X-Plus 0.8 nozzle',
                         'Qidi X-Max 0.8 nozzle',
                         'Qidi X-CF Pro 0.8 nozzle',
                         'Qidi X-Smart 3 0.8 nozzle',
                         'Qidi X-Plus 3 0.8 nozzle',
                         'Qidi X-Max 3 0.8 nozzle'],
 'enable_pressure_advance': ['1'],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['80'],
 'fan_min_speed': ['10'],
 'filament_density': ['1.04'],
 'filament_flow_ratio': ['0.95'],
 'filament_id': 'GFB99',
 'filament_max_volumetric_speed': ['17'],
 'filament_type': ['ABS'],
 'filament_vendor': ['Generic'],
 'from': 'system',
 'inherits': 'fdm_filament_abs',
 'instantiation': 'true',
 'name': 'Qidi Generic ABS',
 'nozzle_temperature': ['260'],
 'overhang_fan_speed': ['80'],
 'pressure_advance': ['0.021'],
 'setting_id': 'GFSA04',
 'slow_down_min_speed': ['20'],
 'type': 'filament'}
