from __future__ import annotations

# source: profiles/Qidi/filament/Qidi Generic PETG-CF.json
DATA = {'compatible_printers': ['Qidi X-Plus 0.2 nozzle',
                         'Qidi X-Max 0.2 nozzle',
                         'Qidi X-CF Pro 0.2 nozzle',
                         'Qidi X-Smart 3 0.2 nozzle',
                         'Qidi X-Plus 3 0.2 nozzle',
                         'Qidi X-Max 3 0.2 nozzle',
                         'Qidi X-Plus 0.4 nozzle',
                         'Qidi X-Max 0.4 nozzle',
                         'Qidi X-CF Pro 0.4 nozzle',
                         'Qidi X-Smart 3 0.4 nozzle',
                         'Qidi X-Plus 3 0.4 nozzle',
                         'Qidi X-Max 3 0.4 nozzle',
                         'Qidi X-Plus 0.6 nozzle',
                         'Qidi X-Max 0.6 nozzle',
                         'Qidi X-CF Pro 0.6 nozzle',
                         'Qidi X-Smart 3 0.6 nozzle',
                         'Qidi X-Plus 3 0.6 nozzle',
                         'Qidi X-Max 3 0.6 nozzle',
                         'Qidi X-Plus 0.8 nozzle',
                         'Qidi X-Max 0.8 nozzle',
                         'Qidi X-CF Pro 0.8 nozzle',
                         'Qidi X-Smart 3 0.8 nozzle',
                         'Qidi X-Plus 3 0.8 nozzle',
                         'Qidi X-Max 3 0.8 nozzle',
                         'Qidi Q1 Pro 0.2 nozzle',
                         'Qidi Q1 Pro 0.4 nozzle',
                         'Qidi Q1 Pro 0.6 nozzle',
                         'Qidi Q1 Pro 0.8 nozzle',
                         'Qidi X-Plus 4 0.2 nozzle',
                         'Qidi X-Plus 4 0.4 nozzle',
                         'Qidi X-Plus 4 0.6 nozzle',
                         'Qidi X-Plus 4 0.8 nozzle'],
 'cool_plate_temp': ['0'],
 'cool_plate_temp_initial_layer': ['0'],
 'enable_pressure_advance': ['1'],
 'eng_plate_temp': ['70'],
 'eng_plate_temp_initial_layer': ['70'],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['30'],
 'fan_min_speed': ['10'],
 'filament_cost': ['34.99'],
 'filament_density': ['1.25'],
 'filament_flow_ratio': ['0.95'],
 'filament_id': 'GFG98',
 'filament_max_volumetric_speed': ['8'],
 'filament_type': ['PETG-CF'],
 'filament_vendor': ['Generic'],
 'from': 'system',
 'hot_plate_temp': ['70'],
 'hot_plate_temp_initial_layer': ['70'],
 'inherits': 'fdm_filament_pet',
 'instantiation': 'true',
 'name': 'Qidi Generic PETG-CF',
 'nozzle_temperature': ['280'],
 'nozzle_temperature_initial_layer': ['280'],
 'nozzle_temperature_range_high': ['290'],
 'nozzle_temperature_range_low': ['240'],
 'overhang_fan_speed': ['90'],
 'overhang_fan_threshold': ['25%'],
 'pressure_advance': ['0.05'],
 'required_nozzle_HRC': ['40'],
 'setting_id': 'GFSG50',
 'slow_down_layer_time': ['6'],
 'temperature_vitrification': ['75'],
 'textured_plate_temp': ['70'],
 'textured_plate_temp_initial_layer': ['70'],
 'type': 'filament'}
