from __future__ import annotations

# source: profiles/Qidi/filament/Tinmorry PETG-ECO.json
DATA = {'compatible_printers': ['Qidi X-Plus 0.4 nozzle',
                         'Qidi X-Max 0.4 nozzle',
                         'Qidi X-CF Pro 0.4 nozzle',
                         'Qidi X-Smart 3 0.4 nozzle',
                         'Qidi X-Plus 3 0.4 nozzle',
                         'Qidi X-Max 3 0.4 nozzle',
                         'Qidi Q1 Pro 0.4 nozzle',
                         'Qidi X-Plus 4 0.4 nozzle',
                         'Qidi X-Smart 3 0.2 nozzle',
                         'Qidi X-Plus 3 0.2 nozzle',
                         'Qidi X-Max 3 0.2 nozzle',
                         'Qidi Q1 Pro 0.2 nozzle',
                         'Qidi X-Plus 4 0.2 nozzle',
                         'Qidi X-Smart 3 0.6 nozzle',
                         'Qidi X-Plus 3 0.6 nozzle',
                         'Qidi X-Max 3 0.6 nozzle',
                         'Qidi Q1 Pro 0.6 nozzle',
                         'Qidi X-Plus 4 0.6 nozzle',
                         'Qidi X-Smart 3 0.8 nozzle',
                         'Qidi X-Plus 3 0.8 nozzle',
                         'Qidi X-Max 3 0.8 nozzle',
                         'Qidi Q1 Pro 0.8 nozzle',
                         'Qidi X-Plus 4 0.8 nozzle',
                         'Qidi Q2 0.4 nozzle',
                         'Qidi Q2 0.6 nozzle',
                         'Qidi Q2 0.8 nozzle'],
 'cool_plate_temp': ['70'],
 'cool_plate_temp_initial_layer': ['70'],
 'enable_pressure_advance': ['1'],
 'eng_plate_temp': ['70'],
 'eng_plate_temp_initial_layer': ['70'],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['90'],
 'fan_min_speed': ['40'],
 'filament_flow_ratio': ['0.95'],
 'filament_id': 'GFG99',
 'filament_max_volumetric_speed': ['12'],
 'filament_vendor': ['Generic'],
 'from': 'system',
 'hot_plate_temp': ['70'],
 'hot_plate_temp_initial_layer': ['70'],
 'inherits': 'fdm_filament_pet',
 'instantiation': 'true',
 'name': 'Tinmorry PETG-ECO',
 'nozzle_temperature': ['235'],
 'nozzle_temperature_initial_layer': ['235'],
 'overhang_fan_speed': ['90'],
 'overhang_fan_threshold': ['25%'],
 'pressure_advance': ['0.042'],
 'reduce_fan_stop_start_freq': ['1'],
 'setting_id': 'GFSG99',
 'slow_down_for_layer_cooling': ['1'],
 'slow_down_layer_time': ['8'],
 'slow_down_min_speed': ['20'],
 'textured_plate_temp': ['70'],
 'textured_plate_temp_initial_layer': ['70'],
 'type': 'filament'}
