from __future__ import annotations

# source: profiles/Prusa/filament/Prusa Generic PA-CF.json
DATA = {'compatible_printers': ['Prusa MK3S 0.25 nozzle',
                         'Prusa MK3S 0.4 nozzle',
                         'Prusa MK3S 0.6 nozzle',
                         'Prusa MK3S 0.8 nozzle',
                         'Prusa MINI 0.25 nozzle',
                         'Prusa MINI 0.4 nozzle',
                         'Prusa MINI 0.6 nozzle',
                         'Prusa MINI 0.8 nozzle',
                         'Prusa MK4 0.25 nozzle',
                         'Prusa MK4 0.4 nozzle',
                         'Prusa MK4 0.6 nozzle',
                         'Prusa MK4 0.8 nozzle',
                         'Prusa MINIIS 0.4 nozzle',
                         'Prusa MINIIS 0.25 nozzle',
                         'Prusa MINIIS 0.6 nozzle',
                         'Prusa MINIIS 0.8 nozzle'],
 'filament_max_volumetric_speed': ['8'],
 'filament_type': ['PA-CF'],
 'from': 'system',
 'inherits': 'fdm_filament_pa',
 'instantiation': 'true',
 'name': 'Prusa Generic PA-CF',
 'nozzle_temperature': ['280'],
 'nozzle_temperature_initial_layer': ['280'],
 'setting_id': 'GFSA04',
 'type': 'filament'}
