from __future__ import annotations

# source: profiles/Prusa/filament/Prusa Generic TPU HF @MK3.5.json
DATA = {'close_fan_the_first_x_layers': ['3'],
 'compatible_printers': ['Prusa MK3.5 0.4 nozzle',
                         'Prusa MK3.5 0.25 nozzle',
                         'Prusa MK3.5 0.6 nozzle',
                         'Prusa MK3.5 0.8 nozzle'],
 'enable_overhang_bridge_fan': ['1'],
 'fan_cooling_layer_time': ['100'],
 'fan_max_speed': ['80'],
 'fan_min_speed': ['30'],
 'filament_deretraction_speed': ['20'],
 'filament_flow_ratio': ['1.15'],
 'filament_id': 'GFU99_3',
 'filament_max_volumetric_speed': ['8'],
 'filament_retraction_length': ['2'],
 'filament_retraction_speed': ['45'],
 'filament_type': ['FLEX'],
 'from': 'system',
 'full_fan_speed_layer': ['3'],
 'hot_plate_temp': ['50'],
 'hot_plate_temp_initial_layer': ['50'],
 'inherits': 'fdm_filament_tpu',
 'instantiation': 'true',
 'name': 'Prusa Generic TPU HF @MK3.5',
 'nozzle_temperature': ['210'],
 'nozzle_temperature_initial_layer': ['220'],
 'overhang_fan_speed': ['50'],
 'overhang_fan_threshold': ['50%'],
 'pressure_advance': ['0'],
 'reduce_fan_stop_start_freq': ['1'],
 'setting_id': 'GFSA04',
 'slow_down_for_layer_cooling': ['1'],
 'slow_down_layer_time': ['4'],
 'slow_down_min_speed': ['10'],
 'support_material_interface_fan_speed': ['-1'],
 'type': 'filament'}
