from __future__ import annotations

# source: profiles/EONArena/filament/Arena PETG-CF @base.json
DATA = {'cool_plate_temp': ['0'],
 'cool_plate_temp_initial_layer': ['0'],
 'eng_plate_temp': ['70'],
 'eng_plate_temp_initial_layer': ['70'],
 'fan_cooling_layer_time': ['20'],
 'fan_max_speed': ['30'],
 'fan_min_speed': ['0'],
 'filament_cost': ['34.99'],
 'filament_density': ['1.25'],
 'filament_flow_ratio': ['0.95'],
 'filament_id': 'GFG50',
 'filament_max_volumetric_speed': ['14'],
 'filament_type': ['PETG-CF'],
 'filament_vendor': ['EON Arena'],
 'from': 'system',
 'hot_plate_temp': ['70'],
 'hot_plate_temp_initial_layer': ['70'],
 'inherits': 'fdm_filament_pet',
 'instantiation': 'false',
 'name': 'Arena PETG-CF @base',
 'nozzle_temperature': ['255'],
 'nozzle_temperature_initial_layer': ['255'],
 'nozzle_temperature_range_high': ['270'],
 'nozzle_temperature_range_low': ['240'],
 'overhang_fan_speed': ['90'],
 'overhang_fan_threshold': ['25%'],
 'required_nozzle_HRC': ['40'],
 'slow_down_layer_time': ['6'],
 'temperature_vitrification': ['75'],
 'textured_plate_temp': ['70'],
 'textured_plate_temp_initial_layer': ['70'],
 'type': 'filament'}
