from __future__ import annotations

# source: profiles/InfiMech/filament/fdm_filament_pet_other.json
DATA = {'additional_cooling_fan_speed': ['0'],
 'close_fan_the_first_x_layers': ['3'],
 'cool_plate_temp': ['60'],
 'cool_plate_temp_initial_layer': ['60'],
 'eng_plate_temp': ['0'],
 'eng_plate_temp_initial_layer': ['0'],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['90'],
 'fan_min_speed': ['40'],
 'filament_cost': ['30'],
 'filament_density': ['1.27'],
 'filament_max_volumetric_speed': ['12'],
 'filament_start_gcode': ['; filament start gcode\n'],
 'filament_type': ['PETG'],
 'filament_vendor': ['Other'],
 'from': 'system',
 'hot_plate_temp': ['75'],
 'hot_plate_temp_initial_layer': ['75'],
 'inherits': 'fdm_filament_common',
 'instantiation': 'false',
 'name': 'fdm_filament_pet_other',
 'nozzle_temperature': ['255'],
 'nozzle_temperature_initial_layer': ['255'],
 'nozzle_temperature_range_high': ['280'],
 'nozzle_temperature_range_low': ['200'],
 'overhang_fan_speed': ['90'],
 'reduce_fan_stop_start_freq': ['1'],
 'slow_down_for_layer_cooling': ['1'],
 'temperature_vitrification': ['80'],
 'textured_plate_temp': ['80'],
 'textured_plate_temp_initial_layer': ['80'],
 'type': 'filament'}
