from __future__ import annotations

# source: profiles/Peopoly/filament/Peopoly Lancer ABS-GF.json
DATA = {'compatible_printers': ['Peopoly Magneto X 0.4 nozzle',
                         'Peopoly Magneto X 0.6 nozzle',
                         'Peopoly Magneto X 0.8 nozzle'],
 'enable_pressure_advance': ['1'],
 'fan_max_speed': ['40'],
 'filament_deretraction_speed': ['60'],
 'filament_flow_ratio': ['0.91'],
 'filament_id': 'GFL99',
 'filament_max_volumetric_speed': ['35'],
 'filament_retraction_length': ['0.8'],
 'filament_retraction_speed': ['60'],
 'filament_type': ['ABS'],
 'filament_vendor': ['Peopoly'],
 'filament_wipe': ['1'],
 'filament_wipe_distance': ['1'],
 'from': 'system',
 'hot_plate_temp': ['100'],
 'hot_plate_temp_initial_layer': ['90'],
 'inherits': 'fdm_filament_abs',
 'instantiation': 'true',
 'name': 'Peopoly Lancer ABS-GF',
 'nozzle_temperature': ['270'],
 'nozzle_temperature_initial_layer': ['260'],
 'overhang_fan_speed': ['30'],
 'pressure_advance': ['0.016'],
 'reduce_fan_stop_start_freq': ['0'],
 'setting_id': 'GFSL99',
 'slow_down_layer_time': ['6'],
 'type': 'filament'}
