from __future__ import annotations

# source: profiles/Flashforge/process/0.12mm Standard @Flashforge AD5M 0.25 Nozzle.json
DATA = {'bottom_shell_layers': '4',
 'brim_width': '3',
 'compatible_printers': ['Flashforge Adventurer 5M 0.25 Nozzle'],
 'elefant_foot_compensation': '0',
 'filename_format': '{input_filename_base}_{filament_type[initial_tool]}_{print_time}.gcode',
 'from': 'system',
 'gap_infill_speed': '150',
 'inherits': '0.20mm Standard @Flashforge AD5M 0.4 Nozzle',
 'initial_layer_acceleration': '1000',
 'initial_layer_infill_speed': '70',
 'initial_layer_line_width': '0.3',
 'initial_layer_print_height': '0.15',
 'initial_layer_speed': '35',
 'inner_wall_line_width': '0.3',
 'inner_wall_speed': '150',
 'instantiation': 'true',
 'internal_solid_infill_line_width': '0.3',
 'internal_solid_infill_speed': '150',
 'layer_height': '0.12',
 'line_width': '0.25',
 'name': '0.12mm Standard @Flashforge AD5M 0.25 Nozzle',
 'outer_wall_line_width': '0.25',
 'outer_wall_speed': '60',
 'post_process': '',
 'print_settings_id': '0.12mm Standard @Flashforge AD5M 0.25 Nozzle',
 'setting_id': 'GP012',
 'skirt_loops': '0',
 'sparse_infill_line_width': '0.3',
 'sparse_infill_speed': '100',
 'support_bottom_z_distance': '0.12',
 'support_interface_spacing': '0.25',
 'support_line_width': '0.25',
 'support_object_xy_distance': '0.2',
 'support_speed': '80',
 'support_top_z_distance': '0.12',
 'top_shell_layers': '7',
 'top_shell_thickness': '0.8',
 'top_surface_line_width': '0.3',
 'top_surface_speed': '150',
 'tree_support_tip_diameter': '1.2',
 'type': 'process',
 'wipe_speed': '80%'}
