from __future__ import annotations

# source: profiles/Flashforge/process/0.13mm Standard @Flashforge AD4 0.3 Nozzle.json
DATA = {'compatible_printers': ['Flashforge Adventurer 4 Series 0.3 Nozzle'],
 'default_acceleration': '10000',
 'from': 'System',
 'inherits': 'fdm_process_flashforge_0.30',
 'initial_layer_acceleration': '1000',
 'initial_layer_infill_speed': '10',
 'initial_layer_line_width': '0.3',
 'initial_layer_print_height': '0.2',
 'initial_layer_speed': '10',
 'initial_layer_travel_speed': '30',
 'inner_wall_acceleration': '5000',
 'inner_wall_line_width': '0.3',
 'inner_wall_speed': '200',
 'instantiation': 'true',
 'internal_solid_infill_acceleration': '8000',
 'internal_solid_infill_line_width': '0.3',
 'layer_height': '0.13',
 'line_width': '0.3',
 'name': '0.13mm Standard @Flashforge AD4 0.3 Nozzle',
 'outer_wall_acceleration': '3000',
 'outer_wall_line_width': '0.3',
 'outer_wall_speed': '25',
 'overhang_1_4_speed': '100',
 'overhang_2_4_speed': '100',
 'overhang_3_4_speed': '80',
 'overhang_4_4_speed': '50',
 'setting_id': 'GP006',
 'sparse_infill_acceleration': '10000',
 'sparse_infill_line_width': '0.3',
 'support_line_width': '0.3',
 'top_surface_line_width': '0.3',
 'top_surface_speed': '60',
 'travel_speed': '100',
 'type': 'process'}
