from __future__ import annotations

# source: profiles/Flashforge/process/0.30mm Fast @Flashforge AD4 0.4 Nozzle.json
DATA = {'accel_to_decel_enable': '0',
 'compatible_printers': ['Flashforge Adventurer 4 Series 0.4 Nozzle'],
 'default_acceleration': '5000',
 'elefant_foot_compensation': '0.15',
 'enable_arc_fitting': '0',
 'filename_format': '{input_filename_base}.gcode',
 'filter_out_gap_fill': '0.5',
 'from': 'system',
 'gap_infill_speed': '50',
 'gcode_label_objects': '0',
 'inherits': 'fdm_process_flashforge_common',
 'initial_layer_acceleration': '60',
 'initial_layer_infill_speed': '60',
 'initial_layer_line_width': '0.4',
 'initial_layer_min_bead_width': '100',
 'initial_layer_print_height': '0.3',
 'initial_layer_speed': '40',
 'initial_layer_travel_speed': '150',
 'inner_wall_acceleration': '1000',
 'inner_wall_line_width': '0.4',
 'inner_wall_speed': '100',
 'instantiation': 'true',
 'internal_bridge_speed': '50',
 'internal_solid_infill_acceleration': '1000',
 'internal_solid_infill_line_width': '0.4',
 'internal_solid_infill_speed': '50',
 'layer_height': '0.3',
 'line_width': '0.4',
 'max_travel_detour_distance': '50',
 'min_bead_width': '100',
 'name': '0.30mm Fast @Flashforge AD4 0.4 Nozzle',
 'outer_wall_acceleration': '1000',
 'outer_wall_line_width': '0.4',
 'outer_wall_speed': '50',
 'overhang_1_4_speed': '100',
 'overhang_2_4_speed': '80',
 'overhang_3_4_speed': '50',
 'overhang_4_4_speed': '30',
 'overhang_speed_classic': '0',
 'post_process': '',
 'reduce_crossing_wall': '1',
 'setting_id': 'GP001',
 'skirt_distance': '5',
 'skirt_speed': '20',
 'slow_down_layers': '1',
 'small_perimeter_speed': '50%',
 'sparse_infill_line_width': '0.4',
 'sparse_infill_speed': '60',
 'support_line_width': '0.4',
 'support_speed': '100',
 'top_surface_acceleration': '50',
 'top_surface_line_width': '0.4',
 'top_surface_speed': '35',
 'travel_acceleration': '5000',
 'travel_speed': '80',
 'type': 'process',
 'wall_sequence': 'outer wall/inner wall',
 'wipe_speed': '200'}
