from __future__ import annotations

# source: profiles/Flashforge/process/0.30mm Standard @Flashforge AD4 0.6 Nozzle.json
DATA = {'compatible_printers': ['Flashforge Adventurer 4 Series 0.6 Nozzle'],
 'from': 'system',
 'gap_infill_speed': '100',
 'infill_wall_overlap': '50%',
 'inherits': 'fdm_process_flashforge_0.30',
 'initial_layer_infill_speed': '30',
 'initial_layer_speed': '10',
 'initial_layer_travel_speed': '70',
 'inner_wall_speed': '100',
 'instantiation': 'true',
 'internal_solid_infill_acceleration': '8000',
 'internal_solid_infill_speed': '100',
 'name': '0.30mm Standard @Flashforge AD4 0.6 Nozzle',
 'only_one_wall_top': '0',
 'outer_wall_acceleration': '3000',
 'outer_wall_speed': '25',
 'overhang_1_4_speed': '100',
 'overhang_2_4_speed': '100',
 'overhang_3_4_speed': '80',
 'overhang_4_4_speed': '50',
 'setting_id': 'GP004',
 'small_perimeter_threshold': '8',
 'sparse_infill_speed': '60',
 'support_interface_speed': '50',
 'support_speed': '40',
 'support_type': 'tree(auto)',
 'top_surface_acceleration': '500',
 'travel_acceleration': '8000',
 'travel_speed': '100',
 'type': 'process'}
