from __future__ import annotations

# source: profiles/Flashforge/process/0.40mm Standard @Flashforge G3U 0.8 Nozzle.json
DATA = {'bridge_flow': '0.96',
 'compatible_printers': ['Flashforge Guider 3 Ultra 0.8 Nozzle'],
 'enable_arc_fitting': '0',
 'filename_format': '{input_filename_base}.gcode',
 'flush_into_support': '0',
 'from': 'system',
 'gap_infill_speed': '100',
 'infill_wall_overlap': '55%',
 'inherits': 'fdm_process_flashforge_0.40',
 'initial_layer_infill_speed': '30',
 'initial_layer_line_width': '0.85',
 'initial_layer_print_height': '0.5',
 'initial_layer_speed': '20',
 'inner_wall_acceleration': '2000',
 'inner_wall_line_width': '0.8',
 'inner_wall_speed': '80',
 'instantiation': 'true',
 'internal_solid_infill_acceleration': '4000',
 'internal_solid_infill_line_width': '0.82',
 'internal_solid_infill_speed': '160',
 'layer_height': '0.4',
 'line_width': '0.8',
 'name': '0.40mm Standard @Flashforge G3U 0.8 Nozzle',
 'outer_wall_acceleration': '1000',
 'outer_wall_line_width': '0.78',
 'outer_wall_speed': '80',
 'overhang_2_4_speed': '30',
 'post_process': '',
 'prime_tower_brim_width': '5',
 'prime_tower_width': '30',
 'prime_volume': '5',
 'print_settings_id': '0.40mm Standard @Flashforge G3U 0.8 Nozzle',
 'seam_gap': '5%',
 'setting_id': 'GP003',
 'sparse_infill_acceleration': '50%',
 'sparse_infill_line_width': '0.82',
 'sparse_infill_speed': '160',
 'support_base_pattern_spacing': '3',
 'support_bottom_interface_spacing': '0.35',
 'support_bottom_z_distance': '0.28',
 'support_interface_bottom_layers': '0',
 'support_interface_filament': '1',
 'support_interface_spacing': '0.35',
 'support_interface_speed': '30',
 'support_interface_top_layers': '3',
 'support_line_width': '0.75',
 'support_object_xy_distance': '0.6',
 'support_speed': '80',
 'support_top_z_distance': '0.4',
 'top_shell_layers': '4',
 'top_shell_thickness': '0',
 'top_surface_acceleration': '1000',
 'top_surface_line_width': '0.78',
 'top_surface_speed': '100',
 'type': 'process',
 'wipe_tower_bridging': '5'}
