from __future__ import annotations

# source: profiles/Flashforge/process/0.56mm Draft @FF AD5X 0.8 nozzle.json
DATA = {'compatible_printers': ['Flashforge AD5X 0.8 nozzle'],
 'enable_prime_tower': '1',
 'exclude_object': '1',
 'filter_out_gap_fill': '0.1',
 'from': 'system',
 'gap_fill_target': 'topbottom',
 'infill_wall_overlap': '20%',
 'inherits': '0.56mm Draft @Flashforge AD5M Pro 0.8 Nozzle',
 'instantiation': 'true',
 'internal_bridge_speed': '35',
 'name': '0.56mm Draft @FF AD5X 0.8 nozzle',
 'only_one_wall_top': '1',
 'prime_tower_brim_width': '5',
 'prime_tower_width': '45',
 'prime_volume': '100',
 'print_settings_id': '0.56mm Draft @FF AD5X 0.8 nozzle',
 'solid_infill_direction': '0',
 'support_bottom_z_distance': '0.3',
 'support_top_z_distance': '0.3',
 'thick_internal_bridges': '0',
 'top_shell_layers': '4',
 'top_shell_thickness': '0',
 'type': 'process'}
