from __future__ import annotations

# source: profiles/CoLiDo/filament/CoLiDo PETG @CoLiDo SR1.json
DATA = {'compatible_printers': ['CoLiDo SR1 0.4 nozzle'],
 'enable_pressure_advance': ['1'],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['90'],
 'fan_min_speed': ['40'],
 'filament_flow_ratio': ['0.9975'],
 'filament_id': 'GFG99',
 'filament_max_volumetric_speed': ['10'],
 'filament_retraction_length': ['0.5'],
 'filament_settings_id': ['CoLiDo PETG @CoLiDo SR1'],
 'filament_start_gcode': ['; filament start gcode\n'],
 'filament_vendor': ['CoLiDo'],
 'from': 'system',
 'inherits': 'fdm_filament_pet',
 'instantiation': 'true',
 'name': 'CoLiDo PETG @CoLiDo SR1',
 'nozzle_temperature': ['210'],
 'nozzle_temperature_initial_layer': ['210'],
 'nozzle_temperature_range_low': ['200'],
 'overhang_fan_speed': ['90'],
 'overhang_fan_threshold': ['25%'],
 'pressure_advance': ['0.028'],
 'reduce_fan_stop_start_freq': ['1'],
 'setting_id': 'GFSG99_06',
 'slow_down_for_layer_cooling': ['1'],
 'slow_down_layer_time': ['8'],
 'slow_down_min_speed': ['10'],
 'type': 'filament'}
