from __future__ import annotations

# source: profiles/CoLiDo/filament/CoLiDo Generic PETG @CoLiDo X16.json
DATA = {'compatible_printers': ['CoLiDo X16 0.4 nozzle', 'CoLiDo 160 V2 0.4 nozzle'],
 'cool_plate_temp': ['0'],
 'cool_plate_temp_initial_layer': ['0'],
 'eng_plate_temp': ['70'],
 'eng_plate_temp_initial_layer': ['70'],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['40'],
 'fan_min_speed': ['10'],
 'filament_density': ['1.25'],
 'filament_flow_ratio': ['0.94'],
 'filament_id': 'GFG99',
 'filament_max_volumetric_speed': ['9'],
 'filament_start_gcode': ['; filament start gcode\n'],
 'filament_vendor': ['CoLiDo'],
 'from': 'system',
 'hot_plate_temp': ['70'],
 'hot_plate_temp_initial_layer': ['70'],
 'inherits': 'fdm_filament_pet',
 'instantiation': 'true',
 'name': 'CoLiDo Generic PETG @CoLiDo X16',
 'nozzle_temperature_range_high': ['270'],
 'nozzle_temperature_range_low': ['230'],
 'overhang_fan_speed': ['90'],
 'overhang_fan_threshold': ['10%'],
 'reduce_fan_stop_start_freq': ['1'],
 'setting_id': 'GFSG99_05',
 'slow_down_for_layer_cooling': ['1'],
 'slow_down_layer_time': ['12'],
 'slow_down_min_speed': ['10'],
 'textured_plate_temp': ['70'],
 'textured_plate_temp_initial_layer': ['70'],
 'type': 'filament'}
