from __future__ import annotations

# source: profiles/Co Print/filament/CoPrint Generic ABS.json
DATA = {'close_fan_the_first_x_layers': ['3'],
 'compatible_printers': ['Co Print ChromaSet 0.4 nozzle',
                         'Co Print ChromaSet 0.4 nozzle - Ender-3 V3',
                         'Co Print ChromaSet 0.4 nozzle - Ender-3 V3 Plus',
                         'Co Print ChromaSet 0.4 nozzle fast'],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['60'],
 'fan_min_speed': ['10'],
 'filament_density': ['1.04'],
 'filament_flow_ratio': ['0.94'],
 'filament_id': 'GFL99',
 'filament_max_volumetric_speed': ['16'],
 'filament_type': ['ABS'],
 'from': 'system',
 'full_fan_speed_layer': ['5'],
 'hot_plate_temp': ['100'],
 'hot_plate_temp_initial_layer': ['100'],
 'inherits': 'CoPrint Generic PLA',
 'instantiation': 'true',
 'name': 'CoPrint Generic ABS',
 'nozzle_temperature': ['280'],
 'nozzle_temperature_initial_layer': ['260'],
 'nozzle_temperature_range_high': ['280'],
 'nozzle_temperature_range_low': ['240'],
 'overhang_fan_threshold': ['25%'],
 'pressure_advance': ['0.02'],
 'setting_id': 'GFSA04',
 'slow_down_layer_time': ['12'],
 'slow_down_min_speed': ['20'],
 'temperature_vitrification': ['100'],
 'type': 'filament'}
