from __future__ import annotations

# source: profiles/OpenEYE/process/0.16mm Balanced Quality @OpenEYE Peacock V2.json
DATA = {'compatible_printers': ['OpenEYE Peacock V2 0.4 nozzle'],
 'default_acceleration': '4000',
 'description': 'High quality profile for 0.16mm layer height, prioritizing print quality and strength.',
 'from': 'system',
 'inherits': 'fdm_process_openeye_0.16_nozzle_0.4',
 'initial_layer_speed': '50',
 'inner_wall_speed': '150',
 'instantiation': 'true',
 'internal_solid_infill_speed': '180',
 'name': '0.16mm Balanced Quality @OpenEYE Peacock V2',
 'outer_wall_acceleration': '2000',
 'outer_wall_speed': '60',
 'overhang_1_4_speed': '60',
 'overhang_2_4_speed': '30',
 'overhang_3_4_speed': '10',
 'prime_tower_brim_width': '3',
 'prime_tower_width': '60',
 'setting_id': 'GP174',
 'sparse_infill_pattern': 'gyroid',
 'sparse_infill_speed': '180',
 'top_surface_speed': '150',
 'type': 'process'}
