from __future__ import annotations

# source: profiles/OpenEYE/process/fdm_process_openeye_0.40_nozzle_0.8.json
DATA = {'bridge_flow': '1',
 'bridge_speed': '30',
 'elefant_foot_compensation': '0.15',
 'from': 'system',
 'inherits': 'fdm_process_openeye_common',
 'initial_layer_infill_speed': '55',
 'initial_layer_line_width': '0.82',
 'initial_layer_print_height': '0.4',
 'initial_layer_speed': '20',
 'inner_wall_line_width': '0.82',
 'instantiation': 'false',
 'internal_solid_infill_line_width': '0.82',
 'ironing_inset': '0.41',
 'layer_height': '0.4',
 'line_width': '0.82',
 'name': 'fdm_process_openeye_0.40_nozzle_0.8',
 'outer_wall_line_width': '0.82',
 'overhang_3_4_speed': '25',
 'overhang_4_4_speed': '5',
 'skeleton_infill_line_width': '0.82',
 'skin_infill_line_width': '0.82',
 'sparse_infill_line_width': '0.82',
 'sparse_infill_speed': '100',
 'support_line_width': '0.82',
 'top_surface_line_width': '0.82',
 'top_surface_pattern': 'monotonic',
 'top_surface_speed': '150',
 'type': 'process'}
