from __future__ import annotations

# source: profiles/Snapmaker/filament/Polymaker/Polymaker PETG @Snapmaker U1.json
DATA = {'bed_type': ['Cool Plate'],
 'close_fan_the_first_x_layers': ['3'],
 'compatible_printers': ['Snapmaker U1 (0.4 nozzle)'],
 'cool_plate_temp': ['60'],
 'cool_plate_temp_initial_layer': ['60'],
 'eng_plate_temp': ['0'],
 'eng_plate_temp_initial_layer': ['0'],
 'fan_max_speed': ['10'],
 'fan_min_speed': ['50'],
 'filament_cost': ['0'],
 'filament_diameter': ['1.75'],
 'filament_end_gcode': ['; filament end gcode \n'],
 'filament_flow_ratio': ['0.96'],
 'filament_id': 'PMPE01',
 'filament_max_volumetric_speed': ['15'],
 'filament_minimal_purge_on_wipe_tower': ['15'],
 'filament_start_gcode': ['; Filament gcode\n'],
 'filament_vendor': ['Polymaker'],
 'from': 'system',
 'full_fan_speed_layer': ['0'],
 'hot_plate_temp': ['80'],
 'hot_plate_temp_initial_layer': ['80'],
 'inherits': 'Polymaker PETG @Base',
 'instantiation': 'true',
 'name': 'Polymaker PETG @Snapmaker U1',
 'nozzle_temperature': ['260'],
 'nozzle_temperature_initial_layer': ['260'],
 'nozzle_temperature_range_high': ['260'],
 'nozzle_temperature_range_low': ['240'],
 'overhang_fan_speed': ['100'],
 'overhang_fan_threshold': ['95%'],
 'setting_id': 'PMPE01_U1',
 'slow_down_for_layer_cooling': ['1'],
 'slow_down_layer_time': ['6'],
 'slow_down_min_speed': ['10'],
 'supertack_plate_temp': ['70'],
 'supertack_plate_temp_initial_layer': ['70'],
 'temperature_vitrification': ['71'],
 'textured_plate_temp': ['80'],
 'textured_plate_temp_initial_layer': ['80'],
 'type': 'filament'}
