from __future__ import annotations

# source: profiles/BBL/machine/Bambu Lab A1 mini 0.2 nozzle.json
DATA = {'default_filament_profile': ['Bambu PLA Basic @BBL A1M 0.2 nozzle'],
 'default_print_profile': '0.10mm Standard @BBL A1M 0.2 nozzle',
 'from': 'system',
 'inherits': 'Bambu Lab A1 mini 0.4 nozzle',
 'instantiation': 'true',
 'max_layer_height': ['0.14'],
 'min_layer_height': ['0.04'],
 'name': 'Bambu Lab A1 mini 0.2 nozzle',
 'nozzle_diameter': ['0.2'],
 'printer_model': 'Bambu Lab A1 mini',
 'printer_variant': '0.2',
 'retraction_length': ['0.4'],
 'setting_id': 'GM021',
 'type': 'machine',
 'upward_compatible_machine': ['Bambu Lab P1S 0.2 nozzle',
                               'Bambu Lab P1P 0.2 nozzle',
                               'Bambu Lab X1 0.2 nozzle',
                               'Bambu Lab X1 Carbon 0.2 nozzle',
                               'Bambu Lab X1E 0.2 nozzle',
                               'Bambu Lab A1 0.2 nozzle',
                               'Bambu Lab H2D 0.2 nozzle',
                               'Bambu Lab H2D Pro 0.2 nozzle',
                               'Bambu Lab H2S 0.2 nozzle',
                               'Bambu Lab P2S 0.2 nozzle']}
