from __future__ import annotations

# source: profiles/BBL/machine/Bambu Lab P1S 0.4 nozzle.json
DATA = {'bed_exclude_area': ['0x0', '18x0', '18x28', '0x28'],
 'change_filament_gcode': ';=P1S 20250822=\n'
                          'M620 S[next_extruder]A\n'
                          'M204 S9000\n'
                          'G1 Z{max_layer_z + 3.0} F1200\n'
                          '\n'
                          'G1 X70 F21000\n'
                          'G1 Y245\n'
                          'G1 Y265 F3000\n'
                          'M400\n'
                          'M106 P1 S0\n'
                          'M106 P2 S0\n'
                          '{if nozzle_temperature[previous_extruder] > 142 && next_extruder < 255}\n'
                          'M104 S{nozzle_temperature[previous_extruder]}\n'
                          '{endif}\n'
                          '{if long_retractions_when_cut[previous_extruder]}\n'
                          'M620.11 S1 I[previous_extruder] E-{retraction_distances_when_cut[previous_extruder]} '
                          'F{flush_volumetric_speeds[previous_extruder]/2.4053*60}\n'
                          '{else}\n'
                          'M620.11 S0\n'
                          '{endif}\n'
                          'M400\n'
                          'G1 X90 F3000\n'
                          'G1 Y255 F4000\n'
                          'G1 X100 F5000\n'
                          'G1 X120 F15000\n'
                          'G1 X20 Y50 F21000\n'
                          'G1 Y-3\n'
                          '{if toolchange_count == 2}\n'
                          '; get travel path for change filament\n'
                          'M620.1 X[travel_point_1_x] Y[travel_point_1_y] F21000 P0\n'
                          'M620.1 X[travel_point_2_x] Y[travel_point_2_y] F21000 P1\n'
                          'M620.1 X[travel_point_3_x] Y[travel_point_3_y] F21000 P2\n'
                          '{endif}\n'
                          'M620.1 E F{flush_volumetric_speeds[previous_extruder]/2.4053*60} '
                          'T{flush_temperatures[previous_extruder]}\n'
                          'T[next_extruder]\n'
                          'M620.1 E F{flush_volumetric_speeds[next_extruder]/2.4053*60} '
                          'T{flush_temperatures[next_extruder]}\n'
                          '\n'
                          '{if next_extruder < 255}\n'
                          '{if long_retractions_when_cut[previous_extruder]}\n'
                          'M620.11 S1 I[previous_extruder] E{retraction_distances_when_cut[previous_extruder]} '
                          'F{flush_volumetric_speeds[previous_extruder]/2.4053*60}\n'
                          'M628 S1\n'
                          'G92 E0\n'
                          'G1 E{retraction_distances_when_cut[previous_extruder]} '
                          'F{flush_volumetric_speeds[previous_extruder]/2.4053*60}\n'
                          'M400\n'
                          'M629 S1\n'
                          '{else}\n'
                          'M620.11 S0\n'
                          '{endif}\n'
                          'G92 E0\n'
                          '{if flush_length_1 > 1}\n'
                          'M83\n'
                          '; FLUSH_START\n'
                          '; always use highest temperature to flush\n'
                          'M400\n'
                          '{if filament_type[next_extruder] == "PETG"}\n'
                          'M109 S260\n'
                          '{elsif filament_type[next_extruder] == "PVA"}\n'
                          'M109 S210\n'
                          '{else}\n'
                          'M109 S{flush_temperatures[next_extruder]}\n'
                          '{endif}\n'
                          '{if flush_length_1 > 23.7}\n'
                          'G1 E23.7 F{flush_volumetric_speeds[previous_extruder]/2.4053*60} ; do not need pulsatile '
                          'flushing for start part\n'
                          'G1 E{(flush_length_1 - 23.7) * 0.02} F50\n'
                          'G1 E{(flush_length_1 - 23.7) * 0.23} '
                          'F{flush_volumetric_speeds[previous_extruder]/2.4053*60}\n'
                          'G1 E{(flush_length_1 - 23.7) * 0.02} F50\n'
                          'G1 E{(flush_length_1 - 23.7) * 0.23} F{flush_volumetric_speeds[next_extruder]/2.4053*60}\n'
                          'G1 E{(flush_length_1 - 23.7) * 0.02} F50\n'
                          'G1 E{(flush_length_1 - 23.7) * 0.23} F{flush_volumetric_speeds[next_extruder]/2.4053*60}\n'
                          'G1 E{(flush_length_1 - 23.7) * 0.02} F50\n'
                          'G1 E{(flush_length_1 - 23.7) * 0.23} F{flush_volumetric_speeds[next_extruder]/2.4053*60}\n'
                          '{else}\n'
                          'G1 E{flush_length_1} F{flush_volumetric_speeds[previous_extruder]/2.4053*60}\n'
                          '{endif}\n'
                          '; FLUSH_END\n'
                          'G1 E-[old_retract_length_toolchange] F1800\n'
                          'G1 E[old_retract_length_toolchange] F300\n'
                          '{endif}\n'
                          '\n'
                          '{if flush_length_2 > 1}\n'
                          '\n'
                          'G91\n'
                          'G1 X3 F12000; move aside to extrude\n'
                          'G90\n'
                          'M83\n'
                          '\n'
                          '; FLUSH_START\n'
                          'G1 E{flush_length_2 * 0.18} F{flush_volumetric_speeds[next_extruder]/2.4053*60}\n'
                          'G1 E{flush_length_2 * 0.02} F50\n'
                          'G1 E{flush_length_2 * 0.18} F{flush_volumetric_speeds[next_extruder]/2.4053*60}\n'
                          'G1 E{flush_length_2 * 0.02} F50\n'
                          'G1 E{flush_length_2 * 0.18} F{flush_volumetric_speeds[next_extruder]/2.4053*60}\n'
                          'G1 E{flush_length_2 * 0.02} F50\n'
                          'G1 E{flush_length_2 * 0.18} F{flush_volumetric_speeds[next_extruder]/2.4053*60}\n'
                          'G1 E{flush_length_2 * 0.02} F50\n'
                          'G1 E{flush_length_2 * 0.18} F{flush_volumetric_speeds[next_extruder]/2.4053*60}\n'
                          'G1 E{flush_length_2 * 0.02} F50\n'
                          '; FLUSH_END\n'
                          'G1 E-[new_retract_length_toolchange] F1800\n'
                          'G1 E[new_retract_length_toolchange] F300\n'
                          '{endif}\n'
                          '\n'
                          '{if flush_length_3 > 1}\n'
                          '\n'
                          'G91\n'
                          'G1 X3 F12000; move aside to extrude\n'
                          'G90\n'
                          'M83\n'
                          '\n'
                          '; FLUSH_START\n'
                          'G1 E{flush_length_3 * 0.18} F{flush_volumetric_speeds[next_extruder]/2.4053*60}\n'
                          'G1 E{flush_length_3 * 0.02} F50\n'
                          'G1 E{flush_length_3 * 0.18} F{flush_volumetric_speeds[next_extruder]/2.4053*60}\n'
                          'G1 E{flush_length_3 * 0.02} F50\n'
                          'G1 E{flush_length_3 * 0.18} F{flush_volumetric_speeds[next_extruder]/2.4053*60}\n'
                          'G1 E{flush_length_3 * 0.02} F50\n'
                          'G1 E{flush_length_3 * 0.18} F{flush_volumetric_speeds[next_extruder]/2.4053*60}\n'
                          'G1 E{flush_length_3 * 0.02} F50\n'
                          'G1 E{flush_length_3 * 0.18} F{flush_volumetric_speeds[next_extruder]/2.4053*60}\n'
                          'G1 E{flush_length_3 * 0.02} F50\n'
                          '; FLUSH_END\n'
                          'G1 E-[new_retract_length_toolchange] F1800\n'
                          'G1 E[new_retract_length_toolchange] F300\n'
                          '{endif}\n'
                          '\n'
                          '{if flush_length_4 > 1}\n'
                          '\n'
                          'G91\n'
                          'G1 X3 F12000; move aside to extrude\n'
                          'G90\n'
                          'M83\n'
                          '\n'
                          '; FLUSH_START\n'
                          'G1 E{flush_length_4 * 0.18} F{flush_volumetric_speeds[next_extruder]/2.4053*60}\n'
                          'G1 E{flush_length_4 * 0.02} F50\n'
                          'G1 E{flush_length_4 * 0.18} F{flush_volumetric_speeds[next_extruder]/2.4053*60}\n'
                          'G1 E{flush_length_4 * 0.02} F50\n'
                          'G1 E{flush_length_4 * 0.18} F{flush_volumetric_speeds[next_extruder]/2.4053*60}\n'
                          'G1 E{flush_length_4 * 0.02} F50\n'
                          'G1 E{flush_length_4 * 0.18} F{flush_volumetric_speeds[next_extruder]/2.4053*60}\n'
                          'G1 E{flush_length_4 * 0.02} F50\n'
                          'G1 E{flush_length_4 * 0.18} F{flush_volumetric_speeds[next_extruder]/2.4053*60}\n'
                          'G1 E{flush_length_4 * 0.02} F50\n'
                          '; FLUSH_END\n'
                          '{endif}\n'
                          '; FLUSH_START\n'
                          'M400\n'
                          'M109 S{nozzle_temperature[next_extruder]}\n'
                          'G1 E2 F{flush_volumetric_speeds[next_extruder]/2.4053*60} ;Compensate for filament spillage '
                          'during waiting temperature\n'
                          '; FLUSH_END\n'
                          'M400\n'
                          'G92 E0\n'
                          'G1 E-[new_retract_length_toolchange] F1800\n'
                          'M106 P1 S255\n'
                          'M400 S3\n'
                          '\n'
                          'G1 X70 F5000\n'
                          'G1 X90 F3000\n'
                          'G1 Y255 F4000\n'
                          'G1 X105 F5000\n'
                          'G1 Y265 F5000\n'
                          'G1 X70 F10000\n'
                          'G1 X100 F5000\n'
                          'G1 X70 F10000\n'
                          'G1 X100 F5000\n'
                          '\n'
                          'G1 X70 F10000\n'
                          'G1 X80 F15000\n'
                          'G1 X60\n'
                          'G1 X80\n'
                          'G1 X60\n'
                          'G1 X80 ; shake to put down garbage\n'
                          'G1 X100 F5000\n'
                          'G1 X165 F15000; wipe and shake\n'
                          'G1 Y256 ; move Y to aside, prevent collision\n'
                          'M400\n'
                          'G1 Z{max_layer_z + 3.0} F3000\n'
                          '{if layer_z <= (initial_layer_print_height + 0.001)}\n'
                          'M204 S[initial_layer_acceleration]\n'
                          '{else}\n'
                          'M204 S[default_acceleration]\n'
                          '{endif}\n'
                          '{else}\n'
                          'G1 X[x_after_toolchange] Y[y_after_toolchange] Z[z_after_toolchange] F12000\n'
                          '{endif}\n'
                          'M621 S[next_extruder]A\n',
 'default_print_profile': '0.20mm Standard @BBL X1C',
 'deretraction_speed': ['30', '30'],
 'enable_long_retraction_when_cut': '2',
 'extruder_offset': ['0x2'],
 'extruder_variant_list': ['Direct Drive Standard,Direct Drive High Flow'],
 'from': 'system',
 'inherits': 'fdm_bbl_3dp_001_common',
 'instantiation': 'true',
 'long_retractions_when_cut': ['0', '0'],
 'machine_end_gcode': ';===== date: 20230428 =====================\n'
                      'M400 ; wait for buffer to clear\n'
                      'G92 E0 ; zero the extruder\n'
                      'G1 E-0.8 F1800 ; retract\n'
                      'G1 Z{max_layer_z + 0.5} F900 ; lower z a little\n'
                      'G1 X65 Y245 F12000 ; move to safe pos \n'
                      'G1 Y265 F3000\n'
                      '\n'
                      'G1 X65 Y245 F12000\n'
                      'G1 Y265 F3000\n'
                      'M140 S0 ; turn off bed\n'
                      'M106 S0 ; turn off fan\n'
                      'M106 P2 S0 ; turn off remote part cooling fan\n'
                      'M106 P3 S0 ; turn off chamber cooling fan\n'
                      '\n'
                      'G1 X100 F12000 ; wipe\n'
                      '; pull back filament to AMS\n'
                      'M620 S255\n'
                      'G1 X20 Y50 F12000\n'
                      'G1 Y-3\n'
                      'T255\n'
                      'G1 X65 F12000\n'
                      'G1 Y265\n'
                      'G1 X100 F12000 ; wipe\n'
                      'M621 S255\n'
                      'M104 S0 ; turn off hotend\n'
                      '\n'
                      'M622.1 S1 ; for prev firmware, default turned on\n'
                      'M1002 judge_flag timelapse_record_flag\n'
                      'M622 J1\n'
                      '    M400 ; wait all motion done\n'
                      '    M991 S0 P-1 ;end smooth timelapse at safe pos\n'
                      '    M400 S3 ;wait for last picture to be taken\n'
                      'M623; end of "timelapse_record_flag"\n'
                      '\n'
                      'M400 ; wait all motion done\n'
                      'M17 S\n'
                      'M17 Z0.4 ; lower z motor current to reduce impact if there is something in the bottom\n'
                      '{if (max_layer_z + 100.0) < 250}\n'
                      '    G1 Z{max_layer_z + 100.0} F600\n'
                      '    G1 Z{max_layer_z +98.0}\n'
                      '{else}\n'
                      '    G1 Z250 F600\n'
                      '    G1 Z248\n'
                      '{endif}\n'
                      'M400 P100\n'
                      'M17 R ; restore z current\n'
                      '\n'
                      'M220 S100  ; Reset feedrate magnitude\n'
                      'M201.2 K1.0 ; Reset acc magnitude\n'
                      'M73.2   R1.0 ;Reset left time magnitude\n'
                      'M1002 set_gcode_claim_speed_level : 0\n'
                      '\n'
                      'M17 X0.8 Y0.8 Z0.5 ; lower motor current to 45% power\n',
 'machine_max_acceleration_e': ['5000', '5000', '5000', '5000'],
 'machine_max_acceleration_extruding': ['20000', '20000', '20000', '20000'],
 'machine_max_acceleration_retracting': ['5000', '5000', '5000', '5000'],
 'machine_max_acceleration_travel': ['9000', '9000', '9000', '9000'],
 'machine_max_acceleration_x': ['20000', '20000', '20000', '20000'],
 'machine_max_acceleration_y': ['20000', '20000', '20000', '20000'],
 'machine_max_acceleration_z': ['500', '200', '200', '200'],
 'machine_max_jerk_e': ['2.5', '2.5', '2.5', '2.5'],
 'machine_max_jerk_x': ['9', '9', '9', '9'],
 'machine_max_jerk_y': ['9', '9', '9', '9'],
 'machine_max_jerk_z': ['3', '3', '3', '3'],
 'machine_max_speed_e': ['30', '30', '30', '30'],
 'machine_max_speed_x': ['500', '200', '200', '200'],
 'machine_max_speed_y': ['500', '200', '200', '200'],
 'machine_max_speed_z': ['20', '20', '20', '20'],
 'machine_min_extruding_rate': ['0'],
 'machine_min_travel_rate': ['0'],
 'machine_start_gcode': ';===== machine: P1S-0.4 ========================\n'
                        ';===== date: 20250822 =====================\n'
                        ';===== turn on the HB fan & MC board fan =================\n'
                        'M104 S75 ;set extruder temp to turn on the HB fan and prevent filament oozing from nozzle\n'
                        'M710 A1 S255 ;turn on MC fan by default(P1S)\n'
                        ';===== reset machine status =================\n'
                        'M290 X40 Y40 Z2.6666666\n'
                        'G91\n'
                        'M17 Z0.4 ; lower the z-motor current\n'
                        'G380 S2 Z30 F300 ; G380 is same as G38; lower the hotbed , to prevent the nozzle is below the '
                        'hotbed\n'
                        'G380 S2 Z-25 F300 ;\n'
                        'G1 Z5 F300;\n'
                        'G90\n'
                        'M17 X1.2 Y1.2 Z0.75 ; reset motor current to default\n'
                        'M960 S5 P1 ; turn on logo lamp\n'
                        'G90\n'
                        'M220 S100 ;Reset Feedrate\n'
                        'M221 S100 ;Reset Flowrate\n'
                        'M73.2   R1.0 ;Reset left time magnitude\n'
                        'M1002 set_gcode_claim_speed_level : 5\n'
                        'M221 X0 Y0 Z0 ; turn off soft endstop to prevent protential logic problem\n'
                        'G29.1 Z{+0.0} ; clear z-trim value first\n'
                        'M204 S10000 ; init ACC set to 10m/s^2\n'
                        '\n'
                        ';===== heatbed preheat ====================\n'
                        'M1002 gcode_claim_action : 2\n'
                        'M140 S[bed_temperature_initial_layer_single] ;set bed temp\n'
                        'M190 S[bed_temperature_initial_layer_single] ;wait for bed temp\n'
                        '\n'
                        '\n'
                        '\n'
                        ';=============turn on fans to prevent PLA jamming=================\n'
                        '{if filament_type[initial_extruder]=="PLA"}\n'
                        '    {if (bed_temperature[initial_extruder] '
                        '>45)||(bed_temperature_initial_layer[initial_extruder] >45)}\n'
                        '    M106 P3 S180\n'
                        '    {endif};Prevent PLA from jamming\n'
                        '{endif}\n'
                        'M106 P2 S100 ; turn on big fan ,to cool down toolhead\n'
                        '\n'
                        ';===== prepare print temperature and material ==========\n'
                        'M104 S[nozzle_temperature_initial_layer] ;set extruder temp\n'
                        'G91\n'
                        'G0 Z10 F1200\n'
                        'G90\n'
                        'G28 X\n'
                        'M975 S1 ; turn on\n'
                        'G1 X60 F12000\n'
                        'G1 Y245\n'
                        'G1 Y265 F3000\n'
                        'M620 M\n'
                        'M620 S[initial_extruder]A   ; switch material if AMS exist\n'
                        '    M109 S[nozzle_temperature_initial_layer]\n'
                        '    G1 X120 F12000\n'
                        '\n'
                        '    G1 X20 Y50 F12000\n'
                        '    G1 Y-3\n'
                        '    T[initial_extruder]\n'
                        '    G1 X54 F12000\n'
                        '    G1 Y265\n'
                        '    M400\n'
                        'M621 S[initial_extruder]A\n'
                        'M620.1 E F{flush_volumetric_speeds[initial_no_support_extruder]/2.4053*60} '
                        'T{flush_temperatures[initial_no_support_extruder]}\n'
                        '\n'
                        '\n'
                        'M412 S1 ; ===turn on filament runout detection===\n'
                        '\n'
                        'M109 S250 ;set nozzle to common flush temp\n'
                        'M106 P1 S0\n'
                        'G92 E0\n'
                        'G1 E50 F200\n'
                        'M400\n'
                        'M104 S[nozzle_temperature_initial_layer]\n'
                        'G92 E0\n'
                        'G1 E50 F200\n'
                        'M400\n'
                        'M106 P1 S255\n'
                        'G92 E0\n'
                        'G1 E5 F300\n'
                        'M109 S{nozzle_temperature_initial_layer[initial_extruder]-20} ; drop nozzle temp, make '
                        'filament shink a bit\n'
                        'G92 E0\n'
                        'G1 E-0.5 F300\n'
                        '\n'
                        'G1 X70 F9000\n'
                        'G1 X76 F15000\n'
                        'G1 X65 F15000\n'
                        'G1 X76 F15000\n'
                        'G1 X65 F15000; shake to put down garbage\n'
                        'G1 X80 F6000\n'
                        'G1 X95 F15000\n'
                        'G1 X80 F15000\n'
                        'G1 X165 F15000; wipe and shake\n'
                        'M400\n'
                        'M106 P1 S0\n'
                        ';===== prepare print temperature and material end =====\n'
                        '\n'
                        '\n'
                        ';===== wipe nozzle ===============================\n'
                        'M1002 gcode_claim_action : 14\n'
                        'M975 S1\n'
                        'M106 S255\n'
                        'G1 X65 Y230 F18000\n'
                        'G1 Y264 F6000\n'
                        'M109 S{nozzle_temperature_initial_layer[initial_extruder]-20}\n'
                        'G1 X100 F18000 ; first wipe mouth\n'
                        '\n'
                        'G0 X135 Y253 F20000  ; move to exposed steel surface edge\n'
                        'G28 Z P0 T300; home z with low precision,permit 300deg temperature\n'
                        'G29.2 S0 ; turn off ABL\n'
                        'G0 Z5 F20000\n'
                        '\n'
                        'G1 X60 Y265\n'
                        'G92 E0\n'
                        'G1 E-0.5 F300 ; retrack more\n'
                        'G1 X100 F5000; second wipe mouth\n'
                        'G1 X70 F15000\n'
                        'G1 X100 F5000\n'
                        'G1 X70 F15000\n'
                        'G1 X100 F5000\n'
                        'G1 X70 F15000\n'
                        'G1 X100 F5000\n'
                        'G1 X70 F15000\n'
                        'G1 X90 F5000\n'
                        'G0 X128 Y261 Z-1.5 F20000  ; move to exposed steel surface and stop the nozzle\n'
                        'M104 S140 ; set temp down to heatbed acceptable\n'
                        'M106 S255 ; turn on fan (G28 has turn off fan)\n'
                        '\n'
                        'M221 S; push soft endstop status\n'
                        'M221 Z0 ;turn off Z axis endstop\n'
                        'G0 Z0.5 F20000\n'
                        'G0 X125 Y259.5 Z-1.01\n'
                        'G0 X131 F211\n'
                        'G0 X124\n'
                        'G0 Z0.5 F20000\n'
                        'G0 X125 Y262.5\n'
                        'G0 Z-1.01\n'
                        'G0 X131 F211\n'
                        'G0 X124\n'
                        'G0 Z0.5 F20000\n'
                        'G0 X125 Y260.0\n'
                        'G0 Z-1.01\n'
                        'G0 X131 F211\n'
                        'G0 X124\n'
                        'G0 Z0.5 F20000\n'
                        'G0 X125 Y262.0\n'
                        'G0 Z-1.01\n'
                        'G0 X131 F211\n'
                        'G0 X124\n'
                        'G0 Z0.5 F20000\n'
                        'G0 X125 Y260.5\n'
                        'G0 Z-1.01\n'
                        'G0 X131 F211\n'
                        'G0 X124\n'
                        'G0 Z0.5 F20000\n'
                        'G0 X125 Y261.5\n'
                        'G0 Z-1.01\n'
                        'G0 X131 F211\n'
                        'G0 X124\n'
                        'G0 Z0.5 F20000\n'
                        'G0 X125 Y261.0\n'
                        'G0 Z-1.01\n'
                        'G0 X131 F211\n'
                        'G0 X124\n'
                        'G0 X128\n'
                        'G2 I0.5 J0 F300\n'
                        'G2 I0.5 J0 F300\n'
                        'G2 I0.5 J0 F300\n'
                        'G2 I0.5 J0 F300\n'
                        '\n'
                        'M109 S140 ; wait nozzle temp down to heatbed acceptable\n'
                        'G2 I0.5 J0 F3000\n'
                        'G2 I0.5 J0 F3000\n'
                        'G2 I0.5 J0 F3000\n'
                        'G2 I0.5 J0 F3000\n'
                        '\n'
                        'M221 R; pop softend status\n'
                        'G1 Z10 F1200\n'
                        'M400\n'
                        'G1 Z10\n'
                        'G1 F30000\n'
                        'G1 X230 Y15\n'
                        'G29.2 S1 ; turn on ABL\n'
                        ';G28 ; home again after hard wipe mouth\n'
                        'M106 S0 ; turn off fan , too noisy\n'
                        ';===== wipe nozzle end ================================\n'
                        '\n'
                        '\n'
                        ';===== bed leveling ==================================\n'
                        'M1002 judge_flag g29_before_print_flag\n'
                        'M622 J1\n'
                        '\n'
                        '    M1002 gcode_claim_action : 1\n'
                        '    G29 A X{first_layer_print_min[0]} Y{first_layer_print_min[1]} '
                        'I{first_layer_print_size[0]} J{first_layer_print_size[1]}\n'
                        '    M400\n'
                        '    M500 ; save cali data\n'
                        '\n'
                        'M623\n'
                        ';===== bed leveling end ================================\n'
                        '\n'
                        ';===== home after wipe mouth============================\n'
                        'M1002 judge_flag g29_before_print_flag\n'
                        'M622 J0\n'
                        '\n'
                        '    M1002 gcode_claim_action : 13\n'
                        '    G28\n'
                        '\n'
                        'M623\n'
                        ';===== home after wipe mouth end =======================\n'
                        '\n'
                        'M975 S1 ; turn on vibration supression\n'
                        '\n'
                        '\n'
                        ';=============turn on fans to prevent PLA jamming=================\n'
                        '{if filament_type[initial_extruder]=="PLA"}\n'
                        '    {if (bed_temperature[initial_extruder] '
                        '>45)||(bed_temperature_initial_layer[initial_extruder] >45)}\n'
                        '    M106 P3 S180\n'
                        '    {endif};Prevent PLA from jamming\n'
                        '{endif}\n'
                        'M106 P2 S100 ; turn on big fan ,to cool down toolhead\n'
                        '\n'
                        '\n'
                        'M104 S{nozzle_temperature_initial_layer[initial_extruder]} ; set extrude temp earlier, to '
                        'reduce wait time\n'
                        '\n'
                        ';===== mech mode fast check============================\n'
                        'G1 X128 Y128 Z10 F20000\n'
                        'M400 P200\n'
                        'M970.3 Q1 A7 B30 C80  H15 K0\n'
                        'M974 Q1 S2 P0\n'
                        '\n'
                        'G1 X128 Y128 Z10 F20000\n'
                        'M400 P200\n'
                        'M970.3 Q0 A7 B30 C90 Q0 H15 K0\n'
                        'M974 Q0 S2 P0\n'
                        '\n'
                        'M975 S1\n'
                        'G1 F30000\n'
                        'G1 X230 Y15\n'
                        'G28 X ; re-home XY\n'
                        ';===== fmech mode fast check============================\n'
                        '\n'
                        '\n'
                        ';===== nozzle load line ===============================\n'
                        'M975 S1\n'
                        'G90\n'
                        'M83\n'
                        'T1000\n'
                        'G1 X18.0 Y1.0 Z0.8 F18000;Move to start position\n'
                        'M109 S{nozzle_temperature_initial_layer[initial_extruder]}\n'
                        'G1 Z0.2\n'
                        'G0 E2 F300\n'
                        'G0 X240 E15 F{outer_wall_volumetric_speed/(0.3*0.5)     * 60}\n'
                        'G0 Y11 E0.700 F{outer_wall_volumetric_speed/(0.3*0.5)/ 4 * 60}\n'
                        'G0 X239.5\n'
                        'G0 E0.2\n'
                        'G0 Y1.5 E0.700\n'
                        'G0 X18 E15 F{outer_wall_volumetric_speed/(0.3*0.5)     * 60}\n'
                        'M400\n'
                        '\n'
                        ';===== for Textured PEI Plate , lower the nozzle as the nozzle was touching topmost of the '
                        'texture when homing ==\n'
                        ';curr_bed_type={curr_bed_type}\n'
                        '{if curr_bed_type=="Textured PEI Plate"}\n'
                        'G29.1 Z{-0.04} ; for Textured PEI Plate\n'
                        '{endif}\n'
                        ';========turn off light and wait extrude temperature =============\n'
                        'M1002 gcode_claim_action : 0\n'
                        'M106 S0 ; turn off fan\n'
                        'M106 P2 S0 ; turn off big fan\n'
                        'M106 P3 S0 ; turn off chamber fan\n'
                        '\n'
                        'M975 S1 ; turn on mech mode supression\n',
 'machine_unload_filament_time': '28',
 'name': 'Bambu Lab P1S 0.4 nozzle',
 'nozzle_diameter': ['0.4'],
 'nozzle_height': '4.2',
 'nozzle_type': ['stainless_steel', 'stainless_steel'],
 'nozzle_volume': ['107', '107'],
 'printer_extruder_id': ['1', '1'],
 'printer_extruder_variant': ['Direct Drive Standard', 'Direct Drive High Flow'],
 'printer_model': 'Bambu Lab P1S',
 'printer_variant': '0.4',
 'retract_before_wipe': ['0%', '0%'],
 'retract_length_toolchange': ['2', '2'],
 'retract_lift_above': ['0', '0'],
 'retract_lift_below': ['249', '249'],
 'retract_restart_extra': ['0', '0'],
 'retract_restart_extra_toolchange': ['0', '0'],
 'retract_when_changing_layer': ['1', '1'],
 'retraction_distances_when_cut': ['18', '18'],
 'retraction_length': ['0.8', '0.8'],
 'retraction_minimum_travel': ['1', '1'],
 'retraction_speed': ['30', '30'],
 'setting_id': 'GM014',
 'time_lapse_gcode': ';========Date 20250206========\n'
                     '; SKIPPABLE_START\n'
                     '; SKIPTYPE: timelapse\n'
                     'M622.1 S1 ; for prev firmware, default turned on\n'
                     'M1002 judge_flag timelapse_record_flag\n'
                     'M622 J1\n'
                     '{if timelapse_type == 0} ; timelapse without wipe tower\n'
                     'M971 S11 C10 O0\n'
                     'M1004 S5 P1  ; external shutter\n'
                     '{elsif timelapse_type == 1} ; timelapse with wipe tower\n'
                     'G92 E0\n'
                     'G1 X65 Y245 F20000 ; move to safe pos\n'
                     'G17\n'
                     'G2 Z{layer_z} I0.86 J0.86 P1 F20000\n'
                     'G1 Y265 F3000\n'
                     'M400\n'
                     'M1004 S5 P1  ; external shutter\n'
                     'M400 P300\n'
                     'M971 S11 C11 O0\n'
                     'G92 E0\n'
                     'G1 X100 F5000\n'
                     'G1 Y255 F20000\n'
                     '{endif}\n'
                     'M623\n'
                     '; SKIPPABLE_END',
 'type': 'machine',
 'upward_compatible_machine': ['Bambu Lab P1P 0.4 nozzle',
                               'Bambu Lab X1 0.4 nozzle',
                               'Bambu Lab X1 Carbon 0.4 nozzle',
                               'Bambu Lab X1E 0.4 nozzle',
                               'Bambu Lab A1 0.4 nozzle',
                               'Bambu Lab H2D 0.4 nozzle',
                               'Bambu Lab H2D Pro 0.4 nozzle',
                               'Bambu Lab H2S 0.4 nozzle',
                               'Bambu Lab P2S 0.4 nozzle'],
 'wipe': ['1', '1'],
 'wipe_distance': ['2', '2'],
 'z_hop': ['0.4', '0.4'],
 'z_hop_types': ['Auto Lift', 'Auto Lift']}
