from __future__ import annotations

# source: profiles/BBL/machine/Bambu Lab P1S 0.8 nozzle.json
DATA = {'default_filament_profile': ['Bambu PLA Basic @BBL X1C 0.8 nozzle'],
 'default_print_profile': '0.40mm Standard @BBL X1C 0.8 nozzle',
 'from': 'system',
 'inherits': 'Bambu Lab P1S 0.4 nozzle',
 'instantiation': 'true',
 'machine_start_gcode': ';===== machine: P1S-0.8 ========================\n'
                        ';===== date: 20250822 =====================\n'
                        ';===== turn on the HB fan & MC board fan =================\n'
                        'M104 S75 ;set extruder temp to turn on the HB fan and prevent filament oozing from nozzle\n'
                        'M710 A1 S255 ; turn on MC fan by default(P1S)\n'
                        ';===== reset machine status =================\n'
                        'M290 X40 Y40 Z2.6666666\n'
                        'G91\n'
                        'M17 Z0.4 ; lower the z-motor current\n'
                        'G380 S2 Z30 F300 ; G380 is same as G38; lower the hotbed , to prevent the nozzle is below the '
                        'hotbed\n'
                        'G380 S2 Z-25 F300 ;\n'
                        'G1 Z5 F300;\n'
                        'G90\n'
                        'M17 X1.2 Y1.2 Z0.75 ; reset motor current to default\n'
                        'M960 S5 P1 ; turn on logo lamp\n'
                        'G90\n'
                        'M220 S100 ;Reset Feedrate\n'
                        'M221 S100 ;Reset Flowrate\n'
                        'M73.2   R1.0 ;Reset left time magnitude\n'
                        'M1002 set_gcode_claim_speed_level : 5\n'
                        'M221 X0 Y0 Z0 ; turn off soft endstop to prevent protential logic problem\n'
                        'G29.1 Z{+0.0} ; clear z-trim value first\n'
                        'M204 S10000 ; init ACC set to 10m/s^2\n'
                        '\n'
                        ';===== heatbed preheat ====================\n'
                        'M1002 gcode_claim_action : 2\n'
                        'M140 S[bed_temperature_initial_layer_single] ;set bed temp\n'
                        'M190 S[bed_temperature_initial_layer_single] ;wait for bed temp\n'
                        '\n'
                        '\n'
                        ';=============turn on fans to prevent PLA jamming=================\n'
                        '{if filament_type[initial_extruder]=="PLA"}\n'
                        '    {if (bed_temperature[initial_extruder] '
                        '>45)||(bed_temperature_initial_layer[initial_extruder] >45)}\n'
                        '    M106 P3 S180\n'
                        '    {endif};Prevent PLA from jamming\n'
                        '{endif}\n'
                        'M106 P2 S100 ; turn on big fan ,to cool down toolhead\n'
                        '\n'
                        ';===== prepare print temperature and material ==========\n'
                        'M104 S[nozzle_temperature_initial_layer] ;set extruder temp\n'
                        'G91\n'
                        'G0 Z10 F1200\n'
                        'G90\n'
                        'G28 X\n'
                        'M975 S1 ; turn on\n'
                        'G1 X60 F12000\n'
                        'G1 Y245\n'
                        'G1 Y265 F3000\n'
                        'M620 M\n'
                        'M620 S[initial_extruder]A   ; switch material if AMS exist\n'
                        '    M109 S[nozzle_temperature_initial_layer]\n'
                        '    G1 X120 F12000\n'
                        '\n'
                        '    G1 X20 Y50 F12000\n'
                        '    G1 Y-3\n'
                        '    T[initial_extruder]\n'
                        '    G1 X54 F12000\n'
                        '    G1 Y265\n'
                        '    M400\n'
                        'M621 S[initial_extruder]A\n'
                        'M620.1 E F{flush_volumetric_speeds[initial_no_support_extruder]/2.4053*60} '
                        'T{flush_temperatures[initial_no_support_extruder]}\n'
                        '\n'
                        '\n'
                        'M412 S1 ; ===turn on filament runout detection===\n'
                        '\n'
                        'M109 S250 ;set nozzle to common flush temp\n'
                        'M106 P1 S0\n'
                        'G92 E0\n'
                        'G1 E50 F200\n'
                        'M400\n'
                        'M104 S[nozzle_temperature_initial_layer]\n'
                        'G92 E0\n'
                        'G1 E50 F200\n'
                        'M400\n'
                        'M106 P1 S255\n'
                        'G92 E0\n'
                        'G1 E5 F300\n'
                        'M109 S{nozzle_temperature_initial_layer[initial_extruder]-20} ; drop nozzle temp, make '
                        'filament shink a bit\n'
                        'G92 E0\n'
                        'G1 E-0.5 F300\n'
                        '\n'
                        'G1 X70 F9000\n'
                        'G1 X76 F15000\n'
                        'G1 X65 F15000\n'
                        'G1 X76 F15000\n'
                        'G1 X65 F15000; shake to put down garbage\n'
                        'G1 X80 F6000\n'
                        'G1 X95 F15000\n'
                        'G1 X80 F15000\n'
                        'G1 X165 F15000; wipe and shake\n'
                        'M400\n'
                        'M106 P1 S0\n'
                        ';===== prepare print temperature and material end =====\n'
                        '\n'
                        '\n'
                        ';===== wipe nozzle ===============================\n'
                        'M1002 gcode_claim_action : 14\n'
                        'M975 S1\n'
                        'M106 S255\n'
                        'G1 X65 Y230 F18000\n'
                        'G1 Y264 F6000\n'
                        'M109 S{nozzle_temperature_initial_layer[initial_extruder]-20}\n'
                        'G1 X100 F18000 ; first wipe mouth\n'
                        '\n'
                        'G0 X135 Y253 F20000  ; move to exposed steel surface edge\n'
                        'G28 Z P0 T300; home z with low precision,permit 300deg temperature\n'
                        'G29.2 S0 ; turn off ABL\n'
                        'G0 Z5 F20000\n'
                        '\n'
                        'G1 X60 Y265\n'
                        'G92 E0\n'
                        'G1 E-0.5 F300 ; retrack more\n'
                        'G1 X100 F5000; second wipe mouth\n'
                        'G1 X70 F15000\n'
                        'G1 X100 F5000\n'
                        'G1 X70 F15000\n'
                        'G1 X100 F5000\n'
                        'G1 X70 F15000\n'
                        'G1 X100 F5000\n'
                        'G1 X70 F15000\n'
                        'G1 X90 F5000\n'
                        'G0 X128 Y261 Z-1.5 F20000  ; move to exposed steel surface and stop the nozzle\n'
                        'M104 S140 ; set temp down to heatbed acceptable\n'
                        'M106 S255 ; turn on fan (G28 has turn off fan)\n'
                        '\n'
                        'M221 S; push soft endstop status\n'
                        'M221 Z0 ;turn off Z axis endstop\n'
                        'G0 Z0.5 F20000\n'
                        'G0 X125 Y259.5 Z-1.01\n'
                        'G0 X131 F211\n'
                        'G0 X124\n'
                        'G0 Z0.5 F20000\n'
                        'G0 X125 Y262.5\n'
                        'G0 Z-1.01\n'
                        'G0 X131 F211\n'
                        'G0 X124\n'
                        'G0 Z0.5 F20000\n'
                        'G0 X125 Y260.0\n'
                        'G0 Z-1.01\n'
                        'G0 X131 F211\n'
                        'G0 X124\n'
                        'G0 Z0.5 F20000\n'
                        'G0 X125 Y262.0\n'
                        'G0 Z-1.01\n'
                        'G0 X131 F211\n'
                        'G0 X124\n'
                        'G0 Z0.5 F20000\n'
                        'G0 X125 Y260.5\n'
                        'G0 Z-1.01\n'
                        'G0 X131 F211\n'
                        'G0 X124\n'
                        'G0 Z0.5 F20000\n'
                        'G0 X125 Y261.5\n'
                        'G0 Z-1.01\n'
                        'G0 X131 F211\n'
                        'G0 X124\n'
                        'G0 Z0.5 F20000\n'
                        'G0 X125 Y261.0\n'
                        'G0 Z-1.01\n'
                        'G0 X131 F211\n'
                        'G0 X124\n'
                        'G0 X128\n'
                        'G2 I0.5 J0 F300\n'
                        'G2 I0.5 J0 F300\n'
                        'G2 I0.5 J0 F300\n'
                        'G2 I0.5 J0 F300\n'
                        '\n'
                        'M109 S140 ; wait nozzle temp down to heatbed acceptable\n'
                        'G2 I0.5 J0 F3000\n'
                        'G2 I0.5 J0 F3000\n'
                        'G2 I0.5 J0 F3000\n'
                        'G2 I0.5 J0 F3000\n'
                        '\n'
                        'M221 R; pop softend status\n'
                        'G1 Z10 F1200\n'
                        'M400\n'
                        'G1 Z10\n'
                        'G1 F30000\n'
                        'G1 X230 Y15\n'
                        'G29.2 S1 ; turn on ABL\n'
                        ';G28 ; home again after hard wipe mouth\n'
                        'M106 S0 ; turn off fan , too noisy\n'
                        ';===== wipe nozzle end ================================\n'
                        '\n'
                        '\n'
                        ';===== bed leveling ==================================\n'
                        'M1002 judge_flag g29_before_print_flag\n'
                        'M622 J1\n'
                        '\n'
                        '    M1002 gcode_claim_action : 1\n'
                        '    G29 A X{first_layer_print_min[0]} Y{first_layer_print_min[1]} '
                        'I{first_layer_print_size[0]} J{first_layer_print_size[1]}\n'
                        '    M400\n'
                        '    M500 ; save cali data\n'
                        '\n'
                        'M623\n'
                        ';===== bed leveling end ================================\n'
                        '\n'
                        ';===== home after wipe mouth============================\n'
                        'M1002 judge_flag g29_before_print_flag\n'
                        'M622 J0\n'
                        '\n'
                        '    M1002 gcode_claim_action : 13\n'
                        '    G28\n'
                        '\n'
                        'M623\n'
                        ';===== home after wipe mouth end =======================\n'
                        '\n'
                        'M975 S1 ; turn on vibration supression\n'
                        '\n'
                        '\n'
                        ';=============turn on fans to prevent PLA jamming=================\n'
                        '{if filament_type[initial_extruder]=="PLA"}\n'
                        '    {if (bed_temperature[initial_extruder] '
                        '>50)||(bed_temperature_initial_layer[initial_extruder] >50)}\n'
                        '    M106 P3 S255\n'
                        '    {elsif (bed_temperature[initial_extruder] '
                        '>45)||(bed_temperature_initial_layer[initial_extruder] >45)}\n'
                        '    M106 P3 S180\n'
                        '    {endif};Prevent PLA from jamming\n'
                        '{endif}\n'
                        'M106 P2 S100 ; turn on big fan ,to cool down toolhead\n'
                        '\n'
                        '\n'
                        'M104 S{nozzle_temperature_initial_layer[initial_extruder]} ; set extrude temp earlier, to '
                        'reduce wait time\n'
                        '\n'
                        ';===== mech mode fast check============================\n'
                        'G1 X128 Y128 Z10 F20000\n'
                        'M400 P200\n'
                        'M970.3 Q1 A7 B30 C80  H15 K0\n'
                        'M974 Q1 S2 P0\n'
                        '\n'
                        'G1 X128 Y128 Z10 F20000\n'
                        'M400 P200\n'
                        'M970.3 Q0 A7 B30 C90 Q0 H15 K0\n'
                        'M974 Q0 S2 P0\n'
                        '\n'
                        'M975 S1\n'
                        'G1 F30000\n'
                        'G1 X230 Y15\n'
                        'G28 X ; re-home XY\n'
                        ';===== fmech mode fast check============================\n'
                        '\n'
                        '\n'
                        ';===== nozzle load line ===============================\n'
                        'M975 S1\n'
                        'G90\n'
                        'M83\n'
                        'T1000\n'
                        'G1 X18.0 Y0.5 Z0.8 F18000;Move to start position\n'
                        'M109 S{nozzle_temperature_initial_layer[initial_extruder]}\n'
                        'G1 Z0.2\n'
                        'G0 E2 F300\n'
                        'G0 X129 E15 F{outer_wall_volumetric_speed/(0.3*1.0)     * 60}\n'
                        'G0 X240 E15\n'
                        'G0 Y15 E1.500 F{outer_wall_volumetric_speed/(0.3*1.0)/ 4 * 60}\n'
                        'G0 X239.5\n'
                        'G0 E0.3\n'
                        'G0 Y1.5 E1.500\n'
                        'G0 X129 E15 F{outer_wall_volumetric_speed/(0.3*1.0)     * 60}\n'
                        'G0 X18 E15\n'
                        'M400\n'
                        '\n'
                        ';===== for Textured PEI Plate , lower the nozzle as the nozzle was touching topmost of the '
                        'texture when homing ==\n'
                        ';curr_bed_type={curr_bed_type}\n'
                        '{if curr_bed_type=="Textured PEI Plate"}\n'
                        'G29.1 Z{-0.04} ; for Textured PEI Plate\n'
                        '{endif}\n'
                        ';========turn off light and wait extrude temperature =============\n'
                        'M1002 gcode_claim_action : 0\n'
                        'M106 S0 ; turn off fan\n'
                        'M106 P2 S0 ; turn off big fan\n'
                        'M106 P3 S0 ; turn off chamber fan\n'
                        '\n'
                        'M975 S1 ; turn on mech mode supression\n',
 'max_layer_height': ['0.56'],
 'min_layer_height': ['0.16'],
 'name': 'Bambu Lab P1S 0.8 nozzle',
 'nozzle_diameter': ['0.8'],
 'nozzle_type': ['hardened_steel', 'hardened_steel'],
 'printer_model': 'Bambu Lab P1S',
 'printer_variant': '0.8',
 'retract_length_toolchange': ['3', '3'],
 'retraction_length': ['3', '3'],
 'setting_id': 'GM017',
 'type': 'machine',
 'upward_compatible_machine': ['Bambu Lab P1P 0.8 nozzle',
                               'Bambu Lab X1 0.8 nozzle',
                               'Bambu Lab X1 Carbon 0.8 nozzle',
                               'Bambu Lab X1E 0.8 nozzle',
                               'Bambu Lab A1 0.8 nozzle',
                               'Bambu Lab H2D 0.8 nozzle',
                               'Bambu Lab H2D Pro 0.8 nozzle',
                               'Bambu Lab H2S 0.8 nozzle',
                               'Bambu Lab P2S 0.8 nozzle']}
