from __future__ import annotations

# source: profiles/TwoTrees/filament/TwoTrees Generic HS PLA @SK1.json
DATA = {'compatible_printers': ['TwoTrees SK1 0.4 nozzle'],
 'cool_plate_temp': '60',
 'cool_plate_temp_initial_layer': '60',
 'enable_pressure_advance': ['1'],
 'eng_plate_temp': '60',
 'eng_plate_temp_initial_layer': '60',
 'fan_min_speed': '35',
 'filament_flow_ratio': ['0.98'],
 'filament_id': 'GFL100',
 'filament_max_volumetric_speed': ['25'],
 'filament_minimal_purge_on_wipe_tower': '15',
 'from': 'system',
 'full_fan_speed_layer': '0',
 'hot_plate_temp': '60',
 'hot_plate_temp_initial_layer': '60',
 'inherits': 'fdm_filament_pla',
 'instantiation': 'true',
 'name': 'TwoTrees Generic HS PLA @SK1',
 'nozzle_temperature': ['220'],
 'nozzle_temperature_initial_layer': ['220'],
 'nozzle_temperature_range_low': ['210'],
 'pressure_advance': ['0.04'],
 'reduce_fan_stop_start_freq': '0',
 'setting_id': 'GFSL100',
 'slow_down_layer_time': '5',
 'slow_down_min_speed': '50',
 'textured_plate_temp': '60',
 'textured_plate_temp_initial_layer': '60',
 'type': 'filament'}
