from __future__ import annotations

# source: profiles/Elegoo/process/ECC/fdm_process_ecc_02010.json
DATA = {'bottom_shell_layers': '5',
 'bridge_flow': '1',
 'elefant_foot_compensation': '0.05',
 'from': 'system',
 'inherits': 'fdm_process_ecc',
 'initial_layer_infill_speed': '60',
 'initial_layer_line_width': '0.3',
 'initial_layer_print_height': '0.15',
 'initial_layer_speed': '35',
 'inner_wall_line_width': '0.22',
 'inner_wall_speed': '100',
 'instantiation': 'false',
 'internal_solid_infill_line_width': '0.22',
 'internal_solid_infill_speed': '100',
 'layer_height': '0.1',
 'line_width': '0.22',
 'name': 'fdm_process_ecc_02010',
 'outer_wall_line_width': '0.22',
 'outer_wall_speed': '60',
 'sparse_infill_line_width': '0.25',
 'sparse_infill_speed': '100',
 'support_line_width': '0.22',
 'top_shell_layers': '7',
 'top_surface_line_width': '0.22',
 'top_surface_speed': '80',
 'type': 'process',
 'wall_loops': '4'}
