from __future__ import annotations

# source: profiles/Elegoo/process/ECC/fdm_process_ecc_08040.json
DATA = {'bridge_flow': '1',
 'bridge_speed': '30',
 'elefant_foot_compensation': '0.15',
 'from': 'system',
 'inherits': 'fdm_process_ecc',
 'initial_layer_infill_speed': '55',
 'initial_layer_line_width': '0.82',
 'initial_layer_print_height': '0.4',
 'initial_layer_speed': '35',
 'inner_wall_line_width': '0.82',
 'instantiation': 'false',
 'internal_solid_infill_line_width': '0.82',
 'layer_height': '0.4',
 'line_width': '0.82',
 'name': 'fdm_process_ecc_08040',
 'outer_wall_line_width': '0.82',
 'overhang_2_4_speed': '40',
 'overhang_3_4_speed': '20',
 'overhang_4_4_speed': '10',
 'sparse_infill_line_width': '0.82',
 'sparse_infill_speed': '100',
 'support_line_width': '0.82',
 'top_surface_line_width': '0.82',
 'top_surface_speed': '150',
 'type': 'process'}
