from __future__ import annotations

# source: profiles/OrcaFilamentLibrary/filament/COEX/COEX PETG @base.json
DATA = {'bed_temperature': ['80'],
 'bed_temperature_initial_layer': ['85'],
 'compatible_printers': [],
 'compatible_printers_condition': '',
 'compatible_prints': [],
 'compatible_prints_condition': '',
 'disable_fan_first_layers': ['2'],
 'enable_pressure_advance': ['1'],
 'fan_max_speed': ['50'],
 'fan_min_speed': ['30'],
 'filament_cost': ['33.00'],
 'filament_density': ['1.27'],
 'filament_deretraction_speed': ['30'],
 'filament_id': 'CXPETB13',
 'filament_max_volumetric_speed': ['12'],
 'filament_notes': 'IMPORTANT: Set travel speed to maximum your machine allows (200-500mm/s) to reduce stringing',
 'filament_retract_before_wipe': ['70%'],
 'filament_retract_layer_change': ['1'],
 'filament_retract_when_changing_layer': ['1'],
 'filament_retraction_length': ['4'],
 'filament_retraction_minimum_travel': ['2'],
 'filament_retraction_speed': ['30'],
 'filament_type': ['PETG'],
 'filament_vendor': ['COEX 3D'],
 'filament_wipe': ['1'],
 'filament_wipe_distance': ['2'],
 'filament_z_hop': ['0.4'],
 'from': 'system',
 'full_fan_speed_layer': ['4'],
 'inherits': 'fdm_filament_pet',
 'instantiation': 'false',
 'name': 'COEX PETG @base',
 'nozzle_temperature': ['245'],
 'nozzle_temperature_initial_layer': ['250'],
 'pressure_advance': ['0.045'],
 'slow_down_layer_time': ['5'],
 'slow_down_min_speed': ['10'],
 'temperature_vitrification': ['70'],
 'type': 'filament'}
