from __future__ import annotations

# source: profiles/OrcaFilamentLibrary/filament/COEX/COEX PLA @base.json
DATA = {'bed_temperature': ['60'],
 'bed_temperature_initial_layer': ['60'],
 'compatible_printers': [],
 'compatible_printers_condition': '',
 'compatible_prints': [],
 'compatible_prints_condition': '',
 'disable_fan_first_layers': ['1'],
 'fan_max_speed': ['100'],
 'fan_min_speed': ['100'],
 'filament_cost': ['24.00'],
 'filament_density': ['1.24'],
 'filament_deretraction_speed': ['40'],
 'filament_id': 'CXPLAB02',
 'filament_max_volumetric_speed': ['18'],
 'filament_retract_before_wipe': ['70%'],
 'filament_retract_layer_change': ['1'],
 'filament_retract_when_changing_layer': ['1'],
 'filament_retraction_length': ['1.5'],
 'filament_retraction_minimum_travel': ['2'],
 'filament_retraction_speed': ['45'],
 'filament_type': ['PLA'],
 'filament_vendor': ['COEX 3D'],
 'filament_wipe': ['1'],
 'filament_wipe_distance': ['2'],
 'from': 'system',
 'full_fan_speed_layer': ['3'],
 'inherits': 'fdm_filament_pla',
 'instantiation': 'false',
 'name': 'COEX PLA @base',
 'nozzle_temperature': ['230'],
 'nozzle_temperature_initial_layer': ['235'],
 'slow_down_layer_time': ['5'],
 'slow_down_min_speed': ['10'],
 'temperature_vitrification': ['55'],
 'type': 'filament'}
