from __future__ import annotations

# source: profiles/OrcaFilamentLibrary/filament/COEX/COEX TPE 30D @base.json
DATA = {'bed_temperature': ['30'],
 'bed_temperature_initial_layer': ['35'],
 'compatible_printers': [],
 'compatible_printers_condition': '',
 'compatible_prints': [],
 'compatible_prints_condition': '',
 'disable_fan_first_layers': ['1'],
 'enable_pressure_advance': ['0'],
 'fan_max_speed': ['100'],
 'fan_min_speed': ['80'],
 'filament_cost': ['80.00'],
 'filament_density': ['1.15'],
 'filament_deretraction_speed': ['20'],
 'filament_id': 'CX30DB20',
 'filament_max_volumetric_speed': ['3.5'],
 'filament_notes': 'Flexible filament - print slowly with minimal retraction',
 'filament_retract_before_wipe': ['0%'],
 'filament_retract_layer_change': ['0'],
 'filament_retract_when_changing_layer': ['0'],
 'filament_retraction_length': ['0.4'],
 'filament_retraction_minimum_travel': ['3'],
 'filament_retraction_speed': ['20'],
 'filament_type': ['TPU'],
 'filament_vendor': ['COEX 3D'],
 'filament_wipe': ['0'],
 'filament_wipe_distance': ['0'],
 'from': 'system',
 'full_fan_speed_layer': ['2'],
 'inherits': 'fdm_filament_tpu',
 'instantiation': 'false',
 'name': 'COEX TPE 30D @base',
 'nozzle_temperature': ['240'],
 'nozzle_temperature_initial_layer': ['240'],
 'slow_down_layer_time': ['10'],
 'slow_down_min_speed': ['5'],
 'temperature_vitrification': ['60'],
 'type': 'filament'}
