from __future__ import annotations

# source: profiles/OrcaFilamentLibrary/filament/COEX/COEX NYLEX UNFILLED @base.json
DATA = {'bed_temperature': ['100'],
 'bed_temperature_initial_layer': ['100'],
 'chamber_temperature': ['0'],
 'compatible_printers': [],
 'compatible_printers_condition': '',
 'compatible_prints': [],
 'compatible_prints_condition': '',
 'disable_fan_first_layers': ['4'],
 'enable_pressure_advance': ['1'],
 'fan_max_speed': ['30'],
 'fan_min_speed': ['0'],
 'filament_cost': ['85.00'],
 'filament_density': ['1.08'],
 'filament_deretraction_speed': ['40'],
 'filament_id': 'CXPAUB21',
 'filament_max_volumetric_speed': ['11'],
 'filament_retract_before_wipe': ['70%'],
 'filament_retract_layer_change': ['1'],
 'filament_retract_when_changing_layer': ['1'],
 'filament_retraction_length': ['2.5'],
 'filament_retraction_minimum_travel': ['2'],
 'filament_retraction_speed': ['40'],
 'filament_type': ['PA'],
 'filament_vendor': ['COEX 3D'],
 'filament_wipe': ['1'],
 'filament_wipe_distance': ['2'],
 'from': 'system',
 'full_fan_speed_layer': ['0'],
 'inherits': 'fdm_filament_pa',
 'instantiation': 'false',
 'name': 'COEX NYLEX UNFILLED @base',
 'nozzle_temperature': ['260'],
 'nozzle_temperature_initial_layer': ['260'],
 'pressure_advance': ['0.02'],
 'slow_down_layer_time': ['5'],
 'slow_down_min_speed': ['10'],
 'temperature_vitrification': ['100'],
 'type': 'filament'}
