from __future__ import annotations

# source: profiles/Elegoo/filament/fdm_filament_abs.json
DATA = {'close_fan_the_first_x_layers': ['3'],
 'cool_plate_temp': ['100'],
 'cool_plate_temp_initial_layer': ['100'],
 'eng_plate_temp': ['100'],
 'eng_plate_temp_initial_layer': ['100'],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['0'],
 'fan_min_speed': ['0'],
 'filament_cost': ['20'],
 'filament_density': ['1.04'],
 'filament_max_volumetric_speed': ['11'],
 'filament_type': ['ABS'],
 'from': 'system',
 'hot_plate_temp': ['100'],
 'hot_plate_temp_initial_layer': ['100'],
 'inherits': 'fdm_filament_common',
 'instantiation': 'false',
 'name': 'fdm_filament_abs',
 'nozzle_temperature': ['245'],
 'nozzle_temperature_initial_layer': ['180'],
 'nozzle_temperature_range_high': ['245'],
 'nozzle_temperature_range_low': ['240'],
 'overhang_fan_speed': ['30'],
 'overhang_fan_threshold': ['25%'],
 'reduce_fan_stop_start_freq': ['1'],
 'slow_down_for_layer_cooling': ['1'],
 'slow_down_layer_time': ['3'],
 'slow_down_min_speed': ['10'],
 'temperature_vitrification': ['110'],
 'textured_plate_temp': ['100'],
 'textured_plate_temp_initial_layer': ['100'],
 'type': 'filament'}
