from __future__ import annotations

# source: profiles/Elegoo/filament/Generic PLA @Elegoo.json
DATA = {'compatible_printers': ['Elegoo Neptune 0.4 nozzle',
                         'Elegoo Neptune X 0.4 nozzle',
                         'Elegoo Neptune 2 0.4 nozzle',
                         'Elegoo Neptune 2S 0.4 nozzle',
                         'Elegoo Neptune 2D 0.4 nozzle',
                         'Elegoo Neptune 3 0.4 nozzle',
                         'Elegoo Neptune 3 Pro 0.4 nozzle',
                         'Elegoo Neptune 3 Plus 0.4 nozzle',
                         'Elegoo Neptune 3 Max 0.4 nozzle',
                         'Elegoo Neptune 4 (0.2 nozzle)',
                         'Elegoo Neptune 4 (0.4 nozzle)',
                         'Elegoo Neptune 4 (0.6 nozzle)',
                         'Elegoo Neptune 4 (0.8 nozzle)',
                         'Elegoo Neptune 4 Max (0.2 nozzle)',
                         'Elegoo Neptune 4 Max (0.4 nozzle)',
                         'Elegoo Neptune 4 Max (0.6 nozzle)',
                         'Elegoo Neptune 4 Max (0.8 nozzle)',
                         'Elegoo Neptune 4 Plus (0.2 nozzle)',
                         'Elegoo Neptune 4 Plus (0.4 nozzle)',
                         'Elegoo Neptune 4 Plus (0.6 nozzle)',
                         'Elegoo Neptune 4 Plus (0.8 nozzle)',
                         'Elegoo Neptune 4 Pro (0.2 nozzle)',
                         'Elegoo Neptune 4 Pro (0.4 nozzle)',
                         'Elegoo Neptune 4 Pro (0.6 nozzle)',
                         'Elegoo Neptune 4 Pro (0.8 nozzle)'],
 'filament_flow_ratio': ['0.98'],
 'filament_id': 'GFL99',
 'filament_max_volumetric_speed': ['15'],
 'from': 'system',
 'inherits': 'fdm_filament_pla',
 'instantiation': 'true',
 'name': 'Generic PLA @Elegoo',
 'nozzle_temperature_initial_layer': ['210'],
 'setting_id': 'GFSL99',
 'slow_down_layer_time': ['8'],
 'type': 'filament'}
