from __future__ import annotations

# source: profiles/Elegoo/filament/Generic PETG PRO @Elegoo.json
DATA = {'compatible_printers': ['Elegoo Neptune 0.4 nozzle',
                         'Elegoo Neptune X 0.4 nozzle',
                         'Elegoo Neptune 2 0.4 nozzle',
                         'Elegoo Neptune 2S 0.4 nozzle',
                         'Elegoo Neptune 2D 0.4 nozzle',
                         'Elegoo Neptune 3 0.4 nozzle',
                         'Elegoo Neptune 3 Pro 0.4 nozzle',
                         'Elegoo Neptune 3 Plus 0.4 nozzle',
                         'Elegoo Neptune 3 Max 0.4 nozzle',
                         'Elegoo Neptune 4 (0.2 nozzle)',
                         'Elegoo Neptune 4 (0.4 nozzle)',
                         'Elegoo Neptune 4 (0.6 nozzle)',
                         'Elegoo Neptune 4 (0.8 nozzle)',
                         'Elegoo Neptune 4 Max (0.2 nozzle)',
                         'Elegoo Neptune 4 Max (0.4 nozzle)',
                         'Elegoo Neptune 4 Max (0.6 nozzle)',
                         'Elegoo Neptune 4 Max (0.8 nozzle)',
                         'Elegoo Neptune 4 Plus (0.2 nozzle)',
                         'Elegoo Neptune 4 Plus (0.4 nozzle)',
                         'Elegoo Neptune 4 Plus (0.6 nozzle)',
                         'Elegoo Neptune 4 Plus (0.8 nozzle)',
                         'Elegoo Neptune 4 Pro (0.2 nozzle)',
                         'Elegoo Neptune 4 Pro (0.4 nozzle)',
                         'Elegoo Neptune 4 Pro (0.6 nozzle)',
                         'Elegoo Neptune 4 Pro (0.8 nozzle)'],
 'cool_plate_temp': ['0'],
 'cool_plate_temp_initial_layer': ['0'],
 'eng_plate_temp': ['70'],
 'eng_plate_temp_initial_layer': ['70'],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['40'],
 'fan_min_speed': ['10'],
 'filament_cost': ['0'],
 'filament_density': ['1.25'],
 'filament_end_gcode': ['; filament end gcode \n'],
 'filament_id': 'GFG99',
 'filament_max_volumetric_speed': ['8'],
 'filament_start_gcode': ['; Filament start gcode\n'],
 'filament_vendor': ['Elegoo'],
 'from': 'system',
 'hot_plate_temp': ['70'],
 'hot_plate_temp_initial_layer': ['70'],
 'inherits': 'fdm_filament_pet',
 'instantiation': 'true',
 'name': 'Generic PETG PRO @Elegoo',
 'nozzle_temperature': ['240'],
 'nozzle_temperature_initial_layer': ['240'],
 'nozzle_temperature_range_high': ['270'],
 'nozzle_temperature_range_low': ['230'],
 'overhang_fan_speed': ['90'],
 'overhang_fan_threshold': ['10%'],
 'setting_id': 'GFSG99',
 'slow_down_layer_time': ['12'],
 'textured_plate_temp': ['70'],
 'textured_plate_temp_initial_layer': ['70'],
 'type': 'filament'}
