from __future__ import annotations

# source: profiles/Cubicon/filament/Cubicon PLA @base.json
DATA = {'additional_cooling_fan_speed': ['80'],
 'compatible_printers': ['Cubicon xCeler-I 0.4 nozzle', 'Cubicon xCeler-Plus 0.4 nozzle'],
 'default_filament_colour': '',
 'fan_max_speed': ['80'],
 'fan_min_speed': ['100'],
 'filament_flow_ratio': ['0.99'],
 'filament_id': 'P510cfa0',
 'filament_max_volumetric_speed': ['23'],
 'filament_settings_id': ['CBC_MTC_0'],
 'filament_type': ['PLA'],
 'filament_vendor': ['Cubicon'],
 'from': 'system',
 'hot_plate_temp': ['60'],
 'hot_plate_temp_initial_layer': ['60'],
 'inherits': 'fdm_filament_pla',
 'instantiation': 'true',
 'is_custom_defined': '0',
 'name': 'Cubicon PLA @base',
 'nozzle_temperature': ['210'],
 'nozzle_temperature_initial_layer': ['205'],
 'nozzle_temperature_range_high': ['230'],
 'nozzle_temperature_range_low': ['190'],
 'slow_down_layer_time': ['3'],
 'slow_down_min_speed': ['50'],
 'temperature_vitrification': ['60'],
 'type': 'filament',
 'version': '1.0.0.0'}
