from __future__ import annotations

# source: profiles/Cubicon/filament/Cubicon ABSk @base.json
DATA = {'additional_cooling_fan_speed': ['0'],
 'close_fan_the_first_x_layers': ['3'],
 'compatible_printers': ['Cubicon xCeler-I 0.4 nozzle', 'Cubicon xCeler-Plus 0.4 nozzle'],
 'default_filament_colour': '',
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['80'],
 'fan_min_speed': ['70'],
 'filament_density': ['1.24'],
 'filament_flow_ratio': ['0.99'],
 'filament_id': 'P510cfb2',
 'filament_max_volumetric_speed': ['23'],
 'filament_settings_id': ['Cubicon ABSk @base'],
 'filament_type': ['ABS'],
 'filament_vendor': ['Cubicon'],
 'hot_plate_temp': ['115'],
 'hot_plate_temp_initial_layer': ['115'],
 'inherits': 'Cubicon ABS @base',
 'instantiation': 'true',
 'is_custom_defined': '0',
 'name': 'Cubicon ABSk @base',
 'nozzle_temperature': ['240'],
 'nozzle_temperature_initial_layer': ['240'],
 'nozzle_temperature_range_high': ['240'],
 'nozzle_temperature_range_low': ['220'],
 'slow_down_layer_time': ['3'],
 'slow_down_min_speed': ['30'],
 'temperature_vitrification': ['85'],
 'type': 'filament',
 'version': '1.0.0.0'}
