from __future__ import annotations

# source: profiles/Cubicon/filament/Cubicon PA-CF @base.json
DATA = {'additional_cooling_fan_speed': ['0'],
 'close_fan_the_first_x_layers': ['3'],
 'compatible_printers': ['Cubicon xCeler-I 0.4 nozzle', 'Cubicon xCeler-Plus 0.4 nozzle'],
 'default_filament_colour': '',
 'fan_cooling_layer_time': ['5'],
 'fan_max_speed': ['50'],
 'fan_min_speed': ['50'],
 'filament_density': ['1.24'],
 'filament_flow_ratio': ['0.99'],
 'filament_id': 'P510cfd0',
 'filament_max_volumetric_speed': ['10'],
 'filament_settings_id': ['Cubicon PA-CF @base'],
 'filament_type': ['PA'],
 'filament_vendor': ['Cubicon'],
 'hot_plate_temp': ['100'],
 'hot_plate_temp_initial_layer': ['100'],
 'inherits': 'fdm_filament_pa',
 'instantiation': 'true',
 'is_custom_defined': '0',
 'name': 'Cubicon PA-CF @base',
 'nozzle_temperature': ['270'],
 'nozzle_temperature_initial_layer': ['265'],
 'nozzle_temperature_range_high': ['280'],
 'nozzle_temperature_range_low': ['260'],
 'slow_down_layer_time': ['2'],
 'slow_down_min_speed': ['20'],
 'temperature_vitrification': ['108'],
 'type': 'filament',
 'version': '1.0.0.0'}
