from __future__ import annotations

# source: profiles/Cubicon/filament/fdm_filament_pc.json
DATA = {'cool_plate_temp': ['0'],
 'cool_plate_temp_initial_layer': ['0'],
 'eng_plate_temp': ['110'],
 'eng_plate_temp_initial_layer': ['110'],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['60'],
 'fan_min_speed': ['10'],
 'filament_cost': ['20'],
 'filament_density': ['1.04'],
 'filament_flow_ratio': ['0.94'],
 'filament_id': 'OGFC99',
 'filament_max_volumetric_speed': ['12'],
 'filament_type': ['PC'],
 'from': 'system',
 'hot_plate_temp': ['110'],
 'hot_plate_temp_initial_layer': ['110'],
 'inherits': 'fdm_filament_common',
 'instantiation': 'false',
 'name': 'fdm_filament_pc',
 'nozzle_temperature': ['280'],
 'nozzle_temperature_initial_layer': ['270'],
 'nozzle_temperature_range_high': ['290'],
 'nozzle_temperature_range_low': ['260'],
 'overhang_fan_speed': ['60'],
 'overhang_fan_threshold': ['25%'],
 'reduce_fan_stop_start_freq': ['1'],
 'slow_down_layer_time': ['2'],
 'slow_down_min_speed': ['10'],
 'supertack_plate_temp': ['0'],
 'supertack_plate_temp_initial_layer': ['0'],
 'temperature_vitrification': ['120'],
 'textured_plate_temp': ['110'],
 'textured_plate_temp_initial_layer': ['110'],
 'type': 'filament'}
