from __future__ import annotations

# source: profiles/Z-Bolt/filament/Z-Bolt PETG.json
DATA = {'compatible_printers': ['Z-Bolt S300 0.4 nozzle',
                         'Z-Bolt S300 0.6 nozzle',
                         'Z-Bolt S300 0.8 nozzle',
                         'Z-Bolt S300 Dual 0.4 nozzle',
                         'Z-Bolt S300 Dual 0.6 nozzle',
                         'Z-Bolt S300 Dual 0.8 nozzle',
                         'Z-Bolt S400 0.4 nozzle',
                         'Z-Bolt S400 0.6 nozzle',
                         'Z-Bolt S400 0.8 nozzle',
                         'Z-Bolt S400 Dual 0.4 nozzle',
                         'Z-Bolt S400 Dual 0.6 nozzle',
                         'Z-Bolt S400 Dual 0.8 nozzle',
                         'Z-Bolt S600 0.4 nozzle',
                         'Z-Bolt S600 0.6 nozzle',
                         'Z-Bolt S600 0.8 nozzle',
                         'Z-Bolt S600 Dual 0.4 nozzle',
                         'Z-Bolt S600 Dual 0.6 nozzle',
                         'Z-Bolt S600 Dual 0.8 nozzle',
                         'Z-Bolt S800 Dual 0.4 nozzle',
                         'Z-Bolt S800 Dual 0.6 nozzle',
                         'Z-Bolt S800 Dual 0.8 nozzle',
                         'Z-Bolt S1000 0.4 nozzle',
                         'Z-Bolt S1000 0.6 nozzle',
                         'Z-Bolt S1000 0.8 nozzle',
                         'Z-Bolt S1000 Dual 0.4 nozzle',
                         'Z-Bolt S1000 Dual 0.6 nozzle',
                         'Z-Bolt S1000 Dual 0.8 nozzle'],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['90'],
 'fan_min_speed': ['45'],
 'filament_flow_ratio': ['0.95'],
 'filament_id': 'GFL102',
 'filament_max_volumetric_speed': ['12'],
 'from': 'system',
 'full_fan_speed_layer': ['3'],
 'hot_plate_temp': ['75'],
 'hot_plate_temp_initial_layer': ['75'],
 'inherits': 'fdm_filament_pet',
 'instantiation': 'true',
 'name': 'Z-Bolt PETG',
 'nozzle_temperature': ['235'],
 'nozzle_temperature_initial_layer': ['235'],
 'overhang_fan_speed': ['90'],
 'overhang_fan_threshold': ['10%'],
 'setting_id': 'GFSL102',
 'slow_down_layer_time': ['12'],
 'slow_down_min_speed': ['20'],
 'textured_plate_temp': ['75'],
 'textured_plate_temp_initial_layer': ['75'],
 'type': 'filament'}
