from __future__ import annotations

# source: profiles/Z-Bolt/filament/Z-Bolt PA.json
DATA = {'chamber_temperatures': ['80'],
 'compatible_printers': ['Z-Bolt S300 0.4 nozzle',
                         'Z-Bolt S300 0.6 nozzle',
                         'Z-Bolt S300 0.8 nozzle',
                         'Z-Bolt S300 Dual 0.4 nozzle',
                         'Z-Bolt S300 Dual 0.6 nozzle',
                         'Z-Bolt S300 Dual 0.8 nozzle',
                         'Z-Bolt S400 0.4 nozzle',
                         'Z-Bolt S400 0.6 nozzle',
                         'Z-Bolt S400 0.8 nozzle',
                         'Z-Bolt S400 Dual 0.4 nozzle',
                         'Z-Bolt S400 Dual 0.6 nozzle',
                         'Z-Bolt S400 Dual 0.8 nozzle',
                         'Z-Bolt S600 0.4 nozzle',
                         'Z-Bolt S600 0.6 nozzle',
                         'Z-Bolt S600 0.8 nozzle',
                         'Z-Bolt S600 Dual 0.4 nozzle',
                         'Z-Bolt S600 Dual 0.6 nozzle',
                         'Z-Bolt S600 Dual 0.8 nozzle',
                         'Z-Bolt S800 Dual 0.4 nozzle',
                         'Z-Bolt S800 Dual 0.6 nozzle',
                         'Z-Bolt S800 Dual 0.8 nozzle',
                         'Z-Bolt S1000 0.4 nozzle',
                         'Z-Bolt S1000 0.6 nozzle',
                         'Z-Bolt S1000 0.8 nozzle',
                         'Z-Bolt S1000 Dual 0.4 nozzle',
                         'Z-Bolt S1000 Dual 0.6 nozzle',
                         'Z-Bolt S1000 Dual 0.8 nozzle'],
 'fan_cooling_layer_time': ['5'],
 'fan_max_speed': ['30'],
 'fan_min_speed': ['10'],
 'filament_flow_ratio': ['0.96'],
 'filament_id': 'GFL103',
 'filament_max_volumetric_speed': ['10'],
 'from': 'system',
 'hot_plate_temp': ['140'],
 'hot_plate_temp_initial_layer': ['140'],
 'inherits': 'fdm_filament_pa',
 'instantiation': 'true',
 'name': 'Z-Bolt PA',
 'nozzle_temperature': ['265'],
 'nozzle_temperature_initial_layer': ['265'],
 'overhang_fan_speed': ['30'],
 'overhang_fan_threshold': ['0%'],
 'setting_id': 'GFSL103',
 'textured_plate_temp': ['130'],
 'textured_plate_temp_initial_layer': ['140'],
 'type': 'filament'}
