from __future__ import annotations

# source: profiles/Z-Bolt/filament/Z-Bolt ABS.json
DATA = {'compatible_printers': ['Z-Bolt S300 0.4 nozzle',
                         'Z-Bolt S300 0.6 nozzle',
                         'Z-Bolt S300 0.8 nozzle',
                         'Z-Bolt S300 Dual 0.4 nozzle',
                         'Z-Bolt S300 Dual 0.6 nozzle',
                         'Z-Bolt S300 Dual 0.8 nozzle',
                         'Z-Bolt S400 0.4 nozzle',
                         'Z-Bolt S400 0.6 nozzle',
                         'Z-Bolt S400 0.8 nozzle',
                         'Z-Bolt S400 Dual 0.4 nozzle',
                         'Z-Bolt S400 Dual 0.6 nozzle',
                         'Z-Bolt S400 Dual 0.8 nozzle',
                         'Z-Bolt S600 0.4 nozzle',
                         'Z-Bolt S600 0.6 nozzle',
                         'Z-Bolt S600 0.8 nozzle',
                         'Z-Bolt S600 Dual 0.4 nozzle',
                         'Z-Bolt S600 Dual 0.6 nozzle',
                         'Z-Bolt S600 Dual 0.8 nozzle',
                         'Z-Bolt S800 Dual 0.4 nozzle',
                         'Z-Bolt S800 Dual 0.6 nozzle',
                         'Z-Bolt S800 Dual 0.8 nozzle',
                         'Z-Bolt S1000 0.4 nozzle',
                         'Z-Bolt S1000 0.6 nozzle',
                         'Z-Bolt S1000 0.8 nozzle',
                         'Z-Bolt S1000 Dual 0.4 nozzle',
                         'Z-Bolt S1000 Dual 0.6 nozzle',
                         'Z-Bolt S1000 Dual 0.8 nozzle'],
 'fan_min_speed': ['25'],
 'filament_id': 'GFL101',
 'filament_max_volumetric_speed': ['15'],
 'from': 'system',
 'hot_plate_temp': ['110'],
 'hot_plate_temp_initial_layer': ['110'],
 'inherits': 'fdm_filament_abs',
 'instantiation': 'true',
 'name': 'Z-Bolt ABS',
 'nozzle_temperature': ['250'],
 'nozzle_temperature_initial_layer': ['250'],
 'setting_id': 'GFSL101',
 'textured_plate_temp': ['110'],
 'textured_plate_temp_initial_layer': ['110'],
 'type': 'filament'}
