from __future__ import annotations

# source: profiles/Folgertech/machine/fdm_folgertech_common.json
DATA = {'auxiliary_fan': '0',
 'bed_exclude_area': ['0x0'],
 'change_filament_gcode': '',
 'default_filament_profile': ['Generic PLA @System'],
 'default_print_profile': '0.20mm Standard @FT 0.4 Nozzle',
 'deretraction_speed': ['40'],
 'extruder_clearance_height_to_lid': '34',
 'extruder_clearance_height_to_rod': '34',
 'extruder_clearance_radius': '47',
 'from': 'system',
 'gcode_flavor': 'marlin',
 'inherits': 'fdm_machine_common',
 'instantiation': 'false',
 'layer_change_gcode': '',
 'machine_end_gcode': 'M140 S0 ; turn off heatbed\n'
                      'M104 S0 ; turn off temperature\n'
                      'M107 ; turn off fan\n'
                      'G28 X Y ; Home X and Y axis\n'
                      'M84 X Y E ; disable motors',
 'machine_max_acceleration_e': ['5000', '5000'],
 'machine_max_acceleration_extruding': ['500', '500'],
 'machine_max_acceleration_retracting': ['1000', '1000'],
 'machine_max_acceleration_travel': ['500', '500'],
 'machine_max_acceleration_x': ['3000', '3000'],
 'machine_max_acceleration_y': ['3000', '3000'],
 'machine_max_acceleration_z': ['100', '100'],
 'machine_max_jerk_e': ['5', '5'],
 'machine_max_jerk_x': ['8', '8'],
 'machine_max_jerk_y': ['8', '8'],
 'machine_max_jerk_z': ['0.4', '0.4'],
 'machine_max_speed_e': ['60', '60'],
 'machine_max_speed_x': ['500', '500'],
 'machine_max_speed_y': ['500', '500'],
 'machine_max_speed_z': ['10', '10'],
 'machine_min_extruding_rate': ['0', '0'],
 'machine_min_travel_rate': ['0', '0'],
 'machine_pause_gcode': 'M25 ;pause print',
 'machine_start_gcode': 'G28 ; Home all axis\n'
                        'G1 X0 Y5 Z0.2 F3000 ; Get ready to prime\n'
                        'G92 E0 ; Reset extrusion distance\n'
                        'G1 X250 E20 F600 ; Prime nozzle',
 'max_layer_height': ['0.32'],
 'min_layer_height': ['0.08'],
 'name': 'fdm_folgertech_common',
 'nozzle_type': 'undefine',
 'printer_settings_id': '',
 'printer_technology': 'FFF',
 'printer_variant': '0.4',
 'retract_before_wipe': ['70%'],
 'retract_length_toolchange': ['2'],
 'retract_restart_extra': ['0'],
 'retract_restart_extra_toolchange': ['0'],
 'retract_when_changing_layer': ['1'],
 'retraction_length': ['5'],
 'retraction_minimum_travel': ['2'],
 'retraction_speed': ['60'],
 'scan_first_layer': '0',
 'silent_mode': '0',
 'single_extruder_multi_material': '1',
 'type': 'machine',
 'wipe': ['1'],
 'z_hop': ['0.4']}
