from __future__ import annotations

# source: profiles/Flashforge/filament/SUNLU/SUNLU PLA+ @base.json
DATA = {'enable_pressure_advance': ['1'],
 'filament_cost': ['18.99'],
 'filament_density': ['1.23'],
 'filament_flow_ratio': ['1.02'],
 'filament_id': 'GFSNL03',
 'filament_max_volumetric_speed': ['12'],
 'filament_scarf_gap': ['0%'],
 'filament_scarf_height': ['5%'],
 'filament_scarf_length': ['10'],
 'filament_scarf_seam_type': ['none'],
 'filament_start_gcode': [';filament start gcode\n;right_extruder_material: PLA\n'],
 'filament_vendor': ['SUNLU'],
 'from': 'system',
 'inherits': 'fdm_filament_pla',
 'instantiation': 'false',
 'name': 'SUNLU PLA+ @base',
 'nozzle_temperature': ['220'],
 'nozzle_temperature_initial_layer': ['220'],
 'nozzle_temperature_range_high': ['240'],
 'nozzle_temperature_range_low': ['190'],
 'pressure_advance': ['0.03'],
 'temperature_vitrification': ['54'],
 'type': 'filament'}
