from __future__ import annotations

# source: profiles/Volumic/machine/SH65 IDRE (0.4 nozzle).json
DATA = {'auxiliary_fan': '0',
 'before_layer_change_gcode': 'G92 E0',
 'change_filament_gcode': '',
 'default_print_profile': 'Performance 150 - 0.15mm',
 'deretraction_speed': ['30'],
 'extruders_count': ['2'],
 'from': 'system',
 'gcode_flavor': 'klipper',
 'host_type': 'octoprint',
 'inherits': 'fdm_volumic_common',
 'instantiation': 'true',
 'layer_change_gcode': 'TIMELAPSE_TAKE_FRAME',
 'machine_end_gcode': 'END_PRINT',
 'machine_max_acceleration_x': ['4500'],
 'machine_max_acceleration_y': ['4500'],
 'machine_max_acceleration_z': ['50'],
 'machine_start_gcode': 'START_PRINT BED=[first_layer_bed_temperature] EXTRUDER={first_layer_temperature[0]} '
                        'EXTRUDER1={first_layer_temperature[1]}',
 'max_layer_height': ['0.3'],
 'min_layer_height': ['0.025'],
 'name': 'SH65 IDRE (0.4 nozzle)',
 'nozzle_diameter': ['0.4', '0.4'],
 'nozzle_type': 'undefine',
 'print_host': '192.168.0.60',
 'printable_area': ['11x0', '613x0', '613x300', '11x300'],
 'printable_height': '280',
 'printer_model': 'SH65 IDRE',
 'printer_variant': '0.4',
 'retraction_length': ['2.4'],
 'retraction_minimum_travel': ['1'],
 'retraction_speed': ['30'],
 'setting_id': 'GM001',
 'single_extruder_multi_material': ['0'],
 'type': 'machine'}
