from __future__ import annotations

# source: profiles/Volumic/machine/VS30SC2 Stage 2 (0.4 nozzle).json
DATA = {'auxiliary_fan': '0',
 'before_layer_change_gcode': 'G92 E0',
 'default_print_profile': 'Normal speed (Stage 2) - 0.20mm',
 'deretraction_speed': ['30'],
 'from': 'system',
 'gcode_flavor': 'klipper',
 'host_type': 'octoprint',
 'inherits': 'fdm_volumic_common',
 'instantiation': 'true',
 'machine_end_gcode': 'END_PRINT',
 'machine_max_acceleration_x': ['4000'],
 'machine_max_acceleration_y': ['4000'],
 'machine_max_acceleration_z': ['50'],
 'machine_start_gcode': 'START_PRINT BED=[first_layer_bed_temperature] EXTRUDER=[first_layer_temperature]',
 'max_layer_height': ['0.3'],
 'min_layer_height': ['0.025'],
 'name': 'VS30SC2 Stage 2 (0.4 nozzle)',
 'nozzle_diameter': ['0.4'],
 'nozzle_type': 'undefine',
 'print_host': '192.168.0.60',
 'printable_area': ['0x0', '300x0', '300x200', '0x200'],
 'printable_height': '310',
 'printer_model': 'VS30SC2 Stage 2',
 'printer_variant': '0.4',
 'retraction_length': ['2.4'],
 'retraction_minimum_travel': ['1'],
 'retraction_speed': ['30'],
 'setting_id': 'GM001',
 'type': 'machine'}
