from __future__ import annotations

# source: profiles/Snapmaker/filament/fdm_filament_petg.json
DATA = {'default_filament_colour': [''],
 'enable_pressure_advance': ['1'],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['90'],
 'fan_min_speed': ['40'],
 'filament_cost': ['30'],
 'filament_density': ['1.27'],
 'filament_flow_ratio': ['0.95'],
 'filament_max_volumetric_speed': ['10'],
 'filament_retraction_length': ['1.8'],
 'filament_retraction_minimum_travel': ['0'],
 'filament_type': ['PETG'],
 'from': 'system',
 'hot_plate_temp': ['70'],
 'hot_plate_temp_initial_layer': ['70'],
 'inherits': 'fdm_filament_common',
 'instantiation': 'false',
 'name': 'fdm_filament_petg',
 'nozzle_temperature': ['245'],
 'nozzle_temperature_initial_layer': ['255'],
 'nozzle_temperature_range_high': ['270'],
 'nozzle_temperature_range_low': ['220'],
 'overhang_fan_speed': ['90'],
 'overhang_fan_threshold': ['25%'],
 'pressure_advance': ['0.03'],
 'reduce_fan_stop_start_freq': ['1'],
 'slow_down_min_speed': ['20'],
 'temperature_vitrification': ['160'],
 'type': 'filament'}
