from __future__ import annotations

# source: profiles/Snapmaker/filament/fdm_filament_pa.json
DATA = {'close_fan_the_first_x_layers': ['3'],
 'default_filament_colour': [''],
 'fan_cooling_layer_time': ['20'],
 'fan_max_speed': ['65'],
 'fan_min_speed': ['30'],
 'filament_cost': ['150'],
 'filament_density': ['1.09'],
 'filament_max_volumetric_speed': ['8'],
 'filament_notes': ['!! It needs to be dried before use.\n'],
 'filament_retraction_length': ['2'],
 'filament_retraction_minimum_travel': ['0'],
 'filament_retraction_speed': ['36'],
 'filament_type': ['PA-CF'],
 'from': 'system',
 'full_fan_speed_layer': ['3'],
 'hot_plate_temp': ['95'],
 'hot_plate_temp_initial_layer': ['90'],
 'inherits': 'fdm_filament_common',
 'instantiation': 'false',
 'name': 'fdm_filament_pa',
 'nozzle_temperature': ['250'],
 'nozzle_temperature_initial_layer': ['255'],
 'nozzle_temperature_range_high': ['260'],
 'nozzle_temperature_range_low': ['250'],
 'overhang_fan_speed': ['60'],
 'overhang_fan_threshold': ['0%'],
 'reduce_fan_stop_start_freq': ['1'],
 'required_nozzle_HRC': ['40'],
 'slow_down_layer_time': ['20'],
 'slow_down_min_speed': ['15'],
 'temperature_vitrification': ['203'],
 'type': 'filament'}
