from __future__ import annotations

# source: profiles/Snapmaker/filament/fdm_filament_asa.json
DATA = {'close_fan_the_first_x_layers': ['4'],
 'default_filament_colour': [''],
 'enable_pressure_advance': ['1'],
 'fan_cooling_layer_time': ['20'],
 'fan_max_speed': ['35'],
 'fan_min_speed': ['10'],
 'filament_cost': ['80'],
 'filament_density': ['1.04'],
 'filament_flow_ratio': ['0.94'],
 'filament_max_volumetric_speed': ['7.6'],
 'filament_retraction_length': ['0.6'],
 'filament_type': ['ASA'],
 'filament_z_hop': ['0.7'],
 'from': 'system',
 'hot_plate_temp': ['90'],
 'hot_plate_temp_initial_layer': ['90'],
 'inherits': 'fdm_filament_common',
 'instantiation': 'false',
 'name': 'fdm_filament_asa',
 'nozzle_temperature': ['255'],
 'nozzle_temperature_initial_layer': ['255'],
 'nozzle_temperature_range_high': ['280'],
 'nozzle_temperature_range_low': ['240'],
 'overhang_fan_speed': ['80'],
 'overhang_fan_threshold': ['25%'],
 'reduce_fan_stop_start_freq': ['1'],
 'slow_down_layer_time': ['5'],
 'slow_down_min_speed': ['20'],
 'temperature_vitrification': ['182'],
 'type': 'filament'}
