from __future__ import annotations

# source: profiles/Snapmaker/filament/fdm_filament_tpu.json
DATA = {'additional_cooling_fan_speed': ['70'],
 'close_fan_the_first_x_layers': ['1'],
 'default_filament_colour': [''],
 'fan_cooling_layer_time': ['100'],
 'fan_max_speed': ['70'],
 'fan_min_speed': ['70'],
 'filament_cost': ['80'],
 'filament_density': ['1.24'],
 'filament_deretraction_speed': ['25'],
 'filament_max_volumetric_speed': ['2.8'],
 'filament_notes': ['!! It needs to be dried before use.\nSunlu TPU 95A\n'],
 'filament_retract_when_changing_layer': ['0'],
 'filament_retraction_length': ['0.5'],
 'filament_retraction_speed': ['25'],
 'filament_type': ['TPU'],
 'filament_z_hop': ['0'],
 'filament_z_hop_types': ['Normal Lift'],
 'from': 'system',
 'hot_plate_temp': ['40'],
 'hot_plate_temp_initial_layer': ['45'],
 'inherits': 'fdm_filament_common',
 'instantiation': 'false',
 'name': 'fdm_filament_tpu',
 'nozzle_temperature': ['225'],
 'nozzle_temperature_initial_layer': ['230'],
 'nozzle_temperature_range_high': ['250'],
 'nozzle_temperature_range_low': ['220'],
 'overhang_fan_speed': ['70'],
 'pressure_advance': ['0.01'],
 'reduce_fan_stop_start_freq': ['1'],
 'slow_down_for_layer_cooling': ['0'],
 'temperature_vitrification': ['138'],
 'type': 'filament'}
