from __future__ import annotations

# source: profiles/Snapmaker/filament/fdm_filament_pet.json
DATA = {'default_filament_colour': [''],
 'enable_pressure_advance': ['1'],
 'fan_cooling_layer_time': ['7'],
 'fan_max_speed': ['40'],
 'fan_min_speed': ['0'],
 'filament_cost': ['8'],
 'filament_density': ['1.29'],
 'filament_max_volumetric_speed': ['6'],
 'filament_notes': ['JiaNong PET 1.63x1.75mm'],
 'filament_type': ['PET'],
 'from': 'system',
 'hot_plate_temp': ['65'],
 'inherits': 'fdm_filament_common',
 'instantiation': 'false',
 'name': 'fdm_filament_pet',
 'nozzle_temperature': ['278'],
 'nozzle_temperature_initial_layer': ['275'],
 'nozzle_temperature_range_high': ['280'],
 'nozzle_temperature_range_low': ['250'],
 'overhang_fan_speed': ['60'],
 'overhang_fan_threshold': ['25%'],
 'pressure_advance': ['0.022'],
 'reduce_fan_stop_start_freq': ['1'],
 'slow_down_layer_time': ['2'],
 'slow_down_min_speed': ['50'],
 'temperature_vitrification': ['230'],
 'type': 'filament'}
