from __future__ import annotations

# source: profiles/Snapmaker/filament/fdm_filament_pla.json
DATA = {'additional_cooling_fan_speed': ['70'],
 'close_fan_the_first_x_layers': ['1'],
 'default_filament_colour': [''],
 'enable_pressure_advance': ['1'],
 'fan_cooling_layer_time': ['100'],
 'fan_min_speed': ['100'],
 'filament_cost': ['60'],
 'filament_density': ['1.24'],
 'filament_flow_ratio': ['0.98'],
 'filament_max_volumetric_speed': ['14'],
 'filament_retraction_length': ['1.2'],
 'filament_retraction_speed': ['60'],
 'filament_type': ['PLA'],
 'from': 'system',
 'inherits': 'fdm_filament_common',
 'instantiation': 'false',
 'name': 'fdm_filament_pla',
 'nozzle_temperature': ['210'],
 'nozzle_temperature_initial_layer': ['220'],
 'nozzle_temperature_range_high': ['240'],
 'nozzle_temperature_range_low': ['190'],
 'overhang_fan_threshold': ['0%'],
 'pressure_advance': ['0.02'],
 'reduce_fan_stop_start_freq': ['1'],
 'slow_down_min_speed': ['15'],
 'temperature_vitrification': ['154'],
 'type': 'filament'}
