from __future__ import annotations

# source: profiles/Snapmaker/filament/fdm_filament_abs.json
DATA = {'close_fan_the_first_x_layers': ['3'],
 'default_filament_colour': [''],
 'enable_pressure_advance': ['1'],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['80'],
 'fan_min_speed': ['15'],
 'filament_cost': ['50'],
 'filament_density': ['1.04'],
 'filament_flow_ratio': ['0.93'],
 'filament_max_volumetric_speed': ['16'],
 'filament_notes': ['eSUN ABS+\nSunlu ABS+\n'],
 'filament_retraction_length': ['0.6'],
 'filament_type': ['ABS'],
 'filament_z_hop': ['0.7'],
 'from': 'system',
 'hot_plate_temp': ['90'],
 'hot_plate_temp_initial_layer': ['90'],
 'inherits': 'fdm_filament_common',
 'instantiation': 'false',
 'name': 'fdm_filament_abs',
 'nozzle_temperature': ['260'],
 'nozzle_temperature_initial_layer': ['260'],
 'nozzle_temperature_range_high': ['280'],
 'nozzle_temperature_range_low': ['240'],
 'overhang_fan_speed': ['80'],
 'overhang_fan_threshold': ['25%'],
 'pressure_advance': ['0.015'],
 'reduce_fan_stop_start_freq': ['1'],
 'slow_down_layer_time': ['3'],
 'slow_down_min_speed': ['20'],
 'temperature_vitrification': ['189'],
 'type': 'filament'}
