from __future__ import annotations

# source: profiles/Snapmaker/filament/Snapmaker PLA-CF @U1 base.json
DATA = {'additional_cooling_fan_speed': ['0'],
 'default_filament_colour': [''],
 'filament_cooling_final_speed': ['60'],
 'filament_cooling_initial_speed': ['35'],
 'filament_cooling_moves': ['2'],
 'filament_density': ['1.22'],
 'filament_end_gcode': [''],
 'filament_id': '17021473250',
 'filament_load_time': ['2'],
 'filament_loading_speed': ['35'],
 'filament_loading_speed_start': ['35'],
 'filament_max_volumetric_speed': ['15'],
 'filament_type': ['PLA-CF'],
 'filament_unload_time': ['2'],
 'filament_unloading_speed': ['35'],
 'filament_unloading_speed_start': ['35'],
 'from': 'system',
 'hot_plate_temp': ['55'],
 'hot_plate_temp_initial_layer': ['55'],
 'inherits': 'fdm_filament_pla',
 'instantiation': 'false',
 'name': 'Snapmaker PLA-CF @U1 base',
 'nozzle_temperature': ['230'],
 'nozzle_temperature_initial_layer': ['230'],
 'nozzle_temperature_range_high': ['250'],
 'nozzle_temperature_range_low': ['210'],
 'required_nozzle_HRC': ['40'],
 'temperature_vitrification': ['150'],
 'type': 'filament'}
