from __future__ import annotations

# source: profiles/Snapmaker/filament/Snapmaker Dual PLA Matte.json
DATA = {'compatible_printers': ['Snapmaker A250 Dual (0.4 nozzle)',
                         'Snapmaker A250 Dual (0.6 nozzle)',
                         'Snapmaker A250 Dual BKit (0.4 nozzle)',
                         'Snapmaker A250 Dual BKit (0.6 nozzle)',
                         'Snapmaker A250 Dual QS+B Kit (0.4 nozzle)',
                         'Snapmaker A250 Dual QS+B Kit (0.6 nozzle)',
                         'Snapmaker A250 Dual QSKit (0.4 nozzle)',
                         'Snapmaker A250 Dual QSKit (0.6 nozzle)',
                         'Snapmaker A350 Dual (0.4 nozzle)',
                         'Snapmaker A350 Dual (0.6 nozzle)',
                         'Snapmaker A350 Dual BKit (0.4 nozzle)',
                         'Snapmaker A350 Dual BKit (0.6 nozzle)',
                         'Snapmaker A350 Dual QS+B Kit (0.4 nozzle)',
                         'Snapmaker A350 Dual QS+B Kit (0.6 nozzle)',
                         'Snapmaker A350 Dual QSKit (0.4 nozzle)',
                         'Snapmaker A350 Dual QSKit (0.6 nozzle)',
                         'Snapmaker Artisan (0.4 nozzle)',
                         'Snapmaker Artisan (0.6 nozzle)'],
 'from': 'system',
 'inherits': 'Snapmaker Dual PLA Matte @base',
 'instantiation': 'true',
 'name': 'Snapmaker Dual PLA Matte',
 'setting_id': '3959402964',
 'type': 'filament'}
