from __future__ import annotations

# source: profiles/Snapmaker/filament/Snapmaker Dual TPU High-Flow.json
DATA = {'compatible_printers': ['Snapmaker A250 Dual (0.4 nozzle)',
                         'Snapmaker A250 Dual (0.6 nozzle)',
                         'Snapmaker A250 Dual (0.8 nozzle)',
                         'Snapmaker A250 Dual BKit (0.4 nozzle)',
                         'Snapmaker A250 Dual BKit (0.6 nozzle)',
                         'Snapmaker A250 Dual BKit (0.8 nozzle)',
                         'Snapmaker A250 Dual QS+B Kit (0.4 nozzle)',
                         'Snapmaker A250 Dual QS+B Kit (0.6 nozzle)',
                         'Snapmaker A250 Dual QS+B Kit (0.8 nozzle)',
                         'Snapmaker A250 Dual QSKit (0.4 nozzle)',
                         'Snapmaker A250 Dual QSKit (0.6 nozzle)',
                         'Snapmaker A250 Dual QSKit (0.8 nozzle)',
                         'Snapmaker A350 Dual (0.4 nozzle)',
                         'Snapmaker A350 Dual (0.6 nozzle)',
                         'Snapmaker A350 Dual (0.8 nozzle)',
                         'Snapmaker A350 Dual BKit (0.4 nozzle)',
                         'Snapmaker A350 Dual BKit (0.6 nozzle)',
                         'Snapmaker A350 Dual BKit (0.8 nozzle)',
                         'Snapmaker A350 Dual QS+B Kit (0.4 nozzle)',
                         'Snapmaker A350 Dual QS+B Kit (0.6 nozzle)',
                         'Snapmaker A350 Dual QS+B Kit (0.8 nozzle)',
                         'Snapmaker A350 Dual QSKit (0.4 nozzle)',
                         'Snapmaker A350 Dual QSKit (0.6 nozzle)',
                         'Snapmaker A350 Dual QSKit (0.8 nozzle)',
                         'Snapmaker Artisan (0.4 nozzle)',
                         'Snapmaker Artisan (0.6 nozzle)',
                         'Snapmaker Artisan (0.8 nozzle)'],
 'filament_deretraction_speed': ['nil'],
 'filament_flow_ratio': ['0.983'],
 'filament_max_volumetric_speed': ['7.6'],
 'filament_notes': ['!! It needs to be dried before use.\nSnapmaker TPU 95A High-Flow\n'],
 'filament_retraction_length': ['0.8'],
 'filament_retraction_speed': ['nil'],
 'from': 'system',
 'inherits': 'Snapmaker Dual TPU @base',
 'instantiation': 'true',
 'name': 'Snapmaker Dual TPU High-Flow',
 'setting_id': '1072918854',
 'type': 'filament'}
