from __future__ import annotations

# source: profiles/Snapmaker/filament/Snapmaker PLA Matte @U1 base.json
DATA = {'additional_cooling_fan_speed': ['70'],
 'close_fan_the_first_x_layers': ['1'],
 'cool_plate_temp': ['60'],
 'cool_plate_temp_initial_layer': ['60'],
 'eng_plate_temp': ['60'],
 'eng_plate_temp_initial_layer': ['60'],
 'fan_cooling_layer_time': ['100'],
 'fan_max_speed': ['100'],
 'fan_min_speed': ['100'],
 'filament_cooling_final_speed': ['60'],
 'filament_cooling_initial_speed': ['35'],
 'filament_cooling_moves': ['2'],
 'filament_cost': ['20'],
 'filament_density': ['1.24'],
 'filament_end_gcode': [''],
 'filament_id': '141703112701',
 'filament_load_time': ['2'],
 'filament_loading_speed': ['35'],
 'filament_loading_speed_start': ['35'],
 'filament_max_volumetric_speed': ['12'],
 'filament_retraction_length': ['nil'],
 'filament_start_gcode': ['; filament start gcode\n'],
 'filament_type': ['PLA'],
 'filament_unload_time': ['2'],
 'filament_unloading_speed': ['35'],
 'filament_unloading_speed_start': ['35'],
 'from': 'system',
 'hot_plate_temp': ['60'],
 'hot_plate_temp_initial_layer': ['60'],
 'instantiation': 'false',
 'name': 'Snapmaker PLA Matte @U1 base',
 'nozzle_temperature': ['220'],
 'nozzle_temperature_initial_layer': ['220'],
 'nozzle_temperature_range_high': ['230'],
 'nozzle_temperature_range_low': ['190'],
 'overhang_fan_speed': ['100'],
 'overhang_fan_threshold': ['50%'],
 'reduce_fan_stop_start_freq': ['1'],
 'slow_down_for_layer_cooling': ['1'],
 'slow_down_layer_time': ['4'],
 'slow_down_min_speed': ['10'],
 'temperature_vitrification': ['60'],
 'textured_plate_temp': ['60'],
 'textured_plate_temp_initial_layer': ['60'],
 'type': 'filament'}
