from __future__ import annotations

# source: profiles/Snapmaker/filament/Snapmaker PET.json
DATA = {'compatible_printers': ['Snapmaker A250 (0.4 nozzle)',
                         'Snapmaker A250 (0.6 nozzle)',
                         'Snapmaker A250 (0.8 nozzle)',
                         'Snapmaker A250 BKit (0.4 nozzle)',
                         'Snapmaker A250 BKit (0.6 nozzle)',
                         'Snapmaker A250 BKit (0.8 nozzle)',
                         'Snapmaker A250 QS+B Kit (0.4 nozzle)',
                         'Snapmaker A250 QS+B Kit (0.6 nozzle)',
                         'Snapmaker A250 QS+B Kit (0.8 nozzle)',
                         'Snapmaker A250 QSKit (0.4 nozzle)',
                         'Snapmaker A250 QSKit (0.6 nozzle)',
                         'Snapmaker A250 QSKit (0.8 nozzle)',
                         'Snapmaker A350 (0.4 nozzle)',
                         'Snapmaker A350 (0.6 nozzle)',
                         'Snapmaker A350 (0.8 nozzle)',
                         'Snapmaker A350 BKit (0.4 nozzle)',
                         'Snapmaker A350 BKit (0.6 nozzle)',
                         'Snapmaker A350 BKit (0.8 nozzle)',
                         'Snapmaker A350 QS+B Kit (0.4 nozzle)',
                         'Snapmaker A350 QS+B Kit (0.6 nozzle)',
                         'Snapmaker A350 QS+B Kit (0.8 nozzle)',
                         'Snapmaker A350 QSKit (0.4 nozzle)',
                         'Snapmaker A350 QSKit (0.6 nozzle)',
                         'Snapmaker A350 QSKit (0.8 nozzle)'],
 'from': 'system',
 'inherits': 'Snapmaker PET @base',
 'instantiation': 'true',
 'name': 'Snapmaker PET',
 'setting_id': '3543479015',
 'type': 'filament'}
