from __future__ import annotations

# source: profiles/Snapmaker/filament/Snapmaker TPE.json
DATA = {'compatible_printers': ['Snapmaker A250 (0.4 nozzle)',
                         'Snapmaker A250 (0.6 nozzle)',
                         'Snapmaker A250 (0.8 nozzle)',
                         'Snapmaker A250 BKit (0.4 nozzle)',
                         'Snapmaker A250 BKit (0.6 nozzle)',
                         'Snapmaker A250 BKit (0.8 nozzle)',
                         'Snapmaker A250 QS+B Kit (0.4 nozzle)',
                         'Snapmaker A250 QS+B Kit (0.6 nozzle)',
                         'Snapmaker A250 QS+B Kit (0.8 nozzle)',
                         'Snapmaker A250 QSKit (0.4 nozzle)',
                         'Snapmaker A250 QSKit (0.6 nozzle)',
                         'Snapmaker A250 QSKit (0.8 nozzle)',
                         'Snapmaker A350 (0.4 nozzle)',
                         'Snapmaker A350 (0.6 nozzle)',
                         'Snapmaker A350 (0.8 nozzle)',
                         'Snapmaker A350 BKit (0.4 nozzle)',
                         'Snapmaker A350 BKit (0.6 nozzle)',
                         'Snapmaker A350 BKit (0.8 nozzle)',
                         'Snapmaker A350 QS+B Kit (0.4 nozzle)',
                         'Snapmaker A350 QS+B Kit (0.6 nozzle)',
                         'Snapmaker A350 QS+B Kit (0.8 nozzle)',
                         'Snapmaker A350 QSKit (0.4 nozzle)',
                         'Snapmaker A350 QSKit (0.6 nozzle)',
                         'Snapmaker A350 QSKit (0.8 nozzle)'],
 'default_filament_colour': [''],
 'fan_max_speed': ['100'],
 'fan_min_speed': ['100'],
 'filament_density': ['1.22'],
 'filament_max_volumetric_speed': ['7.2'],
 'filament_notes': ['eSUN eLastic TPE-83A\n'],
 'from': 'system',
 'hot_plate_temp': ['45'],
 'inherits': 'Snapmaker TPU @base',
 'instantiation': 'true',
 'name': 'Snapmaker TPE',
 'nozzle_temperature': ['240'],
 'nozzle_temperature_initial_layer': ['240'],
 'overhang_fan_speed': ['100'],
 'setting_id': '2302237917',
 'type': 'filament'}
