from __future__ import annotations

# source: profiles/Snapmaker/filament/Snapmaker PETG-CF @U1 base.json
DATA = {'default_filament_colour': [''],
 'enable_pressure_advance': ['0'],
 'fan_cooling_layer_time': ['10'],
 'fan_max_speed': ['20'],
 'fan_min_speed': ['0'],
 'filament_cooling_final_speed': ['60'],
 'filament_cooling_initial_speed': ['35'],
 'filament_cooling_moves': ['2'],
 'filament_cost': ['40'],
 'filament_density': ['1.25'],
 'filament_end_gcode': [''],
 'filament_id': '10425112260',
 'filament_load_time': ['2'],
 'filament_loading_speed': ['35'],
 'filament_loading_speed_start': ['35'],
 'filament_max_volumetric_speed': ['6.4'],
 'filament_retraction_length': ['nil'],
 'filament_retraction_minimum_travel': ['nil'],
 'filament_type': ['PETG-CF'],
 'filament_unload_time': ['2'],
 'filament_unloading_speed': ['35'],
 'filament_unloading_speed_start': ['35'],
 'from': 'system',
 'inherits': 'fdm_filament_petg',
 'instantiation': 'false',
 'name': 'Snapmaker PETG-CF @U1 base',
 'nozzle_temperature_initial_layer': ['250'],
 'nozzle_temperature_range_high': ['255'],
 'overhang_fan_speed': ['55'],
 'overhang_fan_threshold': ['10%'],
 'required_nozzle_HRC': ['40'],
 'slow_down_layer_time': ['6'],
 'slow_down_min_speed': ['10'],
 'temperature_vitrification': ['178'],
 'type': 'filament'}
