from __future__ import annotations

# source: profiles/Flashforge/filament/Flashforge Generic PLA.json
DATA = {'additional_cooling_fan_speed': ['100'],
 'compatible_printers': ['Flashforge Adventurer 5M 0.4 Nozzle',
                         'Flashforge Adventurer 5M 0.6 Nozzle',
                         'Flashforge Adventurer 5M 0.8 Nozzle',
                         'Flashforge Adventurer 5M Pro 0.4 Nozzle',
                         'Flashforge Adventurer 5M Pro 0.6 Nozzle',
                         'Flashforge Adventurer 5M Pro 0.8 Nozzle',
                         'Flashforge AD5X 0.4 nozzle',
                         'Flashforge AD5X 0.6 nozzle',
                         'Flashforge AD5X 0.8 nozzle'],
 'enable_pressure_advance': ['1'],
 'filament_diameter': ['1.75'],
 'filament_end_gcode': ['; filament end gcode\n'],
 'filament_flow_ratio': ['0.98'],
 'filament_id': 'FFG01',
 'filament_max_volumetric_speed': ['25'],
 'filament_start_gcode': ['; filament start gcode\n;right_extruder_material: PLA\n'],
 'from': 'system',
 'hot_plate_temp': ['50'],
 'hot_plate_temp_initial_layer': ['55'],
 'inherits': 'fdm_filament_pla',
 'instantiation': 'true',
 'name': 'Flashforge Generic PLA',
 'nozzle_temperature': ['220'],
 'nozzle_temperature_initial_layer': ['220'],
 'nozzle_temperature_range_high': ['230'],
 'nozzle_temperature_range_low': ['190'],
 'pressure_advance': ['0.025'],
 'setting_id': 'FFGP01',
 'slow_down_layer_time': ['6'],
 'slow_down_min_speed': ['20'],
 'support_material_interface_fan_speed': ['100'],
 'type': 'filament'}
