from __future__ import annotations

# source: profiles/Flashforge/filament/Generic PLA @Flashforge AD4.json
DATA = {'additional_cooling_fan_speed': ['100'],
 'close_fan_the_first_x_layers': ['2'],
 'compatible_printers': ['Flashforge Adventurer 4 Series 0.3 Nozzle',
                         'Flashforge Adventurer 4 Series 0.4 Nozzle',
                         'Flashforge Adventurer 4 Series 0.6 Nozzle'],
 'enable_pressure_advance': ['1'],
 'fan_max_speed': ['60'],
 'fan_min_speed': ['30'],
 'filament_diameter': ['1.75'],
 'filament_end_gcode': ['; filament end gcode\n'],
 'filament_flow_ratio': ['1.07'],
 'filament_id': 'GFL99',
 'filament_max_volumetric_speed': ['20'],
 'filament_retract_when_changing_layer': ['0'],
 'filament_retraction_length': ['5'],
 'filament_start_gcode': ['; filament start gcode\n;right_extruder_material: PLA\n'],
 'filament_vendor': ['Generic'],
 'filament_wipe': ['0'],
 'from': 'system',
 'hot_plate_temp': ['60'],
 'hot_plate_temp_initial_layer': ['60'],
 'inherits': 'Flashforge Generic PLA',
 'instantiation': 'true',
 'name': 'Generic PLA @Flashforge AD4',
 'nozzle_temperature': ['210'],
 'nozzle_temperature_initial_layer': ['210'],
 'nozzle_temperature_range_high': ['230'],
 'nozzle_temperature_range_low': ['190'],
 'pressure_advance': ['0.8'],
 'setting_id': 'GFSA04',
 'slow_down_layer_time': ['10'],
 'slow_down_min_speed': ['20'],
 'support_material_interface_fan_speed': ['100'],
 'type': 'filament'}
