from __future__ import annotations

# source: profiles/Flashforge/filament/Generic ABS @Flashforge AD4.json
DATA = {'chamber_temperature': ['40'],
 'compatible_printers': ['Flashforge Adventurer 4 Series 0.3 Nozzle',
                         'Flashforge Adventurer 4 Series 0.4 Nozzle',
                         'Flashforge Adventurer 4 Series 0.6 Nozzle'],
 'enable_pressure_advance': ['1'],
 'filament_density': ['1.04'],
 'filament_diameter': ['1.75'],
 'filament_end_gcode': ['; filament end gcode\n'],
 'filament_flow_ratio': ['1.093'],
 'filament_id': 'GFB99',
 'filament_max_volumetric_speed': ['15'],
 'filament_start_gcode': ['; filament start gcode\n;right_extruder_material: ABS\n'],
 'filament_vendor': ['Generic'],
 'from': 'system',
 'hot_plate_temp': ['105'],
 'hot_plate_temp_initial_layer': ['105'],
 'inherits': 'Flashforge Generic ABS',
 'instantiation': 'true',
 'name': 'Generic ABS @Flashforge AD4',
 'nozzle_temperature': ['240'],
 'nozzle_temperature_initial_layer': ['240'],
 'pressure_advance': ['0.04'],
 'setting_id': 'GFSA04',
 'slow_down_layer_time': ['8'],
 'slow_down_min_speed': ['20'],
 'support_material_interface_fan_speed': ['80'],
 'temperature_vitrification': ['100'],
 'type': 'filament'}
