from __future__ import annotations

# source: profiles/Flashforge/filament/Generic PLA Silk @Flashforge AD4.json
DATA = {'additional_cooling_fan_speed': ['100'],
 'compatible_printers': ['Flashforge Adventurer 4 Series 0.3 Nozzle',
                         'Flashforge Adventurer 4 Series 0.4 Nozzle',
                         'Flashforge Adventurer 4 Series 0.6 Nozzle'],
 'enable_pressure_advance': ['1'],
 'filament_diameter': ['1.75'],
 'filament_end_gcode': ['; filament end gcode\n'],
 'filament_flow_ratio': ['1.07'],
 'filament_id': 'GFL99',
 'filament_max_volumetric_speed': ['16'],
 'filament_start_gcode': ['; filament start gcode\n;right_extruder_material: PLA Silk\n'],
 'filament_vendor': ['Generic'],
 'from': 'system',
 'hot_plate_temp': ['50'],
 'hot_plate_temp_initial_layer': ['55'],
 'inherits': 'Flashforge Generic PLA-Silk',
 'instantiation': 'true',
 'name': 'Generic PLA Silk @Flashforge AD4',
 'nozzle_temperature': ['220'],
 'nozzle_temperature_initial_layer': ['220'],
 'nozzle_temperature_range_high': ['230'],
 'nozzle_temperature_range_low': ['190'],
 'pressure_advance': ['0.048'],
 'renamed_from': 'PLA Silk @Flashforge AD4',
 'setting_id': 'GFSA04',
 'slow_down_layer_time': ['8'],
 'slow_down_min_speed': ['20'],
 'support_material_interface_fan_speed': ['100'],
 'type': 'filament'}
