from __future__ import annotations

# source: profiles/Tiertime/process/0.12mm Fine @Tiertime UP600 HS.json
DATA = {'bottom_shell_layers': '5',
 'bridge_flow': '1',
 'compatible_printers': ['Tiertime UP600 HS 0.4 nozzle'],
 'elefant_foot_compensation': '0.15',
 'from': 'system',
 'gap_infill_speed': '150',
 'inherits': 'fdm_process_tiertime_HS_common',
 'initial_layer_infill_speed': '105',
 'initial_layer_speed': '50',
 'inner_wall_speed': '200',
 'instantiation': 'true',
 'internal_solid_infill_speed': '200',
 'layer_height': '0.12',
 'name': '0.12mm Fine @Tiertime UP600 HS',
 'outer_wall_speed': '150',
 'overhang_1_4_speed': '60',
 'overhang_2_4_speed': '30',
 'overhang_3_4_speed': '10',
 'setting_id': 'GP026',
 'sparse_infill_speed': '200',
 'support_bottom_z_distance': '0.12',
 'support_threshold_angle': '25',
 'support_top_z_distance': '0.12',
 'top_shell_layers': '8',
 'top_shell_thickness': '1.0',
 'type': 'process'}
