from __future__ import annotations

# source: profiles/FlyingBear/filament/Ghost7/fdm_filament_pc @Ghost7.json
DATA = {'activate_air_filtration': ['1'],
 'close_fan_the_first_x_layers': ['3'],
 'complete_print_exhaust_fan_speed': ['80'],
 'cool_plate_temp': ['0'],
 'cool_plate_temp_initial_layer': ['0'],
 'during_print_exhaust_fan_speed': ['100'],
 'eng_plate_temp': ['110'],
 'eng_plate_temp_initial_layer': ['110'],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['30'],
 'fan_min_speed': ['10'],
 'filament_cost': ['20'],
 'filament_density': ['1.04'],
 'filament_max_volumetric_speed': ['12'],
 'filament_type': ['PC'],
 'filament_vendor': ['FlyingBear'],
 'from': 'system',
 'hot_plate_temp': ['100'],
 'hot_plate_temp_initial_layer': ['100'],
 'inherits': 'fdm_filament_common_Ghost7',
 'instantiation': 'false',
 'name': 'fdm_filament_pc @Ghost7',
 'nozzle_temperature': ['270'],
 'nozzle_temperature_initial_layer': ['260'],
 'nozzle_temperature_range_high': ['280'],
 'nozzle_temperature_range_low': ['240'],
 'overhang_fan_speed': ['100'],
 'overhang_fan_threshold': ['25%'],
 'reduce_fan_stop_start_freq': ['0'],
 'slow_down_for_layer_cooling': ['1'],
 'slow_down_layer_time': ['5'],
 'slow_down_min_speed': ['20'],
 'temperature_vitrification': ['140'],
 'textured_plate_temp': ['110'],
 'textured_plate_temp_initial_layer': ['110'],
 'type': 'filament'}
