name: eon_mobile
description: Temporary Flutter app shell for Android, iOS, and web.
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  eon_shared:
    path: ../../packages/eon_shared

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
