from __future__ import annotations

# source: profiles/Creality/machine/Creality Sermoon V1 0.4 nozzle.json
DATA = {'auxiliary_fan': '1',
 'change_filament_gcode': '; S1 Pause For Filament change\nM125',
 'default_filament_profile': ['Creality Generic PLA'],
 'default_print_profile': '0.20mm Standard @Creality Sermoon V1',
 'extruder_clearance_height_to_lid': '125',
 'extruder_clearance_height_to_rod': '40',
 'extruder_clearance_radius': '50',
 'from': 'system',
 'gcode_flavor': 'marlin',
 'inherits': 'fdm_creality_common',
 'instantiation': 'true',
 'layer_change_gcode': 'SET_PRINT_STATS_INFO CURRENT_LAYER={layer_num + 1}\n;AFTER_LAYER_CHANGE\n;Z>[layer_z]',
 'machine_end_gcode': 'M140 S0                                ; Turn-off bed\n'
                      'M107                                   ; Turn off cooling fan\n'
                      'G91                                    ; Relative positioning\n'
                      'G1 E-1 F2700                           ; Retract\n'
                      'G1 E-2 Z0.2 F2400                      ; Retract and raise Z\n'
                      'G1 X5 Y5 F3000                         ; Wipe\n'
                      'G1 Z0.95                               ; Raise Z more\n'
                      'G90                                    ; Absolute positioning\n'
                      'G1 X10 Y160                            ; Eject print\n'
                      'M106 S0                                ; Turn off fan\n'
                      'M104 S0                                ; Turn-off hot end\n'
                      'M140 S0                                ; Turn-off bed\n'
                      '{ if max_layer_z < printable_height-10 }G1 Z{min(max_layer_z+70,printable_height-10)}; move '
                      'print up {endif}; Eject print z (conditional)\n'
                      'M84 X Y E                              ; Disable steppers except Z\n'
                      'G92 E0                                 ; Reset Extruder\n'
                      'M82;abs extrusion\n'
                      'END_PRINT',
 'machine_max_acceleration_extruding': ['7000', '500'],
 'machine_max_acceleration_retracting': ['7000', '1000'],
 'machine_max_acceleration_x': ['7000', '500'],
 'machine_max_acceleration_y': ['7000', '500'],
 'machine_max_speed_x': ['7000', '500'],
 'machine_max_speed_y': ['7000', '500'],
 'machine_pause_gcode': 'M25 ;pause print\n'
                        '; Sermoon V1 Marlin buffers commands, so flush with these G4 P10 commands\n'
                        'G4 P10\n'
                        'G4 P10\n'
                        'G4 P10\n'
                        'G4 P10\n'
                        'G4 P10\n'
                        'G4 P10\n'
                        'G4 P10\n'
                        'G4 P10\n'
                        'G4 P10\n'
                        'G4 P10\n',
 'machine_start_gcode': ';generated by SuperSlicer 1.5.0 on 2023-06-07 at 17:32:332\n'
                        'G90 ; use absolute coordinates\n'
                        'SET_PRINT_STATS_INFO TOTAL_LAYER=[total_layer_count]\n'
                        'M140 S[bed_temperature_initial_layer]                       ; Set bed temp\n'
                        'M104 S170 ; set temporary nozzle temp to prevent oozing during homing\n'
                        'G28                                    ; Home\n'
                        'M105                                   ; Report Temps\n'
                        'M190 S[bed_temperature_initial_layer]                        ; Wait for bed to reach target\n'
                        'M104 S[nozzle_temperature_initial_layer]                           ; Set hot end temp\n'
                        'M105                                   ; Report Temps\n'
                        'M109 S[nozzle_temperature_initial_layer]                           ; Wait for hot end to '
                        'reach target\n'
                        'M105                                   ; Report Temps\n'
                        'M82                                    ; Absolute extrusion mode\n'
                        '#G28                                    ; Home\n'
                        'G92 E0                                 ; Reset Extruder\n'
                        'G1 Z2.0 F3000                          ; Move Z Axis up\n'
                        'G1 X173.0 Y10 Z0.28 F5000.0             ; Move to start position\n'
                        'G1 X173.0 Y170.0 Z0.28 F1500.0 E15      ; Draw the first line\n'
                        'G1 X173.4 Y170.0 Z0.28 F5000.0          ; Move to side a little\n'
                        'G1 X173.4 Y40 Z0.28 F1500.0 E30         ; Draw the second line\n'
                        'G92 E0                                 ; Reset Extruder\n'
                        'G1 Z2.0 F3000                          ; Move Z Axis up\n'
                        'G92 E0\n'
                        'START_PRINT',
 'name': 'Creality Sermoon V1 0.4 nozzle',
 'nozzle_diameter': ['0.4'],
 'nozzle_type': 'brass',
 'print_host': '10.0.0.51',
 'print_host_webui': '10.0.0.51',
 'printable_area': ['0x0', '175x0', '175x175', '0x175'],
 'printable_height': '165',
 'printer_model': 'Creality Sermoon V1',
 'retract_when_changing_layer': ['0'],
 'retraction_length': ['0.8'],
 'setting_id': 'GM001',
 'thumbnails': ['64x64', '400x400'],
 'type': 'machine',
 'z_hop': ['0']}
