from __future__ import annotations

# source: profiles/Ratrig/filament/RatRig Generic PC.json
DATA = {'compatible_printers': ['RatRig V-Core 3 200 0.4 nozzle',
                         'RatRig V-Core 3 300 0.4 nozzle',
                         'RatRig V-Core 3 400 0.4 nozzle',
                         'RatRig V-Core 3 500 0.4 nozzle',
                         'RatRig V-Minion 0.4 nozzle',
                         'RatRig V-Cast 0.4 nozzle',
                         'RatRig V-Cast 0.6 nozzle',
                         'RatRig V-Core 4 300 0.4 nozzle',
                         'RatRig V-Core 4 300 0.5 nozzle',
                         'RatRig V-Core 4 300 0.6 nozzle',
                         'RatRig V-Core 4 400 0.4 nozzle',
                         'RatRig V-Core 4 400 0.5 nozzle',
                         'RatRig V-Core 4 400 0.6 nozzle',
                         'RatRig V-Core 4 500 0.4 nozzle',
                         'RatRig V-Core 4 500 0.5 nozzle',
                         'RatRig V-Core 4 500 0.6 nozzle',
                         'RatRig V-Core 4 IDEX 300 0.4 nozzle',
                         'RatRig V-Core 4 IDEX 300 0.5 nozzle',
                         'RatRig V-Core 4 IDEX 300 0.6 nozzle',
                         'RatRig V-Core 4 IDEX 400 0.4 nozzle',
                         'RatRig V-Core 4 IDEX 400 0.5 nozzle',
                         'RatRig V-Core 4 IDEX 400 0.6 nozzle',
                         'RatRig V-Core 4 IDEX 500 0.4 nozzle',
                         'RatRig V-Core 4 IDEX 500 0.5 nozzle',
                         'RatRig V-Core 4 IDEX 500 0.6 nozzle',
                         'RatRig V-Core 4 HYBRID 300 0.4 nozzle',
                         'RatRig V-Core 4 HYBRID 300 0.5 nozzle',
                         'RatRig V-Core 4 HYBRID 300 0.6 nozzle',
                         'RatRig V-Core 4 HYBRID 400 0.4 nozzle',
                         'RatRig V-Core 4 HYBRID 400 0.5 nozzle',
                         'RatRig V-Core 4 HYBRID 400 0.6 nozzle',
                         'RatRig V-Core 4 HYBRID 500 0.4 nozzle',
                         'RatRig V-Core 4 HYBRID 500 0.5 nozzle',
                         'RatRig V-Core 4 HYBRID 500 0.6 nozzle'],
 'enable_pressure_advance': ['1'],
 'filament_flow_ratio': ['0.93'],
 'filament_id': 'GFC99',
 'filament_max_volumetric_speed': ['12'],
 'filament_z_hop': ['0'],
 'from': 'system',
 'hot_plate_temp': ['100'],
 'hot_plate_temp_initial_layer': ['100'],
 'inherits': 'fdm_filament_pc',
 'instantiation': 'true',
 'name': 'RatRig Generic PC',
 'nozzle_temperature_initial_layer': ['280'],
 'nozzle_temperature_range_high': ['290'],
 'pressure_advance': ['0.045'],
 'setting_id': 'GFSA04',
 'type': 'filament'}
