from __future__ import annotations

# source: profiles/Ratrig/filament/RatRig BigNozzle ASA.json
DATA = {'close_fan_the_first_x_layers': ['2'],
 'compatible_printers': ['RatRig V-Core 3 200 0.4 nozzle',
                         'RatRig V-Core 3 300 0.4 nozzle',
                         'RatRig V-Core 3 400 0.4 nozzle',
                         'RatRig V-Core 3 500 0.4 nozzle',
                         'RatRig V-Minion 0.4 nozzle',
                         'RatRig V-Cast 0.4 nozzle',
                         'RatRig V-Cast 0.6 nozzle',
                         'RatRig V-Core 4 300 0.4 nozzle',
                         'RatRig V-Core 4 300 0.5 nozzle',
                         'RatRig V-Core 4 300 0.6 nozzle',
                         'RatRig V-Core 4 400 0.4 nozzle',
                         'RatRig V-Core 4 400 0.5 nozzle',
                         'RatRig V-Core 4 400 0.6 nozzle',
                         'RatRig V-Core 4 500 0.4 nozzle',
                         'RatRig V-Core 4 500 0.5 nozzle',
                         'RatRig V-Core 4 500 0.6 nozzle',
                         'RatRig V-Core 4 IDEX 300 0.4 nozzle',
                         'RatRig V-Core 4 IDEX 300 0.5 nozzle',
                         'RatRig V-Core 4 IDEX 300 0.6 nozzle',
                         'RatRig V-Core 4 IDEX 400 0.4 nozzle',
                         'RatRig V-Core 4 IDEX 400 0.5 nozzle',
                         'RatRig V-Core 4 IDEX 400 0.6 nozzle',
                         'RatRig V-Core 4 IDEX 500 0.4 nozzle',
                         'RatRig V-Core 4 IDEX 500 0.5 nozzle',
                         'RatRig V-Core 4 IDEX 500 0.6 nozzle',
                         'RatRig V-Core 4 HYBRID 300 0.4 nozzle',
                         'RatRig V-Core 4 HYBRID 300 0.5 nozzle',
                         'RatRig V-Core 4 HYBRID 300 0.6 nozzle',
                         'RatRig V-Core 4 HYBRID 400 0.4 nozzle',
                         'RatRig V-Core 4 HYBRID 400 0.5 nozzle',
                         'RatRig V-Core 4 HYBRID 400 0.6 nozzle',
                         'RatRig V-Core 4 HYBRID 500 0.4 nozzle',
                         'RatRig V-Core 4 HYBRID 500 0.5 nozzle',
                         'RatRig V-Core 4 HYBRID 500 0.6 nozzle'],
 'enable_pressure_advance': ['1'],
 'fan_cooling_layer_time': ['10'],
 'fan_max_speed': ['30'],
 'fan_min_speed': ['10'],
 'filament_flow_ratio': ['0.92'],
 'filament_id': 'GFB98',
 'filament_max_volumetric_speed': ['19'],
 'filament_z_hop': ['0'],
 'from': 'system',
 'hot_plate_temp_initial_layer': ['108'],
 'inherits': 'fdm_filament_asa',
 'instantiation': 'true',
 'name': 'RatRig BigNozzle ASA',
 'nozzle_temperature': ['265'],
 'nozzle_temperature_initial_layer': ['270'],
 'nozzle_temperature_range_high': ['290'],
 'nozzle_temperature_range_low': ['240'],
 'overhang_fan_speed': ['28'],
 'pressure_advance': ['0.033'],
 'setting_id': 'GFSA04',
 'type': 'filament'}
