from __future__ import annotations

# source: profiles/Ratrig/filament/RatRig PunkFil PETG CF.json
DATA = {'close_fan_the_first_x_layers': ['2'],
 'compatible_printers': ['RatRig V-Core 3 200 0.4 nozzle',
                         'RatRig V-Core 3 300 0.4 nozzle',
                         'RatRig V-Core 3 400 0.4 nozzle',
                         'RatRig V-Core 3 500 0.4 nozzle',
                         'RatRig V-Minion 0.4 nozzle',
                         'RatRig V-Cast 0.4 nozzle',
                         'RatRig V-Cast 0.6 nozzle',
                         'RatRig V-Core 4 300 0.4 nozzle',
                         'RatRig V-Core 4 300 0.5 nozzle',
                         'RatRig V-Core 4 300 0.6 nozzle',
                         'RatRig V-Core 4 400 0.4 nozzle',
                         'RatRig V-Core 4 400 0.5 nozzle',
                         'RatRig V-Core 4 400 0.6 nozzle',
                         'RatRig V-Core 4 500 0.4 nozzle',
                         'RatRig V-Core 4 500 0.5 nozzle',
                         'RatRig V-Core 4 500 0.6 nozzle',
                         'RatRig V-Core 4 IDEX 300 0.4 nozzle',
                         'RatRig V-Core 4 IDEX 300 0.5 nozzle',
                         'RatRig V-Core 4 IDEX 300 0.6 nozzle',
                         'RatRig V-Core 4 IDEX 400 0.4 nozzle',
                         'RatRig V-Core 4 IDEX 400 0.5 nozzle',
                         'RatRig V-Core 4 IDEX 400 0.6 nozzle',
                         'RatRig V-Core 4 IDEX 500 0.4 nozzle',
                         'RatRig V-Core 4 IDEX 500 0.5 nozzle',
                         'RatRig V-Core 4 IDEX 500 0.6 nozzle',
                         'RatRig V-Core 4 HYBRID 300 0.4 nozzle',
                         'RatRig V-Core 4 HYBRID 300 0.5 nozzle',
                         'RatRig V-Core 4 HYBRID 300 0.6 nozzle',
                         'RatRig V-Core 4 HYBRID 400 0.4 nozzle',
                         'RatRig V-Core 4 HYBRID 400 0.5 nozzle',
                         'RatRig V-Core 4 HYBRID 400 0.6 nozzle',
                         'RatRig V-Core 4 HYBRID 500 0.4 nozzle',
                         'RatRig V-Core 4 HYBRID 500 0.5 nozzle',
                         'RatRig V-Core 4 HYBRID 500 0.6 nozzle'],
 'enable_pressure_advance': ['1'],
 'fan_cooling_layer_time': ['10'],
 'fan_max_speed': ['30'],
 'fan_min_speed': ['0'],
 'filament_cost': ['48'],
 'filament_flow_ratio': ['0.93'],
 'filament_id': 'GFB99',
 'filament_max_volumetric_speed': ['20'],
 'filament_type': ['PETG-CF10'],
 'filament_vendor': ['RatRig'],
 'filament_z_hop': ['nil'],
 'from': 'system',
 'hot_plate_temp': ['80'],
 'hot_plate_temp_initial_layer': ['80'],
 'inherits': 'fdm_filament_pet',
 'instantiation': 'true',
 'name': 'RatRig PunkFil PETG CF',
 'nozzle_temperature': ['230'],
 'nozzle_temperature_initial_layer': ['230'],
 'overhang_fan_speed': ['40'],
 'overhang_fan_threshold': ['50%'],
 'pressure_advance': ['0.038'],
 'setting_id': 'GFSA04',
 'slow_down_for_layer_cooling': ['1'],
 'slow_down_layer_time': ['8'],
 'slow_down_min_speed': ['30'],
 'type': 'filament'}
