from __future__ import annotations

# source: profiles/Ratrig/filament/RatRig Generic PLA.json
DATA = {'compatible_printers': ['RatRig V-Core 3 200 0.4 nozzle',
                         'RatRig V-Core 3 300 0.4 nozzle',
                         'RatRig V-Core 3 400 0.4 nozzle',
                         'RatRig V-Core 3 500 0.4 nozzle',
                         'RatRig V-Minion 0.4 nozzle',
                         'RatRig V-Cast 0.4 nozzle',
                         'RatRig V-Cast 0.6 nozzle',
                         'RatRig V-Core 4 300 0.4 nozzle',
                         'RatRig V-Core 4 300 0.5 nozzle',
                         'RatRig V-Core 4 300 0.6 nozzle',
                         'RatRig V-Core 4 400 0.4 nozzle',
                         'RatRig V-Core 4 400 0.5 nozzle',
                         'RatRig V-Core 4 400 0.6 nozzle',
                         'RatRig V-Core 4 500 0.4 nozzle',
                         'RatRig V-Core 4 500 0.5 nozzle',
                         'RatRig V-Core 4 500 0.6 nozzle',
                         'RatRig V-Core 4 IDEX 300 0.4 nozzle',
                         'RatRig V-Core 4 IDEX 300 0.5 nozzle',
                         'RatRig V-Core 4 IDEX 300 0.6 nozzle',
                         'RatRig V-Core 4 IDEX 400 0.4 nozzle',
                         'RatRig V-Core 4 IDEX 400 0.5 nozzle',
                         'RatRig V-Core 4 IDEX 400 0.6 nozzle',
                         'RatRig V-Core 4 IDEX 500 0.4 nozzle',
                         'RatRig V-Core 4 IDEX 500 0.5 nozzle',
                         'RatRig V-Core 4 IDEX 500 0.6 nozzle',
                         'RatRig V-Core 4 HYBRID 300 0.4 nozzle',
                         'RatRig V-Core 4 HYBRID 300 0.5 nozzle',
                         'RatRig V-Core 4 HYBRID 300 0.6 nozzle',
                         'RatRig V-Core 4 HYBRID 400 0.4 nozzle',
                         'RatRig V-Core 4 HYBRID 400 0.5 nozzle',
                         'RatRig V-Core 4 HYBRID 400 0.6 nozzle',
                         'RatRig V-Core 4 HYBRID 500 0.4 nozzle',
                         'RatRig V-Core 4 HYBRID 500 0.5 nozzle',
                         'RatRig V-Core 4 HYBRID 500 0.6 nozzle'],
 'enable_pressure_advance': ['1'],
 'filament_flow_ratio': ['0.92'],
 'filament_id': 'GFL99',
 'filament_max_volumetric_speed': ['20'],
 'filament_z_hop': ['0'],
 'from': 'system',
 'inherits': 'fdm_filament_pla',
 'instantiation': 'true',
 'name': 'RatRig Generic PLA',
 'nozzle_temperature': ['200'],
 'nozzle_temperature_initial_layer': ['205'],
 'pressure_advance': ['0.05'],
 'setting_id': 'GFSA04',
 'slow_down_layer_time': ['8'],
 'type': 'filament'}
