from __future__ import annotations

# source: profiles/MagicMaker/machine/fdm_machine_common.json
DATA = {'before_layer_change_gcode': ';BEFORE_LAYER_CHANGE\n;[layer_z]\nG92 E0\n',
 'change_filament_gcode': '',
 'default_print_profile': '0.10mm Fine @MM hj',
 'deretraction_speed': ['40'],
 'extruder_clearance_height_to_lid': '140',
 'extruder_clearance_height_to_rod': '36',
 'extruder_clearance_radius': '65',
 'extruder_colour': ['#FCE94F'],
 'extruder_offset': ['0x0'],
 'from': 'system',
 'gcode_flavor': 'marlin',
 'instantiation': 'false',
 'machine_end_gcode': '',
 'machine_max_acceleration_e': ['10000'],
 'machine_max_acceleration_extruding': ['1500'],
 'machine_max_acceleration_retracting': ['1500'],
 'machine_max_acceleration_x': ['3000'],
 'machine_max_acceleration_y': ['3000'],
 'machine_max_acceleration_z': ['500'],
 'machine_max_jerk_e': ['2.5'],
 'machine_max_jerk_x': ['20'],
 'machine_max_jerk_y': ['20'],
 'machine_max_jerk_z': ['0.4'],
 'machine_max_speed_e': ['120'],
 'machine_max_speed_x': ['500'],
 'machine_max_speed_y': ['500'],
 'machine_max_speed_z': ['12'],
 'machine_min_extruding_rate': ['0'],
 'machine_min_travel_rate': ['0'],
 'machine_start_gcode': '',
 'max_layer_height': ['0.3'],
 'min_layer_height': ['0.07'],
 'name': 'fdm_machine_common',
 'nozzle_diameter': ['0.4'],
 'printable_height': '212',
 'printer_settings_id': '',
 'printer_technology': 'FFF',
 'printer_variant': '0.4',
 'retract_before_wipe': ['0%'],
 'retract_length_toolchange': ['10'],
 'retract_restart_extra': ['0'],
 'retract_restart_extra_toolchange': ['0'],
 'retract_when_changing_layer': ['1'],
 'retraction_length': ['6'],
 'retraction_minimum_travel': ['2'],
 'retraction_speed': ['50'],
 'silent_mode': '0',
 'single_extruder_multi_material': '1',
 'type': 'machine',
 'wipe': ['1'],
 'z_hop': ['0'],
 'z_lift_type': 'NormalLift'}
