from __future__ import annotations

# source: profiles/Qidi/filament/X4/Bambu ABS @X-Max 4.json
DATA = {'box_temperature_range_high': ['45'],
 'chamber_temperature': ['55'],
 'close_fan_the_first_x_layers': ['3'],
 'compatible_printers': [],
 'during_print_exhaust_fan_speed': ['0'],
 'fan_max_speed': ['80'],
 'fan_min_speed': ['20'],
 'filament_adhesiveness_category': ['200'],
 'filament_density': ['1.05'],
 'filament_flow_ratio': ['0.95'],
 'filament_id': 'GFB99',
 'filament_type': ['ABS'],
 'filament_vendor': ['Bambu Lab'],
 'from': 'system',
 'hot_plate_temp': ['85'],
 'hot_plate_temp_initial_layer': ['85'],
 'inherits': 'fdm_filament_x4_common',
 'instantiation': 'false',
 'name': 'Bambu ABS@X-Max 4-Series',
 'nozzle_temperature': ['260'],
 'nozzle_temperature_initial_layer': ['250'],
 'nozzle_temperature_range_high': ['280'],
 'nozzle_temperature_range_low': ['240'],
 'overhang_fan_speed': ['80'],
 'overhang_fan_threshold': ['25%'],
 'pressure_advance': ['0.026'],
 'setting_id': 'GFSA04',
 'slow_down_layer_time': ['10'],
 'temperature_vitrification': ['100'],
 'type': 'filament'}
