from __future__ import annotations

# source: profiles/Qidi/filament/X4/Generic PETG @X-Max 4.json
DATA = {'box_temperature_range_high': ['45'],
 'close_fan_the_first_x_layers': ['3'],
 'compatible_printers': [],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['90'],
 'fan_min_speed': ['40'],
 'filament_adhesiveness_category': ['300'],
 'filament_density': ['1.27'],
 'filament_flow_ratio': ['0.95'],
 'filament_id': 'QD_3_0_41',
 'filament_max_volumetric_speed': ['12'],
 'filament_type': ['PETG'],
 'filament_vendor': ['Generic'],
 'from': 'system',
 'hot_plate_temp': ['70'],
 'hot_plate_temp_initial_layer': ['70'],
 'inherits': 'fdm_filament_x4_common',
 'instantiation': 'false',
 'name': 'Generic PETG@X-Max 4-Series',
 'nozzle_temperature': ['250'],
 'nozzle_temperature_initial_layer': ['245'],
 'nozzle_temperature_range_high': ['270'],
 'nozzle_temperature_range_low': ['220'],
 'overhang_fan_speed': ['90'],
 'overhang_fan_threshold': ['10%'],
 'pressure_advance': ['0.056'],
 'setting_id': 'GFSG99',
 'slow_down_layer_time': ['12'],
 'supertack_plate_temp': ['70'],
 'supertack_plate_temp_initial_layer': ['70'],
 'temperature_vitrification': ['70'],
 'type': 'filament'}
