from __future__ import annotations

# source: profiles/Qidi/filament/X4/Generic ABS @X-Max 4.json
DATA = {'box_temperature_range_high': ['45'],
 'chamber_temperature': ['55'],
 'close_fan_the_first_x_layers': ['3'],
 'compatible_printers': [],
 'during_print_exhaust_fan_speed': ['0'],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['80'],
 'fan_min_speed': ['10'],
 'filament_adhesiveness_category': ['200'],
 'filament_density': ['1.04'],
 'filament_flow_ratio': ['0.95'],
 'filament_id': 'QD_3_0_11',
 'filament_max_volumetric_speed': ['17'],
 'filament_type': ['ABS'],
 'filament_vendor': ['Generic'],
 'from': 'system',
 'hot_plate_temp': ['85'],
 'hot_plate_temp_initial_layer': ['85'],
 'inherits': 'fdm_filament_x4_common',
 'instantiation': 'false',
 'name': 'Generic ABS@X-Max 4-Series',
 'nozzle_temperature': ['250'],
 'nozzle_temperature_initial_layer': ['250'],
 'nozzle_temperature_range_high': ['280'],
 'nozzle_temperature_range_low': ['240'],
 'overhang_fan_speed': ['80'],
 'overhang_fan_threshold': ['25%'],
 'pressure_advance': ['0.021'],
 'setting_id': 'GFSA04',
 'slow_down_layer_time': ['4'],
 'temperature_vitrification': ['100'],
 'type': 'filament'}
