from __future__ import annotations

# source: profiles/Qidi/filament/X4/Generic PLA Silk @X-Max 4.json
DATA = {'additional_cooling_fan_speed': ['100'],
 'compatible_printers': [],
 'filament_adhesiveness_category': ['100'],
 'filament_density': ['1.2'],
 'filament_id': 'QD_3_0_4',
 'filament_max_volumetric_speed': ['7.5'],
 'filament_retraction_length': ['0.5'],
 'filament_type': ['PLA'],
 'filament_vendor': ['Generic'],
 'from': 'system',
 'hot_plate_temp': ['55'],
 'hot_plate_temp_initial_layer': ['55'],
 'inherits': 'fdm_filament_x4_common',
 'instantiation': 'false',
 'name': 'Generic PLA Silk@X-Max 4-Series',
 'nozzle_temperature': ['220'],
 'nozzle_temperature_initial_layer': ['220'],
 'nozzle_temperature_range_high': ['240'],
 'nozzle_temperature_range_low': ['190'],
 'overhang_fan_threshold': ['50%'],
 'pressure_advance': ['0.032'],
 'setting_id': 'GFSL99_01',
 'supertack_plate_temp': ['35'],
 'supertack_plate_temp_initial_layer': ['35'],
 'temperature_vitrification': ['45'],
 'type': 'filament'}
