from __future__ import annotations

# source: profiles/Qidi/filament/X4/QIDI TPU 95A-HF @X-Max 4.json
DATA = {'compatible_printers': [],
 'fan_cooling_layer_time': ['100'],
 'filament_adhesiveness_category': ['600'],
 'filament_density': ['1.15'],
 'filament_deretraction_speed': ['10'],
 'filament_flow_ratio': ['1'],
 'filament_id': 'QD_3_1_50',
 'filament_max_volumetric_speed': ['8'],
 'filament_retraction_length': ['2'],
 'filament_retraction_speed': ['10'],
 'filament_type': ['TPU'],
 'filament_vendor': ['QIDI'],
 'from': 'system',
 'hot_plate_temp': ['35'],
 'hot_plate_temp_initial_layer': ['35'],
 'impact_strength_z': ['88.7'],
 'inherits': 'fdm_filament_x4_common',
 'instantiation': 'false',
 'name': 'QIDI TPU 95A-HF@X-Max 4-Series',
 'nozzle_temperature': ['230'],
 'nozzle_temperature_initial_layer': ['230'],
 'nozzle_temperature_range_high': ['250'],
 'nozzle_temperature_range_low': ['200'],
 'pressure_advance': ['0.1'],
 'setting_id': 'GFSR99',
 'temperature_vitrification': ['30'],
 'type': 'filament'}
