from __future__ import annotations

# source: profiles/Qidi/filament/X4/QIDI PLA Rapido Matte @X-Max 4.json
DATA = {'additional_cooling_fan_speed': ['100'],
 'compatible_printers': [],
 'fan_cooling_layer_time': ['100'],
 'fan_min_speed': ['60'],
 'filament_adhesiveness_category': ['100'],
 'filament_density': ['1.42'],
 'filament_id': 'QD_3_1_2',
 'filament_type': ['PLA'],
 'from': 'system',
 'hot_plate_temp': ['55'],
 'hot_plate_temp_initial_layer': ['55'],
 'impact_strength_z': ['6.6'],
 'inherits': 'fdm_filament_x4_common',
 'instantiation': 'false',
 'name': 'QIDI PLA Rapido Matte@X-Max 4-Series',
 'nozzle_temperature': ['210'],
 'nozzle_temperature_initial_layer': ['210'],
 'nozzle_temperature_range_high': ['240'],
 'nozzle_temperature_range_low': ['190'],
 'overhang_fan_threshold': ['50%'],
 'setting_id': 'GFSL99',
 'slow_down_layer_time': ['4'],
 'supertack_plate_temp': ['45'],
 'supertack_plate_temp_initial_layer': ['45'],
 'temperature_vitrification': ['45'],
 'type': 'filament'}
