from __future__ import annotations

# source: profiles/Qidi/filament/X4/QIDI PPS-CF @X-Max 4.json
DATA = {'box_temperature': ['65'],
 'box_temperature_range_high': ['65'],
 'box_temperature_range_low': ['0'],
 'chamber_temperature': ['60'],
 'close_fan_the_first_x_layers': ['3'],
 'compatible_printers': [],
 'during_print_exhaust_fan_speed': ['0'],
 'fan_cooling_layer_time': ['5'],
 'fan_max_speed': ['30'],
 'fan_min_speed': ['0'],
 'filament_adhesiveness_category': ['801'],
 'filament_density': ['1.3'],
 'filament_flow_ratio': ['0.97'],
 'filament_id': 'QD_3_1_44',
 'filament_max_volumetric_speed': ['6'],
 'filament_type': ['PPS-CF'],
 'from': 'system',
 'hot_plate_temp': ['110'],
 'hot_plate_temp_initial_layer': ['110'],
 'impact_strength_z': ['2.8'],
 'inherits': 'fdm_filament_x4_common',
 'instantiation': 'false',
 'name': 'QIDI PPS-CF@X-Max 4-Series',
 'nozzle_temperature': ['320'],
 'nozzle_temperature_initial_layer': ['320'],
 'nozzle_temperature_range_high': ['350'],
 'nozzle_temperature_range_low': ['300'],
 'overhang_fan_speed': ['40'],
 'overhang_fan_threshold': ['0%'],
 'pressure_advance': ['0.032'],
 'setting_id': 'GFSN99',
 'slow_down_layer_time': ['2'],
 'temperature_vitrification': ['180'],
 'type': 'filament'}
