from __future__ import annotations

# source: profiles/Qidi/filament/X4/QIDI PLA Rapido Silk @X-Max 4.json
DATA = {'additional_cooling_fan_speed': ['100'],
 'compatible_printers': [],
 'fan_cooling_layer_time': ['100'],
 'filament_adhesiveness_category': ['100'],
 'filament_density': ['1.24'],
 'filament_id': 'QD_3_1_4',
 'filament_max_volumetric_speed': ['10'],
 'filament_retraction_length': ['0.4'],
 'filament_type': ['PLA'],
 'filament_wipe': ['1'],
 'filament_wipe_distance': ['1'],
 'filament_z_hop_types': ['Spiral Lift'],
 'from': 'system',
 'hot_plate_temp': ['55'],
 'hot_plate_temp_initial_layer': ['55'],
 'impact_strength_z': ['4.6'],
 'inherits': 'fdm_filament_x4_common',
 'instantiation': 'false',
 'name': 'QIDI PLA Rapido Silk@X-Max 4-Series',
 'nozzle_temperature': ['220'],
 'nozzle_temperature_initial_layer': ['220'],
 'nozzle_temperature_range_high': ['240'],
 'nozzle_temperature_range_low': ['190'],
 'overhang_fan_threshold': ['50%'],
 'pressure_advance': ['0.024'],
 'setting_id': 'GFSL99',
 'supertack_plate_temp': ['0'],
 'supertack_plate_temp_initial_layer': ['0'],
 'temperature_vitrification': ['45'],
 'type': 'filament'}
