from __future__ import annotations

# source: profiles/Qidi/filament/X4/QIDI PETG Basic @X-Max 4.json
DATA = {'box_temperature_range_high': ['45'],
 'close_fan_the_first_x_layers': ['3'],
 'compatible_printers': [],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['90'],
 'fan_min_speed': ['40'],
 'filament_adhesiveness_category': ['300'],
 'filament_flow_ratio': ['0.95'],
 'filament_id': 'QD_3_1_39',
 'filament_max_volumetric_speed': ['18'],
 'filament_type': ['PETG'],
 'from': 'system',
 'hot_plate_temp': ['70'],
 'hot_plate_temp_initial_layer': ['70'],
 'impact_strength_z': ['10.6'],
 'inherits': 'fdm_filament_x4_common',
 'instantiation': 'false',
 'name': 'QIDI PETG Basic@X-Max 4-Series',
 'nozzle_temperature': ['240'],
 'nozzle_temperature_initial_layer': ['240'],
 'nozzle_temperature_range_high': ['280'],
 'nozzle_temperature_range_low': ['240'],
 'overhang_fan_speed': ['100'],
 'overhang_fan_threshold': ['10%'],
 'pressure_advance': ['0.04'],
 'setting_id': 'GFSG99',
 'slow_down_layer_time': ['12'],
 'supertack_plate_temp': ['70'],
 'supertack_plate_temp_initial_layer': ['70'],
 'temperature_vitrification': ['70'],
 'type': 'filament'}
