from __future__ import annotations

# source: profiles/Qidi/filament/X4/QIDI UltraPA @X-Max 4.json
DATA = {'box_temperature': ['55'],
 'box_temperature_range_high': ['55'],
 'box_temperature_range_low': ['0'],
 'compatible_printers': [],
 'fan_max_speed': ['60'],
 'fan_min_speed': ['40'],
 'filament_adhesiveness_category': ['400'],
 'filament_density': ['1.21'],
 'filament_flow_ratio': ['0.96'],
 'filament_id': 'QD_3_1_24',
 'filament_max_volumetric_speed': ['4'],
 'filament_type': ['UltraPA'],
 'from': 'system',
 'hot_plate_temp': ['80'],
 'hot_plate_temp_initial_layer': ['80'],
 'impact_strength_z': ['15.5'],
 'inherits': 'fdm_filament_x4_common',
 'instantiation': 'false',
 'name': 'QIDI UltraPA@X-Max 4-Series',
 'nozzle_temperature': ['280'],
 'nozzle_temperature_initial_layer': ['280'],
 'nozzle_temperature_range_high': ['290'],
 'nozzle_temperature_range_low': ['250'],
 'pressure_advance': ['0.03'],
 'setting_id': 'GFSN98',
 'slow_down_layer_time': ['15'],
 'temperature_vitrification': ['170'],
 'type': 'filament'}
