from __future__ import annotations

# source: profiles/Qidi/filament/X4/QIDI ASA @X-Max 4.json
DATA = {'box_temperature_range_high': ['45'],
 'chamber_temperature': ['55'],
 'close_fan_the_first_x_layers': ['3'],
 'compatible_printers': [],
 'during_print_exhaust_fan_speed': ['0'],
 'fan_cooling_layer_time': ['40'],
 'fan_max_speed': ['50'],
 'fan_min_speed': ['10'],
 'filament_adhesiveness_category': ['200'],
 'filament_density': ['1.07'],
 'filament_flow_ratio': ['0.92'],
 'filament_id': 'QD_3_1_18',
 'filament_max_volumetric_speed': ['17'],
 'filament_type': ['ASA'],
 'from': 'system',
 'hot_plate_temp': ['90'],
 'hot_plate_temp_initial_layer': ['90'],
 'impact_strength_z': ['4.9'],
 'inherits': 'fdm_filament_x4_common',
 'instantiation': 'false',
 'name': 'QIDI ASA@X-Max 4-Series',
 'nozzle_temperature': ['250'],
 'nozzle_temperature_initial_layer': ['250'],
 'nozzle_temperature_range_high': ['280'],
 'nozzle_temperature_range_low': ['240'],
 'overhang_fan_speed': ['80'],
 'overhang_fan_threshold': ['25%'],
 'pressure_advance': ['0.034'],
 'setting_id': 'GFSA04',
 'slow_down_layer_time': ['10'],
 'temperature_vitrification': ['100'],
 'type': 'filament'}
