from __future__ import annotations

# source: profiles/Qidi/filament/X4/QIDI PC-ABS-FR @X-Max 4.json
DATA = {'box_temperature_range_high': ['50'],
 'chamber_temperature': ['55'],
 'close_fan_the_first_x_layers': ['3'],
 'compatible_printers': [],
 'during_print_exhaust_fan_speed': ['0'],
 'fan_cooling_layer_time': ['100'],
 'fan_max_speed': ['40'],
 'fan_min_speed': ['10'],
 'filament_adhesiveness_category': ['200'],
 'filament_density': ['1.19'],
 'filament_flow_ratio': ['0.92'],
 'filament_id': 'QD_3_1_34',
 'filament_max_volumetric_speed': ['12'],
 'filament_type': ['PC-ABS-FR'],
 'from': 'system',
 'hot_plate_temp': ['90'],
 'hot_plate_temp_initial_layer': ['90'],
 'impact_strength_z': ['8'],
 'inherits': 'fdm_filament_x4_common',
 'instantiation': 'false',
 'name': 'QIDI PC/ABS-FR@X-Max 4-Series',
 'nozzle_temperature': ['250'],
 'nozzle_temperature_initial_layer': ['250'],
 'nozzle_temperature_range_high': ['280'],
 'nozzle_temperature_range_low': ['240'],
 'overhang_fan_speed': ['90'],
 'overhang_fan_threshold': ['75%'],
 'pressure_advance': ['0.042'],
 'setting_id': 'GFSA04',
 'slow_down_layer_time': ['10'],
 'temperature_vitrification': ['100'],
 'type': 'filament'}
