from __future__ import annotations

# source: profiles/Qidi/filament/X4/QIDI UltraPA-CF25 @X-Max 4.json
DATA = {'box_temperature': ['60'],
 'box_temperature_range_high': ['65'],
 'box_temperature_range_low': ['0'],
 'chamber_temperature': ['55'],
 'close_fan_the_first_x_layers': ['3'],
 'compatible_printers': [],
 'during_print_exhaust_fan_speed': ['0'],
 'fan_cooling_layer_time': ['5'],
 'fan_max_speed': ['40'],
 'fan_min_speed': ['20'],
 'filament_adhesiveness_category': ['400'],
 'filament_density': ['1.23'],
 'filament_flow_ratio': ['0.94'],
 'filament_id': 'QD_3_1_26',
 'filament_max_volumetric_speed': ['8'],
 'filament_type': ['UltraPA-CF25'],
 'from': 'system',
 'hot_plate_temp': ['80'],
 'hot_plate_temp_initial_layer': ['80'],
 'impact_strength_z': ['15.5'],
 'inherits': 'fdm_filament_x4_common',
 'instantiation': 'false',
 'name': 'QIDI UltraPA-CF25@X-Max 4-Series',
 'nozzle_temperature': ['300'],
 'nozzle_temperature_initial_layer': ['300'],
 'nozzle_temperature_range_high': ['320'],
 'nozzle_temperature_range_low': ['300'],
 'overhang_fan_speed': ['60'],
 'overhang_fan_threshold': ['0%'],
 'pressure_advance': ['0.026'],
 'setting_id': 'GFSN99',
 'slow_down_layer_time': ['2'],
 'temperature_vitrification': ['230'],
 'type': 'filament'}
