from __future__ import annotations

# source: profiles/Qidi/filament/X4/QIDI ASA-Aero @X-Max 4.json
DATA = {'box_temperature_range_high': ['45'],
 'chamber_temperature': ['60'],
 'close_fan_the_first_x_layers': ['3'],
 'compatible_printers': [],
 'during_print_exhaust_fan_speed': ['0'],
 'fan_cooling_layer_time': ['40'],
 'fan_max_speed': ['50'],
 'fan_min_speed': ['10'],
 'filament_adhesiveness_category': ['200'],
 'filament_density': ['1.03'],
 'filament_flow_ratio': ['0.7'],
 'filament_id': 'QD_3_1_19',
 'filament_max_volumetric_speed': ['12'],
 'filament_retract_when_changing_layer': ['0'],
 'filament_retraction_length': ['0.01'],
 'filament_retraction_minimum_travel': ['0'],
 'filament_type': ['ASA-AERO'],
 'filament_wipe': ['0'],
 'filament_z_hop': ['0'],
 'from': 'system',
 'hot_plate_temp': ['90'],
 'hot_plate_temp_initial_layer': ['90'],
 'impact_strength_z': ['3.4'],
 'inherits': 'fdm_filament_x4_common',
 'instantiation': 'false',
 'name': 'QIDI ASA-Aero@X-Max 4-Series',
 'nozzle_temperature': ['260'],
 'nozzle_temperature_initial_layer': ['250'],
 'nozzle_temperature_range_high': ['280'],
 'nozzle_temperature_range_low': ['240'],
 'overhang_fan_speed': ['80'],
 'overhang_fan_threshold': ['25%'],
 'pressure_advance': ['0.021'],
 'setting_id': 'GFSA04',
 'slow_down_layer_time': ['4'],
 'temperature_vitrification': ['100'],
 'type': 'filament'}
