from __future__ import annotations

# source: profiles/Qidi/filament/X4/QIDI PA12-CF @X-Max 4.json
DATA = {'box_temperature': ['55'],
 'box_temperature_range_high': ['65'],
 'box_temperature_range_low': ['0'],
 'chamber_temperature': ['55'],
 'close_fan_the_first_x_layers': ['3'],
 'compatible_printers': [],
 'fan_cooling_layer_time': ['10'],
 'fan_max_speed': ['40'],
 'fan_min_speed': ['20'],
 'filament_adhesiveness_category': ['400'],
 'filament_density': ['1.09'],
 'filament_flow_ratio': ['0.96'],
 'filament_id': 'QD_3_1_27',
 'filament_max_volumetric_speed': ['8'],
 'filament_type': ['PA12-CF'],
 'from': 'system',
 'hot_plate_temp': ['80'],
 'hot_plate_temp_initial_layer': ['80'],
 'impact_strength_z': ['5.7'],
 'inherits': 'fdm_filament_x4_common',
 'instantiation': 'false',
 'name': 'QIDI PA12-CF@X-Max 4-Series',
 'nozzle_temperature': ['280'],
 'nozzle_temperature_initial_layer': ['280'],
 'nozzle_temperature_range_high': ['300'],
 'nozzle_temperature_range_low': ['280'],
 'overhang_fan_speed': ['40'],
 'overhang_fan_threshold': ['0%'],
 'pressure_advance': ['0.035'],
 'setting_id': 'GFSN99',
 'slow_down_layer_time': ['5'],
 'temperature_vitrification': ['100'],
 'type': 'filament'}
