from __future__ import annotations

# source: profiles/EONArena/process/fdm_process_arena_0.40_nozzle_0.8.json
DATA = {'bottom_shell_layers': '3',
 'bridge_flow': '1',
 'bridge_speed': '30',
 'from': 'system',
 'gap_infill_speed': '50',
 'inherits': 'fdm_process_arena_common',
 'initial_layer_infill_speed': '55',
 'initial_layer_line_width': '0.82',
 'initial_layer_print_height': '0.4',
 'initial_layer_speed': '35',
 'inner_wall_line_width': '0.82',
 'inner_wall_speed': '150',
 'instantiation': 'false',
 'internal_solid_infill_line_width': '0.82',
 'internal_solid_infill_speed': '150',
 'layer_height': '0.4',
 'line_width': '0.82',
 'name': 'fdm_process_arena_0.40_nozzle_0.8',
 'outer_wall_line_width': '0.82',
 'outer_wall_speed': '120',
 'overhang_1_4_speed': '0',
 'overhang_2_4_speed': '50',
 'overhang_3_4_speed': '25',
 'overhang_4_4_speed': '5',
 'sparse_infill_line_width': '0.82',
 'sparse_infill_speed': '100',
 'support_line_width': '0.82',
 'top_shell_layers': '3',
 'top_surface_line_width': '0.82',
 'top_surface_pattern': 'monotonicline',
 'top_surface_speed': '150',
 'type': 'process',
 'wall_loops': '3'}
