from __future__ import annotations

# source: profiles/Blocks/filament/Blocks Generic TPU.json
DATA = {'activate_air_filtration': ['1'],
 'additional_cooling_fan_speed': ['60'],
 'compatible_printers': ['BLOCKS Pro S100 0.4 nozzle',
                         'BLOCKS Pro S100 0.6 nozzle',
                         'BLOCKS Pro S100 0.8 nozzle',
                         'BLOCKS Pro S100 1.0 nozzle',
                         'BLOCKS Pro S100 1.2 nozzle',
                         'BLOCKS Pro S100',
                         'BLOCKS RD50 V2 0.4 nozzle',
                         'BLOCKS RD50 V2 0.6 nozzle',
                         'BLOCKS RD50 V2 0.8 nozzle',
                         'BLOCKS RD50 V2',
                         'BLOCKS RF50 0.4 nozzle',
                         'BLOCKS RF50 0.6 nozzle',
                         'BLOCKS RF50 0.8 nozzle',
                         'BLOCKS RF50'],
 'complete_print_exhaust_fan_speed': ['100'],
 'during_print_exhaust_fan_speed': ['80'],
 'fan_max_speed': ['100'],
 'fan_min_speed': ['10'],
 'filament_density': ['1.25'],
 'filament_flow_ratio': ['0.95'],
 'filament_id': 'BSFI003',
 'filament_max_volumetric_speed': ['4'],
 'filament_shrink': ['99.5%'],
 'from': 'system',
 'hot_plate_temp': ['90'],
 'hot_plate_temp_initial_layer': ['90'],
 'inherits': 'fdm_filament_tpu',
 'instantiation': 'true',
 'name': 'Blocks Generic TPU',
 'nozzle_temperature': ['250'],
 'nozzle_temperature_initial_layer': ['250'],
 'nozzle_temperature_range_high': ['280'],
 'nozzle_temperature_range_low': ['240'],
 'setting_id': 'BSSI003',
 'type': 'filament'}
