from __future__ import annotations

# source: profiles/Blocks/filament/Blocks Generic PETG.json
DATA = {'activate_air_filtration': ['1'],
 'additional_cooling_fan_speed': ['40'],
 'close_fan_the_first_x_layers': ['1'],
 'compatible_printers': ['BLOCKS Pro S100 0.4 nozzle',
                         'BLOCKS Pro S100 0.6 nozzle',
                         'BLOCKS Pro S100 0.8 nozzle',
                         'BLOCKS Pro S100 1.0 nozzle',
                         'BLOCKS Pro S100 1.2 nozzle',
                         'BLOCKS Pro S100',
                         'BLOCKS RD50 V2 0.4 nozzle',
                         'BLOCKS RD50 V2 0.6 nozzle',
                         'BLOCKS RD50 V2 0.8 nozzle',
                         'BLOCKS RD50 V2',
                         'BLOCKS RF50 0.4 nozzle',
                         'BLOCKS RF50 0.6 nozzle',
                         'BLOCKS RF50 0.8 nozzle',
                         'BLOCKS RF50'],
 'complete_print_exhaust_fan_speed': ['80'],
 'during_print_exhaust_fan_speed': ['100'],
 'enable_overhang_bridge_fan': ['1'],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['80'],
 'fan_min_speed': ['40'],
 'filament_density': ['1.24'],
 'filament_flow_ratio': ['0.94'],
 'filament_id': 'BSFI002',
 'filament_max_volumetric_speed': ['12'],
 'filament_shrink': ['99.9%'],
 'from': 'system',
 'hot_plate_temp': ['70'],
 'hot_plate_temp_initial_layer': ['70'],
 'inherits': 'fdm_filament_petg',
 'instantiation': 'true',
 'name': 'Blocks Generic PETG',
 'nozzle_temperature': ['245'],
 'nozzle_temperature_initial_layer': ['250'],
 'nozzle_temperature_range_high': ['270'],
 'nozzle_temperature_range_low': ['210'],
 'overhang_fan_speed': ['100%'],
 'overhang_fan_threshold': ['25%'],
 'reduce_fan_stop_start_freq': ['1'],
 'setting_id': 'BSSI002',
 'slow_down_for_layer_cooling': ['1'],
 'slow_down_layer_time': ['5'],
 'slow_down_min_speed': ['30'],
 'type': 'filament'}
