from __future__ import annotations

# source: profiles/Blocks/filament/Blocks Generic PLA.json
DATA = {'activate_air_filtration': ['1'],
 'additional_cooling_fan_speed': ['100'],
 'compatible_printers': ['BLOCKS Pro S100 0.4 nozzle',
                         'BLOCKS Pro S100 0.6 nozzle',
                         'BLOCKS Pro S100 0.8 nozzle',
                         'BLOCKS Pro S100 1.0 nozzle',
                         'BLOCKS Pro S100 1.2 nozzle',
                         'BLOCKS Pro S100',
                         'BLOCKS RD50 V2 0.4 nozzle',
                         'BLOCKS RD50 V2 0.6 nozzle',
                         'BLOCKS RD50 V2 0.8 nozzle',
                         'BLOCKS RD50 V2',
                         'BLOCKS RF50 0.4 nozzle',
                         'BLOCKS RF50 0.6 nozzle',
                         'BLOCKS RF50 0.8 nozzle',
                         'BLOCKS RF50'],
 'complete_print_exhaust_fan_speed': ['80'],
 'during_print_exhaust_fan_speed': ['100'],
 'filament_flow_ratio': ['0.95'],
 'filament_id': 'BSFI001',
 'filament_max_volumetric_speed': ['18'],
 'from': 'system',
 'inherits': 'fdm_filament_pla',
 'instantiation': 'true',
 'name': 'Blocks Generic PLA',
 'nozzle_temperature': ['210'],
 'nozzle_temperature_initial_layer': ['210'],
 'nozzle_temperature_range_high': ['230'],
 'nozzle_temperature_range_low': ['190'],
 'setting_id': 'BSSI001',
 'slow_down_min_speed': ['30'],
 'type': 'filament'}
