from __future__ import annotations

# source: profiles/Blocks/filament/Blocks Generic ABS.json
DATA = {'activate_air_filtration': ['1'],
 'additional_cooling_fan_speed': ['0'],
 'close_fan_the_first_x_layers': ['4'],
 'compatible_printers': ['BLOCKS RD50 V2 0.4 nozzle',
                         'BLOCKS RD50 V2 0.6 nozzle',
                         'BLOCKS RD50 V2 0.8 nozzle',
                         'BLOCKS RD50 V2',
                         'BLOCKS RF50 0.4 nozzle',
                         'BLOCKS RF50 0.6 nozzle',
                         'BLOCKS RF50 0.8 nozzle',
                         'BLOCKS RF50'],
 'complete_print_exhaust_fan_speed': ['100'],
 'during_print_exhaust_fan_speed': ['100'],
 'enable_overhang_bridge_fan': ['1'],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['100'],
 'fan_min_speed': ['10'],
 'filament_density': ['1.04'],
 'filament_flow_ratio': ['0.95'],
 'filament_id': 'BSFI004',
 'filament_max_volumetric_speed': ['18'],
 'filament_shrink': ['99.5%'],
 'from': 'system',
 'hot_plate_temp': ['90'],
 'hot_plate_temp_initial_layer': ['90'],
 'inherits': 'fdm_filament_abs',
 'instantiation': 'true',
 'name': 'Blocks Generic ABS',
 'nozzle_temperature': ['255'],
 'nozzle_temperature_initial_layer': ['255'],
 'nozzle_temperature_range_high': ['280'],
 'nozzle_temperature_range_low': ['230'],
 'overhang_fan_speed': ['100%'],
 'overhang_fan_threshold': ['25%'],
 'reduce_fan_stop_start_freq': ['1'],
 'setting_id': 'BSSI004',
 'slow_down_for_layer_cooling': ['1'],
 'slow_down_layer_time': ['10'],
 'slow_down_min_speed': ['30'],
 'type': 'filament'}
