from __future__ import annotations

# source: profiles/Blocks/filament/fdm_filament_pa.json
DATA = {'close_fan_the_first_x_layers': ['3'],
 'cool_plate_temp': ['0'],
 'cool_plate_temp_initial_layer': ['0'],
 'eng_plate_temp': ['100'],
 'eng_plate_temp_initial_layer': ['100'],
 'fan_cooling_layer_time': ['10'],
 'fan_max_speed': ['60'],
 'fan_min_speed': ['0'],
 'filament_cost': ['20'],
 'filament_density': ['1.04'],
 'filament_max_volumetric_speed': ['8'],
 'filament_retraction_length': ['1.0'],
 'filament_type': ['PA'],
 'filament_z_hop': ['0.0'],
 'from': 'system',
 'hot_plate_temp': ['100'],
 'hot_plate_temp_initial_layer': ['100'],
 'inherits': 'fdm_filament_common',
 'instantiation': 'false',
 'name': 'fdm_filament_pa',
 'nozzle_temperature': ['270'],
 'nozzle_temperature_initial_layer': ['270'],
 'nozzle_temperature_range_high': ['300'],
 'nozzle_temperature_range_low': ['260'],
 'overhang_fan_speed': ['60'],
 'reduce_fan_stop_start_freq': ['0'],
 'slow_down_for_layer_cooling': ['1'],
 'slow_down_layer_time': ['2'],
 'slow_down_min_speed': ['10'],
 'temperature_vitrification': ['108'],
 'textured_plate_temp': ['100'],
 'textured_plate_temp_initial_layer': ['100'],
 'type': 'filament'}
