from __future__ import annotations

# source: profiles/Blocks/filament/fdm_filament_petg.json
DATA = {'additional_cooling_fan_speed': ['0'],
 'close_fan_the_first_x_layers': ['1'],
 'cool_plate_temp': ['70'],
 'cool_plate_temp_initial_layer': ['70'],
 'eng_plate_temp': ['70'],
 'eng_plate_temp_initial_layer': ['70'],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['80'],
 'fan_min_speed': ['20'],
 'filament_cost': ['30'],
 'filament_density': ['1.24'],
 'filament_max_volumetric_speed': ['20'],
 'filament_retraction_length': ['1.0'],
 'filament_start_gcode': ['; filament start gcode\n'],
 'filament_type': ['PETG'],
 'filament_z_hop': ['0.0'],
 'from': 'system',
 'hot_plate_temp': ['70'],
 'hot_plate_temp_initial_layer': ['70'],
 'inherits': 'fdm_filament_common',
 'instantiation': 'false',
 'name': 'fdm_filament_petg',
 'nozzle_temperature': ['240'],
 'nozzle_temperature_initial_layer': ['245'],
 'nozzle_temperature_range_high': ['255'],
 'nozzle_temperature_range_low': ['210'],
 'overhang_fan_speed': ['70'],
 'overhang_fan_threshold': ['25%'],
 'reduce_fan_stop_start_freq': ['1'],
 'slow_down_for_layer_cooling': ['1'],
 'slow_down_layer_time': ['5'],
 'slow_down_min_speed': ['30'],
 'temperature_vitrification': ['70'],
 'textured_plate_temp': ['70'],
 'textured_plate_temp_initial_layer': ['70'],
 'type': 'filament'}
