from __future__ import annotations

# source: profiles/Qidi/filament/Q2/Generic PLA+ @Q2.json
DATA = {'additional_cooling_fan_speed': ['0'],
 'compatible_printers': [],
 'filament_adhesiveness_category': ['100'],
 'filament_density': ['1.2'],
 'filament_id': 'GFL99',
 'filament_max_volumetric_speed': ['12'],
 'filament_type': ['PLA'],
 'filament_vendor': ['Generic'],
 'from': 'system',
 'inherits': 'fdm_filament_q_common',
 'instantiation': 'false',
 'name': 'Generic PLA+@Q2-Series',
 'nozzle_temperature': ['230'],
 'nozzle_temperature_initial_layer': ['230'],
 'nozzle_temperature_range_high': ['240'],
 'nozzle_temperature_range_low': ['190'],
 'overhang_fan_threshold': ['50%'],
 'setting_id': 'GFSL99',
 'supertack_plate_temp': ['45'],
 'supertack_plate_temp_initial_layer': ['45'],
 'temperature_vitrification': ['45'],
 'type': 'filament'}
