from __future__ import annotations

# source: profiles/Qidi/filament/Q2/PolyLite PLA @Q2.json
DATA = {'additional_cooling_fan_speed': ['100'],
 'additional_cooling_fan_speed_unseal': ['100'],
 'compatible_printers': [],
 'filament_adhesiveness_category': ['100'],
 'filament_density': ['1.2'],
 'filament_flow_ratio': ['1'],
 'filament_id': 'GFL99',
 'filament_max_volumetric_speed': ['11'],
 'filament_type': ['PLA'],
 'filament_vendor': ['Polymaker'],
 'from': 'system',
 'inherits': 'fdm_filament_q_common',
 'instantiation': 'false',
 'name': 'PolyLite PLA@Q2-Series',
 'nozzle_temperature': ['210'],
 'nozzle_temperature_initial_layer': ['210'],
 'nozzle_temperature_range_high': ['240'],
 'nozzle_temperature_range_low': ['190'],
 'overhang_fan_threshold': ['50%'],
 'setting_id': 'GFSL99',
 'slow_down_layer_time': ['10'],
 'supertack_plate_temp': ['45'],
 'supertack_plate_temp_initial_layer': ['45'],
 'temperature_vitrification': ['45'],
 'type': 'filament'}
