from __future__ import annotations

# source: profiles/Qidi/filament/Q2/PolyLite ABS @Q2.json
DATA = {'box_temperature_range_high': ['45'],
 'chamber_temperature': ['60'],
 'close_fan_the_first_x_layers': ['3'],
 'compatible_printers': [],
 'during_print_exhaust_fan_speed': ['0'],
 'fan_max_speed': ['80'],
 'fan_min_speed': ['20'],
 'filament_adhesiveness_category': ['200'],
 'filament_density': ['1.12'],
 'filament_flow_ratio': ['0.96'],
 'filament_id': 'GFB99',
 'filament_max_volumetric_speed': ['17'],
 'filament_type': ['ABS'],
 'filament_vendor': ['Polymaker'],
 'from': 'system',
 'hot_plate_temp': ['90'],
 'hot_plate_temp_initial_layer': ['90'],
 'inherits': 'fdm_filament_q_common',
 'instantiation': 'false',
 'name': 'PolyLite ABS@Q2-Series',
 'nozzle_temperature': ['255'],
 'nozzle_temperature_initial_layer': ['250'],
 'nozzle_temperature_range_high': ['280'],
 'nozzle_temperature_range_low': ['240'],
 'overhang_fan_speed': ['80'],
 'overhang_fan_threshold': ['25%'],
 'pressure_advance': ['0.033'],
 'setting_id': 'GFSA04',
 'slow_down_layer_time': ['6'],
 'temperature_vitrification': ['100'],
 'type': 'filament'}
