from __future__ import annotations

# source: profiles/Qidi/filament/Q2/QIDI PETG-GF @Q2.json
DATA = {'box_temperature_range_high': ['45'],
 'close_fan_the_first_x_layers': ['3'],
 'compatible_printers': [],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['50'],
 'fan_min_speed': ['20'],
 'filament_adhesiveness_category': ['300'],
 'filament_flow_ratio': ['0.95'],
 'filament_id': 'QD_1_1_43',
 'filament_max_volumetric_speed': ['8'],
 'filament_type': ['PETG-GF'],
 'from': 'system',
 'hot_plate_temp': ['80'],
 'hot_plate_temp_initial_layer': ['80'],
 'impact_strength_z': ['10.6'],
 'inherits': 'fdm_filament_q_common',
 'instantiation': 'false',
 'name': 'QIDI PETG-GF@Q2-Series',
 'nozzle_temperature': ['255'],
 'nozzle_temperature_initial_layer': ['255'],
 'nozzle_temperature_range_high': ['270'],
 'nozzle_temperature_range_low': ['240'],
 'overhang_fan_speed': ['100'],
 'overhang_fan_threshold': ['10%'],
 'pressure_advance': ['0.056'],
 'setting_id': 'GFSG99',
 'slow_down_layer_time': ['8'],
 'supertack_plate_temp': ['70'],
 'supertack_plate_temp_initial_layer': ['70'],
 'temperature_vitrification': ['70'],
 'type': 'filament'}
