from __future__ import annotations

# source: profiles/Qidi/filament/Q2/QIDI PAHT-CF @Q2.json
DATA = {'box_temperature': ['60'],
 'box_temperature_range_high': ['65'],
 'box_temperature_range_low': ['0'],
 'close_fan_the_first_x_layers': ['3'],
 'compatible_printers': [],
 'fan_cooling_layer_time': ['10'],
 'fan_max_speed': ['40'],
 'fan_min_speed': ['20'],
 'filament_adhesiveness_category': ['400'],
 'filament_density': ['1.2'],
 'filament_flow_ratio': ['0.96'],
 'filament_id': 'QD_1_1_30',
 'filament_max_volumetric_speed': ['8'],
 'filament_type': ['PAHT-CF'],
 'from': 'system',
 'hot_plate_temp': ['80'],
 'hot_plate_temp_initial_layer': ['80'],
 'impact_strength_z': ['13.3'],
 'inherits': 'fdm_filament_q_common',
 'instantiation': 'false',
 'name': 'QIDI PAHT-CF@Q2-Series',
 'nozzle_temperature': ['300'],
 'nozzle_temperature_initial_layer': ['300'],
 'nozzle_temperature_range_high': ['320'],
 'nozzle_temperature_range_low': ['300'],
 'overhang_fan_speed': ['40'],
 'overhang_fan_threshold': ['0%'],
 'pressure_advance': ['0.032'],
 'setting_id': 'GFSN99',
 'slow_down_layer_time': ['5'],
 'temperature_vitrification': ['180'],
 'type': 'filament'}
