from __future__ import annotations

# source: profiles/Qidi/filament/Q2/QIDI Support For PAHT @Q2.json
DATA = {'box_temperature': ['60'],
 'box_temperature_range_high': ['65'],
 'box_temperature_range_low': ['0'],
 'close_fan_the_first_x_layers': ['3'],
 'compatible_printers': [],
 'fan_cooling_layer_time': ['10'],
 'fan_max_speed': ['60'],
 'fan_min_speed': ['0'],
 'filament_adhesiveness_category': ['800'],
 'filament_density': ['1.26'],
 'filament_flow_ratio': ['0.94'],
 'filament_id': 'QD_1_1_32',
 'filament_is_support': ['1'],
 'filament_max_volumetric_speed': ['8'],
 'filament_type': ['PAHT-S'],
 'from': 'system',
 'hot_plate_temp': ['80'],
 'hot_plate_temp_initial_layer': ['80'],
 'impact_strength_z': ['4.5'],
 'inherits': 'fdm_filament_q_common',
 'instantiation': 'false',
 'name': 'QIDI Support For PAHT@Q2-Series',
 'nozzle_temperature': ['280'],
 'nozzle_temperature_initial_layer': ['280'],
 'nozzle_temperature_range_high': ['280'],
 'nozzle_temperature_range_low': ['260'],
 'overhang_fan_speed': ['30'],
 'overhang_fan_threshold': ['95%'],
 'pressure_advance': ['0.02'],
 'setting_id': 'GFSN95',
 'slow_down_layer_time': ['6'],
 'supertack_plate_temp': ['80'],
 'supertack_plate_temp_initial_layer': ['80'],
 'temperature_vitrification': ['218'],
 'type': 'filament'}
