from __future__ import annotations

# source: profiles/Qidi/filament/Q2/QIDI ABS-GF @Q2.json
DATA = {'box_temperature': ['45'],
 'box_temperature_range_high': ['45'],
 'box_temperature_range_low': ['0'],
 'chamber_temperatures': ['0'],
 'close_fan_the_first_x_layers': ['3'],
 'compatible_printers': [],
 'during_print_exhaust_fan_speed': ['0'],
 'fan_max_speed': ['20'],
 'fan_min_speed': ['20'],
 'filament_adhesiveness_category': ['200'],
 'filament_density': ['1.15'],
 'filament_flow_ratio': ['0.95'],
 'filament_id': 'QD_1_1_12',
 'filament_max_volumetric_speed': ['12'],
 'filament_type': ['ABS-GF'],
 'from': 'system',
 'hot_plate_temp': ['90'],
 'hot_plate_temp_initial_layer': ['90'],
 'impact_strength_z': ['5.3'],
 'inherits': 'fdm_filament_q_common',
 'instantiation': 'false',
 'name': 'QIDI ABS-GF@Q2-Series',
 'nozzle_temperature': ['270'],
 'nozzle_temperature_initial_layer': ['260'],
 'nozzle_temperature_range_high': ['280'],
 'nozzle_temperature_range_low': ['240'],
 'overhang_fan_speed': ['80'],
 'overhang_fan_threshold': ['25%'],
 'pressure_advance': ['0.035'],
 'setting_id': 'GFSA04',
 'slow_down_layer_time': ['5'],
 'temperature_vitrification': ['100'],
 'type': 'filament'}
