from __future__ import annotations

# source: profiles/Qidi/filament/Q2/QIDI TPU-Aero @Q2.json
DATA = {'compatible_printers': [],
 'fan_cooling_layer_time': ['100'],
 'filament_adhesiveness_category': ['600'],
 'filament_density': ['1.15'],
 'filament_flow_ratio': ['0.5'],
 'filament_id': 'QD_1_1_49',
 'filament_max_volumetric_speed': ['6'],
 'filament_retraction_length': ['0'],
 'filament_type': ['TPU-AERO'],
 'filament_vendor': ['QIDI'],
 'from': 'system',
 'hot_plate_temp': ['35'],
 'hot_plate_temp_initial_layer': ['35'],
 'impact_strength_z': ['88.7'],
 'inherits': 'fdm_filament_q_common',
 'instantiation': 'false',
 'name': 'QIDI TPU-Aero@Q2-Series',
 'nozzle_temperature': ['250'],
 'nozzle_temperature_initial_layer': ['250'],
 'nozzle_temperature_range_high': ['270'],
 'nozzle_temperature_range_low': ['230'],
 'pressure_advance': ['0.03'],
 'setting_id': 'GFSR98',
 'slow_down_layer_time': ['14'],
 'temperature_vitrification': ['30'],
 'type': 'filament'}
