from __future__ import annotations

# source: profiles/Snapmaker/process/0.06 Standard @Snapmaker J1 (0.2 nozzle).json
DATA = {'bottom_shell_layers': '4',
 'bridge_flow': '1',
 'compatible_printers': ['Snapmaker J1 (0.2 nozzle)'],
 'from': 'system',
 'inherits': 'fdm_process_idex',
 'initial_layer_infill_speed': '80',
 'initial_layer_line_width': '0.25',
 'initial_layer_print_height': '0.1',
 'inner_wall_line_width': '0.22',
 'inner_wall_speed': '145',
 'instantiation': 'true',
 'internal_solid_infill_line_width': '0.22',
 'layer_height': '0.06',
 'line_width': '0.22',
 'name': '0.06 Standard @Snapmaker J1 (0.2 nozzle)',
 'outer_wall_line_width': '0.22',
 'setting_id': '4149563988',
 'sparse_infill_line_width': '0.22',
 'support_line_width': '0.22',
 'top_shell_layers': '5',
 'top_surface_line_width': '0.22',
 'type': 'process',
 'wall_loops': '4'}
