from __future__ import annotations

# source: profiles/Snapmaker/process/0.06 Standard @Snapmaker Artisan (0.2 nozzle).json
DATA = {'bottom_shell_layers': '4',
 'bridge_flow': '1',
 'compatible_printers': ['Snapmaker Artisan (0.2 nozzle)'],
 'from': 'system',
 'initial_layer_infill_speed': '70',
 'initial_layer_line_width': '0.25',
 'initial_layer_print_height': '0.1',
 'initial_layer_speed': '40',
 'inner_wall_line_width': '0.22',
 'inner_wall_speed': '150',
 'instantiation': 'true',
 'internal_solid_infill_line_width': '0.22',
 'layer_height': '0.06',
 'line_width': '0.22',
 'name': '0.06 Standard @Snapmaker Artisan (0.2 nozzle)',
 'outer_wall_line_width': '0.22',
 'setting_id': '3200425436',
 'sparse_infill_line_width': '0.22',
 'support_line_width': '0.22',
 'top_shell_layers': '5',
 'top_surface_line_width': '0.22',
 'type': 'process',
 'wall_loops': '4'}
