from __future__ import annotations

# source: profiles/Snapmaker/process/0.24 Draft @Snapmaker (0.4 nozzle).json
DATA = {'compatible_printers': ['Snapmaker A250 (0.4 nozzle)',
                         'Snapmaker A350 (0.4 nozzle)',
                         'Snapmaker A250 Dual (0.4 nozzle)',
                         'Snapmaker A350 Dual (0.4 nozzle)',
                         'Snapmaker A250 QSKit (0.4 nozzle)',
                         'Snapmaker A350 QSKit (0.4 nozzle)',
                         'Snapmaker A250 BKit (0.4 nozzle)',
                         'Snapmaker A350 BKit (0.4 nozzle)',
                         'Snapmaker A250 QS+B Kit (0.4 nozzle)',
                         'Snapmaker A350 QS+B Kit (0.4 nozzle)',
                         'Snapmaker A250 Dual QSKit (0.4 nozzle)',
                         'Snapmaker A350 Dual QSKit (0.4 nozzle)',
                         'Snapmaker A250 Dual BKit (0.4 nozzle)',
                         'Snapmaker A350 Dual BKit (0.4 nozzle)',
                         'Snapmaker A250 Dual QS+B Kit (0.4 nozzle)',
                         'Snapmaker A350 Dual QS+B Kit (0.4 nozzle)'],
 'elefant_foot_compensation': '0.15',
 'from': 'system',
 'gap_infill_speed': '85',
 'inherits': 'fdm_process_common',
 'initial_layer_infill_speed': '65',
 'inner_wall_speed': '100',
 'instantiation': 'true',
 'ironing_speed': '30',
 'layer_height': '0.24',
 'name': '0.24 Draft @Snapmaker (0.4 nozzle)',
 'outer_wall_speed': '90',
 'overhang_1_4_speed': '55',
 'overhang_2_4_speed': '30',
 'overhang_3_4_speed': '10',
 'setting_id': '1966563644',
 'sparse_infill_speed': '100',
 'support_speed': '100',
 'support_threshold_angle': '35',
 'top_shell_layers': '3',
 'top_shell_thickness': '0.6',
 'top_surface_line_width': '0.45',
 'top_surface_speed': '70',
 'type': 'process'}
