from __future__ import annotations

# source: profiles/Snapmaker/process/0.25 Benchy @Snapmaker U1 (0.4 nozzle).json
DATA = {'bottom_shell_layers': '2',
 'bridge_acceleration': '3000',
 'bridge_speed': '100',
 'compatible_printers': ['Snapmaker U1 (0.4 nozzle)'],
 'default_acceleration': '3000',
 'detect_overhang_wall': '0',
 'elefant_foot_compensation': '0.15',
 'enable_overhang_speed': '0',
 'ensure_vertical_shell_thickness': 'none',
 'filename_format': 'testBenchy_{print_time}.gcode',
 'from': 'system',
 'gap_fill_target': 'nowhere',
 'gap_infill_speed': '200',
 'infill_combination': '1',
 'infill_direction': '90',
 'inherits': 'fdm_process_U1',
 'initial_layer_acceleration': '1600',
 'initial_layer_infill_speed': '180',
 'initial_layer_print_height': '0.25',
 'initial_layer_speed': '100',
 'initial_layer_travel_speed': '100%',
 'inner_wall_acceleration': '3000',
 'inner_wall_line_width': '0.5',
 'inner_wall_speed': '200',
 'instantiation': 'true',
 'internal_solid_infill_acceleration': '3000',
 'internal_solid_infill_line_width': '0.5',
 'internal_solid_infill_speed': '200',
 'ironing_speed': '30',
 'layer_height': '0.25',
 'line_width': '0.4',
 'minimum_sparse_infill_area': '0',
 'name': '0.25 Benchy @Snapmaker U1 (0.4 nozzle)',
 'outer_wall_acceleration': '1600',
 'outer_wall_line_width': '0.5',
 'outer_wall_speed': '180',
 'overhang_1_4_speed': '180',
 'overhang_2_4_speed': '20',
 'overhang_3_4_speed': '10',
 'reduce_crossing_wall': '0',
 'seam_position': 'nearest',
 'setting_id': '2853588009',
 'small_perimeter_speed': '200',
 'sparse_infill_acceleration': '3000',
 'sparse_infill_density': '10%',
 'sparse_infill_line_width': '0.5',
 'sparse_infill_pattern': 'alignedrectilinear',
 'sparse_infill_speed': '200',
 'top_shell_layers': '3',
 'top_shell_thickness': '0.5',
 'top_surface_acceleration': '3000',
 'top_surface_line_width': '0.5',
 'top_surface_speed': '180',
 'type': 'process',
 'wall_generator': 'classic',
 'wall_loops': '2'}
