from __future__ import annotations

# source: profiles/Snapmaker/process/fdm_process_a400.json
DATA = {'default_acceleration': '2000',
 'enable_arc_fitting': '1',
 'from': 'system',
 'gap_infill_speed': '160',
 'infill_jerk': '8',
 'inherits': 'fdm_process_common',
 'initial_layer_infill_speed': '75',
 'initial_layer_jerk': '8',
 'initial_layer_print_height': '0.2',
 'inner_wall_acceleration': '2000',
 'inner_wall_speed': '160',
 'instantiation': 'false',
 'internal_solid_infill_acceleration': '2000',
 'internal_solid_infill_speed': '160',
 'name': 'fdm_process_a400',
 'outer_wall_jerk': '4',
 'outer_wall_speed': '100',
 'overhang_1_4_speed': '0',
 'setting_id': '3085664947',
 'small_perimeter_threshold': '0',
 'sparse_infill_acceleration': '2000',
 'sparse_infill_speed': '160',
 'support_bottom_z_distance': '0',
 'support_filament': '1',
 'support_interface_filament': '2',
 'support_interface_pattern': 'rectilinear',
 'support_interface_top_layers': '3',
 'support_material_synchronize_layers': '1',
 'support_speed': '100',
 'support_top_z_distance': '0',
 'top_surface_jerk': '4',
 'travel_acceleration': '3000',
 'travel_jerk': '10',
 'travel_speed': '190',
 'type': 'process'}
