from __future__ import annotations

# source: profiles/Snapmaker/process/fdm_process_idex.json
DATA = {'bridge_acceleration': '2000',
 'default_acceleration': '10000',
 'enable_arc_fitting': '1',
 'filename_format': '{input_filename_base}_{layer_height}mm_{print_time}_J1.gcode',
 'from': 'system',
 'gap_infill_speed': '250',
 'infill_jerk': '8',
 'inherits': 'fdm_process_common',
 'initial_layer_infill_speed': '75',
 'initial_layer_jerk': '8',
 'initial_layer_print_height': '0.2',
 'inner_wall_acceleration': '6000',
 'inner_wall_speed': '250',
 'instantiation': 'false',
 'internal_solid_infill_acceleration': '10000',
 'internal_solid_infill_speed': '250',
 'name': 'fdm_process_idex',
 'outer_wall_jerk': '4',
 'outer_wall_speed': '120',
 'overhang_1_4_speed': '60',
 'overhang_2_4_speed': '30',
 'overhang_3_4_speed': '10',
 'preheat_time': '90',
 'setting_id': '2703811679',
 'small_perimeter_threshold': '0',
 'sparse_infill_acceleration': '10000',
 'sparse_infill_speed': '250',
 'support_bottom_z_distance': '0',
 'support_filament': '1',
 'support_interface_filament': '2',
 'support_interface_pattern': 'rectilinear',
 'support_interface_top_layers': '3',
 'support_material_synchronize_layers': '1',
 'support_speed': '100',
 'support_top_z_distance': '0',
 'top_surface_acceleration': '2000',
 'top_surface_jerk': '4',
 'travel_acceleration': '10000',
 'travel_jerk': '10',
 'travel_speed': '300',
 'type': 'process'}
