from __future__ import annotations

# source: profiles/Anker/machine/fdm_machine_common.json
DATA = {'deretraction_speed': ['60'],
 'extruder_colour': ['#018001'],
 'extruder_offset': ['0x0'],
 'from': 'system',
 'instantiation': 'false',
 'machine_max_acceleration_e': ['4000'],
 'machine_max_acceleration_extruding': ['6000'],
 'machine_max_acceleration_retracting': ['1000'],
 'machine_max_acceleration_travel': ['6000'],
 'machine_max_acceleration_x': ['6000'],
 'machine_max_acceleration_y': ['6000'],
 'machine_max_acceleration_z': ['300'],
 'machine_max_jerk_e': ['3'],
 'machine_max_jerk_x': ['12'],
 'machine_max_jerk_y': ['12'],
 'machine_max_jerk_z': ['0.3'],
 'machine_max_speed_e': ['50'],
 'machine_max_speed_x': ['600'],
 'machine_max_speed_y': ['600'],
 'machine_max_speed_z': ['30'],
 'machine_min_extruding_rate': ['0'],
 'machine_min_travel_rate': ['0'],
 'manual_filament_change': '1',
 'max_layer_height': ['0.32'],
 'min_layer_height': ['0.05'],
 'name': 'fdm_machine_common',
 'printer_settings_id': '',
 'printer_technology': 'FFF',
 'retract_before_wipe': ['0%'],
 'retract_length_toolchange': ['2'],
 'retract_restart_extra': ['0'],
 'retract_restart_extra_toolchange': ['0'],
 'retract_when_changing_layer': ['1'],
 'retraction_length': ['0.5'],
 'retraction_minimum_travel': ['1'],
 'retraction_speed': ['60'],
 'silent_mode': '0',
 'single_extruder_multi_material': '1',
 'support_air_filtration': '0',
 'support_chamber_temp_control': '0',
 'type': 'machine',
 'wipe': ['1'],
 'z_hop': ['0']}
