from __future__ import annotations

# source: profiles/Blocks/machine/BLOCKS RF50 0.4 nozzle.json
DATA = {'auxiliary_fan': '1',
 'default_print_profile': '0.20mm Standard 0.4 nozzle @Blocks_RF50',
 'deretraction_speed': ['30'],
 'extruder_clearance_height_to_lid': '185',
 'extruder_clearance_height_to_rod': '30',
 'extruder_clearance_radius': '106',
 'from': 'system',
 'inherits': 'fdm_klipper_common',
 'instantiation': 'true',
 'machine_max_acceleration_extruding': ['20000', '20000'],
 'machine_max_acceleration_x': ['20000', '20000'],
 'machine_max_acceleration_y': ['20000', '20000'],
 'machine_max_acceleration_z': ['200', '200'],
 'machine_max_speed_e': ['60'],
 'machine_max_speed_x': ['500'],
 'machine_max_speed_y': ['500'],
 'machine_max_speed_z': ['12'],
 'max_layer_height': ['0.30'],
 'min_layer_height': ['0.10'],
 'name': 'BLOCKS RF50 0.4 nozzle',
 'nozzle_diameter': ['0.4'],
 'printable_area': ['0x0', '500x0', '500x500', '0x500'],
 'printable_height': '500',
 'printer_model': 'BLOCKS RF50',
 'retract_before_wipe': ['0'],
 'retraction_length': ['1'],
 'retraction_speed': ['60'],
 'settings_id': 'GM009',
 'support_air_filtration': '1',
 'type': 'machine',
 'upward_compatible_machine': ['BLOCKS RF50'],
 'wipe_distance': ['2'],
 'z_hop': ['0.4'],
 'z_hop_types': ['Slope Lift']}
