from __future__ import annotations

# source: profiles/Blocks/machine/fdm_machine_common.json
DATA = {'before_layer_change_gcode': ';BEFORE_LAYER_CHANGE\n;[layer_z]\nG92 E0\n',
 'change_filament_gcode': 'CHANGE_FILAMENT\n',
 'deretraction_speed': ['80'],
 'extruder_clearance_height_to_lid': '0',
 'extruder_clearance_height_to_rod': '0',
 'extruder_clearance_radius': '0',
 'extruder_colour': ['#FCE94F'],
 'extruder_offset': ['0x0'],
 'from': 'system',
 'gcode_flavor': 'klipper',
 'instantiation': 'false',
 'machine_end_gcode': 'M400; wait for buffer to clear\nPRINT_END',
 'machine_max_acceleration_e': ['5000'],
 'machine_max_acceleration_extruding': ['10000'],
 'machine_max_acceleration_retracting': ['10000'],
 'machine_max_acceleration_x': ['10000'],
 'machine_max_acceleration_y': ['10000'],
 'machine_max_acceleration_z': ['100'],
 'machine_max_jerk_e': ['0'],
 'machine_max_jerk_x': ['0'],
 'machine_max_jerk_y': ['0'],
 'machine_max_jerk_z': ['0'],
 'machine_max_speed_e': ['60'],
 'machine_max_speed_x': ['300'],
 'machine_max_speed_y': ['300'],
 'machine_max_speed_z': ['10'],
 'machine_min_extruding_rate': ['0'],
 'machine_min_travel_rate': ['0'],
 'machine_start_gcode': 'PRINT_START EXTRUDER=[nozzle_temperature_inital_layer] BED=[bed_temperature_initial_layer]',
 'max_layer_height': ['1.2'],
 'min_layer_height': ['0.08'],
 'name': 'fdm_machine_common',
 'nozzle_diameter': ['0.4'],
 'printable_height': '900',
 'printer_settings_id': '',
 'printer_technology': 'FFF',
 'printer_variant': '0.4',
 'retract_before_wipe': ['70%'],
 'retract_length_toolchange': ['1'],
 'retract_restart_extra': ['0'],
 'retract_restart_extra_toolchange': ['0'],
 'retract_when_changing_layer': ['1'],
 'retraction_length': ['1'],
 'retraction_minimum_travel': ['2'],
 'retraction_speed': ['60'],
 'silent_mode': '0',
 'single_extruder_multi_material': '1',
 'type': 'machine',
 'wipe': ['1'],
 'z_hop': ['0']}
