from __future__ import annotations

# source: profiles/Blocks/machine/fdm_klipper_common.json
DATA = {'auxiliary_fan': '0',
 'bed_exclude_area': ['0x0'],
 'before_layer_change_gcode': ';BEFORE_LAYER_CHANGE\n;[layer_z]\nG92 E0\n',
 'change_filament_gcode': 'CHANGE_FILAMENT',
 'default_filament_profile': ['Blocks Generic PLA'],
 'deretraction_speed': ['35'],
 'extruder_clearance_height_to_lid': '140',
 'extruder_clearance_height_to_rod': '40',
 'extruder_clearance_radius': '74',
 'from': 'system',
 'gcode_flavor': 'klipper',
 'inherits': 'fdm_machine_common',
 'instantiation': 'false',
 'layer_change_gcode': ';AFTER_LAYER_CHANGE\n;[layer_z]\n',
 'machine_end_gcode': 'M400\nPRINT_END',
 'machine_max_acceleration_e': ['5000', '5000'],
 'machine_max_acceleration_extruding': ['20000', '20000'],
 'machine_max_acceleration_retracting': ['5000', '5000'],
 'machine_max_acceleration_travel': ['5000', '5000'],
 'machine_max_acceleration_x': ['5000', '5000'],
 'machine_max_acceleration_y': ['5000', '5000'],
 'machine_max_acceleration_z': ['500', '200'],
 'machine_max_jerk_e': ['0', '0'],
 'machine_max_jerk_x': ['0', '0'],
 'machine_max_jerk_y': ['0', '0'],
 'machine_max_jerk_z': ['0', '0'],
 'machine_max_speed_e': ['25', '25'],
 'machine_max_speed_x': ['500', '200'],
 'machine_max_speed_y': ['500', '200'],
 'machine_max_speed_z': ['12', '12'],
 'machine_min_extruding_rate': ['0', '0'],
 'machine_min_travel_rate': ['0', '0'],
 'machine_pause_gcode': 'PAUSE',
 'machine_start_gcode': 'PRINT_START EXTRUDER=[nozzle_temperature_initial_layer] BED=[bed_temperature_initial_layer]',
 'max_layer_height': ['1.2'],
 'min_layer_height': ['0.08'],
 'name': 'fdm_klipper_common',
 'nozzle_type': 'undefine',
 'printable_height': '900',
 'printer_settings_id': '',
 'printer_technology': 'FFF',
 'printer_variant': '0.4',
 'retract_before_wipe': ['70%'],
 'retract_length_toolchange': ['2'],
 'retract_restart_extra': ['0'],
 'retract_restart_extra_toolchange': ['0'],
 'retract_when_changing_layer': ['1'],
 'retraction_length': ['0.8'],
 'retraction_minimum_travel': ['1'],
 'retraction_speed': ['35'],
 'scan_first_layer': '0',
 'silent_mode': '0',
 'single_extruder_multi_material': '1',
 'type': 'machine',
 'wipe': ['1'],
 'z_hop': ['0.4'],
 'z_hop_types': 'Normal Lift'}
