from __future__ import annotations

# source: profiles/Positron3D/process/fdm_process_the_positron_common.json
DATA = {'default_acceleration': '5000',
 'default_jerk': '9',
 'exclude_object': '1',
 'from': 'system',
 'gap_infill_speed': '90',
 'infill_jerk': '12',
 'inherits': 'fdm_process_common',
 'initial_layer_acceleration': '500',
 'initial_layer_infill_speed': '105',
 'initial_layer_jerk': '7',
 'initial_layer_speed': '50',
 'inner_wall_acceleration': '3000',
 'inner_wall_jerk': '7',
 'inner_wall_speed': '100',
 'instantiation': 'false',
 'internal_solid_infill_speed': '180',
 'name': 'fdm_process_the_positron_common',
 'outer_wall_acceleration': '1500',
 'outer_wall_jerk': '7',
 'outer_wall_speed': '60',
 'sparse_infill_speed': '180',
 'top_surface_acceleration': '3000',
 'top_surface_jerk': '7',
 'top_surface_speed': '90',
 'travel_acceleration': '7000',
 'travel_jerk': '12',
 'travel_speed': '420',
 'type': 'process'}
