from __future__ import annotations

# source: profiles/Volumic/process/Compatible speed - 0.25mm.json
DATA = {'bottom_shell_layers': '3',
 'compatible_printers': ['EXO42 (0.4 nozzle)',
                         'EXO65 (0.6 nozzle)',
                         'SH65 (0.4 nozzle)',
                         'EXO42 Performance (0.4 nozzle)',
                         'EXO65 Performance (0.4 nozzle)',
                         'EXO65 Performance (0.6 nozzle)',
                         'EXO65 Performance (0.8 nozzle)',
                         'SH65 Performance (0.4 nozzle)',
                         'EXO42 IDRE (0.4 nozzle)',
                         'EXO42 IDRE COPY MODE (0.4 nozzle)',
                         'EXO42 IDRE MIRROR MODE (0.4 nozzle)',
                         'EXO65 IDRE (0.4 nozzle)',
                         'EXO65 IDRE COPY MODE (0.4 nozzle)',
                         'EXO65 IDRE MIRROR MODE (0.4 nozzle)',
                         'SH65 IDRE (0.4 nozzle)',
                         'SH65 IDRE COPY MODE (0.4 nozzle)',
                         'SH65 IDRE MIRROR MODE (0.4 nozzle)',
                         'VS30MK3 (0.4 nozzle)',
                         'VS30SC2 (0.4 nozzle)',
                         'VS30SC (0.4 nozzle)',
                         'VS30ULTRA (0.4 nozzle)',
                         'VS30MK2 (0.4 nozzle)',
                         'VS20MK2 (0.4 nozzle)',
                         'EXO42 Stage 2 (0.4 nozzle)',
                         'EXO65 Stage 2 (0.6 nozzle)',
                         'SH65 Stage 2 (0.4 nozzle)',
                         'VS30SC2 Stage 2 (0.4 nozzle)',
                         'VS30MK3 Stage 2 (0.4 nozzle)'],
 'from': 'system',
 'gap_infill_speed': '60',
 'inherits': 'fdm_process_volumic_common',
 'initial_layer_infill_speed': '50',
 'initial_layer_print_height': '0.25',
 'initial_layer_speed': '50',
 'inner_wall_speed': '60',
 'instantiation': 'true',
 'internal_solid_infill_speed': '60',
 'layer_height': '0.25',
 'name': 'Compatible speed - 0.25mm',
 'outer_wall_speed': '40',
 'setting_id': 'GP004',
 'skirt_speed': '60',
 'sparse_infill_speed': '60',
 'support_interface_speed': '60',
 'support_speed': '60',
 'top_shell_layers': '3',
 'top_surface_speed': '60',
 'travel_speed': '60',
 'type': 'process'}
