from __future__ import annotations

# source: profiles/Volumic/process/fdm_process_volumic_common.json
DATA = {'accel_to_decel_enable': '0',
 'adaptive_layer_height': '0',
 'bottom_shell_layers': '5',
 'bottom_shell_thickness': '0',
 'bottom_surface_pattern': 'monotonic',
 'bridge_acceleration': ['0', '0'],
 'bridge_flow': '1',
 'bridge_no_support': '0',
 'bridge_speed': '100',
 'brim_object_gap': '0',
 'brim_type': 'no_brim',
 'brim_width': '6',
 'default_acceleration': ['0', '0'],
 'detect_overhang_wall': '1',
 'detect_thin_wall': '0',
 'draft_shield': 'disabled',
 'elefant_foot_compensation': '0',
 'enable_arc_fitting': '0',
 'enable_overhang_speed': '1',
 'enable_prime_tower': '0',
 'enable_support': '0',
 'extra_perimeters_on_overhangs': '1',
 'filename_format': '{input_filename_base}_{filament_type[initial_tool]}_{print_time}.gcode',
 'from': 'system',
 'gap_infill_speed': '30',
 'infill_anchor': '20%',
 'infill_combination': '1',
 'infill_combination_max_layer_height': '75%',
 'infill_direction': '45',
 'infill_wall_overlap': '20%',
 'initial_layer_acceleration': ['0', '0'],
 'initial_layer_infill_speed': '20',
 'initial_layer_line_width': '120%',
 'initial_layer_speed': '15',
 'inner_wall_acceleration': ['0', '0'],
 'inner_wall_line_width': '120%',
 'inner_wall_speed': '80',
 'instantiation': 'false',
 'interface_shells': '0',
 'internal_bridge_speed': '100',
 'internal_solid_infill_acceleration': ['0', '0'],
 'internal_solid_infill_line_width': '120%',
 'internal_solid_infill_speed': '40',
 'ironing_flow': '30%',
 'ironing_spacing': '0.1',
 'ironing_speed': '40',
 'ironing_type': 'no ironing',
 'layer_height': '0.2',
 'line_width': '120%',
 'max_travel_detour_distance': '0',
 'minimum_sparse_infill_area': '15',
 'name': 'fdm_process_volumic_common',
 'outer_wall_acceleration': ['0', '0'],
 'outer_wall_line_width': '120%',
 'outer_wall_speed': '60',
 'overhang_1_4_speed': '0',
 'overhang_2_4_speed': '0',
 'overhang_3_4_speed': '100',
 'overhang_4_4_speed': '100',
 'overhang_reverse': '1',
 'precise_outer_wall': '1',
 'prime_tower_width': '60',
 'print_sequence': 'by layer',
 'print_settings_id': '',
 'raft_first_layer_expansion': '0',
 'raft_layers': '0',
 'reduce_crossing_wall': '1',
 'reduce_infill_retraction': '1',
 'resolution': '0.01',
 'seam_position': 'aligned',
 'skirt_distance': '2',
 'skirt_height': '1',
 'skirt_loops': '1',
 'sparse_infill_acceleration': ['0', '0'],
 'sparse_infill_density': '25%',
 'sparse_infill_line_width': '120%',
 'sparse_infill_pattern': 'grid',
 'sparse_infill_speed': '50',
 'spiral_mode': '0',
 'standby_temperature_delta': '-5',
 'support_angle': '45',
 'support_base_pattern': 'lightning',
 'support_base_pattern_spacing': '2.5',
 'support_bottom_interface_spacing': '0.5',
 'support_bottom_z_distance': '0.1',
 'support_filament': '0',
 'support_interface_bottom_layers': '4',
 'support_interface_filament': '0',
 'support_interface_loop_pattern': '0',
 'support_interface_spacing': '0.5',
 'support_interface_top_layers': '4',
 'support_line_width': '120%',
 'support_object_xy_distance': '0.35',
 'support_on_build_plate_only': '1',
 'support_style': 'snug',
 'support_threshold_angle': '30',
 'support_top_z_distance': '0.1',
 'support_type': 'normal(auto)',
 'thick_bridges': '1',
 'top_shell_layers': '5',
 'top_shell_thickness': '0',
 'top_surface_acceleration': ['0', '0'],
 'top_surface_line_width': '120%',
 'top_surface_pattern': 'monotonicline',
 'top_surface_speed': '30',
 'travel_acceleration': ['0', '0'],
 'travel_speed': '150',
 'tree_support_branch_angle': '50',
 'tree_support_tip_diameter': '1',
 'tree_support_wall_count': '0',
 'type': 'process',
 'wall_infill_order': 'inner wall/outer wall/infill',
 'wall_loops': '3',
 'wipe_tower_extra_spacing': '200',
 'wipe_tower_no_sparse_layers': '0',
 'xy_contour_compensation': '0',
 'xy_hole_compensation': '0'}
