from __future__ import annotations

# source: profiles/Volumic/process/High performance - 0.30mm.json
DATA = {'bottom_shell_layers': '3',
 'compatible_printers': ['EXO42 Performance (0.4 nozzle)',
                         'EXO65 Performance (0.4 nozzle)',
                         'EXO65 Performance (0.6 nozzle)',
                         'EXO65 Performance (0.8 nozzle)',
                         'SH65 Performance (0.4 nozzle)',
                         'EXO42 IDRE COPY MODE (0.4 nozzle)',
                         'EXO42 IDRE MIRROR MODE (0.4 nozzle)',
                         'EXO65 IDRE COPY MODE (0.4 nozzle)',
                         'EXO65 IDRE MIRROR MODE (0.4 nozzle)',
                         'SH65 IDRE COPY MODE (0.4 nozzle)',
                         'SH65 IDRE MIRROR MODE (0.4 nozzle)'],
 'from': 'system',
 'gap_infill_speed': '280',
 'inherits': 'fdm_process_volumic_common',
 'initial_layer_infill_speed': '160',
 'initial_layer_print_height': '0.3',
 'initial_layer_speed': '160',
 'initial_layer_travel_speed': '600',
 'inner_wall_speed': '220',
 'instantiation': 'true',
 'internal_solid_infill_speed': '280',
 'layer_height': '0.3',
 'name': 'High performance - 0.30mm',
 'outer_wall_speed': '160',
 'setting_id': 'GP004',
 'skirt_speed': '200',
 'sparse_infill_speed': '280',
 'support_interface_speed': '280',
 'support_speed': '280',
 'top_shell_layers': '3',
 'top_surface_speed': '135',
 'travel_speed': '600',
 'type': 'process'}
