from __future__ import annotations

# source: profiles/Volumic/process/Normal speed (Stage 2) - 0.15mm.json
DATA = {'bottom_shell_layers': '8',
 'compatible_printers': ['EXO42 Stage 2 (0.4 nozzle)',
                         'EXO65 Stage 2 (0.6 nozzle)',
                         'SH65 Stage 2 (0.4 nozzle)',
                         'VS30SC2 Stage 2 (0.4 nozzle)',
                         'VS30MK3 Stage 2 (0.4 nozzle)'],
 'from': 'system',
 'gap_infill_speed': '130',
 'inherits': 'fdm_process_volumic_common',
 'initial_layer_infill_speed': '80',
 'initial_layer_print_height': '0.15',
 'initial_layer_speed': '80',
 'inner_wall_speed': '130',
 'instantiation': 'true',
 'internal_solid_infill_speed': '130',
 'layer_height': '0.15',
 'name': 'Normal speed (Stage 2) - 0.15mm',
 'outer_wall_speed': '100',
 'setting_id': 'GP004',
 'skirt_speed': '130',
 'sparse_infill_speed': '130',
 'support_interface_speed': '130',
 'support_speed': '130',
 'top_shell_layers': '8',
 'top_surface_speed': '100',
 'travel_speed': '200',
 'type': 'process'}
