from __future__ import annotations

# source: profiles/Volumic/process/Normal performance DUAL - 0.20mm.json
DATA = {'bottom_shell_layers': '5',
 'compatible_printers': ['EXO42 IDRE (0.4 nozzle)', 'EXO65 IDRE (0.4 nozzle)', 'SH65 IDRE (0.4 nozzle)'],
 'enable_prime_tower': '1',
 'from': 'system',
 'gap_infill_speed': '220',
 'inherits': 'fdm_process_volumic_common',
 'initial_layer_infill_speed': '130',
 'initial_layer_print_height': '0.2',
 'initial_layer_speed': '130',
 'initial_layer_travel_speed': '600',
 'inner_wall_speed': '180',
 'instantiation': 'true',
 'internal_solid_infill_speed': '220',
 'layer_height': '0.2',
 'name': 'Normal performance DUAL - 0.20mm',
 'outer_wall_speed': '130',
 'prime_tower_brim_width': '4',
 'prime_tower_width': '20',
 'prime_volume': '20',
 'setting_id': 'GP004',
 'skirt_speed': '130',
 'sparse_infill_speed': '220',
 'support_interface_speed': '220',
 'support_speed': '220',
 'top_shell_layers': '5',
 'top_surface_speed': '120',
 'travel_speed': '600',
 'type': 'process',
 'wipe_tower_max_purge_speed': '200'}
