from __future__ import annotations

# source: profiles/Volumic/process/Very high speed - 0.15mm.json
DATA = {'bottom_shell_layers': '8',
 'compatible_printers': ['EXO42 (0.4 nozzle)',
                         'EXO65 (0.6 nozzle)',
                         'SH65 (0.4 nozzle)',
                         'VS30SC2 (0.4 nozzle)',
                         'VS30SC (0.4 nozzle)',
                         'VS30ULTRA (0.4 nozzle)'],
 'from': 'system',
 'gap_infill_speed': '170',
 'inherits': 'fdm_process_volumic_common',
 'initial_layer_infill_speed': '80',
 'initial_layer_print_height': '0.15',
 'initial_layer_speed': '80',
 'inner_wall_speed': '170',
 'instantiation': 'true',
 'internal_solid_infill_speed': '170',
 'layer_height': '0.15',
 'name': 'Very high speed - 0.15mm',
 'outer_wall_speed': '110',
 'setting_id': 'GP004',
 'skirt_speed': '170',
 'sparse_infill_speed': '170',
 'support_interface_speed': '170',
 'support_speed': '170',
 'top_shell_layers': '8',
 'top_surface_speed': '170',
 'travel_speed': '170',
 'type': 'process'}
