from __future__ import annotations

# source: profiles/Co Print/machine/fdm_coprint_common.json
DATA = {'before_layer_change_gcode': 'TIMELAPSE_TAKE_FRAME\nG92 E0',
 'cooling_tube_length': ['0'],
 'cooling_tube_retraction': ['0'],
 'default_filament_profile': ['CoPrint Generic PLA'],
 'default_print_profile': '0.20mm Standard @Co Print ChromaSet 0.4',
 'deretraction_speed': ['30'],
 'extra_loading_move': ['0'],
 'extruder_clearance_height_to_lid': ['36'],
 'extruder_clearance_height_to_rod': ['36'],
 'extruder_clearance_radius': ['65'],
 'from': 'system',
 'gcode_flavor': 'klipper',
 'inherits': 'fdm_machine_common',
 'instantiation': 'false',
 'machine_end_gcode': 'end_print',
 'machine_max_acceleration_e': ['2500'],
 'machine_max_acceleration_extruding': ['5000'],
 'machine_max_acceleration_retracting': ['2500'],
 'machine_max_acceleration_travel': ['40000'],
 'machine_max_acceleration_x': ['5000'],
 'machine_max_acceleration_y': ['5000'],
 'machine_max_acceleration_z': ['100'],
 'machine_max_jerk_e': ['2.5'],
 'machine_max_jerk_x': ['8'],
 'machine_max_jerk_y': ['8'],
 'machine_max_jerk_z': ['0.2'],
 'machine_max_speed_e': ['100'],
 'machine_max_speed_x': ['500'],
 'machine_max_speed_y': ['500'],
 'machine_max_speed_z': ['10'],
 'machine_start_gcode': 'start_print  EXTRUDER=[initial_extruder] EXTRUDER_TEMP=[nozzle_temperature_initial_layer] '
                        'BED_TEMP=[bed_temperature_initial_layer_single]',
 'max_layer_height': ['0.32'],
 'min_layer_height': ['0.08'],
 'name': 'fdm_coprint_common',
 'nozzle_diameter': ['0.4'],
 'parking_pos_retraction': ['10'],
 'printable_area': ['0x0', '225x0', '225x225', '0x225'],
 'printable_height': '250',
 'printer_variant': '0.4',
 'retract_before_wipe': ['0%'],
 'retract_length_toolchange': ['2'],
 'retract_lift_below': ['343'],
 'retract_restart_extra': ['0'],
 'retraction_length': ['0.5'],
 'retraction_minimum_travel': ['1'],
 'retraction_speed': ['60'],
 'thumbnails': ['300x300', '400x300', '96x96', '32x32'],
 'thumbnails_format': 'PNG',
 'type': 'machine',
 'wipe_distance': ['2'],
 'z_hop': ['0.2']}
