from __future__ import annotations

# source: profiles/Anker/filament/fdm_filament_pet.json
DATA = {'close_fan_the_first_x_layers': ['3'],
 'enable_overhang_bridge_fan': ['1'],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['50'],
 'fan_min_speed': ['30'],
 'filament_cost': ['18'],
 'filament_density': ['1.24'],
 'filament_flow_ratio': ['0.95'],
 'filament_max_volumetric_speed': ['8'],
 'filament_type': ['PET'],
 'from': 'system',
 'full_fan_speed_layer': ['3'],
 'hot_plate_temp': ['80'],
 'hot_plate_temp_initial_layer': ['80'],
 'inherits': 'fdm_filament_common',
 'instantiation': 'false',
 'name': 'fdm_filament_pet',
 'nozzle_temperature': ['240'],
 'nozzle_temperature_initial_layer': ['240'],
 'nozzle_temperature_range_high': ['260'],
 'nozzle_temperature_range_low': ['220'],
 'overhang_fan_speed': ['50'],
 'overhang_fan_threshold': ['50%'],
 'reduce_fan_stop_start_freq': ['1'],
 'slow_down_for_layer_cooling': ['1'],
 'slow_down_layer_time': ['8'],
 'slow_down_min_speed': ['10'],
 'support_material_interface_fan_speed': ['-1'],
 'temperature_vitrification': ['85'],
 'type': 'filament'}
