from __future__ import annotations

# source: profiles/Anker/filament/fdm_filament_tpu.json
DATA = {'close_fan_the_first_x_layers': ['3'],
 'enable_overhang_bridge_fan': ['1'],
 'fan_cooling_layer_time': ['100'],
 'fan_max_speed': ['80'],
 'fan_min_speed': ['30'],
 'filament_cost': ['25'],
 'filament_density': ['1.21'],
 'filament_flow_ratio': ['1.03'],
 'filament_max_volumetric_speed': ['1.8'],
 'filament_type': ['TPU'],
 'from': 'system',
 'full_fan_speed_layer': ['3'],
 'hot_plate_temp': ['25'],
 'hot_plate_temp_initial_layer': ['25'],
 'inherits': 'fdm_filament_common',
 'instantiation': 'false',
 'name': 'fdm_filament_tpu',
 'nozzle_temperature': ['240'],
 'nozzle_temperature_initial_layer': ['240'],
 'nozzle_temperature_range_high': ['250'],
 'nozzle_temperature_range_low': ['200'],
 'overhang_fan_speed': ['50'],
 'overhang_fan_threshold': ['50%'],
 'reduce_fan_stop_start_freq': ['1'],
 'slow_down_for_layer_cooling': ['1'],
 'slow_down_layer_time': ['4'],
 'slow_down_min_speed': ['10'],
 'support_material_interface_fan_speed': ['-1'],
 'temperature_vitrification': ['30'],
 'type': 'filament'}
