from __future__ import annotations

# source: profiles/Anker/filament/fdm_filament_pva.json
DATA = {'close_fan_the_first_x_layers': ['1'],
 'enable_overhang_bridge_fan': ['1'],
 'fan_cooling_layer_time': ['100'],
 'fan_max_speed': ['80'],
 'fan_min_speed': ['60'],
 'filament_cost': ['60'],
 'filament_density': ['1.25'],
 'filament_flow_ratio': ['0.95'],
 'filament_is_support': ['1'],
 'filament_max_volumetric_speed': ['16'],
 'filament_soluble': ['1'],
 'filament_type': ['PVA'],
 'from': 'system',
 'full_fan_speed_layer': ['3'],
 'hot_plate_temp': ['65'],
 'hot_plate_temp_initial_layer': ['65'],
 'inherits': 'fdm_filament_common',
 'instantiation': 'false',
 'name': 'fdm_filament_pva',
 'nozzle_temperature': ['220'],
 'nozzle_temperature_initial_layer': ['220'],
 'nozzle_temperature_range_high': ['240'],
 'nozzle_temperature_range_low': ['190'],
 'overhang_fan_speed': ['100'],
 'overhang_fan_threshold': ['50%'],
 'reduce_fan_stop_start_freq': ['1'],
 'slow_down_for_layer_cooling': ['1'],
 'slow_down_layer_time': ['7'],
 'slow_down_min_speed': ['20'],
 'support_material_interface_fan_speed': ['-1'],
 'temperature_vitrification': ['85'],
 'type': 'filament'}
