from __future__ import annotations

# source: profiles/Anker/filament/fdm_filament_pc.json
DATA = {'close_fan_the_first_x_layers': ['3'],
 'enable_overhang_bridge_fan': ['1'],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['20'],
 'fan_min_speed': ['15'],
 'filament_cost': ['45'],
 'filament_density': ['1.21'],
 'filament_flow_ratio': ['0.94'],
 'filament_max_volumetric_speed': ['14'],
 'filament_type': ['PC'],
 'from': 'system',
 'full_fan_speed_layer': ['3'],
 'hot_plate_temp': ['100'],
 'hot_plate_temp_initial_layer': ['100'],
 'inherits': 'fdm_filament_common',
 'instantiation': 'false',
 'name': 'fdm_filament_pc',
 'nozzle_temperature': ['270'],
 'nozzle_temperature_initial_layer': ['270'],
 'nozzle_temperature_range_high': ['280'],
 'nozzle_temperature_range_low': ['260'],
 'overhang_fan_speed': ['60'],
 'overhang_fan_threshold': ['25%'],
 'reduce_fan_stop_start_freq': ['0'],
 'slow_down_for_layer_cooling': ['1'],
 'slow_down_layer_time': ['4'],
 'slow_down_min_speed': ['20'],
 'support_material_interface_fan_speed': ['-1'],
 'temperature_vitrification': ['140'],
 'type': 'filament'}
