from __future__ import annotations

# source: profiles/Anker/filament/fdm_filament_pa.json
DATA = {'close_fan_the_first_x_layers': ['4'],
 'enable_overhang_bridge_fan': ['1'],
 'fan_cooling_layer_time': ['4'],
 'fan_max_speed': ['60'],
 'fan_min_speed': ['0'],
 'filament_cost': ['40'],
 'filament_density': ['1.05'],
 'filament_flow_ratio': ['0.97'],
 'filament_max_volumetric_speed': ['8'],
 'filament_type': ['PA'],
 'from': 'system',
 'full_fan_speed_layer': ['4'],
 'hot_plate_temp': ['95'],
 'hot_plate_temp_initial_layer': ['95'],
 'inherits': 'fdm_filament_common',
 'instantiation': 'false',
 'name': 'fdm_filament_pa',
 'nozzle_temperature': ['290'],
 'nozzle_temperature_initial_layer': ['290'],
 'nozzle_temperature_range_high': ['300'],
 'nozzle_temperature_range_low': ['260'],
 'overhang_fan_speed': ['30'],
 'overhang_fan_threshold': ['25%'],
 'reduce_fan_stop_start_freq': ['0'],
 'slow_down_for_layer_cooling': ['1'],
 'slow_down_layer_time': ['2'],
 'slow_down_min_speed': ['10'],
 'support_material_interface_fan_speed': ['-1'],
 'temperature_vitrification': ['108'],
 'type': 'filament'}
