from __future__ import annotations

PRINTERS_DATA = {'BL-P001.json': {'00.00.00.00': {'auto_cali_not_support_filaments': ['GFU03', 'GFU04'],
                                  'auto_pa_cali_thumbnail_image': 'fd_calibration_auto',
                                  'compatible_machine': ['BL-P002', 'C11', 'C12', 'C13'],
                                  'display_name': 'Bambu Lab X1 Carbon',
                                  'enable_set_nozzle_info': False,
                                  'has_cali_line': True,
                                  'model_id': 'BL-P001',
                                  'print': {'ipcam': {'file': {'model_download': 'enabled', 'remote': 'tutk'},
                                                      'liveview': {'remote': 'tutk'},
                                                      'resolution_supported': ['720p', '1080p'],
                                                      'virtual_camera': 'enabled'},
                                            'nozzle_replace_wiki': {'en': 'https://wiki.bambulab.com/en/x1/maintenance/replace-hotend',
                                                                    'zh': 'https://wiki.bambulab.com/zh/x1/maintenance/replace-hotend'},
                                            'nozzle_temp_range': [0, 300],
                                            'support_1080dpi': False,
                                            'support_ai_monitoring': False,
                                            'support_ams_ext_mix_print': True,
                                            'support_ams_humidity': False,
                                            'support_auto_flow_calibration': False,
                                            'support_auto_recovery_step_loss': False,
                                            'support_aux_fan': True,
                                            'support_bed_leveling': 1,
                                            'support_build_plate_marker_detect': False,
                                            'support_chamber': True,
                                            'support_chamber_fan': True,
                                            'support_chamber_temp_edit': False,
                                            'support_cloud_print_only': False,
                                            'support_command_ams_switch': False,
                                            'support_extrusion_cali': False,
                                            'support_filament_backup': False,
                                            'support_first_layer_inspect': True,
                                            'support_flow_calibration': True,
                                            'support_lidar_calibration': True,
                                            'support_motor_noise_cali': False,
                                            'support_mqtt_alive': False,
                                            'support_print_all': True,
                                            'support_print_without_sd': True,
                                            'support_prompt_sound': False,
                                            'support_save_remote_print_file_to_storage': True,
                                            'support_send_to_sd': False,
                                            'support_timelapse': True,
                                            'support_tunnel_mqtt': False,
                                            'support_update_remain': False,
                                            'support_user_preset': False},
                                  'printer_arch': 'core_xy',
                                  'printer_connect_help_image': 'input_access_code_x1',
                                  'printer_ext_image': ['ext_image_xp'],
                                  'printer_is_enclosed': True,
                                  'printer_series': 'series_x1',
                                  'printer_thumbnail_image': 'printer_thumbnail_x1c',
                                  'printer_type': '3DPrinter-X1-Carbon',
                                  'printer_use_ams_image': 'ams_icon',
                                  'support_safety_options': False,
                                  'support_wrapping_detection': False,
                                  'use_ams_type': 'generic'},
                  '01.01.01.00': {'print': {'support_1080dpi': True,
                                            'support_ai_monitoring': True,
                                            'support_ams_humidity': True,
                                            'support_auto_recovery_step_loss': True,
                                            'support_build_plate_marker_detect': True,
                                            'support_build_plate_marker_detect_type': 1,
                                            'support_filament_backup': True,
                                            'support_send_to_sd': True,
                                            'support_update_remain': True}},
                  '01.05.06.01': {'print': {'support_command_ams_switch': True}},
                  '01.05.06.05': {'engineer': '00.03.10.05', 'print': {'support_mqtt_alive': True}},
                  '01.05.06.06': {'print': {'support_tunnel_mqtt': True}},
                  '01.06.06.00': {'print': {'support_user_preset': True}}},
 'BL-P002.json': {'00.00.00.00': {'auto_cali_not_support_filaments': ['GFU03', 'GFU04'],
                                  'auto_pa_cali_thumbnail_image': 'fd_calibration_auto',
                                  'compatible_machine': ['BL-P001', 'C11', 'C12', 'C13'],
                                  'display_name': 'Bambu Lab X1',
                                  'enable_set_nozzle_info': False,
                                  'has_cali_line': True,
                                  'model_id': 'BL-P002',
                                  'print': {'ipcam': {'file': {'model_download': 'enabled', 'remote': 'tutk'},
                                                      'liveview': {'remote': 'tutk'},
                                                      'resolution_supported': ['720p', '1080p'],
                                                      'virtual_camera': 'enabled'},
                                            'nozzle_replace_wiki': {'en': 'https://wiki.bambulab.com/en/x1/maintenance/replace-hotend',
                                                                    'zh': 'https://wiki.bambulab.com/zh/x1/maintenance/replace-hotend'},
                                            'nozzle_temp_range': [0, 300],
                                            'support_1080dpi': False,
                                            'support_ai_monitoring': False,
                                            'support_ams_ext_mix_print': True,
                                            'support_ams_humidity': False,
                                            'support_auto_flow_calibration': False,
                                            'support_auto_recovery_step_loss': False,
                                            'support_aux_fan': True,
                                            'support_bed_leveling': 1,
                                            'support_build_plate_marker_detect': False,
                                            'support_chamber': True,
                                            'support_chamber_fan': True,
                                            'support_chamber_temp_edit': False,
                                            'support_cloud_print_only': False,
                                            'support_command_ams_switch': False,
                                            'support_extrusion_cali': False,
                                            'support_filament_backup': False,
                                            'support_first_layer_inspect': True,
                                            'support_flow_calibration': True,
                                            'support_lidar_calibration': True,
                                            'support_motor_noise_cali': False,
                                            'support_mqtt_alive': False,
                                            'support_print_all': True,
                                            'support_print_without_sd': True,
                                            'support_prompt_sound': False,
                                            'support_save_remote_print_file_to_storage': True,
                                            'support_send_to_sd': False,
                                            'support_timelapse': True,
                                            'support_tunnel_mqtt': False,
                                            'support_update_remain': False,
                                            'support_user_preset': False},
                                  'printer_arch': 'core_xy',
                                  'printer_connect_help_image': 'input_access_code_x1',
                                  'printer_ext_image': ['ext_image_xp'],
                                  'printer_is_enclosed': True,
                                  'printer_series': 'series_x1',
                                  'printer_thumbnail_image': 'printer_thumbnail',
                                  'printer_type': '3DPrinter-X1',
                                  'printer_use_ams_image': 'ams_icon',
                                  'support_safety_options': False,
                                  'support_wrapping_detection': False,
                                  'use_ams_type': 'generic'},
                  '01.01.01.00': {'print': {'support_1080dpi': True,
                                            'support_ai_monitoring': True,
                                            'support_ams_humidity': True,
                                            'support_auto_recovery_step_loss': True,
                                            'support_build_plate_marker_detect': True,
                                            'support_build_plate_marker_detect_type': 1,
                                            'support_filament_backup': True,
                                            'support_send_to_sd': True,
                                            'support_update_remain': True}},
                  '01.05.06.01': {'print': {'support_command_ams_switch': True}},
                  '01.05.06.05': {'engineer': '00.03.10.05', 'print': {'support_mqtt_alive': True}},
                  '01.05.06.06': {'print': {'support_tunnel_mqtt': True}},
                  '01.06.06.00': {'print': {'support_user_preset': True}}},
 'C11.json': {'00.00.00.00': {'auto_cali_not_support_filaments': ['GFU03', 'GFU04'],
                              'auto_pa_cali_thumbnail_image': 'fd_calibration_auto',
                              'compatible_machine': ['BL-P001', 'BL-P002', 'C12', 'C13'],
                              'display_name': 'Bambu Lab P1P',
                              'enable_set_nozzle_info': False,
                              'ftp_folder': 'sdcard/',
                              'has_cali_line': False,
                              'model_id': 'C11',
                              'print': {'bed_temperature_limit': 100,
                                        'ipcam': {'liveview': {'local': 'local'}, 'resolution_supported': ['720p']},
                                        'nozzle_replace_wiki': {'en': 'https://wiki.bambulab.com/en/p1/maintenance/complete-hot-end-assembly',
                                                                'zh': 'https://wiki.bambulab.com/zh/p1/maintenance/complete-hot-end-assembly'},
                                        'nozzle_temp_range': [0, 300],
                                        'support_1080dpi': False,
                                        'support_ai_monitoring': False,
                                        'support_ams_ext_mix_print': True,
                                        'support_ams_humidity': True,
                                        'support_auto_flow_calibration': False,
                                        'support_auto_recovery_step_loss': True,
                                        'support_aux_fan': True,
                                        'support_bed_leveling': 1,
                                        'support_build_plate_marker_detect': False,
                                        'support_chamber': False,
                                        'support_chamber_fan': True,
                                        'support_chamber_temp_edit': False,
                                        'support_cloud_print_only': True,
                                        'support_command_ams_switch': False,
                                        'support_extrusion_cali': True,
                                        'support_filament_backup': True,
                                        'support_first_layer_inspect': False,
                                        'support_flow_calibration': False,
                                        'support_lidar_calibration': False,
                                        'support_motor_noise_cali': False,
                                        'support_mqtt_alive': False,
                                        'support_print_all': False,
                                        'support_print_without_sd': False,
                                        'support_prompt_sound': False,
                                        'support_send_to_sd': False,
                                        'support_timelapse': True,
                                        'support_tunnel_mqtt': False,
                                        'support_update_remain': True,
                                        'support_user_preset': False},
                              'printer_arch': 'core_xy',
                              'printer_connect_help_image': 'input_access_code_p1p',
                              'printer_ext_image': ['ext_image_xp'],
                              'printer_is_enclosed': False,
                              'printer_series': 'series_p1p',
                              'printer_thumbnail_image': 'printer_thumbnail_p1p',
                              'printer_type': 'C11',
                              'printer_use_ams_image': 'ams_icon',
                              'support_wrapping_detection': False,
                              'use_ams_type': 'generic'},
              '01.02.00.00': {'print': {'support_send_to_sd': True}},
              '01.02.99.00': {'print': {'ipcam': {'liveview': {'remote': 'tutk'}}}},
              '01.02.99.10': {'print': {'support_command_ams_switch': True}},
              '01.03.50.01': {'engineer': '00.06.03.51',
                              'print': {'support_mqtt_alive': True, 'support_tunnel_mqtt': True}},
              '01.04.50.01': {'print': {'ipcam': {'file': {'remote': 'tutk'}}, 'support_user_preset': True}},
              '01.07.50.00': {'print': {'support_print_all': True}}},
 'C12.json': {'00.00.00.00': {'auto_cali_not_support_filaments': ['GFU03', 'GFU04'],
                              'auto_pa_cali_thumbnail_image': 'fd_calibration_auto',
                              'compatible_machine': ['BL-P001', 'BL-P002', 'C11', 'C13'],
                              'display_name': 'Bambu Lab P1S',
                              'enable_set_nozzle_info': False,
                              'ftp_folder': 'sdcard/',
                              'has_cali_line': False,
                              'model_id': 'C12',
                              'print': {'bed_temperature_limit': 100,
                                        'ipcam': {'liveview': {'local': 'local'}, 'resolution_supported': ['720p']},
                                        'nozzle_replace_wiki': {'en': 'https://wiki.bambulab.com/en/p1/maintenance/complete-hot-end-assembly',
                                                                'zh': 'https://wiki.bambulab.com/zh/p1/maintenance/complete-hot-end-assembly'},
                                        'nozzle_temp_range': [0, 300],
                                        'support_1080dpi': False,
                                        'support_ai_monitoring': False,
                                        'support_ams_ext_mix_print': True,
                                        'support_ams_humidity': True,
                                        'support_auto_flow_calibration': False,
                                        'support_auto_recovery_step_loss': True,
                                        'support_aux_fan': True,
                                        'support_bed_leveling': 1,
                                        'support_build_plate_marker_detect': False,
                                        'support_chamber': True,
                                        'support_chamber_fan': True,
                                        'support_chamber_temp_edit': False,
                                        'support_cloud_print_only': True,
                                        'support_command_ams_switch': False,
                                        'support_extrusion_cali': True,
                                        'support_filament_backup': True,
                                        'support_first_layer_inspect': False,
                                        'support_flow_calibration': False,
                                        'support_lidar_calibration': False,
                                        'support_motor_noise_cali': False,
                                        'support_mqtt_alive': False,
                                        'support_print_all': False,
                                        'support_print_without_sd': False,
                                        'support_prompt_sound': False,
                                        'support_send_to_sd': True,
                                        'support_timelapse': True,
                                        'support_tunnel_mqtt': False,
                                        'support_update_remain': True,
                                        'support_user_preset': False},
                              'printer_arch': 'core_xy',
                              'printer_connect_help_image': 'input_access_code_p1p',
                              'printer_ext_image': ['ext_image_xp'],
                              'printer_is_enclosed': True,
                              'printer_series': 'series_p1p',
                              'printer_thumbnail_image': 'printer_thumbnail_p1s',
                              'printer_type': 'C12',
                              'printer_use_ams_image': 'ams_icon',
                              'support_wrapping_detection': False,
                              'use_ams_type': 'generic'},
              '01.02.99.10': {'print': {'support_command_ams_switch': True}},
              '01.03.50.01': {'engineer': '00.06.03.51',
                              'print': {'ipcam': {'liveview': {'remote': 'tutk'}},
                                        'support_mqtt_alive': True,
                                        'support_tunnel_mqtt': True},
                              'resolution_supported': ['720p']},
              '01.04.50.01': {'print': {'ipcam': {'file': {'remote': 'tutk'}}, 'support_user_preset': True}},
              '01.07.50.00': {'print': {'support_print_all': True}}},
 'C13.json': {'00.00.00.00': {'auto_cali_not_support_filaments': ['GFU03', 'GFU04'],
                              'auto_pa_cali_thumbnail_image': 'fd_calibration_auto',
                              'compatible_machine': ['BL-P001', 'BL-P002', 'C11', 'C12'],
                              'display_name': 'Bambu Lab X1E',
                              'enable_set_nozzle_info': False,
                              'has_cali_line': True,
                              'model_id': 'C13',
                              'print': {'bed_temperature_limit': 110,
                                        'ipcam': {'file': {'model_download': 'enabled', 'remote': 'tutk'},
                                                  'liveview': {'remote': 'tutk'},
                                                  'resolution_supported': ['720p', '1080p'],
                                                  'virtual_camera': 'enabled'},
                                        'nozzle_max_temperature': 320,
                                        'nozzle_replace_wiki': {'en': 'https://wiki.bambulab.com/en/x1/maintenance/replace-hotend',
                                                                'zh': 'https://wiki.bambulab.com/zh/x1/maintenance/replace-hotend'},
                                        'nozzle_temp_range': [0, 320],
                                        'support_1080dpi': True,
                                        'support_ai_monitoring': True,
                                        'support_ams_ext_mix_print': True,
                                        'support_ams_humidity': True,
                                        'support_auto_flow_calibration': False,
                                        'support_auto_recovery_step_loss': True,
                                        'support_aux_fan': True,
                                        'support_bed_leveling': 1,
                                        'support_build_plate_marker_detect': True,
                                        'support_build_plate_marker_detect_type': 1,
                                        'support_chamber': True,
                                        'support_chamber_fan': True,
                                        'support_chamber_temp_edit': True,
                                        'support_chamber_temp_edit_range': [0, 60],
                                        'support_cloud_print_only': False,
                                        'support_command_ams_switch': True,
                                        'support_extrusion_cali': False,
                                        'support_filament_backup': True,
                                        'support_first_layer_inspect': True,
                                        'support_flow_calibration': True,
                                        'support_lidar_calibration': True,
                                        'support_motor_noise_cali': False,
                                        'support_mqtt_alive': True,
                                        'support_print_all': True,
                                        'support_print_without_sd': True,
                                        'support_prompt_sound': False,
                                        'support_send_to_sd': True,
                                        'support_ssl_for_mqtt': True,
                                        'support_timelapse': True,
                                        'support_tunnel_mqtt': True,
                                        'support_update_remain': True,
                                        'support_user_preset': False},
                              'printer_arch': 'core_xy',
                              'printer_connect_help_image': 'input_access_code_x1',
                              'printer_ext_image': ['ext_image_xp'],
                              'printer_is_enclosed': True,
                              'printer_series': 'series_x1',
                              'printer_thumbnail_image': 'printer_thumbnail_x1e',
                              'printer_type': 'C13',
                              'printer_use_ams_image': 'ams_icon',
                              'support_safety_options': False,
                              'support_wrapping_detection': False,
                              'use_ams_type': 'generic'},
              '01.05.06.06': {'rv2166': '00.00.21.20'}},
 'N1.json': {'00.00.00.00': {'auto_cali_not_support_filaments': ['GFU03', 'GFU04'],
                             'auto_pa_cali_thumbnail_image': 'fd_calibration_auto_i3',
                             'compatible_machine': [],
                             'display_name': 'Bambu Lab A1 mini',
                             'enable_set_nozzle_info': False,
                             'ftp_folder': 'sdcard/',
                             'has_cali_line': False,
                             'model_id': 'N1',
                             'print': {'bed_temperature_limit': 80,
                                       'ipcam': {'liveview': {'local': 'local', 'remote': 'tutk'},
                                                 'resolution_supported': ['720p']},
                                       'nozzle_replace_wiki': {'en': 'https://wiki.bambulab.com/en/a1-mini/maintenance/hotend-heating-assembly-replacement',
                                                               'zh': 'https://wiki.bambulab.com/zh/a1-mini/maintenance/hotend-heating-assembly-replacement'},
                                       'nozzle_temp_range': [0, 300],
                                       'support_1080dpi': True,
                                       'support_ai_monitoring': False,
                                       'support_ams_ext_mix_print': False,
                                       'support_ams_humidity': False,
                                       'support_auto_flow_calibration': False,
                                       'support_auto_recovery_step_loss': True,
                                       'support_aux_fan': False,
                                       'support_bed_leveling': 1,
                                       'support_chamber': False,
                                       'support_chamber_fan': False,
                                       'support_chamber_temp_edit': False,
                                       'support_cloud_print_only': True,
                                       'support_command_ams_switch': True,
                                       'support_extrusion_cali': True,
                                       'support_filament_backup': True,
                                       'support_first_layer_inspect': False,
                                       'support_flow_calibration': True,
                                       'support_lidar_calibration': False,
                                       'support_motor_noise_cali': True,
                                       'support_mqtt_alive': True,
                                       'support_print_all': False,
                                       'support_print_without_sd': False,
                                       'support_prompt_sound': True,
                                       'support_send_to_sd': True,
                                       'support_timelapse': True,
                                       'support_tunnel_mqtt': True,
                                       'support_update_remain': False,
                                       'support_user_preset': False},
                             'printer_arch': 'i3',
                             'printer_connect_help_image': 'input_access_code_n1',
                             'printer_ext_image': ['ext_image_n1'],
                             'printer_is_enclosed': False,
                             'printer_series': 'series_n',
                             'printer_thumbnail_image': 'printer_thumbnail_n1',
                             'printer_type': 'N1',
                             'printer_use_ams_image': 'extra_icon',
                             'support_safety_options': False,
                             'support_wrapping_detection': False,
                             'use_ams_type': 'f1'},
             '01.01.50.01': {'print': {'ipcam': {'file': {'remote': 'tutk'}}, 'support_user_preset': True}}},
 'N2S.json': {'00.00.00.00': {'auto_cali_not_support_filaments': ['GFU03', 'GFU04'],
                              'auto_pa_cali_thumbnail_image': 'fd_calibration_auto_i3',
                              'compatible_machine': [],
                              'display_name': 'Bambu Lab A1',
                              'enable_set_nozzle_info': False,
                              'ftp_folder': 'sdcard/',
                              'has_cali_line': False,
                              'model_id': 'N2S',
                              'print': {'bed_temperature_limit': 100,
                                        'ipcam': {'liveview': {'local': 'local', 'remote': 'tutk'},
                                                  'resolution_supported': ['720p']},
                                        'nozzle_replace_wiki': {'en': 'https://wiki.bambulab.com/en/a1-mini/maintenance/hotend-heating-assembly-replacement',
                                                                'zh': 'https://wiki.bambulab.com/zh/a1-mini/maintenance/hotend-heating-assembly-replacement'},
                                        'nozzle_temp_range': [0, 300],
                                        'support_1080dpi': True,
                                        'support_ai_monitoring': False,
                                        'support_ams_ext_mix_print': False,
                                        'support_ams_humidity': False,
                                        'support_auto_flow_calibration': False,
                                        'support_auto_recovery_step_loss': True,
                                        'support_aux_fan': False,
                                        'support_bed_leveling': 1,
                                        'support_chamber': False,
                                        'support_chamber_fan': False,
                                        'support_chamber_temp_edit': False,
                                        'support_cloud_print_only': True,
                                        'support_command_ams_switch': True,
                                        'support_extrusion_cali': True,
                                        'support_filament_backup': True,
                                        'support_first_layer_inspect': False,
                                        'support_flow_calibration': True,
                                        'support_lidar_calibration': False,
                                        'support_motor_noise_cali': True,
                                        'support_mqtt_alive': True,
                                        'support_print_all': False,
                                        'support_print_without_sd': False,
                                        'support_prompt_sound': True,
                                        'support_send_to_sd': True,
                                        'support_timelapse': True,
                                        'support_tunnel_mqtt': True,
                                        'support_update_remain': False,
                                        'support_user_preset': False},
                              'printer_arch': 'i3',
                              'printer_connect_help_image': 'input_access_code_n1',
                              'printer_ext_image': ['ext_image_n2s'],
                              'printer_is_enclosed': False,
                              'printer_series': 'series_n',
                              'printer_thumbnail_image': 'printer_thumbnail_n2s',
                              'printer_type': 'N2S',
                              'printer_use_ams_image': 'extra_icon',
                              'support_safety_options': False,
                              'support_wrapping_detection': False,
                              'use_ams_type': 'f1'},
              '01.01.50.01': {'print': {'ipcam': {'file': {'remote': 'tutk'}}}}},
 'N7.json': {'00.00.00.00': {'auto_pa_cali_thumbnail_image': 'fd_calibration_auto_n7',
                             'compatible_machine': [],
                             'display_name': 'Bambu Lab P2S',
                             'enable_set_nozzle_info': False,
                             'fan': {'0': {'10': 'Left(Aux)', '2': 'Right(Aux)', 'description': ''},
                                     '1': {'10': 'Left(Aux)', '2': 'Right(Filter)'},
                                     'special_cooling_text': 'Cooling mode is suitable for printing PLA/PETG/TPU '
                                                             'materials.'},
                             'has_cali_line': True,
                             'model_id': 'N7',
                             'print': {'bed_temp_range': [0, 110],
                                       'ipcam': {'file': {'local': 'local',
                                                          'model_download': 'enabled',
                                                          'remote': 'tutk'},
                                                 'liveview': {'remote': 'tutk'},
                                                 'resolution_supported': ['1080p'],
                                                 'virtual_camera': 'enabled'},
                                       'nozzle_replace_wiki': {'en': 'https://wiki.bambulab.com/en/h2/maintenance/replace-hotend',
                                                               'zh': 'https://wiki.bambulab.com/zh/h2/maintenance/replace-hotend'},
                                       'nozzle_temp_range': [0, 300],
                                       'support_1080dpi': True,
                                       'support_ai_monitoring': True,
                                       'support_ams_ext_mix_print': True,
                                       'support_ams_humidity': True,
                                       'support_auto_flow_calibration': True,
                                       'support_auto_recovery_step_loss': True,
                                       'support_aux_fan': True,
                                       'support_bed_leveling': 2,
                                       'support_build_plate_marker_detect': True,
                                       'support_build_plate_marker_detect_type': 2,
                                       'support_chamber': True,
                                       'support_chamber_fan': True,
                                       'support_chamber_temp_edit': False,
                                       'support_cloud_print_only': False,
                                       'support_clump_position_calibration': True,
                                       'support_command_ams_switch': True,
                                       'support_extrusion_cali': False,
                                       'support_filament_backup': True,
                                       'support_first_layer_inspect': False,
                                       'support_flow_calibration': True,
                                       'support_high_tempbed_calibration': True,
                                       'support_lidar_calibration': False,
                                       'support_motor_noise_cali': False,
                                       'support_mqtt_alive': True,
                                       'support_nozzle_offset_calibration': False,
                                       'support_print_all': True,
                                       'support_print_without_sd': True,
                                       'support_prompt_sound': False,
                                       'support_save_remote_print_file_to_storage': True,
                                       'support_send_to_sd': True,
                                       'support_ssl_for_mqtt': True,
                                       'support_timelapse': True,
                                       'support_tunnel_mqtt': True,
                                       'support_update_remain': True,
                                       'support_user_preset': False},
                             'printer_arch': 'core_xy',
                             'printer_connect_help_image': 'input_access_code_x1',
                             'printer_ext_image': ['ext_image_n7'],
                             'printer_is_enclosed': True,
                             'printer_series': 'series_x1',
                             'printer_thumbnail_image': 'printer_thumbnail_N7',
                             'printer_type': 'N7',
                             'printer_use_ams_image': 'ams_icon',
                             'subseries': ['N7-V2'],
                             'support_safety_options': True,
                             'support_wrapping_detection': True,
                             'use_ams_type': 'generic'}},
 'O1D.json': {'00.00.00.00': {'auto_pa_cali_thumbnail_image': 'fd_calibration_auto_multi_extruders',
                              'compatible_machine': ['O1E'],
                              'display_name': 'Bambu Lab H2D',
                              'enable_set_nozzle_info': False,
                              'has_cali_line': True,
                              'model_id': 'O1D',
                              'print': {'2D': {'laser': {'power': [10, 40]}},
                                        'bed_temp_range': [0, 120],
                                        'ipcam': {'file': {'local': 'local',
                                                           'model_download': 'enabled',
                                                           'remote': 'tutk'},
                                                  'liveview': {'remote': 'tutk'},
                                                  'resolution_supported': ['1080p'],
                                                  'virtual_camera': 'enabled'},
                                        'nozzle_replace_wiki': {'en': 'https://wiki.bambulab.com/en/h2/maintenance/replace-hotend',
                                                                'zh': 'https://wiki.bambulab.com/zh/h2/maintenance/replace-hotend'},
                                        'nozzle_temp_range': [0, 350],
                                        'support_1080dpi': True,
                                        'support_ai_monitoring': True,
                                        'support_ams_ext_mix_print': True,
                                        'support_ams_humidity': True,
                                        'support_auto_flow_calibration': True,
                                        'support_auto_recovery_step_loss': True,
                                        'support_aux_fan': True,
                                        'support_bed_leveling': 2,
                                        'support_build_plate_marker_detect': True,
                                        'support_build_plate_marker_detect_type': 2,
                                        'support_chamber': True,
                                        'support_chamber_fan': True,
                                        'support_chamber_temp_edit': True,
                                        'support_chamber_temp_edit_range': [0, 65],
                                        'support_chamber_temp_switch_heating': 40,
                                        'support_cloud_print_only': False,
                                        'support_command_ams_switch': True,
                                        'support_extrusion_cali': False,
                                        'support_filament_backup': True,
                                        'support_first_layer_inspect': False,
                                        'support_flow_calibration': True,
                                        'support_high_tempbed_calibration': True,
                                        'support_lidar_calibration': False,
                                        'support_motor_noise_cali': False,
                                        'support_mqtt_alive': True,
                                        'support_nozzle_offset_calibration': True,
                                        'support_print_all': True,
                                        'support_print_without_sd': True,
                                        'support_prompt_sound': False,
                                        'support_refresh_nozzle': True,
                                        'support_save_remote_print_file_to_storage': True,
                                        'support_send_to_sd': True,
                                        'support_ssl_for_mqtt': True,
                                        'support_timelapse': True,
                                        'support_tunnel_mqtt': True,
                                        'support_update_remain': True,
                                        'support_user_preset': False},
                              'printer_arch': 'core_xy',
                              'printer_connect_help_image': 'input_access_code_h2d',
                              'printer_ext_image': ['ext_image_o_right', 'ext_image_o_left'],
                              'printer_is_enclosed': True,
                              'printer_modes': ['fdm', 'laser', 'cut'],
                              'printer_series': 'series_o',
                              'printer_thumbnail_image': 'printer_thumbnail_h2d',
                              'printer_type': 'O1D',
                              'printer_use_ams_image': 'ams_icon',
                              'support_safety_options': False,
                              'support_wrapping_detection': True,
                              'use_ams_type': 'generic'}},
 'O1E.json': {'00.00.00.00': {'auto_pa_cali_thumbnail_image': 'fd_calibration_auto_multi_extruders',
                              'compatible_machine': ['O1D'],
                              'display_name': 'Bambu Lab H2D Pro',
                              'enable_set_nozzle_info': False,
                              'has_cali_line': True,
                              'model_id': 'O1E',
                              'print': {'2D': {'laser': {'power': [10, 40]}},
                                        'bed_temp_range': [0, 120],
                                        'ipcam': {'file': {'local': 'local',
                                                           'model_download': 'enabled',
                                                           'remote': 'tutk'},
                                                  'liveview': {'remote': 'tutk'},
                                                  'resolution_supported': ['1080p'],
                                                  'virtual_camera': 'enabled'},
                                        'nozzle_replace_wiki': {'en': 'https://wiki.bambulab.com/en/h2/maintenance/replace-hotend',
                                                                'zh': 'https://wiki.bambulab.com/zh/h2/maintenance/replace-hotend'},
                                        'nozzle_temp_range': [0, 350],
                                        'support_1080dpi': True,
                                        'support_ai_monitoring': True,
                                        'support_ams_ext_mix_print': True,
                                        'support_ams_humidity': True,
                                        'support_auto_flow_calibration': True,
                                        'support_auto_recovery_step_loss': True,
                                        'support_aux_fan': True,
                                        'support_bed_leveling': 2,
                                        'support_build_plate_marker_detect': True,
                                        'support_build_plate_marker_detect_type': 2,
                                        'support_chamber': True,
                                        'support_chamber_fan': True,
                                        'support_chamber_temp_edit': True,
                                        'support_chamber_temp_edit_range': [0, 65],
                                        'support_chamber_temp_switch_heating': 40,
                                        'support_cloud_print_only': False,
                                        'support_command_ams_switch': True,
                                        'support_extrusion_cali': False,
                                        'support_filament_backup': True,
                                        'support_first_layer_inspect': False,
                                        'support_flow_calibration': True,
                                        'support_high_tempbed_calibration': True,
                                        'support_lidar_calibration': False,
                                        'support_motor_noise_cali': False,
                                        'support_mqtt_alive': True,
                                        'support_nozzle_offset_calibration': True,
                                        'support_print_all': True,
                                        'support_print_without_sd': True,
                                        'support_prompt_sound': False,
                                        'support_refresh_nozzle': True,
                                        'support_save_remote_print_file_to_storage': True,
                                        'support_send_to_sd': True,
                                        'support_ssl_for_mqtt': True,
                                        'support_timelapse': True,
                                        'support_tunnel_mqtt': True,
                                        'support_update_remain': True,
                                        'support_user_preset': False},
                              'printer_arch': 'core_xy',
                              'printer_connect_help_image': 'input_access_code_h2d',
                              'printer_ext_image': ['ext_image_o_right', 'ext_image_o_left'],
                              'printer_is_enclosed': True,
                              'printer_modes': ['fdm', 'laser', 'cut'],
                              'printer_series': 'series_o',
                              'printer_thumbnail_image': 'printer_thumbnail_o1e',
                              'printer_type': 'O1E',
                              'printer_use_ams_image': 'ams_icon',
                              'support_safety_options': False,
                              'support_wrapping_detection': True,
                              'use_ams_type': 'generic'}},
 'O1S.json': {'00.00.00.00': {'auto_pa_cali_thumbnail_image': 'fd_calibration_auto_single_o',
                              'compatible_machine': [],
                              'display_name': 'Bambu Lab H2S',
                              'enable_set_nozzle_info': False,
                              'has_cali_line': True,
                              'model_id': 'O1S',
                              'print': {'2D': {'laser': {'power': [10, 40]}},
                                        'bed_temp_range': [0, 120],
                                        'ipcam': {'file': {'local': 'local',
                                                           'model_download': 'enabled',
                                                           'remote': 'tutk'},
                                                  'liveview': {'remote': 'tutk'},
                                                  'resolution_supported': ['1080p'],
                                                  'virtual_camera': 'enabled'},
                                        'nozzle_replace_wiki': {'en': 'https://wiki.bambulab.com/en/h2s/maintenance/replace-silicone-sock-and-hotend',
                                                                'zh': 'https://wiki.bambulab.com/zh/h2s/maintenance/replace-silicone-sock-and-hotend'},
                                        'nozzle_temp_range': [0, 350],
                                        'support_1080dpi': True,
                                        'support_ai_monitoring': True,
                                        'support_ams_ext_mix_print': True,
                                        'support_ams_humidity': True,
                                        'support_auto_flow_calibration': True,
                                        'support_auto_recovery_step_loss': True,
                                        'support_aux_fan': True,
                                        'support_bed_leveling': 2,
                                        'support_build_plate_marker_detect': True,
                                        'support_build_plate_marker_detect_type': 2,
                                        'support_chamber_fan': True,
                                        'support_chamber_temp_edit': True,
                                        'support_chamber_temp_edit_range': [0, 65],
                                        'support_chamber_temp_switch_heating': 40,
                                        'support_cloud_print_only': False,
                                        'support_command_ams_switch': True,
                                        'support_extrusion_cali': False,
                                        'support_filament_backup': True,
                                        'support_first_layer_inspect': False,
                                        'support_flow_calibration': True,
                                        'support_high_tempbed_calibration': True,
                                        'support_lidar_calibration': False,
                                        'support_motor_noise_cali': False,
                                        'support_mqtt_alive': True,
                                        'support_nozzle_offset_calibration': False,
                                        'support_print_all': True,
                                        'support_print_without_sd': True,
                                        'support_prompt_sound': False,
                                        'support_save_remote_print_file_to_storage': True,
                                        'support_send_to_sd': True,
                                        'support_ssl_for_mqtt': True,
                                        'support_timelapse': True,
                                        'support_tunnel_mqtt': True,
                                        'support_update_remain': True,
                                        'support_user_preset': False},
                              'printer_arch': 'core_xy',
                              'printer_connect_help_image': 'input_access_code_x1',
                              'printer_ext_image': ['ext_image_o1s'],
                              'printer_is_enclosed': True,
                              'printer_modes': ['fdm', 'laser', 'cut'],
                              'printer_series': 'series_o',
                              'printer_thumbnail_image': 'printer_thumbnail_o1s',
                              'printer_type': 'O1S',
                              'printer_use_ams_image': 'ams_icon',
                              'support_safety_options': False,
                              'use_ams_type': 'generic'}},
 'filaments_blacklist.json': {'blacklist': [{'action': 'prohibition',
                                             'description': 'TPU is not supported by AMS.',
                                             'slot': 'ams',
                                             'type': 'TPU'},
                                            {'action': 'prohibition',
                                             'description': "AMS does not support 'Bambu Lab PET-CF'.",
                                             'slot': 'ams',
                                             'type': 'PET-CF',
                                             'vendor': 'Bambu Lab'},
                                            {'action': 'warning',
                                             'description': 'Please cold pull before printing TPU to avoid clogging. '
                                                            'You may use cold pull maintenance on the printer.',
                                             'type': 'TPU'},
                                            {'action': 'warning',
                                             'description': 'Please cold pull before printing TPU to avoid clogging. '
                                                            'You may use cold pull maintenance on the printer.',
                                             'type': 'TPU-AMS'},
                                            {'action': 'warning',
                                             'description': 'Damp PVA will become flexible and get stuck inside AMS, '
                                                            'please take care to dry it before use.',
                                             'slot': 'ams',
                                             'type': 'PVA'},
                                            {'action': 'warning',
                                             'description': 'Damp PVA is flexible and may get stuck in extruder. Dry '
                                                            'it before use.',
                                             'slot': 'ext',
                                             'type': 'PVA'},
                                            {'action': 'warning',
                                             'description': 'PPS-CF is brittle and could break in bended PTFE tube '
                                                            'above Toolhead.',
                                             'model_id': ['O1S'],
                                             'type': 'PPS-CF',
                                             'wiki': 'https://e.bambulab.com/t?c=UC64kdlpHxN3Mb15'},
                                            {'action': 'warning',
                                             'description': 'PPA-CF is brittle and could break in bended PTFE tube '
                                                            'above Toolhead.',
                                             'model_id': ['O1S'],
                                             'type': 'PPA-CF',
                                             'wiki': 'https://e.bambulab.com/t?c=UC64kdlpHxN3Mb15'},
                                            {'action': 'warning',
                                             'description': "CF/GF filaments are hard and brittle, it's easy to break "
                                                            'or get stuck in AMS, please use with caution.',
                                             'slot': 'ams',
                                             'type_suffix': 'CF'},
                                            {'action': 'warning',
                                             'description': "CF/GF filaments are hard and brittle, it's easy to break "
                                                            'or get stuck in AMS, please use with caution.',
                                             'slot': 'ams',
                                             'type_suffix': 'GF'},
                                            {'action': 'warning',
                                             'description': 'The rough surface of PLA Glow can accelerate wear on the '
                                                            'AMS system, particularly on the internal components of '
                                                            'the AMS Lite.',
                                             'model_id': ['N1', 'N2S'],
                                             'name': 'PLA Glow',
                                             'slot': 'ams',
                                             'type': 'PLA',
                                             'vendor': 'Bambu Lab'}],
                              'whitelist': []}}
