from __future__ import annotations

# source: profiles/Ratrig/process/0.20mm Quality @RatRig V-Core 4 0.4.json
DATA = {'bottom_shell_layers': '3',
 'bridge_acceleration': '2500',
 'bridge_flow': '0.85',
 'bridge_speed': '50',
 'compatible_printers': ['RatRig V-Core 4 300 0.4 nozzle',
                         'RatRig V-Core 4 400 0.4 nozzle',
                         'RatRig V-Core 4 500 0.4 nozzle'],
 'default_acceleration': '10000',
 'elefant_foot_compensation': '0.1',
 'from': 'system',
 'gap_infill_speed': '200',
 'infill_anchor': '600%',
 'infill_anchor_max': '5',
 'infill_combination': '1',
 'infill_wall_overlap': '18%',
 'inherits': 'fdm_process_ratrig_common',
 'inital_layer_height': '0.3',
 'initial_layer_acceleration': '1500',
 'initial_layer_line_width': '0.5',
 'initial_layer_speed': '50',
 'inner_wall_acceleration': '8000',
 'inner_wall_line_width': '0.45',
 'inner_wall_speed': '350',
 'instantiation': 'true',
 'internal_solid_infill_acceleration': '0',
 'internal_solid_infill_line_width': '0.45',
 'internal_solid_infill_speed': '100%',
 'layer_height': '0.2',
 'line_width': '0.45',
 'name': '0.20mm Quality @RatRig V-Core 4 0.4',
 'outer_wall_acceleration': '4000',
 'outer_wall_line_width': '0.45',
 'outer_wall_speed': '250',
 'resolution': '0.0125',
 'setting_id': 'GP006',
 'skirt_distance': '10',
 'skirt_loops': '2',
 'small_perimeter_speed': '250',
 'sparse_infill_acceleration': '10000',
 'sparse_infill_density': '25%',
 'sparse_infill_line_width': '0.45',
 'sparse_infill_speed': '400',
 'support_bottom_z_distance': '0.2',
 'support_interface_speed': '100%',
 'support_line_width': '0.45',
 'support_object_xy_distance': '60%',
 'support_on_build_plate_only': '1',
 'support_speed': '50',
 'support_threshold_angle': '65',
 'top_shell_layers': '4',
 'top_shell_thickness': '0',
 'top_surface_acceleration': '0',
 'top_surface_line_width': '0.45',
 'top_surface_speed': '100%',
 'travel_acceleration': '10000',
 'travel_speed': '500',
 'type': 'process',
 'wall_count': '4'}
