from __future__ import annotations

# source: profiles/Ratrig/process/0.20mm Quality @RatRig V-Core 4 IDEX 0.6.json
DATA = {'bottom_shell_layers': '3',
 'bridge_flow': '0.85',
 'compatible_printers': ['RatRig V-Core 4 IDEX 300 0.6 nozzle',
                         'RatRig V-Core 4 IDEX 400 0.6 nozzle',
                         'RatRig V-Core 4 IDEX 500 0.6 nozzle',
                         'RatRig V-Core 4 IDEX 300 COPY MODE 0.6 nozzle',
                         'RatRig V-Core 4 IDEX 400 COPY MODE 0.6 nozzle',
                         'RatRig V-Core 4 IDEX 500 COPY MODE 0.6 nozzle',
                         'RatRig V-Core 4 IDEX 300 MIRROR MODE 0.6 nozzle',
                         'RatRig V-Core 4 IDEX 400 MIRROR MODE 0.6 nozzle',
                         'RatRig V-Core 4 IDEX 500 MIRROR MODE 0.6 nozzle'],
 'elefant_foot_compensation': '0.1',
 'from': 'system',
 'infill_anchor': '600%',
 'infill_anchor_max': '5',
 'infill_combination': '1',
 'infill_wall_overlap': '18%',
 'inherits': 'fdm_process_ratrig_idex',
 'inital_layer_height': '0.3',
 'initial_layer_line_width': '0.8',
 'inner_wall_line_width': '0.60',
 'instantiation': 'true',
 'internal_solid_infill_line_width': '0.60',
 'layer_height': '0.2',
 'line_width': '0.65',
 'name': '0.20mm Quality @RatRig V-Core 4 IDEX 0.6',
 'outer_wall_line_width': '0.58',
 'resolution': '0.0125',
 'setting_id': 'GP006',
 'skirt_distance': '10',
 'skirt_loops': '2',
 'sparse_infill_density': '25%',
 'sparse_infill_line_width': '0.60',
 'support_bottom_z_distance': '0.2',
 'support_line_width': '0.60',
 'support_object_xy_distance': '60%',
 'support_on_build_plate_only': '1',
 'support_threshold_angle': '65',
 'top_shell_layers': '4',
 'top_shell_thickness': '0',
 'top_surface_line_width': '0.60',
 'type': 'process',
 'wall_count': '4'}
