from __future__ import annotations

# source: profiles/Ratrig/process/0.25mm Speed @RatRig V-Core 4 IDEX 0.8.json
DATA = {'bottom_shell_layers': '2',
 'bridge_acceleration': '5000',
 'bridge_flow': '0.85',
 'bridge_speed': '150',
 'compatible_printers': ['RatRig V-Core 4 IDEX 300 0.8 nozzle',
                         'RatRig V-Core 4 IDEX 400 0.8 nozzle',
                         'RatRig V-Core 4 IDEX 500 0.8 nozzle',
                         'RatRig V-Core 4 IDEX 300 COPY MODE 0.8 nozzle',
                         'RatRig V-Core 4 IDEX 400 COPY MODE 0.8 nozzle',
                         'RatRig V-Core 4 IDEX 500 COPY MODE 0.8 nozzle',
                         'RatRig V-Core 4 IDEX 300 MIRROR MODE 0.8 nozzle',
                         'RatRig V-Core 4 IDEX 400 MIRROR MODE 0.8 nozzle',
                         'RatRig V-Core 4 IDEX 500 MIRROR MODE 0.8 nozzle'],
 'default_acceleration': '20000',
 'elefant_foot_compensation': '0.1',
 'from': 'system',
 'gap_infill_speed': '200',
 'infill_anchor': '600%',
 'infill_anchor_max': '5',
 'infill_combination': '1',
 'infill_wall_overlap': '18%',
 'inherits': 'fdm_process_ratrig_common',
 'inital_layer_height': '0.3',
 'initial_layer_acceleration': '2500',
 'initial_layer_line_width': '1.1',
 'initial_layer_speed': '200',
 'inner_wall_acceleration': '20000',
 'inner_wall_line_width': '0.75',
 'inner_wall_speed': '500',
 'instantiation': 'true',
 'internal_solid_infill_acceleration': '0',
 'internal_solid_infill_line_width': '0.75',
 'internal_solid_infill_speed': '100%',
 'layer_height': '0.25',
 'line_width': '0.75',
 'name': '0.25mm Speed @RatRig V-Core 4 IDEX 0.8',
 'outer_wall_acceleration': '15000',
 'outer_wall_line_width': '0.70',
 'outer_wall_speed': '500',
 'resolution': '0.0125',
 'setting_id': 'GP006',
 'small_perimeter_speed': '500',
 'sparse_infill_acceleration': '20000',
 'sparse_infill_density': '10%',
 'sparse_infill_line_width': '0.75',
 'sparse_infill_speed': '500',
 'support_bottom_z_distance': '0.2',
 'support_interface_speed': '100%',
 'support_line_width': '0.75',
 'support_object_xy_distance': '60%',
 'support_on_build_plate_only': '1',
 'support_speed': '50',
 'support_threshold_angle': '65',
 'top_shell_layers': '3',
 'top_shell_thickness': '0',
 'top_surface_acceleration': '0',
 'top_surface_line_width': '0.75',
 'top_surface_speed': '100%',
 'travel_acceleration': '10000',
 'travel_speed': '800',
 'type': 'process',
 'wall_count': '2'}
