from __future__ import annotations

# source: profiles/Elegoo/process/0.20mm Standard @Elegoo Neptune4 Plus (0.6 nozzle).json
DATA = {'bottom_shell_layers': '3',
 'compatible_printers': ['Elegoo Neptune 4 Plus (0.6 nozzle)'],
 'from': 'system',
 'inherits': 'fdm_process_neptune4_common',
 'initial_layer_line_width': '0.62',
 'inner_wall_line_width': '0.65',
 'instantiation': 'true',
 'internal_solid_infill_line_width': '0.65',
 'layer_height': '0.2',
 'line_width': '0.6',
 'name': '0.20mm Standard @Elegoo Neptune4 Plus (0.6 nozzle)',
 'outer_wall_line_width': '0.6',
 'resolution': '0.012',
 'setting_id': 'GP004',
 'sparse_infill_line_width': '0.65',
 'support_interface_spacing': '0.2',
 'support_line_width': '0.55',
 'support_top_z_distance': '0.2',
 'top_shell_layers': '4',
 'top_shell_thickness': '0.8',
 'top_surface_line_width': '0.56',
 'type': 'process'}
