from __future__ import annotations

# source: profiles/Elegoo/process/0.40mm Standard @Elegoo Giga 0.8 nozzle.json
DATA = {'bridge_speed': '25',
 'compatible_printers': ['Elegoo OrangeStorm Giga 0.8 nozzle'],
 'default_acceleration': '3000',
 'detect_thin_wall': '0',
 'filename_format': 'EOGiga1_{nozzle_diameter[0]}_{input_filename_base}_{filament_type[0]}{layer_height}_{print_time}.gcode',
 'from': 'system',
 'inherits': 'fdm_process_elegoo_08040',
 'initial_layer_acceleration': '1000',
 'initial_layer_infill_speed': '60',
 'initial_layer_speed': '45',
 'inner_wall_acceleration': '3000',
 'instantiation': 'true',
 'internal_solid_infill_speed': '150',
 'make_overhang_printable_angle': '90',
 'name': '0.40mm Standard @Elegoo Giga 0.8 nozzle',
 'outer_wall_acceleration': '2000',
 'outer_wall_speed': '100',
 'print_flow_ratio': '1.0',
 'resolution': '0.05',
 'setting_id': 'PEOSG08040',
 'sparse_infill_speed': '150',
 'thick_internal_bridges': '0',
 'top_shell_layers': '4',
 'travel_acceleration': '3000',
 'travel_speed': '300',
 'type': 'process'}
