from __future__ import annotations

# source: profiles/Elegoo/process/fdm_process_elegoo_10050.json
DATA = {'bridge_flow': '1',
 'bridge_speed': '20',
 'elefant_foot_compensation': '0.2',
 'from': 'system',
 'inherits': 'fdm_process_elegoo_common',
 'initial_layer_infill_speed': '55',
 'initial_layer_line_width': '1.00',
 'initial_layer_print_height': '0.4',
 'initial_layer_speed': '35',
 'inner_wall_line_width': '1.00',
 'instantiation': 'false',
 'internal_solid_infill_line_width': '1.00',
 'layer_height': '0.5',
 'line_width': '1.00',
 'name': 'fdm_process_elegoo_10050',
 'outer_wall_line_width': '1.00',
 'outer_wall_speed': '80',
 'overhang_2_4_speed': '35',
 'overhang_3_4_speed': '15',
 'overhang_4_4_speed': '8',
 'sparse_infill_line_width': '1.00',
 'sparse_infill_speed': '100',
 'support_line_width': '1.00',
 'top_surface_line_width': '1.00',
 'top_surface_speed': '150',
 'type': 'process'}
