from __future__ import annotations

# source: profiles/Elegoo/process/fdm_process_neptune4max_common.json
DATA = {'accel_to_decel_factor': '50%',
 'default_acceleration': '3000',
 'default_jerk': '7',
 'exclude_object': '1',
 'from': 'system',
 'gap_infill_speed': '120',
 'infill_jerk': '7',
 'inherits': 'fdm_process_neptune4_common',
 'initial_layer_acceleration': '1000',
 'initial_layer_infill_speed': '80',
 'initial_layer_jerk': '7',
 'initial_layer_speed': '50',
 'inner_wall_acceleration': '2000',
 'inner_wall_jerk': '6',
 'inner_wall_speed': '160',
 'instantiation': 'false',
 'internal_solid_infill_speed': '200',
 'name': 'fdm_process_neptune4max_common',
 'outer_wall_acceleration': '2000',
 'outer_wall_jerk': '6',
 'outer_wall_speed': '120',
 'overhang_1_4_speed': '0',
 'overhang_2_4_speed': '50',
 'overhang_3_4_speed': '30',
 'overhang_4_4_speed': '10',
 'sparse_infill_speed': '200',
 'top_surface_acceleration': '2000',
 'top_surface_jerk': '7',
 'top_surface_speed': '120',
 'travel_acceleration': '3000',
 'travel_jerk': '7',
 'travel_speed': '300',
 'type': 'process'}
