from __future__ import annotations

# source: profiles/Custom/process/fdm_process_mytoolchanger_common.json
DATA = {'default_acceleration': '5000',
 'enable_prime_tower': '1',
 'exclude_object': '1',
 'from': 'system',
 'gap_infill_speed': '100',
 'inherits': 'fdm_process_klipper_common',
 'initial_layer_acceleration': '500',
 'initial_layer_infill_speed': '105',
 'initial_layer_speed': '50',
 'inner_wall_acceleration': '5000',
 'inner_wall_speed': '200',
 'instantiation': 'false',
 'internal_solid_infill_speed': '200',
 'name': 'fdm_process_mytoolchanger_common',
 'ooze_prevention': '1',
 'outer_wall_acceleration': '3000',
 'outer_wall_speed': '120',
 'preheat_steps': '1',
 'preheat_time': '30',
 'sparse_infill_speed': '200',
 'standby_temperature_delta': '-40',
 'top_surface_acceleration': '3000',
 'top_surface_speed': '100',
 'travel_acceleration': '7000',
 'travel_speed': '350',
 'type': 'process',
 'wipe_tower_cone_angle': '25',
 'wipe_tower_extra_spacing': '150%',
 'wipe_tower_rotation_angle': '90'}
