from __future__ import annotations

# source: profiles/Eryone/filament/Eryone ABS-CF.json
DATA = {'close_fan_the_first_x_layers': ['3'],
 'compatible_printers': ['Thinker X400 0.4 nozzle'],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['60'],
 'fan_min_speed': ['30'],
 'filament_end_gcode': ['; filament end gcode \nSET_FAN_SPEED FAN=filter_fan SPEED=0'],
 'filament_flow_ratio': ['0.92'],
 'filament_id': 'EFL81',
 'filament_max_volumetric_speed': ['10'],
 'filament_retraction_length': ['1'],
 'filament_settings_id': ['Eryone ABS-CF'],
 'filament_start_gcode': ['; filament start gcode\nSET_FAN_SPEED FAN=filter_fan SPEED=0'],
 'filament_type': ['ABS-CF'],
 'filament_vendor': ['Eryone'],
 'from': 'system',
 'hot_plate_temp': ['100'],
 'hot_plate_temp_initial_layer': ['100'],
 'inherits': 'Eryone Standard PLA',
 'instantiation': 'true',
 'name': 'Eryone ABS-CF',
 'nozzle_temperature': ['250'],
 'nozzle_temperature_initial_layer': ['260'],
 'nozzle_temperature_range_high': ['290'],
 'nozzle_temperature_range_low': ['240'],
 'overhang_fan_threshold': ['25%'],
 'setting_id': 'EFSA11',
 'slow_down_layer_time': ['10'],
 'support_material_interface_fan_speed': ['60'],
 'temperature_vitrification': ['100'],
 'type': 'filament'}
