from __future__ import annotations

# source: profiles/Eryone/filament/Eryone ASA-CF.json
DATA = {'close_fan_the_first_x_layers': ['3'],
 'compatible_printers': ['Thinker X400 0.4 nozzle'],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['50'],
 'fan_min_speed': ['20'],
 'filament_end_gcode': ['; filament end gcode \nSET_FAN_SPEED FAN=filter_fan SPEED=0'],
 'filament_flow_ratio': ['0.92'],
 'filament_id': 'EFL82',
 'filament_max_volumetric_speed': ['8'],
 'filament_retraction_length': ['1'],
 'filament_settings_id': ['Eryone ASA-CF'],
 'filament_start_gcode': ['; filament start gcode\nSET_FAN_SPEED FAN=filter_fan SPEED=0'],
 'filament_type': ['ASA-CF'],
 'filament_vendor': ['Eryone'],
 'from': 'system',
 'hot_plate_temp': ['110'],
 'hot_plate_temp_initial_layer': ['110'],
 'inherits': 'Eryone Standard PLA',
 'instantiation': 'true',
 'name': 'Eryone ASA-CF',
 'nozzle_temperature': ['260'],
 'nozzle_temperature_initial_layer': ['275'],
 'nozzle_temperature_range_high': ['290'],
 'nozzle_temperature_range_low': ['240'],
 'overhang_fan_threshold': ['25%'],
 'setting_id': 'EFSA82',
 'slow_down_layer_time': ['12'],
 'support_material_interface_fan_speed': ['60'],
 'temperature_vitrification': ['180'],
 'type': 'filament'}
