from __future__ import annotations

# source: profiles/Eryone/filament/Eryone PETG-CF.json
DATA = {'close_fan_the_first_x_layers': ['3'],
 'compatible_printers': ['Thinker X400 0.4 nozzle'],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['90'],
 'fan_min_speed': ['50'],
 'filament_end_gcode': ['; filament end gcode \nSET_FAN_SPEED FAN=filter_fan SPEED=0\n'],
 'filament_flow_ratio': ['0.94'],
 'filament_id': 'EFL43',
 'filament_max_volumetric_speed': ['14'],
 'filament_retraction_length': ['1'],
 'filament_settings_id': ['Eryone PETG'],
 'filament_start_gcode': ['; filament start gcode\nSET_FAN_SPEED FAN=filter_fan SPEED=1'],
 'filament_type': ['PETG-CF'],
 'filament_vendor': ['Eryone'],
 'from': 'system',
 'hot_plate_temp': ['80'],
 'hot_plate_temp_initial_layer': ['80'],
 'inherits': 'Eryone Standard PLA',
 'instantiation': 'true',
 'name': 'Eryone PETG-CF',
 'nozzle_temperature': ['245'],
 'nozzle_temperature_initial_layer': ['250'],
 'nozzle_temperature_range_high': ['270'],
 'nozzle_temperature_range_low': ['225'],
 'overhang_fan_threshold': ['25%'],
 'setting_id': 'EFSA43',
 'slow_down_layer_time': ['7'],
 'slow_down_min_speed': ['20'],
 'support_material_interface_fan_speed': ['80'],
 'temperature_vitrification': ['80'],
 'type': 'filament'}
