from __future__ import annotations

# source: profiles/Anker/process/fdm_process_anker_fast_common.json
DATA = {'bottom_shell_thickness': '0',
 'bridge_acceleration': '1500',
 'default_acceleration': '6000',
 'default_jerk': '9',
 'from': 'system',
 'gap_infill_speed': '300',
 'infill_jerk': '9',
 'inherits': 'fdm_process_anker_common',
 'initial_layer_acceleration': '2500',
 'initial_layer_jerk': '9',
 'inner_wall_acceleration': '6000',
 'inner_wall_jerk': '9',
 'inner_wall_speed': '600',
 'instantiation': 'false',
 'name': 'fdm_process_anker_fast_common',
 'outer_wall_acceleration': '3000',
 'outer_wall_jerk': '9',
 'reduce_crossing_wall': '0',
 'sparse_infill_density': '10%',
 'sparse_infill_pattern': 'crosshatch',
 'sparse_infill_speed': '600',
 'support_speed': '360',
 'top_shell_thickness': '0',
 'top_surface_acceleration': '2500',
 'top_surface_jerk': '9',
 'top_surface_pattern': 'monotonicline',
 'top_surface_speed': '360',
 'travel_acceleration': '6000',
 'travel_jerk': '10',
 'travel_speed': '500',
 'type': 'process'}
