from __future__ import annotations

# source: profiles/InfiMech/filament/HSN/fdm_filament_pla_Hyper_other @HSN.json
DATA = {'additional_cooling_fan_speed': ['100'],
 'close_fan_the_first_x_layers': ['1'],
 'cool_plate_temp': ['60'],
 'cool_plate_temp_initial_layer': ['60'],
 'eng_plate_temp': ['60'],
 'eng_plate_temp_initial_layer': ['60'],
 'fan_cooling_layer_time': ['100'],
 'fan_max_speed': ['100'],
 'fan_min_speed': ['100'],
 'filament_cost': ['20'],
 'filament_density': ['1.24'],
 'filament_max_volumetric_speed': ['12'],
 'filament_start_gcode': ['; filament start gcode\n'],
 'filament_type': ['PLA'],
 'filament_vendor': ['Other'],
 'from': 'system',
 'hot_plate_temp': ['60'],
 'hot_plate_temp_initial_layer': ['65'],
 'inherits': 'fdm_filament_common_HSN',
 'instantiation': 'false',
 'name': 'fdm_filament_pla_Hyper_other @HSN',
 'nozzle_temperature': ['220'],
 'nozzle_temperature_initial_layer': ['220'],
 'nozzle_temperature_range_high': ['230'],
 'nozzle_temperature_range_low': ['190'],
 'overhang_fan_speed': ['100'],
 'overhang_fan_threshold': ['50%'],
 'reduce_fan_stop_start_freq': ['1'],
 'slow_down_for_layer_cooling': ['1'],
 'slow_down_layer_time': ['8'],
 'slow_down_min_speed': ['20'],
 'temperature_vitrification': ['60'],
 'textured_plate_temp': ['60'],
 'textured_plate_temp_initial_layer': ['60'],
 'type': 'filament'}
