from __future__ import annotations

# source: profiles/OrcaFilamentLibrary/filament/AliZ/AliZ PA-CF @base.json
DATA = {'complete_print_exhaust_fan_speed': ['80'],
 'during_print_exhaust_fan_speed': ['60'],
 'enable_pressure_advance': ['0'],
 'eng_plate_temp': ['80'],
 'eng_plate_temp_initial_layer': ['80'],
 'fan_cooling_layer_time': ['5'],
 'fan_max_speed': ['30'],
 'fan_min_speed': ['10'],
 'filament_cost': ['49.9'],
 'filament_flow_ratio': ['1'],
 'filament_id': 'AliZ003',
 'filament_max_volumetric_speed': ['8'],
 'filament_type': ['PA-CF'],
 'filament_vendor': ['Aliz'],
 'from': 'system',
 'full_fan_speed_layer': ['2'],
 'inherits': 'fdm_filament_pa',
 'instantiation': 'false',
 'name': 'AliZ PA-CF @base',
 'nozzle_temperature': ['290'],
 'nozzle_temperature_initial_layer': ['290'],
 'nozzle_temperature_range_high': ['300'],
 'nozzle_temperature_range_low': ['260'],
 'overhang_fan_speed': ['40'],
 'overhang_fan_threshold': ['0%'],
 'pressure_advance': ['0.026'],
 'slow_down_layer_time': ['2'],
 'slow_down_min_speed': ['10'],
 'type': 'filament'}
