from __future__ import annotations

# source: profiles/OrcaFilamentLibrary/filament/AliZ/AliZ PETG-CF @base.json
DATA = {'close_fan_the_first_x_layers': ['2'],
 'enable_pressure_advance': ['0'],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['35'],
 'fan_min_speed': ['10'],
 'filament_cost': ['49.9'],
 'filament_flow_ratio': ['1'],
 'filament_id': 'AZ01-1',
 'filament_max_volumetric_speed': ['10'],
 'filament_type': ['PETG-CF'],
 'filament_vendor': ['Aliz'],
 'from': 'system',
 'hot_plate_temp': ['79'],
 'hot_plate_temp_initial_layer': ['79'],
 'inherits': 'AliZ PETG @base',
 'instantiation': 'false',
 'name': 'AliZ PETG-CF @base',
 'nozzle_temperature': ['275'],
 'nozzle_temperature_initial_layer': ['275'],
 'nozzle_temperature_range_high': ['290'],
 'nozzle_temperature_range_low': ['260'],
 'overhang_fan_speed': ['100'],
 'overhang_fan_threshold': ['25%'],
 'pressure_advance': ['0.033'],
 'slow_down_min_speed': ['10'],
 'textured_plate_temp': ['70'],
 'textured_plate_temp_initial_layer': ['70'],
 'type': 'filament'}
