from __future__ import annotations

# source: profiles/OrcaFilamentLibrary/filament/AliZ/AliZ PETG @base.json
DATA = {'close_fan_the_first_x_layers': ['2'],
 'enable_pressure_advance': ['0'],
 'fan_max_speed': ['80'],
 'fan_min_speed': ['30'],
 'filament_cost': ['49.9'],
 'filament_flow_ratio': ['1'],
 'filament_id': 'AliZ001',
 'filament_max_volumetric_speed': ['15'],
 'filament_vendor': ['Aliz'],
 'from': 'system',
 'hot_plate_temp': ['79'],
 'hot_plate_temp_initial_layer': ['79'],
 'inherits': 'fdm_filament_pet',
 'instantiation': 'false',
 'name': 'AliZ PETG @base',
 'nozzle_temperature': ['250'],
 'nozzle_temperature_initial_layer': ['250'],
 'overhang_fan_threshold': ['25%'],
 'pressure_advance': ['0.036'],
 'textured_plate_temp': ['70'],
 'textured_plate_temp_initial_layer': ['70'],
 'type': 'filament'}
