from __future__ import annotations

# source: profiles/WonderMaker/filament/fdm_filament_pha.json
DATA = {'additional_cooling_fan_speed': ['70'],
 'close_fan_the_first_x_layers': ['1'],
 'cool_plate_temp': ['35'],
 'cool_plate_temp_initial_layer': ['35'],
 'eng_plate_temp': ['0'],
 'eng_plate_temp_initial_layer': ['0'],
 'fan_cooling_layer_time': ['100'],
 'fan_min_speed': ['100'],
 'filament_cost': ['27.99'],
 'filament_density': ['1.24'],
 'filament_max_volumetric_speed': ['6'],
 'filament_type': ['PHA'],
 'from': 'system',
 'hot_plate_temp': ['55'],
 'hot_plate_temp_initial_layer': ['55'],
 'inherits': 'fdm_filament_common',
 'instantiation': 'false',
 'name': 'fdm_filament_pha',
 'nozzle_temperature': ['220'],
 'nozzle_temperature_initial_layer': ['220'],
 'nozzle_temperature_range_high': ['240'],
 'nozzle_temperature_range_low': ['190'],
 'overhang_fan_threshold': ['50%'],
 'reduce_fan_stop_start_freq': ['1'],
 'slow_down_layer_time': ['4'],
 'slow_down_min_speed': ['20'],
 'supertack_plate_temp': ['0'],
 'supertack_plate_temp_initial_layer': ['0'],
 'temperature_vitrification': ['120'],
 'textured_plate_temp': ['55'],
 'textured_plate_temp_initial_layer': ['55'],
 'type': 'filament'}
