from __future__ import annotations

# source: profiles/WonderMaker/filament/WonderMaker PETG Basic.json
DATA = {'compatible_printers': ['WonderMaker ZR 0.2 nozzle',
                         'WonderMaker ZR 0.4 nozzle',
                         'WonderMaker ZR 0.6 nozzle',
                         'WonderMaker ZR 0.8 nozzle',
                         'WonderMaker ZR Ultra 0.2 nozzle',
                         'WonderMaker ZR Ultra 0.4 nozzle',
                         'WonderMaker ZR Ultra 0.6 nozzle',
                         'WonderMaker ZR Ultra 0.8 nozzle',
                         'WonderMaker ZR Ultra S 0.2 nozzle',
                         'WonderMaker ZR Ultra S 0.4 nozzle',
                         'WonderMaker ZR Ultra S 0.6 nozzle',
                         'WonderMaker ZR Ultra S 0.8 nozzle'],
 'cool_plate_temp': ['0'],
 'cool_plate_temp_initial_layer': ['0'],
 'description': 'To get better transparent or translucent results with the corresponding filament, please refer to '
                'this wiki: Printing tips for transparent PETG.',
 'eng_plate_temp': ['70'],
 'eng_plate_temp_initial_layer': ['70'],
 'fan_cooling_layer_time': ['30'],
 'fan_max_speed': ['40'],
 'fan_min_speed': ['10'],
 'filament_cost': ['24.99'],
 'filament_density': ['1.25'],
 'filament_flow_ratio': ['0.95'],
 'filament_id': 'GFG00',
 'filament_max_volumetric_speed': ['8'],
 'filament_multitool_ramming': ['1'],
 'filament_vendor': ['WonderMaker'],
 'from': 'system',
 'hot_plate_temp': ['70'],
 'hot_plate_temp_initial_layer': ['70'],
 'inherits': 'fdm_filament_pet',
 'instantiation': 'true',
 'name': 'WonderMaker PETG Basic',
 'nozzle_temperature_range_high': ['270'],
 'nozzle_temperature_range_low': ['230'],
 'overhang_fan_speed': ['90'],
 'overhang_fan_threshold': ['10%'],
 'slow_down_layer_time': ['12'],
 'textured_plate_temp': ['70'],
 'textured_plate_temp_initial_layer': ['70'],
 'type': 'filament'}
