from __future__ import annotations

# source: profiles/FlyingBear/process/fdm_process_ghost_6.json
DATA = {'bottom_shell_layers': '3',
 'bridge_speed': '50',
 'default_acceleration': '1000',
 'elefant_foot_compensation': '0.15',
 'elefant_foot_compensation_layers': '1',
 'from': 'system',
 'gap_infill_speed': '80',
 'infill_wall_overlap': '15%',
 'inherits': 'fdm_process_marlin_common',
 'initial_layer_acceleration': '500',
 'initial_layer_infill_speed': '60',
 'initial_layer_print_height': '0.2',
 'initial_layer_speed': '45',
 'inner_wall_acceleration': '1000',
 'inner_wall_speed': '80',
 'instantiation': 'false',
 'internal_bridge_speed': '150%',
 'internal_solid_infill_speed': '80',
 'ironing_speed': '30',
 'layer_height': '0.2',
 'name': 'fdm_process_ghost_6',
 'outer_wall_acceleration': '1000',
 'outer_wall_speed': '60',
 'overhang_1_4_speed': '0',
 'overhang_2_4_speed': '50',
 'overhang_3_4_speed': '30',
 'overhang_4_4_speed': '10',
 'sparse_infill_speed': '80',
 'support_interface_speed': '40',
 'support_speed': '60',
 'top_shell_layers': '3',
 'top_shell_thickness': '0.6',
 'top_surface_acceleration': '1000',
 'top_surface_speed': '50',
 'travel_acceleration': '1500',
 'travel_speed': '150',
 'type': 'process',
 'wall_generator': 'arachne'}
