from __future__ import annotations

# source: profiles/CONSTRUCT3D/filament/fdm_filament_pet.json
DATA = {'close_fan_the_first_x_layers': ['3'],
 'eng_plate_temp': ['75'],
 'eng_plate_temp_initial_layer': ['80'],
 'fan_cooling_layer_time': ['20'],
 'fan_max_speed': ['100'],
 'fan_min_speed': ['30'],
 'filament_cost': ['25'],
 'filament_density': ['1.27'],
 'filament_max_volumetric_speed': ['35'],
 'filament_start_gcode': ['; filament start gcode\n'],
 'filament_type': ['PETG'],
 'from': 'system',
 'hot_plate_temp': ['80'],
 'hot_plate_temp_initial_layer': ['80'],
 'inherits': 'fdm_filament_common',
 'instantiation': 'false',
 'name': 'fdm_filament_pet',
 'nozzle_temperature': ['255'],
 'nozzle_temperature_initial_layer': ['255'],
 'nozzle_temperature_range_high': ['260'],
 'nozzle_temperature_range_low': ['230'],
 'overhang_fan_speed': ['70'],
 'reduce_fan_stop_start_freq': ['1'],
 'slow_down_for_layer_cooling': ['1'],
 'temperature_vitrification': ['75'],
 'type': 'filament'}
