from __future__ import annotations

# source: profiles/Prusa/process/0.05mm UltraDetail @MK3S 0.4.json
DATA = {'bottom_shell_layers': '10',
 'bridge_acceleration': '300',
 'bridge_flow': '0.6',
 'bridge_speed': '25',
 'compatible_printers': ['Prusa MK3S 0.4 nozzle'],
 'from': 'system',
 'gap_infill_speed': '20',
 'inherits': 'process_common_mk3',
 'inner_wall_acceleration': '300',
 'inner_wall_line_width': '0.45',
 'inner_wall_speed': '30',
 'instantiation': 'true',
 'internal_solid_infill_line_width': '0.45',
 'internal_solid_infill_speed': '30',
 'layer_height': '0.05',
 'line_width': '0.45',
 'name': '0.05mm UltraDetail @MK3S 0.4',
 'outer_wall_line_width': '0.45',
 'outer_wall_speed': '20',
 'print_settings_id': '0.05mm UltraDetail @MK3S 0.4',
 'raft_contact_distance': '0.1',
 'small_perimeter_speed': '20',
 'sparse_infill_acceleration': '800',
 'sparse_infill_line_width': '0.45',
 'sparse_infill_pattern': 'crosshatch',
 'sparse_infill_speed': '30',
 'support_base_pattern_spacing': '1.5',
 'support_bottom_z_distance': '0.1',
 'support_interface_speed': '24',
 'support_line_width': '0.33',
 'support_object_xy_distance': '0.27',
 'support_speed': '30',
 'support_top_z_distance': '0.1',
 'thick_bridges': '1',
 'top_shell_layers': '14',
 'top_surface_line_width': '0.4',
 'top_surface_speed': '20',
 'type': 'process',
 'wall_loops': '3'}
