from __future__ import annotations

# source: profiles/Prusa/process/0.07mm Detail @MK3.5.json
DATA = {'bottom_shell_layers': '8',
 'bottom_shell_thickness': '0.5',
 'bridge_speed': '30',
 'compatible_printers': ['Prusa MK3.5 0.25 nozzle'],
 'from': 'system',
 'inherits': 'process_detail_MK3.5',
 'initial_layer_line_width': '0.32',
 'initial_layer_print_height': '0.15',
 'inner_wall_line_width': '0.25',
 'instantiation': 'true',
 'internal_solid_infill_line_width': '0.25',
 'internal_solid_infill_speed': '140',
 'layer_height': '0.07',
 'line_width': '0.27',
 'name': '0.07mm Detail @MK3.5',
 'outer_wall_line_width': '0.25',
 'setting_id': 'GP004',
 'sparse_infill_line_width': '0.25',
 'support_base_pattern_spacing': '1',
 'support_bottom_z_distance': '0.09',
 'support_line_width': '0.25',
 'support_top_z_distance': '0.09',
 'top_shell_layers': '10',
 'top_shell_thickness': '0.7',
 'top_surface_line_width': '0.27',
 'type': 'process'}
