from __future__ import annotations

# source: profiles/Prusa/process/0.10mm Speed @MINIIS.json
DATA = {'bottom_shell_layers': '5',
 'bottom_shell_thickness': '0.5',
 'bridge_speed': '35',
 'compatible_printers': ['Prusa MINIIS 0.4 nozzle'],
 'from': 'system',
 'inherits': 'process_speed_miniis',
 'initial_layer_line_width': '0.5',
 'initial_layer_print_height': '0.2',
 'inner_wall_acceleration': '2000',
 'inner_wall_line_width': '0.45',
 'instantiation': 'true',
 'internal_solid_infill_acceleration': '3000',
 'internal_solid_infill_line_width': '0.45',
 'layer_height': '0.10',
 'line_width': '0.45',
 'name': '0.10mm Speed @MINIIS',
 'outer_wall_acceleration': '1500',
 'outer_wall_line_width': '0.45',
 'setting_id': 'GP004',
 'sparse_infill_acceleration': '3000',
 'sparse_infill_line_width': '0.45',
 'support_base_pattern_spacing': '2',
 'support_bottom_z_distance': '0.17',
 'support_line_width': '0.36',
 'support_top_z_distance': '0.17',
 'top_shell_layers': '7',
 'top_shell_thickness': '0.7',
 'top_surface_line_width': '0.4',
 'type': 'process'}
