from __future__ import annotations

# source: profiles/Prusa/process/0.12mm Structural @Prusa XL 5T 0.25.json
DATA = {'bottom_shell_layers': '7',
 'bottom_shell_thickness': '0.5',
 'bridge_acceleration': '1500',
 'bridge_speed': '30',
 'brim_object_gap': '0',
 'compatible_printers': ['Prusa XL 5T 0.25 nozzle'],
 'default_acceleration': '2000',
 'elefant_foot_compensation': '0',
 'from': 'system',
 'gap_infill_speed': '50',
 'infill_anchor': '1',
 'infill_wall_overlap': '15%',
 'inherits': 'process_common_xl_5t',
 'inital_layer_height': '0.2',
 'initial_layer_acceleration': '500',
 'initial_layer_line_width': '0.32',
 'inner_wall_acceleration': '1500',
 'inner_wall_line_width': '0.27',
 'inner_wall_speed': '70',
 'instantiation': 'true',
 'internal_solid_infill_acceleration': '2500',
 'internal_solid_infill_line_width': '0.27',
 'internal_solid_infill_speed': '140',
 'layer_height': '0.12',
 'line_width': '0.27',
 'name': '0.12mm Structural @Prusa XL 5T 0.25',
 'outer_wall_acceleration': '1000',
 'outer_wall_line_width': '0.27',
 'outer_wall_speed': '40',
 'overhang_1_4_speed': '80%',
 'overhang_2_4_speed': '30',
 'overhang_3_4_speed': '25',
 'overhang_4_4_speed': '15',
 'raft_contact_distance': '0.08',
 'raft_first_layer_density': '95%',
 'raft_first_layer_expansion': '3.5',
 'resolution': '0.008',
 'setting_id': 'GP004',
 'small_perimeter_speed': '40',
 'sparse_infill_acceleration': '2500',
 'sparse_infill_density': '15%',
 'sparse_infill_line_width': '0.27',
 'sparse_infill_speed': '100',
 'support_base_pattern_spacing': '1',
 'support_bottom_z_distance': '0.09',
 'support_interface_spacing': '0.2',
 'support_interface_speed': '75%',
 'support_interface_top_layers': '5',
 'support_line_width': '0.25',
 'support_object_xy_distance': '150%',
 'support_speed': '70',
 'support_threshold_angle': '40',
 'support_top_z_distance': '0.09',
 'top_shell_layers': '9',
 'top_shell_thickness': '0.6',
 'top_surface_acceleration': '1000',
 'top_surface_line_width': '0.27',
 'top_surface_speed': '60',
 'travel_acceleration': '4000',
 'tree_support_bramch_diameter_angle': '5',
 'tree_support_tip_diameter': '0.8',
 'type': 'process',
 'wall_loops': '3'}
