from __future__ import annotations

# source: profiles/Prusa/process/0.12mm Speed @MK3.5.json
DATA = {'bottom_shell_layers': '6',
 'bottom_shell_thickness': '0.5',
 'bridge_speed': '25',
 'compatible_printers': ['Prusa MK3.5 0.25 nozzle'],
 'from': 'system',
 'gap_infill_speed': '50',
 'inherits': 'process_detail_MK3.5',
 'initial_layer_line_width': '0.32',
 'initial_layer_print_height': '0.15',
 'inner_wall_line_width': '0.27',
 'inner_wall_speed': '120',
 'instantiation': 'true',
 'internal_solid_infill_acceleration': '2500',
 'internal_solid_infill_line_width': '0.27',
 'internal_solid_infill_speed': '140',
 'layer_height': '0.12',
 'line_width': '0.27',
 'name': '0.12mm Speed @MK3.5',
 'outer_wall_line_width': '0.27',
 'outer_wall_speed': '120',
 'overhang_1_4_speed': '60',
 'setting_id': 'GP004',
 'small_perimeter_speed': '120',
 'sparse_infill_acceleration': '2500',
 'sparse_infill_line_width': '0.27',
 'sparse_infill_speed': '100',
 'support_bottom_z_distance': '0.09',
 'support_line_width': '0.25',
 'support_speed': '70',
 'support_top_z_distance': '0.09',
 'top_shell_layers': '9',
 'top_shell_thickness': '0.7',
 'top_surface_line_width': '0.27',
 'top_surface_speed': '60',
 'type': 'process'}
