from __future__ import annotations

# source: profiles/Prusa/process/0.15mm Quality @MK3S 0.25.json
DATA = {'bottom_shell_layers': '5',
 'bridge_acceleration': '500',
 'bridge_flow': '1',
 'bridge_speed': '25',
 'compatible_printers': ['Prusa MK3S 0.25 nozzle'],
 'from': 'system',
 'gap_infill_speed': '30',
 'inherits': 'process_common_mk3',
 'initial_layer_acceleration': '500',
 'initial_layer_infill_speed': '30',
 'initial_layer_line_width': '0.3',
 'inner_wall_acceleration': '500',
 'inner_wall_line_width': '0.27',
 'inner_wall_speed': '30',
 'instantiation': 'true',
 'internal_solid_infill_line_width': '0.27',
 'internal_solid_infill_speed': '45',
 'layer_height': '0.15',
 'line_width': '0.25',
 'name': '0.15mm Quality @MK3S 0.25',
 'outer_wall_line_width': '0.27',
 'outer_wall_speed': '20',
 'print_settings_id': '0.15mm Quality @MK3S 0.25',
 'raft_contact_distance': '0.2',
 'small_perimeter_speed': '20',
 'sparse_infill_acceleration': '1000',
 'sparse_infill_line_width': '0.27',
 'sparse_infill_pattern': 'crosshatch',
 'sparse_infill_speed': '45',
 'support_base_pattern_spacing': '2',
 'support_bottom_z_distance': '0.2',
 'support_interface_speed': '40',
 'support_line_width': '0.25',
 'support_object_xy_distance': '0.27',
 'support_speed': '15',
 'support_top_z_distance': '0.2',
 'thick_bridges': '0',
 'top_shell_layers': '6',
 'top_surface_line_width': '0.25',
 'top_surface_speed': '30',
 'type': 'process',
 'wall_loops': '3'}
