from __future__ import annotations

# source: profiles/Prusa/process/0.15mm Standard @MK3.5.json
DATA = {'bottom_shell_layers': '4',
 'bottom_shell_thickness': '0.5',
 'bridge_speed': '25',
 'compatible_printers': ['Prusa MK3.5 0.4 nozzle'],
 'from': 'system',
 'inherits': 'process_detail_MK3.5',
 'initial_layer_line_width': '0.5',
 'initial_layer_print_height': '0.20',
 'inner_wall_acceleration': '2000',
 'inner_wall_line_width': '0.45',
 'inner_wall_speed': '80',
 'instantiation': 'true',
 'internal_solid_infill_acceleration': '2500',
 'internal_solid_infill_line_width': '0.45',
 'layer_height': '0.15',
 'line_width': '0.45',
 'name': '0.15mm Standard @MK3.5',
 'outer_wall_acceleration': '1500',
 'outer_wall_line_width': '0.45',
 'outer_wall_speed': '45',
 'setting_id': 'GP004',
 'sparse_infill_acceleration': '2500',
 'sparse_infill_line_width': '0.45',
 'sparse_infill_speed': '110',
 'support_bottom_z_distance': '0.17',
 'support_line_width': '0.36',
 'support_top_z_distance': '0.17',
 'top_shell_layers': '5',
 'top_shell_thickness': '0.7',
 'top_surface_line_width': '0.42',
 'top_surface_speed': '45',
 'type': 'process'}
