from __future__ import annotations

# source: profiles/Prusa/process/0.15mm Standard @MINIIS 0.6.json
DATA = {'bottom_shell_layers': '4',
 'bottom_shell_thickness': '0.5',
 'bridge_acceleration': '1500',
 'bridge_speed': '40',
 'compatible_printers': ['Prusa MINIIS 0.6 nozzle'],
 'default_acceleration': '2000',
 'from': 'system',
 'gap_infill_speed': '80',
 'inherits': 'process_common_miniis',
 'initial_layer_acceleration': '500',
 'initial_layer_line_width': '0.68',
 'initial_layer_print_height': '0.25',
 'inner_wall_acceleration': '2500',
 'inner_wall_line_width': '0.6',
 'inner_wall_speed': '70',
 'instantiation': 'true',
 'internal_solid_infill_acceleration': '2500',
 'internal_solid_infill_line_width': '0.6',
 'internal_solid_infill_speed': '140',
 'layer_height': '0.15',
 'line_width': '0.68',
 'name': '0.15mm Standard @MINIIS 0.6',
 'outer_wall_acceleration': '1500',
 'outer_wall_line_width': '0.6',
 'outer_wall_speed': '45',
 'setting_id': 'GP004',
 'sparse_infill_acceleration': '4000',
 'sparse_infill_line_width': '0.6',
 'sparse_infill_speed': '140',
 'support_base_pattern_spacing': '2',
 'support_bottom_z_distance': '0.25',
 'support_interface_spacing': '0.25',
 'support_line_width': '0.5',
 'support_top_z_distance': '0.25',
 'top_shell_layers': '5',
 'top_shell_thickness': '0.7',
 'top_surface_acceleration': '1500',
 'top_surface_line_width': '0.5',
 'top_surface_speed': '70',
 'travel_acceleration': '4000',
 'travel_speed': '300',
 'type': 'process',
 'wall_loops': '2'}
