from __future__ import annotations

# source: profiles/Prusa/process/0.15mm Speed @MINIIS 0.25.json
DATA = {'bottom_shell_layers': '4',
 'bottom_shell_thickness': '0.5',
 'bridge_speed': '25',
 'compatible_printers': ['Prusa MINIIS 0.25 nozzle'],
 'from': 'system',
 'inherits': 'process_detail_miniis',
 'initial_layer_line_width': '0.32',
 'initial_layer_print_height': '0.15',
 'inner_wall_acceleration': '2000',
 'inner_wall_line_width': '0.27',
 'inner_wall_speed': '120',
 'instantiation': 'true',
 'internal_solid_infill_acceleration': '2500',
 'internal_solid_infill_line_width': '0.27',
 'internal_solid_infill_speed': '140',
 'layer_height': '0.15',
 'line_width': '0.27',
 'name': '0.15mm Speed @MINIIS 0.25',
 'outer_wall_acceleration': '1500',
 'outer_wall_line_width': '0.27',
 'outer_wall_speed': '120',
 'setting_id': 'GP004',
 'sparse_infill_acceleration': '2500',
 'sparse_infill_line_width': '0.27',
 'sparse_infill_speed': '100',
 'support_bottom_z_distance': '0.09',
 'support_line_width': '0.25',
 'support_top_z_distance': '0.09',
 'top_shell_layers': '5',
 'top_shell_thickness': '0.7',
 'top_surface_line_width': '0.27',
 'top_surface_speed': '120',
 'type': 'process'}
