from __future__ import annotations

# source: profiles/Prusa/process/0.20mm Speed @MK3.5 0.6.json
DATA = {'bridge_acceleration': '1500',
 'bridge_speed': '40',
 'compatible_printers': ['Prusa MK3.5 0.6 nozzle'],
 'from': 'system',
 'gap_infill_speed': '80',
 'inherits': 'process_speed_MK3.5',
 'initial_layer_acceleration': '500',
 'initial_layer_line_width': '0.68',
 'initial_layer_print_height': '0.25',
 'inner_wall_acceleration': '2500',
 'inner_wall_line_width': '0.62',
 'inner_wall_speed': '115',
 'instantiation': 'true',
 'internal_solid_infill_acceleration': '3000',
 'internal_solid_infill_line_width': '0.62',
 'internal_solid_infill_speed': '100',
 'layer_height': '0.20',
 'line_width': '0.68',
 'name': '0.20mm Speed @MK3.5 0.6',
 'outer_wall_acceleration': '2000',
 'outer_wall_line_width': '0.62',
 'outer_wall_speed': '115',
 'overhang_1_4_speed': '45',
 'setting_id': 'GP004',
 'small_perimeter_speed': '115',
 'sparse_infill_line_width': '0.62',
 'sparse_infill_speed': '120',
 'support_base_pattern_spacing': '2',
 'support_bottom_interface_spacing': '0.22',
 'support_bottom_z_distance': '0.22',
 'support_interface_spacing': '0.25',
 'support_line_width': '0.5',
 'support_top_z_distance': '0.22',
 'top_surface_acceleration': '1500',
 'top_surface_line_width': '0.5',
 'top_surface_speed': '70',
 'travel_speed': '300',
 'type': 'process',
 'wall_loops': '2'}
