from __future__ import annotations

# source: profiles/Prusa/process/0.20mm Speed @Prusa XL 0.4.json
DATA = {'bottom_shell_layers': '4',
 'bottom_shell_thickness': '0.5',
 'bridge_acceleration': '1500',
 'bridge_speed': '50',
 'brim_object_gap': '0.1',
 'compatible_printers': ['Prusa XL 0.4 nozzle'],
 'default_acceleration': '2500',
 'elefant_foot_compensation': '0.2',
 'from': 'system',
 'gap_infill_speed': '120',
 'infill_anchor': '2',
 'infill_wall_overlap': '15%',
 'inherits': 'process_common_xl',
 'inital_layer_height': '0.2',
 'initial_layer_acceleration': '500',
 'initial_layer_line_width': '0.5',
 'inner_wall_acceleration': '3000',
 'inner_wall_line_width': '0.45',
 'inner_wall_speed': '170',
 'instantiation': 'true',
 'internal_solid_infill_acceleration': '4000',
 'internal_solid_infill_line_width': '0.45',
 'internal_solid_infill_speed': '200',
 'layer_height': '0.2',
 'line_width': '0.45',
 'name': '0.20mm Speed @Prusa XL 0.4',
 'outer_wall_acceleration': '2500',
 'outer_wall_line_width': '0.45',
 'outer_wall_speed': '170',
 'overhang_1_4_speed': '90%',
 'overhang_2_4_speed': '30',
 'overhang_3_4_speed': '25',
 'overhang_4_4_speed': '15',
 'raft_contact_distance': '0.15',
 'raft_first_layer_density': '80%',
 'raft_first_layer_expansion': '3.5',
 'resolution': '0.008',
 'setting_id': 'GP004',
 'small_perimeter_speed': '170',
 'sparse_infill_acceleration': '4000',
 'sparse_infill_density': '15%',
 'sparse_infill_line_width': '0.45',
 'sparse_infill_speed': '200',
 'support_base_pattern_spacing': '2',
 'support_bottom_z_distance': '0.2',
 'support_interface_spacing': '0.2',
 'support_interface_speed': '50%',
 'support_interface_top_layers': '5',
 'support_line_width': '0.36',
 'support_object_xy_distance': '80%',
 'support_speed': '110',
 'support_threshold_angle': '40',
 'support_top_z_distance': '0.2',
 'top_shell_layers': '5',
 'top_shell_thickness': '0.7',
 'top_surface_acceleration': '1500',
 'top_surface_line_width': '0.42',
 'top_surface_speed': '100',
 'travel_acceleration': '5000',
 'tree_support_bramch_diameter_angle': '5',
 'tree_support_tip_diameter': '0.8',
 'type': 'process',
 'wall_loops': '2'}
