from __future__ import annotations

# source: profiles/Prusa/process/0.20mm High Flow @MK3.5.json
DATA = {'bridge_acceleration': '1500',
 'bridge_speed': '50',
 'compatible_printers': ['Prusa MK3.5 0.4 nozzle'],
 'from': 'system',
 'gap_infill_speed': '120',
 'inherits': 'process_highflow_MK3.5',
 'initial_layer_acceleration': '500',
 'initial_layer_line_width': '0.5',
 'initial_layer_print_height': '0.20',
 'inner_wall_acceleration': '4000',
 'inner_wall_line_width': '0.45',
 'inner_wall_speed': '250',
 'instantiation': 'true',
 'internal_solid_infill_acceleration': '4000',
 'internal_solid_infill_line_width': '0.45',
 'internal_solid_infill_speed': '250',
 'layer_height': '0.20',
 'line_width': '0.45',
 'name': '0.20mm High Flow @MK3.5',
 'outer_wall_acceleration': '4000',
 'outer_wall_line_width': '0.45',
 'outer_wall_speed': '200',
 'overhang_1_4_speed': '45',
 'setting_id': 'GP004',
 'small_perimeter_speed': '170',
 'sparse_infill_line_width': '0.45',
 'sparse_infill_speed': '250',
 'support_line_width': '0.36',
 'support_speed': '120',
 'top_surface_acceleration': '2000',
 'top_surface_line_width': '0.42',
 'top_surface_speed': '100',
 'travel_speed': '300',
 'type': 'process',
 'wall_loops': '3'}
