from __future__ import annotations

# source: profiles/Prusa/process/0.25mm High Flow @MK3.5.json
DATA = {'bottom_shell_layers': '3',
 'bottom_shell_thickness': '0.6',
 'bridge_acceleration': '1500',
 'bridge_speed': '40',
 'compatible_printers': ['Prusa MK3.5 0.6 nozzle'],
 'default_acceleration': '2500',
 'from': 'system',
 'gap_infill_speed': '70',
 'inherits': 'process_highflow_MK3.5',
 'initial_layer_acceleration': '500',
 'initial_layer_infill_speed': '70',
 'initial_layer_line_width': '0.68',
 'initial_layer_print_height': '0.25',
 'initial_layer_speed': '40',
 'inner_wall_acceleration': '4000',
 'inner_wall_line_width': '0.68',
 'inner_wall_speed': '180',
 'instantiation': 'true',
 'internal_solid_infill_acceleration': '3000',
 'internal_solid_infill_line_width': '0.68',
 'internal_solid_infill_speed': '190',
 'layer_height': '0.25',
 'line_width': '0.68',
 'name': '0.25mm High Flow @MK3.5',
 'outer_wall_acceleration': '4000',
 'outer_wall_line_width': '0.68',
 'outer_wall_speed': '180',
 'overhang_1_4_speed': '45',
 'setting_id': 'GP004',
 'small_perimeter_speed': '170',
 'sparse_infill_line_width': '0.68',
 'sparse_infill_speed': '190',
 'support_base_pattern_spacing': '2',
 'support_bottom_interface_spacing': '0.22',
 'support_bottom_z_distance': '0.22',
 'support_interface_spacing': '0.25',
 'support_line_width': '0.5',
 'support_speed': '110',
 'support_top_z_distance': '0.22',
 'top_shell_layers': '4',
 'top_shell_thickness': '0.9',
 'top_surface_acceleration': '2000',
 'top_surface_line_width': '0.55',
 'top_surface_speed': '60',
 'travel_speed': '300',
 'type': 'process',
 'wall_loops': '2'}
