from __future__ import annotations

# source: profiles/Prusa/process/0.25mm Speed @MINIIS.json
DATA = {'bottom_shell_thickness': '0.6',
 'compatible_printers': ['Prusa MINIIS 0.6 nozzle'],
 'from': 'system',
 'gap_infill_speed': '60',
 'inherits': 'process_speed_miniis',
 'initial_layer_line_width': '0.68',
 'initial_layer_print_height': '0.25',
 'inner_wall_line_width': '0.68',
 'inner_wall_speed': '80',
 'instantiation': 'true',
 'internal_solid_infill_acceleration': '3000',
 'internal_solid_infill_line_width': '0.68',
 'internal_solid_infill_speed': '80',
 'layer_height': '0.25',
 'line_width': '0.68',
 'name': '0.25mm Speed @MINIIS',
 'outer_wall_line_width': '0.68',
 'outer_wall_speed': '70',
 'overhang_1_4_speed': '45',
 'setting_id': 'GP004',
 'small_perimeter_speed': '70',
 'sparse_infill_line_width': '0.68',
 'sparse_infill_speed': '90',
 'support_base_pattern_spacing': '2',
 'support_bottom_interface_spacing': '0.22',
 'support_bottom_z_distance': '0.22',
 'support_interface_spacing': '0.25',
 'support_line_width': '0.5',
 'support_speed': '80',
 'support_top_z_distance': '0.22',
 'top_shell_layers': '4',
 'top_shell_thickness': '0.9',
 'top_surface_line_width': '0.55',
 'top_surface_speed': '60',
 'travel_speed': '300',
 'type': 'process',
 'wall_loops': '2'}
