from __future__ import annotations

# source: profiles/Prusa/process/0.30mm Quality @MK3S 0.6.json
DATA = {'bottom_shell_layers': '4',
 'bottom_shell_thickness': '0.6',
 'bridge_acceleration': '1000',
 'bridge_flow': '1',
 'bridge_speed': '25',
 'compatible_printers': ['Prusa MK3S 0.6 nozzle'],
 'elefant_foot_compensation': '0.2',
 'from': 'system',
 'gap_infill_speed': '40',
 'infill_wall_overlap': '15%',
 'inherits': 'process_common_mk3',
 'initial_layer_line_width': '0.65',
 'inner_wall_acceleration': '800',
 'inner_wall_line_width': '0.65',
 'inner_wall_speed': '50',
 'instantiation': 'true',
 'internal_solid_infill_line_width': '0.65',
 'internal_solid_infill_speed': '70',
 'layer_height': '0.3',
 'line_width': '0.65',
 'name': '0.30mm Quality @MK3S 0.6',
 'outer_wall_line_width': '0.65',
 'outer_wall_speed': '35',
 'print_settings_id': '0.30mm Quality @MK3S 0.6',
 'raft_contact_distance': '0.2',
 'small_perimeter_speed': '30',
 'sparse_infill_acceleration': '1000',
 'sparse_infill_line_width': '0.65',
 'sparse_infill_pattern': 'crosshatch',
 'sparse_infill_speed': '70',
 'support_base_pattern_spacing': '2',
 'support_bottom_z_distance': '0.2',
 'support_interface_speed': '36',
 'support_line_width': '0.55',
 'support_object_xy_distance': '0.36',
 'support_speed': '50',
 'support_top_z_distance': '0.2',
 'thick_bridges': '0',
 'top_shell_layers': '4',
 'top_shell_thickness': '0.9',
 'top_surface_line_width': '0.6',
 'top_surface_speed': '45',
 'type': 'process',
 'wall_loops': '2'}
