from __future__ import annotations

# source: profiles/Prusa/process/0.30mm Detail @MK3.5.json
DATA = {'bottom_shell_layers': '2',
 'bottom_shell_thickness': '0.5',
 'compatible_printers': ['Prusa MK3.5 0.8 nozzle'],
 'from': 'system',
 'inherits': 'process_detail_MK3.5',
 'initial_layer_line_width': '1',
 'initial_layer_print_height': '0.4',
 'inner_wall_line_width': '0.9',
 'instantiation': 'true',
 'internal_solid_infill_line_width': '0.9',
 'layer_height': '0.3',
 'line_width': '0.9',
 'name': '0.30mm Detail @MK3.5',
 'outer_wall_line_width': '0.9',
 'setting_id': 'GP004',
 'sparse_infill_line_width': '0.9',
 'support_base_pattern_spacing': '2',
 'support_bottom_interface_spacing': '0.25',
 'support_bottom_z_distance': '0.25',
 'support_interface_spacing': '0.35',
 'support_line_width': '0.65',
 'support_top_z_distance': '0.25',
 'top_shell_layers': '3',
 'top_shell_thickness': '0.7',
 'top_surface_line_width': '0.7',
 'travel_speed': '300',
 'type': 'process',
 'wall_loops': '2'}
