from __future__ import annotations

# source: profiles/Prusa/process/0.40mm High Flow @MK3.5.json
DATA = {'bottom_shell_layers': '3',
 'bottom_shell_thickness': '0.8',
 'bridge_acceleration': '1000',
 'bridge_speed': '22',
 'compatible_printers': ['Prusa MK3.5 0.8 nozzle'],
 'default_acceleration': '2000',
 'from': 'system',
 'gap_infill_speed': '65',
 'inherits': 'process_highflow_MK3.5',
 'initial_layer_acceleration': '500',
 'initial_layer_infill_speed': '55',
 'initial_layer_line_width': '1',
 'initial_layer_print_height': '0.3',
 'initial_layer_speed': '40',
 'inner_wall_acceleration': '3000',
 'inner_wall_line_width': '0.9',
 'inner_wall_speed': '100',
 'instantiation': 'true',
 'internal_solid_infill_acceleration': '3000',
 'internal_solid_infill_line_width': '0.9',
 'internal_solid_infill_speed': '100',
 'layer_height': '0.4',
 'line_width': '0.9',
 'name': '0.40mm High Flow @MK3.5',
 'outer_wall_acceleration': '2500',
 'outer_wall_line_width': '0.9',
 'outer_wall_speed': '90',
 'setting_id': 'GP004',
 'small_perimeter_speed': '90',
 'sparse_infill_acceleration': '4000',
 'sparse_infill_line_width': '0.9',
 'sparse_infill_speed': '105',
 'support_base_pattern_spacing': '2',
 'support_bottom_interface_spacing': '0.25',
 'support_bottom_z_distance': '0.25',
 'support_interface_spacing': '0.35',
 'support_line_width': '0.65',
 'support_speed': '90',
 'support_top_z_distance': '0.25',
 'top_shell_layers': '4',
 'top_shell_thickness': '1.2',
 'top_surface_acceleration': '1500',
 'top_surface_line_width': '0.75',
 'top_surface_speed': '75',
 'travel_acceleration': '4000',
 'travel_speed': '300',
 'type': 'process',
 'wall_loops': '2'}
