from __future__ import annotations

# source: profiles/Prusa/process/process_common_mk4.json
DATA = {'bridge_speed': '25',
 'default_acceleration': '4000',
 'default_jerk': '9',
 'exclude_object': '1',
 'from': 'system',
 'gap_infill_speed': '120',
 'inherits': 'fdm_process_common',
 'initial_layer_acceleration': '700',
 'initial_layer_infill_speed': '80',
 'initial_layer_speed': '45',
 'inner_wall_acceleration': '4000',
 'inner_wall_jerk': '7',
 'inner_wall_speed': '170',
 'instantiation': 'false',
 'internal_bridge_speed': '50',
 'internal_solid_infill_speed': '200',
 'name': 'process_common_mk4',
 'outer_wall_acceleration': '3000',
 'outer_wall_jerk': '7',
 'outer_wall_speed': '170',
 'sparse_infill_speed': '200',
 'top_surface_acceleration': '1000',
 'top_surface_speed': '100',
 'travel_acceleration': '4000',
 'travel_jerk': '9',
 'travel_speed': '300',
 'type': 'process'}
