from __future__ import annotations

# source: profiles/RH3D/process/0.20mm Slow @E3NG v1.2S.json
DATA = {'bridge_acceleration': '2000',
 'bridge_speed': '40',
 'compatible_printers': ['E3NG v1.2S - 0.4 nozzle', 'E3NG v1.2S - 0.5 nozzle', 'E3NG v1.2S - 0.6 nozzle'],
 'default_acceleration': '3000',
 'from': 'system',
 'gap_infill_speed': '140',
 'infill_combination': '0',
 'inherits': 'process_common_E3NG v1.2S',
 'initial_layer_acceleration': '3000',
 'initial_layer_infill_speed': '75',
 'initial_layer_print_height': '0.2',
 'initial_layer_speed': '60',
 'inner_wall_acceleration': '3000',
 'inner_wall_speed': '140',
 'instantiation': 'true',
 'internal_solid_infill_acceleration': '3000',
 'internal_solid_infill_line_width': '125%',
 'internal_solid_infill_speed': '140',
 'ironing_speed': '80',
 'layer_height': '0.2',
 'name': '0.20mm Slow @E3NG v1.2S',
 'only_one_wall_first_layer': '1',
 'only_one_wall_top': '1',
 'outer_wall_acceleration': '3000',
 'outer_wall_speed': '140',
 'overhang_1_4_speed': '60',
 'overhang_2_4_speed': '35',
 'overhang_3_4_speed': '20',
 'overhang_4_4_speed': '8',
 'reduce_crossing_wall': '1',
 'seam_position': 'aligned',
 'setting_id': 'NG1020',
 'small_perimeter_speed': '140',
 'sparse_infill_acceleration': '4000',
 'sparse_infill_line_width': '125%',
 'sparse_infill_speed': '140',
 'support_interface_speed': '60',
 'top_surface_acceleration': '2000',
 'top_surface_line_width': '100%',
 'top_surface_speed': '140',
 'travel_acceleration': '3000',
 'travel_speed': '400',
 'type': 'process'}
