from __future__ import annotations

# source: profiles/RH3D/process/0.20mm Fast @E3NG v1.2S.json
DATA = {'bridge_acceleration': '5000',
 'bridge_speed': '75',
 'compatible_printers': ['E3NG v1.2S - 0.4 nozzle', 'E3NG v1.2S - 0.5 nozzle', 'E3NG v1.2S - 0.6 nozzle'],
 'default_acceleration': '10000',
 'from': 'system',
 'gap_infill_speed': '300',
 'infill_combination': '1',
 'inherits': 'process_common_E3NG v1.2S',
 'initial_layer_acceleration': '7500',
 'initial_layer_infill_speed': '150',
 'initial_layer_print_height': '0.2',
 'initial_layer_speed': '100',
 'inner_wall_acceleration': '10000',
 'inner_wall_speed': '340',
 'instantiation': 'true',
 'internal_solid_infill_acceleration': '10000',
 'internal_solid_infill_line_width': '125%',
 'internal_solid_infill_speed': '340',
 'ironing_speed': '150',
 'layer_height': '0.2',
 'name': '0.20mm Fast @E3NG v1.2S',
 'only_one_wall_first_layer': '0',
 'only_one_wall_top': '0',
 'outer_wall_acceleration': '7500',
 'outer_wall_speed': '300',
 'overhang_1_4_speed': '100',
 'overhang_2_4_speed': '50',
 'overhang_3_4_speed': '30',
 'overhang_4_4_speed': '15',
 'reduce_crossing_wall': '0',
 'seam_position': 'nearest',
 'setting_id': 'NG3020',
 'small_perimeter_speed': '300',
 'sparse_infill_acceleration': '12500',
 'sparse_infill_line_width': '125%',
 'sparse_infill_speed': '400',
 'support_interface_speed': '120',
 'top_surface_acceleration': '7500',
 'top_surface_line_width': '100%',
 'top_surface_speed': '300',
 'travel_acceleration': '10000',
 'travel_speed': '400',
 'type': 'process'}
