from __future__ import annotations

# source: profiles/Mellow/process/fdm_process_M1_common.json
DATA = {'default_acceleration': '6000',
 'default_jerk': '0',
 'exclude_object': '1',
 'from': 'system',
 'gap_infill_speed': '200',
 'infill_jerk': '12',
 'inherits': 'fdm_process_common',
 'initial_layer_acceleration': '1000',
 'initial_layer_infill_speed': '105',
 'initial_layer_jerk': '7',
 'initial_layer_speed': '50',
 'inner_wall_acceleration': '5000',
 'inner_wall_jerk': '7',
 'inner_wall_speed': '250',
 'instantiation': 'false',
 'internal_solid_infill_speed': '280',
 'name': 'fdm_process_M1_common',
 'outer_wall_acceleration': '3000',
 'outer_wall_jerk': '7',
 'outer_wall_speed': '200',
 'sparse_infill_speed': '300',
 'top_surface_acceleration': '3000',
 'top_surface_jerk': '7',
 'top_surface_speed': '200',
 'travel_acceleration': '6000',
 'travel_jerk': '12',
 'travel_speed': '400',
 'type': 'process'}
