from __future__ import annotations

# source: profiles/Z-Bolt/machine/fdm_zbolt_common.json
DATA = {'auxiliary_fan': '0',
 'default_filament_profile': ['Z-Bolt Generic PLA'],
 'default_print_profile': '0.20mm Standard @Z-Bolt S300',
 'deretraction_speed': ['30'],
 'from': 'system',
 'gcode_flavor': 'klipper',
 'inherits': 'fdm_machine_common',
 'instantiation': 'false',
 'machine_end_gcode': 'END_PRINT',
 'machine_max_acceleration_e': ['5000', '5000'],
 'machine_max_acceleration_extruding': ['20000', '20000'],
 'machine_max_acceleration_retracting': ['5000', '5000'],
 'machine_max_acceleration_travel': ['9000', '9000'],
 'machine_max_acceleration_x': ['20000', '20000'],
 'machine_max_acceleration_y': ['20000', '20000'],
 'machine_max_acceleration_z': ['500', '200'],
 'machine_max_jerk_e': ['2.5', '2.5'],
 'machine_max_jerk_x': ['9', '9'],
 'machine_max_jerk_y': ['9', '9'],
 'machine_max_jerk_z': ['3', '3'],
 'machine_max_speed_e': ['30', '30'],
 'machine_max_speed_x': ['500', '200'],
 'machine_max_speed_y': ['500', '200'],
 'machine_max_speed_z': ['20', '20'],
 'machine_min_extruding_rate': ['0', '0'],
 'machine_min_travel_rate': ['0', '0'],
 'machine_pause_gcode': 'PAUSE',
 'machine_start_gcode': 'START_PRINT',
 'max_layer_height': ['0.4'],
 'min_layer_height': ['0.08'],
 'name': 'fdm_zbolt_common',
 'nozzle_diameter': ['0.4'],
 'nozzle_type': 'hardened_steel',
 'printer_variant': '0.4',
 'retract_before_wipe': ['0%'],
 'retract_length_toolchange': ['2'],
 'retraction_length': ['0.8'],
 'retraction_minimum_travel': ['1'],
 'retraction_speed': ['30'],
 'single_extruder_multi_material': '1',
 'type': 'machine',
 'z_hop': ['0.4'],
 'z_hop_types': 'Normal Lift'}
