from __future__ import annotations

# source: profiles/Qidi/process/0.10mm Standard @X-Max 4 0.2 nozzle.json
DATA = {'bottom_color_penetration_layers': '5',
 'bottom_shell_layers': '5',
 'bridge_flow': '1',
 'compatible_printers': ['Qidi X-Max 4 0.2 nozzle'],
 'default_acceleration': ['10000'],
 'elefant_foot_compensation': '0.15',
 'enable_arc_fitting': '1',
 'from': 'system',
 'inherits': 'fdm_process_n_common',
 'initial_layer_infill_speed': ['70'],
 'initial_layer_line_width': '0.25',
 'initial_layer_print_height': '0.1',
 'initial_layer_speed': ['40'],
 'inner_wall_acceleration': ['5000'],
 'inner_wall_line_width': '0.22',
 'instantiation': 'true',
 'internal_solid_infill_line_width': '0.22',
 'layer_height': '0.1',
 'line_width': '0.22',
 'name': '0.10mm Standard @X-Max 4 0.2 nozzle',
 'outer_wall_acceleration': ['3000'],
 'outer_wall_line_width': '0.22',
 'setting_id': 'GP007',
 'skeleton_infill_line_width': '0.22',
 'skin_infill_line_width': '0.22',
 'small_perimeter_threshold': ['4'],
 'smooth_coefficient': '4',
 'sparse_infill_line_width': '0.22',
 'sparse_infill_speed': ['100'],
 'support_bottom_z_distance': '0.1',
 'support_line_width': '0.22',
 'support_top_z_distance': '0.1',
 'top_color_penetration_layers': '7',
 'top_shell_layers': '7',
 'top_surface_line_width': '0.22',
 'top_surface_speed': ['150'],
 'travel_speed': ['500'],
 'type': 'process',
 'wall_loops': '4'}
