from __future__ import annotations

# source: profiles/Qidi/process/0.12mm Fine @X-Max 4.json
DATA = {'bottom_color_penetration_layers': '5',
 'bottom_shell_layers': '7',
 'bridge_flow': '1',
 'compatible_printers': ['Qidi X-Max 4 0.4 nozzle'],
 'default_acceleration': ['10000'],
 'elefant_foot_compensation': '0.15',
 'enable_arc_fitting': '1',
 'from': 'system',
 'gap_infill_speed': ['350'],
 'inherits': 'fdm_process_n_common',
 'initial_layer_infill_speed': ['105'],
 'initial_layer_speed': ['50'],
 'inner_wall_acceleration': ['5000'],
 'inner_wall_speed': ['350'],
 'instantiation': 'true',
 'internal_solid_infill_speed': ['350'],
 'layer_height': '0.12',
 'name': '0.12mm Fine @X-Max 4',
 'outer_wall_acceleration': ['3000'],
 'outer_wall_speed': ['200'],
 'overhang_1_4_speed': ['60'],
 'overhang_2_4_speed': ['30'],
 'overhang_3_4_speed': ['10'],
 'setting_id': 'GP004',
 'small_perimeter_threshold': ['50'],
 'smooth_coefficient': '4',
 'sparse_infill_speed': ['430'],
 'support_bottom_z_distance': '0.12',
 'support_threshold_angle': '20',
 'support_top_z_distance': '0.12',
 'top_color_penetration_layers': '7',
 'top_shell_layers': '8',
 'top_shell_thickness': '0.8',
 'top_surface_speed': ['200'],
 'type': 'process',
 'wall_loops': '4'}
