from __future__ import annotations

# source: profiles/Qidi/process/0.24mm Standard @X-Max 4.json
DATA = {'bridge_flow': '1',
 'compatible_printers': ['Qidi X-Max 4 0.4 nozzle'],
 'default_acceleration': ['10000'],
 'elefant_foot_compensation': '0.15',
 'enable_arc_fitting': '1',
 'from': 'system',
 'gap_infill_speed': ['230'],
 'inherits': 'fdm_process_n_common',
 'inner_wall_acceleration': ['5000'],
 'inner_wall_speed': ['230'],
 'instantiation': 'true',
 'internal_solid_infill_speed': ['230'],
 'layer_height': '0.24',
 'name': '0.24mm Standard @X-Max 4',
 'outer_wall_acceleration': ['3000'],
 'outer_wall_speed': ['200'],
 'overhang_3_4_speed': ['25'],
 'overhang_4_4_speed': ['5'],
 'setting_id': 'GP004',
 'small_perimeter_threshold': ['4'],
 'smooth_coefficient': '4',
 'sparse_infill_speed': ['230'],
 'support_threshold_angle': '35',
 'top_color_penetration_layers': '4',
 'top_shell_layers': '4',
 'top_shell_thickness': '1.0',
 'top_surface_line_width': '0.45',
 'travel_speed': ['500'],
 'type': 'process'}
