from __future__ import annotations

# source: profiles/Qidi/process/0.30mm Extra Draft @Qidi Q1 Pro.json
DATA = {'adaptive_layer_height': '1',
 'bottom_shell_layers': '3',
 'bottom_shell_thickness': '0',
 'bottom_surface_pattern': 'monotonic',
 'bridge_flow': '1',
 'bridge_no_support': '0',
 'brim_object_gap': '0',
 'brim_width': '0',
 'compatible_printers': ['Qidi Q1 Pro 0.4 nozzle'],
 'compatible_printers_condition': '',
 'detect_overhang_wall': '1',
 'detect_thin_wall': '1',
 'draft_shield': 'disabled',
 'elefant_foot_compensation': '0.1',
 'enable_prime_tower': '0',
 'enable_support': '0',
 'filename_format': '{input_filename_base}_{filament_type[initial_tool]}_{print_time}.gcode',
 'from': 'system',
 'infill_combination': '0',
 'infill_direction': '45',
 'infill_wall_overlap': '15%',
 'inherits': 'fdm_process_qidi_x3_common',
 'initial_layer_line_width': '0.5',
 'initial_layer_print_height': '0.3',
 'inner_wall_line_width': '0.45',
 'instantiation': 'true',
 'interface_shells': '0',
 'internal_solid_infill_line_width': '0',
 'ironing_flow': '15%',
 'ironing_spacing': '0.1',
 'ironing_type': 'no ironing',
 'layer_height': '0.3',
 'line_width': '0.42',
 'max_travel_detour_distance': '0',
 'minimum_sparse_infill_area': '10',
 'name': '0.30mm Extra Draft @Qidi Q1 Pro',
 'outer_wall_line_width': '0.4',
 'prime_tower_width': '60',
 'print_sequence': 'by layer',
 'print_settings_id': '',
 'raft_layers': '0',
 'reduce_crossing_wall': '0',
 'reduce_infill_retraction': '1',
 'resolution': '0.012',
 'seam_position': 'aligned',
 'setting_id': 'GP004',
 'skirt_distance': '2',
 'skirt_height': '1',
 'skirt_loops': '2',
 'sparse_infill_density': '15%',
 'sparse_infill_line_width': '0.45',
 'sparse_infill_pattern': 'crosshatch',
 'spiral_mode': '0',
 'standby_temperature_delta': '-5',
 'support_base_pattern': 'rectilinear',
 'support_base_pattern_spacing': '2.5',
 'support_filament': '0',
 'support_interface_bottom_layers': '-1',
 'support_interface_filament': '0',
 'support_interface_loop_pattern': '0',
 'support_interface_spacing': '0.5',
 'support_interface_top_layers': '3',
 'support_line_width': '0.42',
 'support_object_xy_distance': '50%',
 'support_on_build_plate_only': '0',
 'support_style': 'grid',
 'support_threshold_angle': '30',
 'support_top_z_distance': '0.3',
 'support_type': 'normal(auto)',
 'top_shell_layers': '4',
 'top_shell_thickness': '0.8',
 'top_surface_line_width': '0.45',
 'top_surface_pattern': 'monotonicline',
 'tree_support_branch_angle': '40',
 'tree_support_wall_count': '0',
 'type': 'process',
 'wall_infill_order': 'inner wall/outer wall/infill',
 'wall_loops': '2',
 'wipe_tower_no_sparse_layers': '0',
 'xy_contour_compensation': '0',
 'xy_hole_compensation': '0'}
