from __future__ import annotations

# source: profiles/Qidi/process/fdm_process_QIDI_0.36_nozzle_0.6.json
DATA = {'bottom_shell_layers': '3',
 'bridge_flow': '1',
 'bridge_speed': '30',
 'from': 'system',
 'gap_infill_speed': '50',
 'inherits': 'fdm_process_qidi_x3_common',
 'initial_layer_infill_speed': '55',
 'initial_layer_line_width': '0.62',
 'initial_layer_print_height': '0.3',
 'initial_layer_speed': '35',
 'inner_wall_line_width': '0.62',
 'inner_wall_speed': '150',
 'instantiation': 'false',
 'internal_solid_infill_line_width': '0.62',
 'internal_solid_infill_speed': '150',
 'layer_height': '0.36',
 'line_width': '0.62',
 'name': 'fdm_process_QIDI_0.36_nozzle_0.6',
 'outer_wall_line_width': '0.62',
 'outer_wall_speed': '120',
 'overhang_1_4_speed': '0',
 'overhang_2_4_speed': '50',
 'overhang_3_4_speed': '15',
 'overhang_4_4_speed': '10',
 'sparse_infill_line_width': '0.62',
 'sparse_infill_speed': '100',
 'support_line_width': '0.62',
 'top_shell_layers': '3',
 'top_surface_line_width': '0.62',
 'top_surface_speed': '150',
 'type': 'process',
 'wall_loops': '2'}
