from __future__ import annotations

# source: profiles/Qidi/process/fdm_process_QIDI_0.06_nozzle_0.2.json
DATA = {'bottom_shell_layers': '5',
 'bridge_flow': '1',
 'from': 'system',
 'inherits': 'fdm_process_qidi_x3_common',
 'initial_layer_infill_speed': '70',
 'initial_layer_line_width': '0.25',
 'initial_layer_print_height': '0.1',
 'initial_layer_speed': '40',
 'inner_wall_line_width': '0.22',
 'instantiation': 'false',
 'internal_solid_infill_line_width': '0.22',
 'layer_height': '0.06',
 'line_width': '0.22',
 'name': 'fdm_process_QIDI_0.06_nozzle_0.2',
 'outer_wall_line_width': '0.22',
 'sparse_infill_line_width': '0.22',
 'sparse_infill_speed': '100',
 'support_line_width': '0.22',
 'top_shell_layers': '7',
 'top_surface_line_width': '0.22',
 'top_surface_speed': '150',
 'type': 'process',
 'wall_loops': '4'}
