from __future__ import annotations

# source: profiles/FlyingBear/process/S1/0.16mm Optimal @FlyingBear S1.json
DATA = {'accel_to_decel_enable': '0',
 'bottom_shell_layers': '4',
 'bridge_speed': '25',
 'brim_object_gap': '0.1',
 'compatible_printers': ['FlyingBear S1 0.4 nozzle'],
 'exclude_object': '1',
 'from': 'system',
 'gap_infill_speed': '250',
 'inherits': 'fdm_process_common_S1',
 'inner_wall_acceleration': '3000',
 'inner_wall_speed': '250',
 'instantiation': 'true',
 'internal_bridge_speed': '50',
 'internal_solid_infill_line_width': '0.42',
 'internal_solid_infill_speed': '300',
 'layer_height': '0.16',
 'line_width': '0.42',
 'name': '0.16mm Optimal @FlyingBear S1',
 'outer_wall_line_width': '0.42',
 'outer_wall_speed': '120',
 'overhang_1_4_speed': '50',
 'overhang_2_4_speed': '50',
 'overhang_3_4_speed': '30',
 'overhang_speed_classic': '0',
 'precise_outer_wall': '0',
 'print_flow_ratio': '0.95',
 'seam_gap': '10%',
 'setting_id': 'GP005',
 'skirt_speed': '50',
 'sparse_infill_speed': '330',
 'support_line_width': '0.42',
 'top_shell_layers': '6',
 'top_shell_thickness': '1',
 'top_surface_line_width': '0.42',
 'type': 'process'}
